// AUTOGENERATED by ffxi-decomp. Do not edit by hand.
// version: 972 (sha256=d4622c1cc4a3012c, image_base=0x00100000)
// source:  main/tk/IwDeleteMenu.h
// functions: 1


// ---------------------------------------------------------------------------
// OnInitialUpdatePrimitive
// CIwDeleteMenu::OnInitialUpdatePrimitive(void)
//   symbol: OnInitialUpdatePrimitive__13CIwDeleteMenuFv
//   rva:    0x00314e80  size: 92 bytes  tool: ghidra-12.0.4
//   source: main/tk/IwDeleteMenu.h
// ---------------------------------------------------------------------------


/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void CIwDeleteMenu::OnInitialUpdatePrimitive(CIwDeleteMenu *this)

{
  *(undefined1 *)(*(int *)(this + 8) + 0x5d) = 0;
  *(undefined1 *)(*(int *)(this + 8) + 0x81) = 0;
  *(undefined1 *)(*(int *)(this + 8) + 0x82) = 0;
  *(undefined1 *)(*(int *)(this + 8) + 0x80) = 0;
  return;
}

