// AUTOGENERATED by ffxi-decomp. Do not edit by hand.
// version: 972 (sha256=d4622c1cc4a3012c, image_base=0x00100000)
// source:  main/net/game_prot/wcaQueryBuilder.c
// functions: 58


// ---------------------------------------------------------------------------
// FFWCaParse_MatchKeyword
// FFWCaParse_MatchKeyword(int, const char *, const char *)
//   symbol: FFWCaParse_MatchKeyword__FiPCcPCc
//   rva:    0x001c8500  size: 568 bytes  tool: ghidra-12.0.4
//   source: main/net/game_prot/wcaQueryBuilder.c
// ---------------------------------------------------------------------------


char * FFWCaParse_MatchKeyword__FiPCcPCc(undefined8 str,char *keyword,char *param_3)

{
  char cVar1;
  bool bVar2;
  int iVar3;
  char cVar4;
  char *pcStack_20;
  
  cVar4 = '\0';
  if ((*keyword == '\0') || ((_ctype_[*keyword + 1] & 8) != 0)) {
    pcStack_20 = (char *)0x0;
  }
  else {
    pcStack_20 = keyword;
    if (*keyword == '\"') {
      pcStack_20 = keyword + 1;
      cVar4 = *keyword;
    }
    while (((*pcStack_20 != '\0' && (cVar4 != *pcStack_20)) &&
           ((cVar4 != '\0' || ((_ctype_[*pcStack_20 + 1] & 8) == 0))))) {
      if (*param_3 == '\0') {
        return (char *)0x0;
      }
      cVar1 = *param_3;
      iVar3 = toupper((int)*pcStack_20);
      if ((long)cVar1 != (long)iVar3) {
        return (char *)0x0;
      }
      pcStack_20 = pcStack_20 + 1;
      param_3 = param_3 + 1;
    }
    if (*param_3 == '\0') {
      bVar2 = false;
      if ((cVar4 != '\0') && (*pcStack_20 != '\0')) {
        bVar2 = true;
      }
      if (bVar2) {
        pcStack_20 = pcStack_20 + 1;
      }
    }
    else {
      pcStack_20 = (char *)0x0;
    }
  }
  return pcStack_20;
}



// ---------------------------------------------------------------------------
// FFWCaParse_ZoneKeyword
// FFWCaParse_ZoneKeyword(int, const char *, const char * *)
//   symbol: FFWCaParse_ZoneKeyword__FiPCcPPCc
//   rva:    0x001c8740  size: 500 bytes  tool: ghidra-12.0.4
//   source: main/net/game_prot/wcaQueryBuilder.c
// ---------------------------------------------------------------------------


undefined * FFWCaParse_ZoneKeyword__FiPCcPPCc(undefined4 ctx,char *str,undefined4 *nxt_p)

{
  undefined *puVar1;
  long lVar2;
  long lVar3;
  undefined **ppuVar4;
  char *pcStack_20;
  
  lVar2 = 0;
  ppuVar4 = &FFWCaParse_ZoneTable;
  if (((str == (char *)0x0) || (*str == '\0')) ||
     (ppuVar4 = &FFWCaParse_ZoneTable, (_ctype_[*str + 1] & 4) == 0)) {
    while ((ppuVar4[1] != (undefined *)0x0 &&
           (lVar2 = FFWCaParse_MatchKeyword__FiPCcPCc(ctx,str,ppuVar4[1]), lVar2 == 0))) {
      ppuVar4 = ppuVar4 + 2;
    }
    if (((lVar2 == 0) || ((int)*ppuVar4 < 1)) ||
       ((0xff < (int)*ppuVar4 ||
        ((lVar3 = gcZoneEnterGet(), lVar3 != 0 &&
         ((1 << ((uint)*ppuVar4 & 7) & (uint)*(byte *)((int)lVar3 + ((int)*ppuVar4 >> 3))) != 0)))))
       ) {
      *nxt_p = (int)lVar2;
      puVar1 = *ppuVar4;
    }
    else {
      *nxt_p = 0;
      puVar1 = (undefined *)0xffffffff;
    }
  }
  else {
    puVar1 = (undefined *)atoi(str);
    pcStack_20 = str;
    while ((*pcStack_20 != '\0' && ((_ctype_[*pcStack_20 + 1] & 8) == 0))) {
      pcStack_20 = pcStack_20 + 1;
    }
    *nxt_p = pcStack_20;
  }
  return puVar1;
}



// ---------------------------------------------------------------------------
// FFWCaInitQueryInfo
//   symbol: FFWCaInitQueryInfo
//   rva:    0x001c8940  size: 184 bytes  tool: ghidra-12.0.4
//   source: main/net/game_prot/wcaQueryBuilder.c
// ---------------------------------------------------------------------------


void FFWCaInitQueryInfo(undefined4 *qinfo)

{
  *qinfo = 0;
  *(undefined2 *)(qinfo + 8) = 0;
  *(undefined2 *)((int)qinfo + 0x22) = 0xffff;
  *(undefined2 *)(qinfo + 9) = 0xffff;
  *(undefined2 *)(qinfo + 0xd) = 0xffff;
  *(undefined2 *)((int)qinfo + 0x36) = 0xffff;
  *(undefined2 *)(qinfo + 0xe) = 0xffff;
  *(undefined2 *)(qinfo + 7) = 0xffff;
  *(undefined2 *)((int)qinfo + 0x1e) = 0xffff;
  *(undefined1 *)(qinfo + 3) = 0;
  *(undefined2 *)((int)qinfo + 0x3a) = 0;
  *(undefined2 *)((int)qinfo + 0x3e) = 0;
  qinfo[0x10] = 0;
  *(undefined1 *)(qinfo + 0xf) = 0xff;
  *(undefined1 *)((int)qinfo + 0x3d) = 0xff;
  qinfo[0x11] = 0;
  return;
}



// ---------------------------------------------------------------------------
// FFWCaInitQueryExInfo
//   symbol: FFWCaInitQueryExInfo
//   rva:    0x001c8a00  size: 56 bytes  tool: ghidra-12.0.4
//   source: main/net/game_prot/wcaQueryBuilder.c
// ---------------------------------------------------------------------------


void FFWCaInitQueryExInfo(int qinfo)

{
  FFWCaInitQueryInfo(qinfo);
  *(undefined2 *)(qinfo + 0x48) = 0;
  *(undefined2 *)(qinfo + 0x4a) = 0;
  return;
}



// ---------------------------------------------------------------------------
// FFWCaInitQueryIdInfo
//   symbol: FFWCaInitQueryIdInfo
//   rva:    0x001c8a40  size: 28 bytes  tool: ghidra-12.0.4
//   source: main/net/game_prot/wcaQueryBuilder.c
// ---------------------------------------------------------------------------


void FFWCaInitQueryIdInfo(undefined2 *idInfo)

{
  *idInfo = 0;
  return;
}



// ---------------------------------------------------------------------------
// FFWCaInitQueryGroupInfo
//   symbol: FFWCaInitQueryGroupInfo
//   rva:    0x001c8a60  size: 44 bytes  tool: ghidra-12.0.4
//   source: main/net/game_prot/wcaQueryBuilder.c
// ---------------------------------------------------------------------------


void FFWCaInitQueryGroupInfo(undefined4 *grpInfo)

{
  grpInfo[2] = 0;
  grpInfo[1] = 0;
  *grpInfo = 0;
  return;
}



// ---------------------------------------------------------------------------
// FFWCaInitItemQuery
//   symbol: FFWCaInitItemQuery
//   rva:    0x001c8a90  size: 48 bytes  tool: ghidra-12.0.4
//   source: main/net/game_prot/wcaQueryBuilder.c
// ---------------------------------------------------------------------------


void * FFWCaInitItemQuery(void *qinfo)

{
  void *pvVar1;
  
  pvVar1 = memset(qinfo,0,0xa8);
  return pvVar1;
}



// ---------------------------------------------------------------------------
// FFWCaSetAuctionMarket
//   symbol: FFWCaSetAuctionMarket
//   rva:    0x001c8ac0  size: 36 bytes  tool: ghidra-12.0.4
//   source: main/net/game_prot/wcaQueryBuilder.c
// ---------------------------------------------------------------------------


void FFWCaSetAuctionMarket(int qinfo,undefined1 mid)

{
  *(undefined1 *)(qinfo + 4) = mid;
  return;
}



// ---------------------------------------------------------------------------
// FFWCaSetAuctionCategory
//   symbol: FFWCaSetAuctionCategory
//   rva:    0x001c8af0  size: 36 bytes  tool: ghidra-12.0.4
//   source: main/net/game_prot/wcaQueryBuilder.c
// ---------------------------------------------------------------------------


void FFWCaSetAuctionCategory(int qinfo,undefined2 cid)

{
  *(undefined2 *)(qinfo + 6) = cid;
  return;
}



// ---------------------------------------------------------------------------
// FFWCaSetAuctionReplyCount
//   symbol: FFWCaSetAuctionReplyCount
//   rva:    0x001c8b20  size: 36 bytes  tool: ghidra-12.0.4
//   source: main/net/game_prot/wcaQueryBuilder.c
// ---------------------------------------------------------------------------


void FFWCaSetAuctionReplyCount(undefined2 *qinfo,undefined2 cnt)

{
  *qinfo = cnt;
  return;
}



// ---------------------------------------------------------------------------
// FFWCaSetItemHistTarget
//   symbol: FFWCaSetItemHistTarget
//   rva:    0x001c8b50  size: 52 bytes  tool: ghidra-12.0.4
//   source: main/net/game_prot/wcaQueryBuilder.c
// ---------------------------------------------------------------------------


void FFWCaSetItemHistTarget(int qinfo,undefined2 itemNo)

{
  *(undefined2 *)(qinfo + 6) = 0;
  *(undefined2 *)(qinfo + 2) = itemNo;
  *(undefined1 *)(qinfo + 5) = 0;
  return;
}



// ---------------------------------------------------------------------------
// FFWCaSetStackItemHistTarget
//   symbol: FFWCaSetStackItemHistTarget
//   rva:    0x001c8b90  size: 60 bytes  tool: ghidra-12.0.4
//   source: main/net/game_prot/wcaQueryBuilder.c
// ---------------------------------------------------------------------------


void FFWCaSetStackItemHistTarget(int qinfo,undefined2 itemNo)

{
  *(undefined2 *)(qinfo + 6) = 0;
  *(undefined2 *)(qinfo + 2) = itemNo;
  *(char *)(qinfo + 5) = *(char *)(qinfo + 5) + '\x01';
  return;
}



// ---------------------------------------------------------------------------
// FFWCaSetItemQueryValueWithSort
//   symbol: FFWCaSetItemQueryValueWithSort
//   rva:    0x001c8bd0  size: 448 bytes  tool: ghidra-12.0.4
//   source: main/net/game_prot/wcaQueryBuilder.c
// ---------------------------------------------------------------------------


bool FFWCaSetItemQueryValueWithSort(int qinfo,int type,uint val1,short val2,int sortOrder)

{
  int iVar1;
  uint uVar2;
  
  uVar2 = 0;
  while( true ) {
    if (*(ushort *)(qinfo + 2) <= uVar2) {
      if (uVar2 < 0x14) {
        *(int *)(qinfo + uVar2 * 8 + 8) = type;
        iVar1 = qinfo + uVar2 * 8;
        *(byte *)(iVar1 + 0xc) = *(byte *)(iVar1 + 0xc) & 0xfe | 1;
        iVar1 = qinfo + uVar2 * 8;
        *(byte *)(iVar1 + 0xc) = *(byte *)(iVar1 + 0xc) & 0xfd | (sortOrder == -1) << 1;
        iVar1 = qinfo + uVar2 * 8;
        *(uint *)(iVar1 + 0xc) = *(uint *)(iVar1 + 0xc) & 0xfffe0003 | (val1 & 0x7fff) << 2;
        iVar1 = qinfo + uVar2 * 8;
        *(ushort *)(iVar1 + 0xe) = *(ushort *)(iVar1 + 0xe) & 1 | val2 << 1;
        *(short *)(qinfo + 2) = *(short *)(qinfo + 2) + 1;
      }
      return uVar2 < 0x14;
    }
    if (type == *(int *)(qinfo + uVar2 * 8 + 8)) break;
    uVar2 = uVar2 + 1 & 0xffff;
  }
  return false;
}



// ---------------------------------------------------------------------------
// FFWCaSetItemQuerySort
//   symbol: FFWCaSetItemQuerySort
//   rva:    0x001c8d90  size: 412 bytes  tool: ghidra-12.0.4
//   source: main/net/game_prot/wcaQueryBuilder.c
// ---------------------------------------------------------------------------


void FFWCaSetItemQuerySort(int qinfo,int type,int sortOrder)

{
  int iVar1;
  uint uVar2;
  
  uVar2 = 0;
  while( true ) {
    if (*(ushort *)(qinfo + 2) <= uVar2) {
      if (uVar2 < 0x14) {
        *(int *)(qinfo + uVar2 * 8 + 8) = type;
        iVar1 = qinfo + uVar2 * 8;
        *(byte *)(iVar1 + 0xc) = *(byte *)(iVar1 + 0xc) & 0xfe;
        iVar1 = qinfo + uVar2 * 8;
        *(byte *)(iVar1 + 0xc) = *(byte *)(iVar1 + 0xc) & 0xfd | (sortOrder == -1) << 1;
        iVar1 = qinfo + uVar2 * 8;
        *(uint *)(iVar1 + 0xc) = *(uint *)(iVar1 + 0xc) & 0xfffe0003;
        iVar1 = qinfo + uVar2 * 8;
        *(ushort *)(iVar1 + 0xe) = *(ushort *)(iVar1 + 0xe) & 1;
        *(short *)(qinfo + 2) = *(short *)(qinfo + 2) + 1;
      }
      return;
    }
    if (type == *(int *)(qinfo + uVar2 * 8 + 8)) break;
    uVar2 = uVar2 + 1 & 0xffff;
  }
  return;
}



// ---------------------------------------------------------------------------
// FFWCaParse_getLevel
// FFWCaParse_getLevel(FFWCaQueryInfo *, const char *)
//   symbol: FFWCaParse_getLevel__FP14FFWCaQueryInfoPCc
//   rva:    0x001c8f30  size: 1000 bytes  tool: ghidra-12.0.4
//   source: main/net/game_prot/wcaQueryBuilder.c
// ---------------------------------------------------------------------------


char * FFWCaParse_getLevel__FP14FFWCaQueryInfoPCc(int qinfo,char *str)

{
  uint uVar1;
  undefined2 uVar2;
  int aiStack_28 [6];
  char *pcStack_10;
  
  aiStack_28[2] = qinfo;
  pcStack_10 = str;
  uVar1 = 0;
  aiStack_28[1] = -1;
  aiStack_28[0] = -1;
  while ((*pcStack_10 != '\0' && ((_ctype_[*pcStack_10 + 1] & 8) != 0))) {
    pcStack_10 = pcStack_10 + 1;
  }
  while( true ) {
    while( true ) {
      if ((*pcStack_10 == '\0') || ((_ctype_[*pcStack_10 + 1] & 8) != 0)) {
        if ((aiStack_28[0] < 0) && (aiStack_28[1] < 0)) {
          pcStack_10 = (char *)0x0;
        }
        else {
          uVar2 = (undefined2)aiStack_28[0];
          if (uVar1 == 0) {
            if (aiStack_28[0] < 0) {
              uVar2 = 0;
            }
            else if (0xff < aiStack_28[0]) {
              uVar2 = 0;
            }
            *(undefined2 *)(aiStack_28[2] + 0x1e) = uVar2;
            *(undefined2 *)(aiStack_28[2] + 0x1c) = uVar2;
          }
          else if ((aiStack_28[0] < 0x100) || (aiStack_28[1] < aiStack_28[0])) {
            if ((aiStack_28[1] < 0x100) || (aiStack_28[0] < aiStack_28[1])) {
              if (aiStack_28[0] < 0) {
                uVar2 = 0;
              }
              else if (0xff < aiStack_28[0]) {
                uVar2 = 0xff;
              }
              *(undefined2 *)(aiStack_28[2] + 0x1c) = uVar2;
              if (aiStack_28[1] < 0) {
                uVar2 = 0xff;
              }
              else if (aiStack_28[1] < 0x100) {
                uVar2 = (undefined2)aiStack_28[1];
              }
              else {
                uVar2 = 0xff;
              }
              *(undefined2 *)(aiStack_28[2] + 0x1e) = uVar2;
            }
            else {
              *(undefined2 *)(aiStack_28[2] + 0x1e) = 0;
              *(undefined2 *)(aiStack_28[2] + 0x1c) = 0;
            }
          }
          else {
            *(undefined2 *)(aiStack_28[2] + 0x1e) = 0;
            *(undefined2 *)(aiStack_28[2] + 0x1c) = 0;
          }
        }
        return pcStack_10;
      }
      if (((_ctype_[*pcStack_10 + 1] & 4) == 0) || (1 < uVar1)) break;
      aiStack_28[uVar1] = 0;
      while ((*pcStack_10 != '\0' && ((_ctype_[*pcStack_10 + 1] & 4) != 0))) {
        aiStack_28[uVar1] = (int)*pcStack_10 + aiStack_28[uVar1] * 10 + -0x30;
        pcStack_10 = pcStack_10 + 1;
      }
    }
    if (((*pcStack_10 != '<') && (*pcStack_10 != '-')) || (uVar1 != 0)) break;
    uVar1 = 1;
    pcStack_10 = pcStack_10 + 1;
  }
  return (char *)0x0;
}



// ---------------------------------------------------------------------------
// FFWCaParse_getRank
// FFWCaParse_getRank(FFWCaQueryInfo *, const char *)
//   symbol: FFWCaParse_getRank__FP14FFWCaQueryInfoPCc
//   rva:    0x001c9320  size: 792 bytes  tool: ghidra-12.0.4
//   source: main/net/game_prot/wcaQueryBuilder.c
// ---------------------------------------------------------------------------


char * FFWCaParse_getRank__FP14FFWCaQueryInfoPCc(int qinfo,char *str)

{
  uint uVar1;
  undefined1 uVar2;
  int aiStack_28 [6];
  char *pcStack_10;
  
  aiStack_28[2] = qinfo;
  pcStack_10 = str;
  uVar1 = 0;
  aiStack_28[1] = -1;
  aiStack_28[0] = -1;
  while ((*pcStack_10 != '\0' && ((_ctype_[*pcStack_10 + 1] & 8) != 0))) {
    pcStack_10 = pcStack_10 + 1;
  }
  while( true ) {
    while( true ) {
      if ((*pcStack_10 == '\0') || ((_ctype_[*pcStack_10 + 1] & 8) != 0)) {
        if ((aiStack_28[0] < 0) && (aiStack_28[1] < 0)) {
          pcStack_10 = (char *)0x0;
        }
        else if (uVar1 == 0) {
          *(undefined1 *)(aiStack_28[2] + 0x3d) = (undefined1)aiStack_28[0];
          *(undefined1 *)(aiStack_28[2] + 0x3c) = (undefined1)aiStack_28[0];
        }
        else {
          if (aiStack_28[0] < 0) {
            aiStack_28[0]._0_1_ = 0;
          }
          else if (99 < aiStack_28[0]) {
            aiStack_28[0]._0_1_ = 100;
          }
          *(undefined1 *)(aiStack_28[2] + 0x3c) = (undefined1)aiStack_28[0];
          if (aiStack_28[1] < 0) {
            uVar2 = 100;
          }
          else if (aiStack_28[1] < 100) {
            uVar2 = (undefined1)aiStack_28[1];
          }
          else {
            uVar2 = 100;
          }
          *(undefined1 *)(aiStack_28[2] + 0x3d) = uVar2;
        }
        return pcStack_10;
      }
      if (((_ctype_[*pcStack_10 + 1] & 4) == 0) || (1 < uVar1)) break;
      aiStack_28[uVar1] = 0;
      while ((*pcStack_10 != '\0' && ((_ctype_[*pcStack_10 + 1] & 4) != 0))) {
        aiStack_28[uVar1] = (int)*pcStack_10 + aiStack_28[uVar1] * 10 + -0x30;
        pcStack_10 = pcStack_10 + 1;
      }
    }
    if (((*pcStack_10 != '<') && (*pcStack_10 != '-')) || (uVar1 != 0)) break;
    uVar1 = 1;
    pcStack_10 = pcStack_10 + 1;
  }
  return (char *)0x0;
}



// ---------------------------------------------------------------------------
// FFWCaParse_parseCategoryArg
// FFWCaParse_parseCategoryArg(FFWCaQueryInfo *, int, int, const char *)
//   symbol: FFWCaParse_parseCategoryArg__FP14FFWCaQueryInfoiiPCc
//   rva:    0x001c9640  size: 1432 bytes  tool: ghidra-12.0.4
//   source: main/net/game_prot/wcaQueryBuilder.c
// ---------------------------------------------------------------------------


char * FFWCaParse_parseCategoryArg__FP14FFWCaQueryInfoiiPCc
                 (int qinfo,uint catCode,undefined4 ctx,char *str)

{
  undefined2 uVar1;
  long lVar2;
  uint uVar3;
  int iVar4;
  undefined4 *puVar5;
  int *piVar6;
  char cVar7;
  char *pcVar8;
  char *pcStack_70;
  undefined2 uStack_6c;
  undefined2 uStack_68;
  char *pcStack_64;
  undefined2 uStack_60;
  char *pcStack_5c;
  char *pcStack_54;
  int iStack_40;
  uint uStack_30;
  undefined4 uStack_20;
  char *pcStack_10;
  
  pcStack_70 = (char *)0x0;
  uVar3 = catCode & 0x1f;
  iStack_40 = qinfo;
  uStack_30 = catCode;
  uStack_20 = ctx;
  pcStack_10 = str;
  if (uVar3 == 6) {
    pcStack_54 = (char *)0x0;
    for (piVar6 = &FFWCaParse_StatusTable; piVar6[1] != 0; piVar6 = piVar6 + 2) {
      lVar2 = FFWCaParse_MatchKeyword__FiPCcPCc(uStack_20,pcStack_10,piVar6[1]);
      pcStack_54 = (char *)lVar2;
      if (lVar2 != 0) break;
    }
    pcStack_70 = pcStack_54;
    if (0 < *piVar6) {
      *(ushort *)(iStack_40 + 0x3a) = *(ushort *)(iStack_40 + 0x3a) | (ushort)*piVar6;
    }
  }
  else if (uVar3 == 5) {
    pcStack_5c = (char *)0x0;
    for (puVar5 = &FFWCaParse_RaceTable; puVar5[1] != 0; puVar5 = puVar5 + 2) {
      lVar2 = FFWCaParse_MatchKeyword__FiPCcPCc(uStack_20,pcStack_10,puVar5[1]);
      pcStack_5c = (char *)lVar2;
      if (lVar2 != 0) break;
    }
    pcStack_70 = pcStack_5c;
    uStack_60 = (undefined2)*puVar5;
    *(undefined2 *)(iStack_40 + 0x38) = uStack_60;
  }
  else if (uVar3 == 0x10) {
    pcStack_70 = (char *)FFWCaParse_getRank__FP14FFWCaQueryInfoPCc(qinfo,str);
  }
  else if (uVar3 == 4) {
    pcStack_70 = (char *)FFWCaParse_getLevel__FP14FFWCaQueryInfoPCc(qinfo,str);
  }
  else if (uVar3 == 3) {
    pcStack_64 = (char *)0x0;
    for (puVar5 = &FFWCaParse_JobTable; puVar5[1] != 0; puVar5 = puVar5 + 2) {
      lVar2 = FFWCaParse_MatchKeyword__FiPCcPCc(uStack_20,pcStack_10,puVar5[1]);
      pcStack_64 = (char *)lVar2;
      if (lVar2 != 0) break;
    }
    pcStack_70 = pcStack_64;
    uStack_68 = (undefined2)*puVar5;
    *(undefined2 *)(iStack_40 + 0x36) = uStack_68;
  }
  else if (uVar3 == 2) {
    for (puVar5 = &FFWCaParse_HomeTable; pcVar8 = (char *)0x0, puVar5[1] != 0; puVar5 = puVar5 + 2)
    {
      lVar2 = FFWCaParse_MatchKeyword__FiPCcPCc(uStack_20,pcStack_10,puVar5[1]);
      pcVar8 = (char *)lVar2;
      if (lVar2 != 0) break;
    }
    uStack_6c = (undefined2)*puVar5;
    *(undefined2 *)(iStack_40 + 0x34) = uStack_6c;
    pcStack_70 = pcVar8;
  }
  else if (uVar3 == 1) {
    uVar1 = FFWCaParse_ZoneKeyword__FiPCcPPCc(ctx,str,&pcStack_70);
    *(undefined2 *)(iStack_40 + 0x22) = uVar1;
    if (-1 < *(short *)(iStack_40 + 0x22)) {
      iVar4 = 0;
      while (((iVar4 < 8 && (-1 < *(short *)(iStack_40 + iVar4 * 2 + 0x24))) &&
             (*(short *)(iStack_40 + iVar4 * 2 + 0x24) != *(short *)(iStack_40 + 0x22)))) {
        iVar4 = iVar4 + 1;
      }
      if ((7 < iVar4) || (*(short *)(iStack_40 + iVar4 * 2 + 0x24) < 0)) {
        for (iVar4 = 7; 0 < iVar4; iVar4 = iVar4 + -1) {
          *(undefined2 *)(iStack_40 + iVar4 * 2 + 0x24) =
               *(undefined2 *)(iStack_40 + (iVar4 + -1) * 2 + 0x24);
        }
        *(undefined2 *)(iStack_40 + 0x24) = *(undefined2 *)(iStack_40 + 0x22);
      }
    }
  }
  else if (uVar3 == 0) {
    pcVar8 = (char *)(qinfo + 0xc);
    cVar7 = '\0';
    pcStack_70 = str;
    while ((*pcStack_70 != '\0' && ((_ctype_[*pcStack_70 + 1] & 8) != 0))) {
      pcStack_70 = pcStack_70 + 1;
    }
    if (*pcStack_70 == '\"') {
      cVar7 = *pcStack_70;
      pcStack_70 = pcStack_70 + 1;
    }
    while (((*pcStack_70 != '\0' && (cVar7 != *pcStack_70)) &&
           ((cVar7 != '\0' || ((_ctype_[*pcStack_70 + 1] & 8) == 0))))) {
      if ((int)pcVar8 - (qinfo + 0xc) < 0xf) {
        *pcVar8 = *pcStack_70;
        pcVar8 = pcVar8 + 1;
      }
      pcStack_70 = pcStack_70 + 1;
    }
    if ((cVar7 != '\0') && (cVar7 == *pcStack_70)) {
      pcStack_70 = pcStack_70 + 1;
    }
    *pcVar8 = '\0';
  }
  return pcStack_70;
}



// ---------------------------------------------------------------------------
// FFWCaParse_buildQueryInfo
// FFWCaParse_buildQueryInfo(FFWCaQueryInfo *, const char *, short, short *, unsigned int)
//   symbol: FFWCaParse_buildQueryInfo__FP14FFWCaQueryInfoPCcsPsUi
//   rva:    0x001c9be0  size: 4076 bytes  tool: ghidra-12.0.4
//   source: main/net/game_prot/wcaQueryBuilder.c
// ---------------------------------------------------------------------------


void FFWCaParse_buildQueryInfo__FP14FFWCaQueryInfoPCcsPsUi
               (uint *qinfo,char *str,short defZone,short *regZone,undefined4 actComlink)

{
  short sVar1;
  uint uVar2;
  bool bVar3;
  uint uVar4;
  long lVar5;
  uint *puVar6;
  int *piVar7;
  int iVar8;
  char *pcStack_b4;
  byte bStack_ac;
  char *pcStack_a4;
  int iStack_9c;
  char *pcStack_94;
  int iStack_8c;
  int iStack_84;
  int iStack_7c;
  int iStack_74;
  int iStack_6c;
  int iStack_64;
  byte bStack_5c;
  char *pcStack_40;
  
  FFWCaInitQueryInfo(qinfo);
  pcStack_40 = str;
LAB_002caacc:
  do {
    if (*pcStack_40 == '\0') {
LAB_002caae4:
      if (((*qinfo & 2) == 0) && (-1 < defZone)) {
        *(short *)((int)qinfo + 0x22) = defZone;
        *qinfo = *qinfo | 2;
        *(short *)(qinfo + 9) = defZone;
        *(undefined2 *)((int)qinfo + 0x26) = 0xffff;
        *(ushort *)((int)qinfo + 0x3e) = *(ushort *)((int)qinfo + 0x3e) | 2;
      }
      else if (((*qinfo & 2) != 0) && (0 < *(short *)((int)qinfo + 0x22))) {
        *(ushort *)((int)qinfo + 0x3e) = *(ushort *)((int)qinfo + 0x3e) | 2;
      }
      return;
    }
    while ((*pcStack_40 != '\0' && ((_ctype_[*pcStack_40 + 1] & 8) != 0))) {
      pcStack_40 = pcStack_40 + 1;
    }
    if ((*pcStack_40 == '+') || ((*pcStack_40 == '-' && ((_ctype_[pcStack_40[1] + 1] & 4) == 0)))) {
      pcStack_b4 = (char *)0x0;
      for (puVar6 = &FFWCaParse_CategoryTable; puVar6[1] != 0; puVar6 = puVar6 + 2) {
        lVar5 = FFWCaParse_MatchKeyword__FiPCcPCc(1,pcStack_40 + 1,puVar6[1]);
        pcStack_b4 = (char *)lVar5;
        if (lVar5 != 0) break;
      }
      uVar2 = *puVar6;
      if (((((int)uVar2 < 0) || (uVar2 == 0xb)) || (uVar2 == 0xc)) ||
         ((uVar2 == 6 || ((*qinfo & 1 << (uVar2 & 0x1f)) != 0)))) goto LAB_002caae4;
      for (iVar8 = 0; iVar8 < (int)(uint)(ushort)qinfo[8]; iVar8 = iVar8 + 1) {
        if ((uVar2 & 0x1f) == (*(byte *)((int)qinfo + iVar8 + 4) & 0x1f)) {
          bVar3 = true;
          goto LAB_002c9e08;
        }
      }
      bVar3 = false;
LAB_002c9e08:
      if (bVar3) goto LAB_002caae4;
      if (*pcStack_40 == '-') {
        bStack_5c = 0x80;
      }
      else {
        bStack_5c = 0;
      }
      bStack_ac = (byte)uVar2 | bStack_5c;
      for (iVar8 = 0; iVar8 < (int)(uint)(ushort)qinfo[8]; iVar8 = iVar8 + 1) {
        if ((uVar2 & 0x1f) == (*(byte *)((int)qinfo + iVar8 + 4) & 0x1f)) goto LAB_002c9ec0;
      }
      uVar4 = qinfo[8];
      *(ushort *)(qinfo + 8) = (ushort)uVar4 + 1;
      *(byte *)((int)qinfo + (ushort)uVar4 + 4) = bStack_ac;
LAB_002c9ec0:
      pcStack_40 = pcStack_b4;
      while ((*pcStack_40 != '\0' && ((_ctype_[*pcStack_40 + 1] & 8) != 0))) {
        pcStack_40 = pcStack_40 + 1;
      }
      lVar5 = FFWCaParse_parseCategoryArg__FP14FFWCaQueryInfoiiPCc(qinfo,uVar2,1,pcStack_40);
      if (lVar5 != 0) {
        *qinfo = *qinfo | 1 << (uVar2 & 0x1f);
        pcStack_40 = (char *)lVar5;
      }
      goto LAB_002caacc;
    }
    if (*pcStack_40 != '=') {
      if ((*pcStack_40 != '&') || ((_ctype_[pcStack_40[1] + 1] & 4) == 0)) {
        pcStack_94 = (char *)0x0;
        for (puVar6 = &FFWCaParse_CategoryTable; puVar6[1] != 0; puVar6 = puVar6 + 2) {
          lVar5 = FFWCaParse_MatchKeyword__FiPCcPCc(0,pcStack_40,puVar6[1]);
          pcStack_94 = (char *)lVar5;
          if (lVar5 != 0) break;
        }
        uVar2 = *puVar6;
        if ((int)uVar2 < 0) {
          lVar5 = FFWCaParse_parseCategoryArg__FP14FFWCaQueryInfoiiPCc(qinfo,6,0,pcStack_40);
          if (lVar5 == 0) {
            if ((*qinfo & 2) == 0) {
              for (iStack_8c = 0; iStack_8c < (int)(uint)(ushort)qinfo[8];
                  iStack_8c = iStack_8c + 1) {
                if ((*(byte *)((int)qinfo + iStack_8c + 4) & 0x1f) == 1) {
                  bVar3 = true;
                  goto LAB_002ca638;
                }
              }
              bVar3 = false;
LAB_002ca638:
              if (((!bVar3) && ((_ctype_[*pcStack_40 + 1] & 4) == 0)) &&
                 (lVar5 = FFWCaParse_parseCategoryArg__FP14FFWCaQueryInfoiiPCc
                                    (qinfo,1,0,pcStack_40), lVar5 != 0)) {
                *qinfo = *qinfo | 2;
                pcStack_40 = (char *)lVar5;
                goto LAB_002caacc;
              }
            }
            if ((*qinfo & 0x10) == 0) {
              for (iStack_84 = 0; iStack_84 < (int)(uint)(ushort)qinfo[8];
                  iStack_84 = iStack_84 + 1) {
                if ((*(byte *)((int)qinfo + iStack_84 + 4) & 0x1f) == 4) {
                  bVar3 = true;
                  goto LAB_002ca744;
                }
              }
              bVar3 = false;
LAB_002ca744:
              if ((!bVar3) &&
                 (lVar5 = FFWCaParse_parseCategoryArg__FP14FFWCaQueryInfoiiPCc
                                    (qinfo,4,0,pcStack_40), lVar5 != 0)) {
                *qinfo = *qinfo | 0x10;
                pcStack_40 = (char *)lVar5;
                goto LAB_002caacc;
              }
            }
            if ((*qinfo & 8) == 0) {
              for (iStack_7c = 0; iStack_7c < (int)(uint)(ushort)qinfo[8];
                  iStack_7c = iStack_7c + 1) {
                if ((*(byte *)((int)qinfo + iStack_7c + 4) & 0x1f) == 3) {
                  bVar3 = true;
                  goto LAB_002ca814;
                }
              }
              bVar3 = false;
LAB_002ca814:
              if ((!bVar3) &&
                 (lVar5 = FFWCaParse_parseCategoryArg__FP14FFWCaQueryInfoiiPCc
                                    (qinfo,3,0,pcStack_40), lVar5 != 0)) {
                *qinfo = *qinfo | 8;
                pcStack_40 = (char *)lVar5;
                goto LAB_002caacc;
              }
            }
            if ((*qinfo & 4) == 0) {
              for (iStack_74 = 0; iStack_74 < (int)(uint)(ushort)qinfo[8];
                  iStack_74 = iStack_74 + 1) {
                if ((*(byte *)((int)qinfo + iStack_74 + 4) & 0x1f) == 2) {
                  bVar3 = true;
                  goto LAB_002ca8e4;
                }
              }
              bVar3 = false;
LAB_002ca8e4:
              if ((!bVar3) &&
                 (lVar5 = FFWCaParse_parseCategoryArg__FP14FFWCaQueryInfoiiPCc
                                    (qinfo,2,0,pcStack_40), lVar5 != 0)) {
                *qinfo = *qinfo | 4;
                pcStack_40 = (char *)lVar5;
                goto LAB_002caacc;
              }
            }
            if ((*qinfo & 0x20) == 0) {
              for (iStack_6c = 0; iStack_6c < (int)(uint)(ushort)qinfo[8];
                  iStack_6c = iStack_6c + 1) {
                if ((*(byte *)((int)qinfo + iStack_6c + 4) & 0x1f) == 5) {
                  bVar3 = true;
                  goto LAB_002ca9b4;
                }
              }
              bVar3 = false;
LAB_002ca9b4:
              if ((!bVar3) &&
                 (lVar5 = FFWCaParse_parseCategoryArg__FP14FFWCaQueryInfoiiPCc
                                    (qinfo,5,0,pcStack_40), lVar5 != 0)) {
                *qinfo = *qinfo | 0x20;
                pcStack_40 = (char *)lVar5;
                goto LAB_002caacc;
              }
            }
            if ((*qinfo & 1) != 0) goto LAB_002caae4;
            for (iStack_64 = 0; iStack_64 < (int)(uint)(ushort)qinfo[8]; iStack_64 = iStack_64 + 1
                ) {
              if ((*(byte *)((int)qinfo + iStack_64 + 4) & 0x1f) == 0) {
                bVar3 = true;
                goto LAB_002caa80;
              }
            }
            bVar3 = false;
LAB_002caa80:
            if ((bVar3) ||
               (lVar5 = FFWCaParse_parseCategoryArg__FP14FFWCaQueryInfoiiPCc(qinfo,0,0,pcStack_40)
               , lVar5 == 0)) goto LAB_002caae4;
            *qinfo = *qinfo | 1;
            pcStack_40 = (char *)lVar5;
            goto LAB_002caacc;
          }
          *qinfo = *qinfo | 0x40;
          pcStack_40 = (char *)lVar5;
          goto LAB_002caacc;
        }
        if ((uVar2 != 6) && ((*qinfo & 1 << (uVar2 & 0x1f)) != 0)) goto LAB_002caae4;
        pcStack_40 = pcStack_94;
        while ((*pcStack_40 != '\0' && ((_ctype_[*pcStack_40 + 1] & 8) != 0))) {
          pcStack_40 = pcStack_40 + 1;
        }
        if (uVar2 == 0xc) {
          *(ushort *)((int)qinfo + 0x3e) = *(ushort *)((int)qinfo + 0x3e) | 4;
        }
        else if (uVar2 == 0xb) {
          FFWCaSetQueryComlink(qinfo,actComlink);
        }
        else {
          if (uVar2 == 0x12) {
            if ((((*qinfo & 2) == 0) && (regZone != (short *)0x0)) && (-1 < *regZone)) {
              for (iVar8 = 0; (iVar8 < 8 && (-1 < regZone[iVar8])); iVar8 = iVar8 + 1) {
                sVar1 = regZone[iVar8];
                *(short *)((int)qinfo + iVar8 * 2 + 0x24) = sVar1;
                *(short *)((int)qinfo + 0x22) = sVar1;
              }
              if (iVar8 < 8) {
                *(undefined2 *)((int)qinfo + iVar8 * 2 + 0x24) = 0xffff;
              }
              *qinfo = *qinfo | 2;
            }
            goto LAB_002caacc;
          }
          lVar5 = FFWCaParse_parseCategoryArg__FP14FFWCaQueryInfoiiPCc(qinfo,uVar2,1,pcStack_40);
          if (lVar5 == 0) goto LAB_002caae4;
          pcStack_40 = (char *)lVar5;
        }
        *qinfo = *qinfo | 1 << (uVar2 & 0x1f);
        goto LAB_002caacc;
      }
      if ((pcStack_40[1] == '1') || ((pcStack_40[1] == '2' || (pcStack_40[1] == '3')))) {
        FFWCaSetQueryMsgType(qinfo,1 << ((int)pcStack_40[1] - 0x30U & 0x1f));
      }
      else {
        FFWCaSetQueryMsgType(qinfo,1);
      }
      while ((*pcStack_40 != '\0' && ((_ctype_[*pcStack_40 + 1] & 8) == 0))) {
        pcStack_40 = pcStack_40 + 1;
      }
      goto LAB_002caacc;
    }
    pcStack_a4 = (char *)0x0;
    for (piVar7 = &FFWCaParse_CategoryTable; piVar7[1] != 0; piVar7 = piVar7 + 2) {
      lVar5 = FFWCaParse_MatchKeyword__FiPCcPCc(1,pcStack_40 + 1,piVar7[1]);
      pcStack_a4 = (char *)lVar5;
      if (lVar5 != 0) break;
    }
    if ((*piVar7 != 0) || ((*qinfo & 1) != 0)) goto LAB_002caae4;
    for (iVar8 = 0; iVar8 < (int)(uint)(ushort)qinfo[8]; iVar8 = iVar8 + 1) {
      if ((*(byte *)((int)qinfo + iVar8 + 4) & 0x1f) == 0) {
        bVar3 = true;
        goto LAB_002ca070;
      }
    }
    bVar3 = false;
LAB_002ca070:
    if (bVar3) goto LAB_002caae4;
    for (iStack_9c = 0; iStack_9c < (int)(uint)(ushort)qinfo[8]; iStack_9c = iStack_9c + 1) {
      if ((*(byte *)((int)qinfo + iStack_9c + 4) & 0x1f) == 0) goto LAB_002ca0f4;
    }
    uVar2 = qinfo[8];
    *(ushort *)(qinfo + 8) = (ushort)uVar2 + 1;
    *(undefined1 *)((int)qinfo + (ushort)uVar2 + 4) = 0;
LAB_002ca0f4:
    pcStack_40 = pcStack_a4;
    *(ushort *)((int)qinfo + 0x3e) = *(ushort *)((int)qinfo + 0x3e) | 1;
    while ((*pcStack_40 != '\0' && ((_ctype_[*pcStack_40 + 1] & 8) != 0))) {
      pcStack_40 = pcStack_40 + 1;
    }
    lVar5 = FFWCaParse_parseCategoryArg__FP14FFWCaQueryInfoiiPCc(qinfo,0,1,pcStack_40);
    if (lVar5 != 0) {
      *qinfo = *qinfo | 1;
      pcStack_40 = (char *)lVar5;
    }
  } while( true );
}



// ---------------------------------------------------------------------------
// _wcaBuilfQueryBlock
// _wcaBuilfQueryBlock(FFWCaQueryInfo *, unsigned char *, unsigned char, unsigned char)
//   symbol: _wcaBuilfQueryBlock__FP14FFWCaQueryInfoPUcUcUc
//   rva:    0x001cabd0  size: 7372 bytes  tool: ghidra-12.0.4
//   source: main/net/game_prot/wcaQueryBuilder.c
// ---------------------------------------------------------------------------


int _wcaBuilfQueryBlock__FP14FFWCaQueryInfoPUcUcUc
              (uint *qinfo,byte *blkTop,byte catBitW,byte extCat)

{
  byte bVar1;
  short sVar2;
  short sVar3;
  ushort uVar4;
  short sVar5;
  uint uVar6;
  size_t sVar7;
  uint uVar8;
  uint uVar9;
  byte bVar10;
  byte *pbVar11;
  uint *puVar12;
  int iVar13;
  int iStack_60;
  int iStack_5c;
  int iStack_58;
  int iStack_54;
  int iStack_50;
  int iStack_4c;
  int iStack_48;
  int iStack_44;
  
  for (iStack_60 = 0; iStack_60 < (int)(uint)(ushort)qinfo[8]; iStack_60 = iStack_60 + 1) {
    if ((*(byte *)((int)qinfo + iStack_60 + 4) & 0x1f) == 0) goto LAB_002cac8c;
  }
  uVar9 = qinfo[8];
  *(ushort *)(qinfo + 8) = (ushort)uVar9 + 1;
  *(undefined1 *)((int)qinfo + (ushort)uVar9 + 4) = 0;
LAB_002cac8c:
  if ((*qinfo & 0x10) != 0) {
    for (iStack_5c = 0; iStack_5c < (int)(uint)(ushort)qinfo[8]; iStack_5c = iStack_5c + 1) {
      if ((*(byte *)((int)qinfo + iStack_5c + 4) & 0x1f) == 4) goto LAB_002cad1c;
    }
    uVar9 = qinfo[8];
    *(ushort *)(qinfo + 8) = (ushort)uVar9 + 1;
    *(undefined1 *)((int)qinfo + (ushort)uVar9 + 4) = 4;
  }
LAB_002cad1c:
  if ((*qinfo & 8) != 0) {
    for (iStack_58 = 0; iStack_58 < (int)(uint)(ushort)qinfo[8]; iStack_58 = iStack_58 + 1) {
      if ((*(byte *)((int)qinfo + iStack_58 + 4) & 0x1f) == 3) goto LAB_002cadac;
    }
    uVar9 = qinfo[8];
    *(ushort *)(qinfo + 8) = (ushort)uVar9 + 1;
    *(undefined1 *)((int)qinfo + (ushort)uVar9 + 4) = 3;
  }
LAB_002cadac:
  if ((*qinfo & 4) != 0) {
    for (iStack_54 = 0; iStack_54 < (int)(uint)(ushort)qinfo[8]; iStack_54 = iStack_54 + 1) {
      if ((*(byte *)((int)qinfo + iStack_54 + 4) & 0x1f) == 2) goto LAB_002cae3c;
    }
    uVar9 = qinfo[8];
    *(ushort *)(qinfo + 8) = (ushort)uVar9 + 1;
    *(undefined1 *)((int)qinfo + (ushort)uVar9 + 4) = 2;
  }
LAB_002cae3c:
  if ((*qinfo & 0x20) != 0) {
    for (iStack_50 = 0; iStack_50 < (int)(uint)(ushort)qinfo[8]; iStack_50 = iStack_50 + 1) {
      if ((*(byte *)((int)qinfo + iStack_50 + 4) & 0x1f) == 5) goto LAB_002caecc;
    }
    uVar9 = qinfo[8];
    *(ushort *)(qinfo + 8) = (ushort)uVar9 + 1;
    *(undefined1 *)((int)qinfo + (ushort)uVar9 + 4) = 5;
  }
LAB_002caecc:
  if ((*qinfo & 2) != 0) {
    for (iStack_4c = 0; iStack_4c < (int)(uint)(ushort)qinfo[8]; iStack_4c = iStack_4c + 1) {
      if ((*(byte *)((int)qinfo + iStack_4c + 4) & 0x1f) == 1) goto LAB_002caf5c;
    }
    uVar9 = qinfo[8];
    *(ushort *)(qinfo + 8) = (ushort)uVar9 + 1;
    *(undefined1 *)((int)qinfo + (ushort)uVar9 + 4) = 1;
  }
LAB_002caf5c:
  if ((*qinfo & 0x40) != 0) {
    for (iStack_48 = 0; iStack_48 < (int)(uint)(ushort)qinfo[8]; iStack_48 = iStack_48 + 1) {
      if ((*(byte *)((int)qinfo + iStack_48 + 4) & 0x1f) == 6) goto LAB_002cafec;
    }
    uVar9 = qinfo[8];
    *(ushort *)(qinfo + 8) = (ushort)uVar9 + 1;
    *(undefined1 *)((int)qinfo + (ushort)uVar9 + 4) = 6;
  }
LAB_002cafec:
  if ((extCat == 0) && ((*qinfo & 0x10000) != 0)) {
    for (iStack_44 = 0; iStack_44 < (int)(uint)(ushort)qinfo[8]; iStack_44 = iStack_44 + 1) {
      if ((*(byte *)((int)qinfo + iStack_44 + 4) & 0x1f) == 0x10) goto LAB_002cb090;
    }
    uVar9 = qinfo[8];
    *(ushort *)(qinfo + 8) = (ushort)uVar9 + 1;
    *(undefined1 *)((int)qinfo + (ushort)uVar9 + 4) = 0x10;
  }
LAB_002cb090:
  sVar5 = 8;
  uVar9 = 0;
  pbVar11 = blkTop;
  for (sVar3 = 0; (long)sVar3 < (long)(ulong)(ushort)qinfo[8]; sVar3 = sVar3 + 1) {
    bVar10 = *(byte *)((int)qinfo + sVar3 + 4);
    bVar1 = *(byte *)((int)qinfo + sVar3 + 4);
    uVar8 = bVar1 & 0x1f;
    if ((extCat == 0) || (uVar8 < extCat)) {
      uVar6 = uVar8;
      uVar4 = (ushort)catBitW;
      while( true ) {
        if ((short)uVar4 < 1) break;
        if (sVar5 < 8) {
          uVar9 = (uVar9 & 0x7f) << 1;
          sVar5 = sVar5 + 1;
        }
        else {
          *pbVar11 = (byte)uVar9;
          uVar9 = 0;
          sVar5 = 1;
          pbVar11 = pbVar11 + 1;
        }
        if ((uVar6 & 1 << (catBitW - 1 & 0x1f)) != 0) {
          uVar9 = uVar9 | 1;
        }
        uVar6 = uVar6 << 1;
        uVar4 = uVar4 - 1;
      }
      if (sVar5 < 8) {
        uVar9 = (uVar9 & 0x7f) << 1;
        sVar5 = sVar5 + 1;
      }
      else {
        *pbVar11 = (byte)uVar9;
        uVar9 = 0;
        sVar5 = 1;
        pbVar11 = pbVar11 + 1;
      }
      if ((bVar10 & 0x80) != 0) {
        uVar9 = uVar9 | 1;
      }
      if (sVar5 < 8) {
        uVar9 = (uVar9 & 0x7f) << 1;
        sVar5 = sVar5 + 1;
      }
      else {
        *pbVar11 = (byte)uVar9;
        uVar9 = 0;
        sVar5 = 1;
        pbVar11 = pbVar11 + 1;
      }
      if ((*qinfo & 1 << uVar8) != 0) {
        if (uVar8 == 6) {
          if (*(short *)((int)qinfo + 0x3a) != 0) {
            uVar9 = uVar9 | 1;
            uVar4 = *(ushort *)((int)qinfo + 0x3a);
            sVar2 = 0x10;
            while (0 < sVar2) {
              if (sVar5 < 8) {
                uVar9 = (uVar9 & 0x7f) << 1;
                sVar5 = sVar5 + 1;
              }
              else {
                *pbVar11 = (byte)uVar9;
                uVar9 = 0;
                sVar5 = 1;
                pbVar11 = pbVar11 + 1;
              }
              if ((uVar4 & 0x8000) != 0) {
                uVar9 = uVar9 | 1;
              }
              uVar4 = uVar4 << 1;
              sVar2 = sVar2 + -1;
            }
          }
        }
        else if (uVar8 == 5) {
          if (-1 < (short)qinfo[0xe]) {
            uVar9 = uVar9 | 1;
            uVar8 = (uint)(short)qinfo[0xe];
            sVar2 = 4;
            while (0 < sVar2) {
              if (sVar5 < 8) {
                uVar9 = (uVar9 & 0x7f) << 1;
                sVar5 = sVar5 + 1;
              }
              else {
                *pbVar11 = (byte)uVar9;
                uVar9 = 0;
                sVar5 = 1;
                pbVar11 = pbVar11 + 1;
              }
              if ((uVar8 & 8) != 0) {
                uVar9 = uVar9 | 1;
              }
              uVar8 = uVar8 << 1;
              sVar2 = sVar2 + -1;
            }
          }
        }
        else if (uVar8 == 0x10) {
          if ((-1 < (char)qinfo[0xf]) && (-1 < *(char *)((int)qinfo + 0x3d))) {
            uVar9 = uVar9 | 1;
            uVar8 = (uint)(char)qinfo[0xf];
            sVar2 = 8;
            while (0 < sVar2) {
              if (sVar5 < 8) {
                uVar9 = (uVar9 & 0x7f) << 1;
                sVar5 = sVar5 + 1;
              }
              else {
                *pbVar11 = (byte)uVar9;
                uVar9 = 0;
                sVar5 = 1;
                pbVar11 = pbVar11 + 1;
              }
              if ((uVar8 & 0x80) != 0) {
                uVar9 = uVar9 | 1;
              }
              uVar8 = uVar8 << 1;
              sVar2 = sVar2 + -1;
            }
            uVar8 = (uint)*(char *)((int)qinfo + 0x3d);
            sVar2 = 8;
            while (0 < sVar2) {
              if (sVar5 < 8) {
                uVar9 = (uVar9 & 0x7f) << 1;
                sVar5 = sVar5 + 1;
              }
              else {
                *pbVar11 = (byte)uVar9;
                uVar9 = 0;
                sVar5 = 1;
                pbVar11 = pbVar11 + 1;
              }
              if ((uVar8 & 0x80) != 0) {
                uVar9 = uVar9 | 1;
              }
              uVar8 = uVar8 << 1;
              sVar2 = sVar2 + -1;
            }
          }
        }
        else if (uVar8 == 4) {
          if ((-1 < (short)qinfo[7]) && (-1 < *(short *)((int)qinfo + 0x1e))) {
            uVar9 = uVar9 | 1;
            uVar8 = (uint)(short)qinfo[7];
            sVar2 = 8;
            while (0 < sVar2) {
              if (sVar5 < 8) {
                uVar9 = (uVar9 & 0x7f) << 1;
                sVar5 = sVar5 + 1;
              }
              else {
                *pbVar11 = (byte)uVar9;
                uVar9 = 0;
                sVar5 = 1;
                pbVar11 = pbVar11 + 1;
              }
              if ((uVar8 & 0x80) != 0) {
                uVar9 = uVar9 | 1;
              }
              uVar8 = uVar8 << 1;
              sVar2 = sVar2 + -1;
            }
            uVar8 = (uint)*(short *)((int)qinfo + 0x1e);
            sVar2 = 8;
            while (0 < sVar2) {
              if (sVar5 < 8) {
                uVar9 = (uVar9 & 0x7f) << 1;
                sVar5 = sVar5 + 1;
              }
              else {
                *pbVar11 = (byte)uVar9;
                uVar9 = 0;
                sVar5 = 1;
                pbVar11 = pbVar11 + 1;
              }
              if ((uVar8 & 0x80) != 0) {
                uVar9 = uVar9 | 1;
              }
              uVar8 = uVar8 << 1;
              sVar2 = sVar2 + -1;
            }
          }
        }
        else if (uVar8 == 3) {
          if (-1 < *(short *)((int)qinfo + 0x36)) {
            uVar9 = uVar9 | 1;
            uVar8 = (uint)*(short *)((int)qinfo + 0x36);
            sVar2 = 5;
            while (0 < sVar2) {
              if (sVar5 < 8) {
                uVar9 = (uVar9 & 0x7f) << 1;
                sVar5 = sVar5 + 1;
              }
              else {
                *pbVar11 = (byte)uVar9;
                uVar9 = 0;
                sVar5 = 1;
                pbVar11 = pbVar11 + 1;
              }
              if ((uVar8 & 0x10) != 0) {
                uVar9 = uVar9 | 1;
              }
              uVar8 = uVar8 << 1;
              sVar2 = sVar2 + -1;
            }
          }
        }
        else if (uVar8 == 2) {
          if (-1 < (short)qinfo[0xd]) {
            uVar9 = uVar9 | 1;
            uVar8 = (uint)(short)qinfo[0xd];
            sVar2 = 2;
            while (0 < sVar2) {
              if (sVar5 < 8) {
                uVar9 = (uVar9 & 0x7f) << 1;
                sVar5 = sVar5 + 1;
              }
              else {
                *pbVar11 = (byte)uVar9;
                uVar9 = 0;
                sVar5 = 1;
                pbVar11 = pbVar11 + 1;
              }
              if ((uVar8 & 2) != 0) {
                uVar9 = uVar9 | 1;
              }
              uVar8 = uVar8 << 1;
              sVar2 = sVar2 + -1;
            }
          }
        }
        else if (uVar8 == 1) {
          iVar13 = 0;
          while ((iVar13 < 8 && (-1 < *(short *)((int)qinfo + iVar13 * 2 + 0x24)))) {
            uVar9 = uVar9 | 1;
            uVar8 = (uint)*(short *)((int)qinfo + iVar13 * 2 + 0x24);
            sVar2 = 8;
            while (0 < sVar2) {
              if (sVar5 < 8) {
                uVar9 = (uVar9 & 0x7f) << 1;
                sVar5 = sVar5 + 1;
              }
              else {
                *pbVar11 = (byte)uVar9;
                uVar9 = 0;
                sVar5 = 1;
                pbVar11 = pbVar11 + 1;
              }
              if ((uVar8 & 0x80) != 0) {
                uVar9 = uVar9 | 1;
              }
              uVar8 = uVar8 << 1;
              sVar2 = sVar2 + -1;
            }
            uVar8 = 1;
            uVar4 = (ushort)catBitW;
            while( true ) {
              if ((short)uVar4 < 1) break;
              if (sVar5 < 8) {
                uVar9 = (uVar9 & 0x7f) << 1;
                sVar5 = sVar5 + 1;
              }
              else {
                *pbVar11 = (byte)uVar9;
                uVar9 = 0;
                sVar5 = 1;
                pbVar11 = pbVar11 + 1;
              }
              if ((uVar8 & 1 << (catBitW - 1 & 0x1f)) != 0) {
                uVar9 = uVar9 | 1;
              }
              uVar8 = uVar8 << 1;
              uVar4 = uVar4 - 1;
            }
            if (sVar5 < 8) {
              uVar9 = (uVar9 & 0x7f) << 1;
              sVar5 = sVar5 + 1;
            }
            else {
              *pbVar11 = (byte)uVar9;
              uVar9 = 0;
              sVar5 = 1;
              pbVar11 = pbVar11 + 1;
            }
            if ((bVar10 & 0x80) != 0) {
              uVar9 = uVar9 | 1;
            }
            if (sVar5 < 8) {
              uVar9 = (uVar9 & 0x7f) << 1;
              sVar5 = sVar5 + 1;
            }
            else {
              *pbVar11 = (byte)uVar9;
              uVar9 = 0;
              sVar5 = 1;
              pbVar11 = pbVar11 + 1;
            }
            iVar13 = iVar13 + 1;
          }
        }
        else if (((bVar1 & 0x1f) == 0) && ((char)qinfo[3] != '\0')) {
          if (sVar5 < 8) {
            uVar9 = (uVar9 & 0x7f | 1) << 1;
            sVar5 = sVar5 + 1;
          }
          else {
            *pbVar11 = (byte)uVar9 | 1;
            uVar9 = 0;
            sVar5 = 1;
            pbVar11 = pbVar11 + 1;
          }
          if ((*(ushort *)((int)qinfo + 0x3e) & 1) != 0) {
            uVar9 = uVar9 | 1;
          }
          sVar7 = strlen((char *)(qinfo + 3));
          sVar2 = 4;
          while (0 < sVar2) {
            if (sVar5 < 8) {
              uVar9 = (uVar9 & 0x7f) << 1;
              sVar5 = sVar5 + 1;
            }
            else {
              *pbVar11 = (byte)uVar9;
              uVar9 = 0;
              sVar5 = 1;
              pbVar11 = pbVar11 + 1;
            }
            if ((sVar7 & 8) != 0) {
              uVar9 = uVar9 | 1;
            }
            sVar7 = (size_t)((int)sVar7 << 1);
            sVar2 = sVar2 + -1;
          }
          for (puVar12 = qinfo + 3; (char)*puVar12 != '\0'; puVar12 = (uint *)((int)puVar12 + 1))
          {
            bVar10 = (byte)*puVar12;
            sVar2 = 7;
            while (0 < sVar2) {
              if (sVar5 < 8) {
                uVar9 = (uVar9 & 0x7f) << 1;
                sVar5 = sVar5 + 1;
              }
              else {
                *pbVar11 = (byte)uVar9;
                uVar9 = 0;
                sVar5 = 1;
                pbVar11 = pbVar11 + 1;
              }
              if ((bVar10 & 0x40) != 0) {
                uVar9 = uVar9 | 1;
              }
              bVar10 = bVar10 << 1;
              sVar2 = sVar2 + -1;
            }
          }
        }
      }
    }
  }
  if ((*qinfo & 0x800) != 0) {
    if (extCat == 0) {
      uVar8 = 0xb;
      uVar4 = (ushort)catBitW;
      while (0 < (short)uVar4) {
        if (sVar5 < 8) {
          uVar9 = (uVar9 & 0x7f) << 1;
          sVar5 = sVar5 + 1;
        }
        else {
          *pbVar11 = (byte)uVar9;
          uVar9 = 0;
          sVar5 = 1;
          pbVar11 = pbVar11 + 1;
        }
        if ((uVar8 & 1 << (catBitW - 1 & 0x1f)) != 0) {
          uVar9 = uVar9 | 1;
        }
        uVar8 = uVar8 << 1;
        uVar4 = uVar4 - 1;
      }
    }
    else {
      uVar8 = (uint)extCat;
      uVar4 = (ushort)catBitW;
      while (0 < (short)uVar4) {
        if (sVar5 < 8) {
          uVar9 = (uVar9 & 0x7f) << 1;
          sVar5 = sVar5 + 1;
        }
        else {
          *pbVar11 = (byte)uVar9;
          uVar9 = 0;
          sVar5 = 1;
          pbVar11 = pbVar11 + 1;
        }
        if ((uVar8 & 1 << (catBitW - 1 & 0x1f)) != 0) {
          uVar9 = uVar9 | 1;
        }
        uVar8 = uVar8 << 1;
        uVar4 = uVar4 - 1;
      }
      uVar8 = 3;
      uVar4 = (ushort)catBitW;
      while (0 < (short)uVar4) {
        if (sVar5 < 8) {
          uVar9 = (uVar9 & 0x7f) << 1;
          sVar5 = sVar5 + 1;
        }
        else {
          *pbVar11 = (byte)uVar9;
          uVar9 = 0;
          sVar5 = 1;
          pbVar11 = pbVar11 + 1;
        }
        if ((uVar8 & 1 << (catBitW - 1 & 0x1f)) != 0) {
          uVar9 = uVar9 | 1;
        }
        uVar8 = uVar8 << 1;
        uVar4 = uVar4 - 1;
      }
    }
    uVar8 = qinfo[0x10];
    sVar3 = 0x20;
    while (0 < sVar3) {
      if (sVar5 < 8) {
        uVar9 = (uVar9 & 0x7f) << 1;
        sVar5 = sVar5 + 1;
      }
      else {
        *pbVar11 = (byte)uVar9;
        uVar9 = 0;
        sVar5 = 1;
        pbVar11 = pbVar11 + 1;
      }
      if ((uVar8 & 0x80000000) != 0) {
        uVar9 = uVar9 | 1;
      }
      uVar8 = uVar8 << 1;
      sVar3 = sVar3 + -1;
    }
  }
  if ((*qinfo & 0x1000) != 0) {
    if (extCat == 0) {
      uVar8 = 0xc;
      uVar4 = (ushort)catBitW;
      while (0 < (short)uVar4) {
        if (sVar5 < 8) {
          uVar9 = (uVar9 & 0x7f) << 1;
          sVar5 = sVar5 + 1;
        }
        else {
          *pbVar11 = (byte)uVar9;
          uVar9 = 0;
          sVar5 = 1;
          pbVar11 = pbVar11 + 1;
        }
        if ((uVar8 & 1 << (catBitW - 1 & 0x1f)) != 0) {
          uVar9 = uVar9 | 1;
        }
        uVar8 = uVar8 << 1;
        uVar4 = uVar4 - 1;
      }
    }
    else {
      uVar8 = (uint)extCat;
      uVar4 = (ushort)catBitW;
      while (0 < (short)uVar4) {
        if (sVar5 < 8) {
          uVar9 = (uVar9 & 0x7f) << 1;
          sVar5 = sVar5 + 1;
        }
        else {
          *pbVar11 = (byte)uVar9;
          uVar9 = 0;
          sVar5 = 1;
          pbVar11 = pbVar11 + 1;
        }
        if ((uVar8 & 1 << (catBitW - 1 & 0x1f)) != 0) {
          uVar9 = uVar9 | 1;
        }
        uVar8 = uVar8 << 1;
        uVar4 = uVar4 - 1;
      }
      uVar8 = 4;
      uVar4 = (ushort)catBitW;
      while (0 < (short)uVar4) {
        if (sVar5 < 8) {
          uVar9 = (uVar9 & 0x7f) << 1;
          sVar5 = sVar5 + 1;
        }
        else {
          *pbVar11 = (byte)uVar9;
          uVar9 = 0;
          sVar5 = 1;
          pbVar11 = pbVar11 + 1;
        }
        if ((uVar8 & 1 << (catBitW - 1 & 0x1f)) != 0) {
          uVar9 = uVar9 | 1;
        }
        uVar8 = uVar8 << 1;
        uVar4 = uVar4 - 1;
      }
    }
  }
  if (((*qinfo & 0x20000) != 0) && (extCat == 0)) {
    uVar8 = 0x11;
    uVar4 = (ushort)catBitW;
    while (0 < (short)uVar4) {
      if (sVar5 < 8) {
        uVar9 = (uVar9 & 0x7f) << 1;
        sVar5 = sVar5 + 1;
      }
      else {
        *pbVar11 = (byte)uVar9;
        uVar9 = 0;
        sVar5 = 1;
        pbVar11 = pbVar11 + 1;
      }
      if ((uVar8 & 1 << (catBitW - 1 & 0x1f)) != 0) {
        uVar9 = uVar9 | 1;
      }
      uVar8 = uVar8 << 1;
      uVar4 = uVar4 - 1;
    }
    uVar8 = qinfo[0x11];
    sVar3 = 0x20;
    while (0 < sVar3) {
      if (sVar5 < 8) {
        uVar9 = (uVar9 & 0x7f) << 1;
        sVar5 = sVar5 + 1;
      }
      else {
        *pbVar11 = (byte)uVar9;
        uVar9 = 0;
        sVar5 = 1;
        pbVar11 = pbVar11 + 1;
      }
      if ((uVar8 & 0x80000000) != 0) {
        uVar9 = uVar9 | 1;
      }
      uVar8 = uVar8 << 1;
      sVar3 = sVar3 + -1;
    }
  }
  do {
    if (sVar5 < 8) {
      uVar9 = (uVar9 & 0x7f) << 1;
      sVar5 = sVar5 + 1;
    }
    else {
      *pbVar11 = (byte)uVar9;
      uVar9 = 0;
      sVar5 = 1;
      pbVar11 = pbVar11 + 1;
    }
  } while (1 < sVar5);
  *blkTop = ((char)pbVar11 - (char)blkTop) - 1;
  return (int)pbVar11 - (int)blkTop;
}



// ---------------------------------------------------------------------------
// FFWCaBuildQueryBlock_V100
//   symbol: FFWCaBuildQueryBlock_V100
//   rva:    0x001cc8a0  size: 56 bytes  tool: ghidra-12.0.4
//   source: main/net/game_prot/wcaQueryBuilder.c
// ---------------------------------------------------------------------------


void FFWCaBuildQueryBlock_V100(undefined4 qinfo,undefined4 blkTop)

{
  _wcaBuilfQueryBlock__FP14FFWCaQueryInfoPUcUcUc(qinfo,blkTop,5,0);
  return;
}



// ---------------------------------------------------------------------------
// _wcaDecodeReplyBlock
// _wcaDecodeReplyBlock(const unsigned char *, FFWCaReplyInfo *, unsigned short, unsigned char, unsigned char)
//   symbol: _wcaDecodeReplyBlock__FPCUcP14FFWCaReplyInfoUsUcUc
//   rva:    0x001cc8e0  size: 5484 bytes  tool: ghidra-12.0.4
//   source: main/net/game_prot/wcaQueryBuilder.c
// ---------------------------------------------------------------------------


byte * _wcaDecodeReplyBlock__FPCUcP14FFWCaReplyInfoUsUcUc
                 (byte *blkTop,uint *rpl,short withId,byte catBitW,byte extCat)

{
  ushort uVar1;
  ushort uVar2;
  short sVar3;
  short sVar4;
  uint uVar5;
  byte bVar6;
  uint uVar7;
  ushort uVar8;
  short sVar9;
  ushort uVar10;
  ushort uVar11;
  uint uStack_5c;
  uint *puStack_58;
  byte bStack_51;
  
  memset(rpl,0,0x30);
  uVar1 = (ushort)*blkTop;
  sVar3 = 8;
  uVar5 = 0;
  while (-1 < (short)uVar1) {
    uVar10 = 0;
    uVar11 = (ushort)catBitW;
    while (uVar8 = uVar11 - 1, 0 < (short)uVar11) {
      if (sVar3 < 8) {
        uVar5 = (uVar5 & 0x7f) << 1;
        sVar3 = sVar3 + 1;
      }
      else {
        if ((short)uVar1 < 1) {
          return (byte *)0x0;
        }
        blkTop = blkTop + 1;
        uVar5 = (uint)*blkTop;
        uVar1 = uVar1 - 1;
        sVar3 = 1;
      }
      uVar10 = uVar10 << 1;
      uVar11 = uVar8;
      if ((uVar5 & 0x80) != 0) {
        uVar10 = uVar10 | 1;
      }
    }
    if ((extCat == 0) || (extCat != uVar10)) {
      if ((*rpl & 1 << ((int)(short)uVar10 & 0x1fU)) != 0) break;
      *rpl = *rpl | 1 << ((int)(short)uVar10 & 0x1fU);
    }
    if ((extCat != 0) && (extCat == uVar10)) {
      uVar8 = 0;
      uVar11 = (ushort)catBitW;
      while (uVar2 = uVar11 - 1, 0 < (short)uVar11) {
        if (sVar3 < 8) {
          uVar7 = uVar5 << 1;
          sVar3 = sVar3 + 1;
        }
        else {
          if ((short)uVar1 < 1) {
            return (byte *)0x0;
          }
          blkTop = blkTop + 1;
          uVar7 = (uint)*blkTop;
          uVar1 = uVar1 - 1;
          sVar3 = 1;
        }
        uVar5 = uVar7 & 0xff;
        uVar8 = uVar8 << 1;
        uVar11 = uVar2;
        if ((uVar7 & 0x80) != 0) {
          uVar8 = uVar8 | 1;
        }
      }
      uVar8 = uVar8 | 8;
      if (uVar8 == 0xe) {
        uStack_5c = 0;
        sVar9 = 0x20;
        while (sVar4 = sVar9 + -1, 0 < sVar9) {
          if (sVar3 < 8) {
            uVar7 = uVar5 << 1;
            sVar3 = sVar3 + 1;
          }
          else {
            if ((short)uVar1 < 1) {
              return (byte *)0x0;
            }
            blkTop = blkTop + 1;
            uVar7 = (uint)*blkTop;
            uVar1 = uVar1 - 1;
            sVar3 = 1;
          }
          uVar5 = uVar7 & 0xff;
          uStack_5c = uStack_5c << 1;
          sVar9 = sVar4;
          if ((uVar7 & 0x80) != 0) {
            uStack_5c = uStack_5c | 1;
          }
        }
        *rpl = *rpl | 0x4000;
        rpl[10] = uStack_5c;
      }
      else if (uVar8 == 0xd) {
        bStack_51 = 0;
        sVar9 = 8;
        while (sVar4 = sVar9 + -1, 0 < sVar9) {
          if (sVar3 < 8) {
            uVar7 = uVar5 << 1;
            sVar3 = sVar3 + 1;
          }
          else {
            if ((short)uVar1 < 1) {
              return (byte *)0x0;
            }
            blkTop = blkTop + 1;
            uVar7 = (uint)*blkTop;
            uVar1 = uVar1 - 1;
            sVar3 = 1;
          }
          uVar5 = uVar7 & 0xff;
          bStack_51 = bStack_51 << 1;
          sVar9 = sVar4;
          if ((uVar7 & 0x80) != 0) {
            bStack_51 = bStack_51 | 1;
          }
        }
        *rpl = *rpl | 0x2000;
        *(byte *)((int)rpl + 0x26) = bStack_51;
      }
      else if (uVar8 == 8) {
        uVar11 = 0;
        sVar9 = 0x10;
        while (sVar4 = sVar9 + -1, 0 < sVar9) {
          if (sVar3 < 8) {
            uVar7 = uVar5 << 1;
            sVar3 = sVar3 + 1;
          }
          else {
            if ((short)uVar1 < 1) {
              return (byte *)0x0;
            }
            blkTop = blkTop + 1;
            uVar7 = (uint)*blkTop;
            uVar1 = uVar1 - 1;
            sVar3 = 1;
          }
          uVar5 = uVar7 & 0xff;
          uVar11 = uVar11 << 1;
          sVar9 = sVar4;
          if ((uVar7 & 0x80) != 0) {
            uVar11 = uVar11 | 1;
          }
        }
        if (withId != 0) {
          *rpl = *rpl | 0x100;
          *(ushort *)(rpl + 9) = uVar11;
        }
      }
    }
    switch(uVar10) {
    case 0:
      puStack_58 = rpl + 1;
      uVar11 = 0;
      sVar9 = 4;
      while (sVar4 = sVar9 + -1, 0 < sVar9) {
        if (sVar3 < 8) {
          uVar7 = uVar5 << 1;
          sVar3 = sVar3 + 1;
        }
        else {
          if ((short)uVar1 < 1) {
            return (byte *)0x0;
          }
          blkTop = blkTop + 1;
          uVar7 = (uint)*blkTop;
          uVar1 = uVar1 - 1;
          sVar3 = 1;
        }
        uVar5 = uVar7 & 0xff;
        uVar11 = uVar11 << 1;
        sVar9 = sVar4;
        if ((uVar7 & 0x80) != 0) {
          uVar11 = uVar11 | 1;
        }
      }
      while (0 < (short)uVar11) {
        bVar6 = 0;
        sVar9 = 7;
        while (sVar4 = sVar9 + -1, 0 < sVar9) {
          if (sVar3 < 8) {
            uVar7 = uVar5 << 1;
            sVar3 = sVar3 + 1;
          }
          else {
            if ((short)uVar1 < 1) {
              return (byte *)0x0;
            }
            blkTop = blkTop + 1;
            uVar7 = (uint)*blkTop;
            uVar1 = uVar1 - 1;
            sVar3 = 1;
          }
          uVar5 = uVar7 & 0xff;
          bVar6 = bVar6 << 1;
          sVar9 = sVar4;
          if ((uVar7 & 0x80) != 0) {
            bVar6 = bVar6 | 1;
          }
        }
        *(byte *)puStack_58 = bVar6 & 0x7f;
        puStack_58 = (uint *)((int)puStack_58 + 1);
        uVar11 = uVar11 - 1;
      }
      *(undefined1 *)puStack_58 = 0;
      break;
    case 1:
      *(undefined2 *)(rpl + 5) = 0;
      sVar9 = 8;
      while (sVar4 = sVar9 + -1, 0 < sVar9) {
        if (sVar3 < 8) {
          uVar7 = uVar5 << 1;
          sVar3 = sVar3 + 1;
        }
        else {
          if ((short)uVar1 < 1) {
            return (byte *)0x0;
          }
          blkTop = blkTop + 1;
          uVar7 = (uint)*blkTop;
          uVar1 = uVar1 - 1;
          sVar3 = 1;
        }
        uVar5 = uVar7 & 0xff;
        *(short *)(rpl + 5) = (short)rpl[5] << 1;
        sVar9 = sVar4;
        if ((uVar7 & 0x80) != 0) {
          *(ushort *)(rpl + 5) = (ushort)rpl[5] | 1;
        }
      }
      break;
    case 2:
      *(undefined2 *)((int)rpl + 0x16) = 0;
      sVar9 = 2;
      while (sVar4 = sVar9 + -1, 0 < sVar9) {
        if (sVar3 < 8) {
          uVar7 = uVar5 << 1;
          sVar3 = sVar3 + 1;
        }
        else {
          if ((short)uVar1 < 1) {
            return (byte *)0x0;
          }
          blkTop = blkTop + 1;
          uVar7 = (uint)*blkTop;
          uVar1 = uVar1 - 1;
          sVar3 = 1;
        }
        uVar5 = uVar7 & 0xff;
        *(short *)((int)rpl + 0x16) = *(short *)((int)rpl + 0x16) << 1;
        sVar9 = sVar4;
        if ((uVar7 & 0x80) != 0) {
          *(ushort *)((int)rpl + 0x16) = *(ushort *)((int)rpl + 0x16) | 1;
        }
      }
      break;
    case 3:
      *(undefined2 *)(rpl + 6) = 0;
      sVar9 = 5;
      while (sVar4 = sVar9 + -1, 0 < sVar9) {
        if (sVar3 < 8) {
          uVar7 = uVar5 << 1;
          sVar3 = sVar3 + 1;
        }
        else {
          if ((short)uVar1 < 1) {
            return (byte *)0x0;
          }
          blkTop = blkTop + 1;
          uVar7 = (uint)*blkTop;
          uVar1 = uVar1 - 1;
          sVar3 = 1;
        }
        uVar5 = uVar7 & 0xff;
        *(short *)(rpl + 6) = (short)rpl[6] << 1;
        sVar9 = sVar4;
        if ((uVar7 & 0x80) != 0) {
          *(ushort *)(rpl + 6) = (ushort)rpl[6] | 1;
        }
      }
      *(undefined2 *)((int)rpl + 0x1a) = 0;
      sVar9 = 5;
      while (sVar4 = sVar9 + -1, 0 < sVar9) {
        if (sVar3 < 8) {
          uVar7 = uVar5 << 1;
          sVar3 = sVar3 + 1;
        }
        else {
          if ((short)uVar1 < 1) {
            return (byte *)0x0;
          }
          blkTop = blkTop + 1;
          uVar7 = (uint)*blkTop;
          uVar1 = uVar1 - 1;
          sVar3 = 1;
        }
        uVar5 = uVar7 & 0xff;
        *(short *)((int)rpl + 0x1a) = *(short *)((int)rpl + 0x1a) << 1;
        sVar9 = sVar4;
        if ((uVar7 & 0x80) != 0) {
          *(ushort *)((int)rpl + 0x1a) = *(ushort *)((int)rpl + 0x1a) | 1;
        }
      }
      break;
    case 4:
      *(undefined2 *)(rpl + 7) = 0;
      sVar9 = 8;
      while (sVar4 = sVar9 + -1, 0 < sVar9) {
        if (sVar3 < 8) {
          uVar7 = uVar5 << 1;
          sVar3 = sVar3 + 1;
        }
        else {
          if ((short)uVar1 < 1) {
            return (byte *)0x0;
          }
          blkTop = blkTop + 1;
          uVar7 = (uint)*blkTop;
          uVar1 = uVar1 - 1;
          sVar3 = 1;
        }
        uVar5 = uVar7 & 0xff;
        *(short *)(rpl + 7) = (short)rpl[7] << 1;
        sVar9 = sVar4;
        if ((uVar7 & 0x80) != 0) {
          *(ushort *)(rpl + 7) = (ushort)rpl[7] | 1;
        }
      }
      *(undefined2 *)((int)rpl + 0x1e) = 0;
      sVar9 = 8;
      while (sVar4 = sVar9 + -1, 0 < sVar9) {
        if (sVar3 < 8) {
          uVar7 = uVar5 << 1;
          sVar3 = sVar3 + 1;
        }
        else {
          if ((short)uVar1 < 1) {
            return (byte *)0x0;
          }
          blkTop = blkTop + 1;
          uVar7 = (uint)*blkTop;
          uVar1 = uVar1 - 1;
          sVar3 = 1;
        }
        uVar5 = uVar7 & 0xff;
        *(short *)((int)rpl + 0x1e) = *(short *)((int)rpl + 0x1e) << 1;
        sVar9 = sVar4;
        if ((uVar7 & 0x80) != 0) {
          *(ushort *)((int)rpl + 0x1e) = *(ushort *)((int)rpl + 0x1e) | 1;
        }
      }
      break;
    case 5:
      *(undefined2 *)(rpl + 8) = 0;
      sVar9 = 4;
      while (sVar4 = sVar9 + -1, 0 < sVar9) {
        if (sVar3 < 8) {
          uVar7 = uVar5 << 1;
          sVar3 = sVar3 + 1;
        }
        else {
          if ((short)uVar1 < 1) {
            return (byte *)0x0;
          }
          blkTop = blkTop + 1;
          uVar7 = (uint)*blkTop;
          uVar1 = uVar1 - 1;
          sVar3 = 1;
        }
        uVar5 = uVar7 & 0xff;
        *(short *)(rpl + 8) = (short)rpl[8] << 1;
        sVar9 = sVar4;
        if ((uVar7 & 0x80) != 0) {
          *(ushort *)(rpl + 8) = (ushort)rpl[8] | 1;
        }
      }
      break;
    case 6:
      *(undefined2 *)((int)rpl + 0x22) = 0;
      sVar9 = 0x10;
      while (sVar4 = sVar9 + -1, 0 < sVar9) {
        if (sVar3 < 8) {
          uVar7 = uVar5 << 1;
          sVar3 = sVar3 + 1;
        }
        else {
          if ((short)uVar1 < 1) {
            return (byte *)0x0;
          }
          blkTop = blkTop + 1;
          uVar7 = (uint)*blkTop;
          uVar1 = uVar1 - 1;
          sVar3 = 1;
        }
        uVar5 = uVar7 & 0xff;
        *(short *)((int)rpl + 0x22) = *(short *)((int)rpl + 0x22) << 1;
        sVar9 = sVar4;
        if ((uVar7 & 0x80) != 0) {
          *(ushort *)((int)rpl + 0x22) = *(ushort *)((int)rpl + 0x22) | 1;
        }
      }
      break;
    case 8:
      *(undefined2 *)(rpl + 9) = 0;
      sVar9 = 0x10;
      while (sVar4 = sVar9 + -1, 0 < sVar9) {
        if (sVar3 < 8) {
          uVar7 = uVar5 << 1;
          sVar3 = sVar3 + 1;
        }
        else {
          if ((short)uVar1 < 1) {
            return (byte *)0x0;
          }
          blkTop = blkTop + 1;
          uVar7 = (uint)*blkTop;
          uVar1 = uVar1 - 1;
          sVar3 = 1;
        }
        uVar5 = uVar7 & 0xff;
        *(short *)(rpl + 9) = (short)rpl[9] << 1;
        sVar9 = sVar4;
        if ((uVar7 & 0x80) != 0) {
          *(ushort *)(rpl + 9) = (ushort)rpl[9] | 1;
        }
      }
      break;
    case 0xd:
      *(undefined1 *)((int)rpl + 0x26) = 0;
      sVar9 = 8;
      while (sVar4 = sVar9 + -1, 0 < sVar9) {
        if (sVar3 < 8) {
          uVar7 = uVar5 << 1;
          sVar3 = sVar3 + 1;
        }
        else {
          if ((short)uVar1 < 1) {
            return (byte *)0x0;
          }
          blkTop = blkTop + 1;
          uVar7 = (uint)*blkTop;
          uVar1 = uVar1 - 1;
          sVar3 = 1;
        }
        uVar5 = uVar7 & 0xff;
        *(char *)((int)rpl + 0x26) = *(char *)((int)rpl + 0x26) << 1;
        sVar9 = sVar4;
        if ((uVar7 & 0x80) != 0) {
          *(byte *)((int)rpl + 0x26) = *(byte *)((int)rpl + 0x26) | 1;
        }
      }
      break;
    case 0xe:
      rpl[10] = 0;
      sVar9 = 0x20;
      while (sVar4 = sVar9 + -1, 0 < sVar9) {
        if (sVar3 < 8) {
          uVar7 = uVar5 << 1;
          sVar3 = sVar3 + 1;
        }
        else {
          if ((short)uVar1 < 1) {
            return (byte *)0x0;
          }
          blkTop = blkTop + 1;
          uVar7 = (uint)*blkTop;
          uVar1 = uVar1 - 1;
          sVar3 = 1;
        }
        uVar5 = uVar7 & 0xff;
        rpl[10] = rpl[10] << 1;
        sVar9 = sVar4;
        if ((uVar7 & 0x80) != 0) {
          rpl[10] = rpl[10] | 1;
        }
      }
      break;
    case 0x10:
      *(undefined1 *)((int)rpl + 0x27) = 0;
      sVar9 = 8;
      while (sVar4 = sVar9 + -1, 0 < sVar9) {
        if (sVar3 < 8) {
          uVar7 = uVar5 << 1;
          sVar3 = sVar3 + 1;
        }
        else {
          if ((short)uVar1 < 1) {
            return (byte *)0x0;
          }
          blkTop = blkTop + 1;
          uVar7 = (uint)*blkTop;
          uVar1 = uVar1 - 1;
          sVar3 = 1;
        }
        uVar5 = uVar7 & 0xff;
        *(char *)((int)rpl + 0x27) = *(char *)((int)rpl + 0x27) << 1;
        sVar9 = sVar4;
        if ((uVar7 & 0x80) != 0) {
          *(byte *)((int)rpl + 0x27) = *(byte *)((int)rpl + 0x27) | 1;
        }
      }
      break;
    case 0x11:
      rpl[0xb] = 0;
      sVar9 = 0x20;
      while (sVar4 = sVar9 + -1, 0 < sVar9) {
        if (sVar3 < 8) {
          uVar7 = uVar5 << 1;
          sVar3 = sVar3 + 1;
        }
        else {
          if ((short)uVar1 < 1) {
            return (byte *)0x0;
          }
          blkTop = blkTop + 1;
          uVar7 = (uint)*blkTop;
          uVar1 = uVar1 - 1;
          sVar3 = 1;
        }
        uVar5 = uVar7 & 0xff;
        rpl[0xb] = rpl[0xb] << 1;
        sVar9 = sVar4;
        if ((uVar7 & 0x80) != 0) {
          rpl[0xb] = rpl[0xb] | 1;
        }
      }
    }
  }
  return blkTop + 1;
}



// ---------------------------------------------------------------------------
// FFWCaDecodeReplyBlock_V100
//   symbol: FFWCaDecodeReplyBlock_V100
//   rva:    0x001cde50  size: 64 bytes  tool: ghidra-12.0.4
//   source: main/net/game_prot/wcaQueryBuilder.c
// ---------------------------------------------------------------------------


void FFWCaDecodeReplyBlock_V100(undefined4 blkTop,undefined4 rpl,undefined2 withId)

{
  _wcaDecodeReplyBlock__FPCUcP14FFWCaReplyInfoUsUcUc(blkTop,rpl,withId,5,0);
  return;
}



// ---------------------------------------------------------------------------
// FFWCaDecodeReplyItemBlock2
//   symbol: FFWCaDecodeReplyItemBlock2
//   rva:    0x001cde90  size: 292 bytes  tool: ghidra-12.0.4
//   source: main/net/game_prot/wcaQueryBuilder.c
// ---------------------------------------------------------------------------


uint FFWCaDecodeReplyItemBlock2(void *blkTop,uint blkEnd,ushort *rpl)

{
  uint uVar1;
  
  if (*rpl < 0x14) {
    memcpy(rpl + (uint)*rpl * 6 + 2,blkTop,2);
    memcpy(rpl + (uint)*rpl * 6 + 4,(void *)((int)blkTop + 2),4);
    memcpy(rpl + (uint)*rpl * 6 + 6,(void *)((int)blkTop + 6),4);
    uVar1 = (int)blkTop + 10;
    if (uVar1 <= blkEnd) {
      *rpl = *rpl + 1;
    }
  }
  else {
    uVar1 = 0;
  }
  return uVar1;
}



// ---------------------------------------------------------------------------
// FFWCaDecodeReplyItemHistBlock2
//   symbol: FFWCaDecodeReplyItemHistBlock2
//   rva:    0x001cdfc0  size: 408 bytes  tool: ghidra-12.0.4
//   source: main/net/game_prot/wcaQueryBuilder.c
// ---------------------------------------------------------------------------


void * FFWCaDecodeReplyItemHistBlock2(void *blkTop,void *blkEnd,ushort *rpl)

{
  if (*rpl == 0) {
    memcpy(rpl + 1,blkTop,2);
    blkTop = (void *)((int)blkTop + 2);
  }
  while ((blkTop < blkEnd && (*rpl < 10))) {
    memcpy(rpl + (uint)*rpl * 0x14 + 2,blkTop,4);
    memcpy(rpl + (uint)*rpl * 0x14 + 4,(void *)((int)blkTop + 4),4);
    memcpy(rpl + (uint)*rpl * 0x14 + 6,(void *)((int)blkTop + 8),0x10);
    memcpy(rpl + (uint)*rpl * 0x14 + 0xe,(void *)((int)blkTop + 0x18),0x10);
    blkTop = (void *)((int)blkTop + 0x28);
    if (blkTop <= blkEnd) {
      *rpl = *rpl + 1;
    }
  }
  return blkTop;
}



// ---------------------------------------------------------------------------
// FFWCaDecodeReplyUserMessageInfo
//   symbol: FFWCaDecodeReplyUserMessageInfo
//   rva:    0x001ce160  size: 228 bytes  tool: ghidra-12.0.4
//   source: main/net/game_prot/wcaQueryBuilder.c
// ---------------------------------------------------------------------------


void * FFWCaDecodeReplyUserMessageInfo(void *blkTop,void *blkEnd,void *rpl)

{
  ushort uStack_32;
  void *pvStack_30;
  void *pvStack_20;
  void *pvStack_10;
  
  *(undefined1 *)((int)rpl + 2) = 0;
  if (blkTop < blkEnd) {
    pvStack_30 = blkTop;
    pvStack_20 = blkEnd;
    pvStack_10 = rpl;
    memcpy(rpl,blkTop,2);
    memcpy(&uStack_32,(void *)((int)blkTop + 2),2);
    blkTop = (void *)((int)blkTop + 4);
    if (0x80 < uStack_32) {
      uStack_32 = 0x80;
    }
    if ((void *)((int)blkTop + (uint)uStack_32) <= pvStack_20) {
      memcpy((void *)((int)pvStack_10 + 2),blkTop,(ulong)uStack_32);
      blkTop = (void *)((int)blkTop + (uint)uStack_32);
      *(undefined1 *)((int)pvStack_10 + 0x81) = 0;
    }
  }
  return blkTop;
}



// ---------------------------------------------------------------------------
// FFWCaBuildQueryExInfo2
//   symbol: FFWCaBuildQueryExInfo2
//   rva:    0x001ce250  size: 176 bytes  tool: ghidra-12.0.4
//   source: main/net/game_prot/wcaQueryBuilder.c
// ---------------------------------------------------------------------------


void FFWCaBuildQueryExInfo2
               (int param_1,undefined4 param_2,undefined2 param_3,undefined4 param_4,
               undefined4 param_5,undefined4 param_6,code *param_7)

{
  undefined2 uVar1;
  
  FFWCaParse_buildQueryInfo__FP14FFWCaQueryInfoPCcsPsUi(param_1,param_2,param_3,param_4,param_5);
  if ((*(ushort *)(param_1 + 0x3e) & 4) != 0) {
    uVar1 = (*param_7)(param_6,param_1 + 0x4a,200);
    *(undefined2 *)(param_1 + 0x48) = uVar1;
    if (200 < *(ushort *)(param_1 + 0x48)) {
      *(undefined2 *)(param_1 + 0x48) = 200;
    }
  }
  return;
}



// ---------------------------------------------------------------------------
// FFWCaBuildQueryExInfo
//   symbol: FFWCaBuildQueryExInfo
//   rva:    0x001ce300  size: 172 bytes  tool: ghidra-12.0.4
//   source: main/net/game_prot/wcaQueryBuilder.c
// ---------------------------------------------------------------------------


void FFWCaBuildQueryExInfo
               (int param_1,undefined4 param_2,undefined2 param_3,undefined4 param_4,
               undefined4 param_5,code *param_6)

{
  undefined2 uVar1;
  
  FFWCaParse_buildQueryInfo__FP14FFWCaQueryInfoPCcsPsUi(param_1,param_2,param_3,0,param_4);
  if ((*(ushort *)(param_1 + 0x3e) & 4) != 0) {
    uVar1 = (*param_6)(param_5,param_1 + 0x4a,200);
    *(undefined2 *)(param_1 + 0x48) = uVar1;
    if (200 < *(ushort *)(param_1 + 0x48)) {
      *(undefined2 *)(param_1 + 0x48) = 200;
    }
  }
  return;
}



// ---------------------------------------------------------------------------
// FFWCaCheckSum
//   symbol: FFWCaCheckSum
//   rva:    0x001ce3b0  size: 236 bytes  tool: ghidra-12.0.4
//   source: main/net/game_prot/wcaQueryBuilder.c
// ---------------------------------------------------------------------------


int FFWCaCheckSum(ushort *pktTop,short pktSize)

{
  int iVar1;
  ulong uVar2;
  
  uVar2 = 0;
  for (; 1 < pktSize; pktSize = pktSize + -2) {
    uVar2 = uVar2 + *pktTop;
    pktTop = pktTop + 1;
  }
  if (0 < pktSize) {
    uVar2 = uVar2 + (long)(int)((uint)(byte)*pktTop << 8);
  }
  uVar2 = (uVar2 & 0xffff) + (uVar2 >> 0x10 & 0xffff);
  uVar2 = uVar2 + (uVar2 >> 0x10);
  if ((uVar2 == 0) || (0xfffe < uVar2)) {
    iVar1 = 0xffff;
  }
  else {
    iVar1 = 0xffff - (int)uVar2;
  }
  return iVar1;
}



// ---------------------------------------------------------------------------
// FFWCaGetAreaType
//   symbol: FFWCaGetAreaType
//   rva:    0x001ce4a0  size: 156 bytes  tool: ghidra-12.0.4
//   source: main/net/game_prot/wcaQueryBuilder.c
// ---------------------------------------------------------------------------


uint FFWCaGetAreaType(ushort code)

{
  uint uVar1;
  
  if ((code < 100) || (0xfc < code)) {
    uVar1 = 0;
  }
  else {
    uVar1 = *(uint *)(ffAreaTypeTab + ((int)(code - 100) >> 4 & 0xffffU) * 4) >>
            ((code - 100 & 0xf) << 1) & 3;
  }
  return uVar1;
}



// ---------------------------------------------------------------------------
// FFWCaGetAreaName
//   symbol: FFWCaGetAreaName
//   rva:    0x001ce540  size: 340 bytes  tool: ghidra-12.0.4
//   source: main/net/game_prot/wcaQueryBuilder.c
// ---------------------------------------------------------------------------


int FFWCaGetAreaName(short langCode,int nameType,ushort code)

{
  short *psVar1;
  int *piVar2;
  short *psVar3;
  
  if ((99 < code) && (code < 0xfd)) {
    psVar3 = (short *)0x0;
    for (psVar1 = &ffAreaNameTab; (*(int *)(psVar1 + 2) != 0 && (langCode != *psVar1));
        psVar1 = psVar1 + 4) {
      if ((psVar3 != (short *)0x0) && (*psVar1 == 0)) {
        psVar3 = psVar1;
      }
    }
    if (psVar1 == (short *)0x0) {
      psVar1 = psVar3;
    }
    if (((psVar1 != (short *)0x0) && (*(int *)(psVar1 + 2) != 0)) &&
       (piVar2 = (int *)(*(int *)(psVar1 + 2) + (code - 100) * 0xc), *piVar2 != 0)) {
      if (nameType == 2) {
        return piVar2[1];
      }
      if (nameType == 1) {
        return piVar2[2];
      }
      if (nameType == 0) {
        return *piVar2;
      }
    }
  }
  return 0;
}



// ---------------------------------------------------------------------------
// FFWCaRacePrintName
//   symbol: FFWCaRacePrintName
//   rva:    0x001ce6a0  size: 180 bytes  tool: ghidra-12.0.4
//   source: main/net/game_prot/wcaQueryBuilder.c
// ---------------------------------------------------------------------------


undefined4 FFWCaRacePrintName(undefined8 code,short param_2)

{
  uint uVar1;
  undefined4 uVar2;
  
  uVar1 = (int)param_2 & 0xf;
  if (*(int *)(ffRaceList + uVar1 * 0xc + 8) == 0) {
    uVar2 = *(undefined4 *)(ffRaceList + uVar1 * 0xc);
  }
  else {
    uVar2 = *(undefined4 *)(ffRaceList + uVar1 * 0xc + 8);
  }
  return uVar2;
}



// ---------------------------------------------------------------------------
// FFWCaBuildFormatedString
//   symbol: FFWCaBuildFormatedString
//   rva:    0x001ce760  size: 2184 bytes  tool: ghidra-12.0.4
//   source: main/net/game_prot/wcaQueryBuilder.c
// ---------------------------------------------------------------------------


char * FFWCaBuildFormatedString(char *buffer,undefined8 rpl,uint *param_3)

{
  bool bVar1;
  uint uVar2;
  long lVar3;
  ushort uVar4;
  char *pcVar5;
  char *pcVar6;
  char *__dest;
  char *pcStack_68;
  char *pcStack_50;
  char *pcStack_4c;
  
  strcpy(buffer,(char *)(param_3 + 1));
  for (pcVar6 = buffer; *pcVar6 != '\0'; pcVar6 = pcVar6 + 1) {
  }
  *pcVar6 = ' ';
  pcVar5 = pcVar6 + 2;
  pcVar6[1] = ' ';
  if (((*param_3 & 4) == 0) || ((*(ushort *)((int)param_3 + 0x22) & 0x4000) != 0)) {
    strcpy(pcVar5,_3499);
    for (; *pcVar5 != '\0'; pcVar5 = pcVar5 + 1) {
    }
  }
  else {
    pcVar6 = pcVar6 + 3;
    *pcVar5 = '[';
    uVar2 = (int)(short)param_3[6] & 0x1f;
    if (*(int *)(ffJobList + uVar2 * 0xc + 8) == 0) {
      pcVar5 = *(char **)(ffJobList + uVar2 * 0xc);
    }
    else {
      pcVar5 = *(char **)(ffJobList + uVar2 * 0xc + 8);
    }
    strcpy(pcVar6,pcVar5);
    for (; *pcVar6 != '\0'; pcVar6 = pcVar6 + 1) {
    }
    sprintf(pcVar6,_3498,(ulong)(ushort)param_3[7]);
    for (; *pcVar6 != '\0'; pcVar6 = pcVar6 + 1) {
    }
    pcVar5 = pcVar6 + 1;
    *pcVar6 = '(';
    uVar2 = (int)(short)param_3[8] & 0xf;
    if (*(int *)(ffRaceList + uVar2 * 0xc + 8) == 0) {
      pcVar6 = *(char **)(ffRaceList + uVar2 * 0xc);
    }
    else {
      pcVar6 = *(char **)(ffRaceList + uVar2 * 0xc + 8);
    }
    strcpy(pcVar5,pcVar6);
    for (; *pcVar5 != '\0'; pcVar5 = pcVar5 + 1) {
    }
    pcVar6 = pcVar5 + 1;
    *pcVar5 = '/';
    uVar2 = (int)*(short *)((int)param_3 + 0x16) & 3;
    if (*(int *)(ffHomeList + uVar2 * 0xc + 8) == 0) {
      pcStack_68 = *(char **)(ffHomeList + uVar2 * 0xc);
    }
    else {
      pcStack_68 = *(char **)(ffHomeList + uVar2 * 0xc + 8);
    }
    strcpy(pcVar6,pcStack_68);
    for (; *pcVar6 != '\0'; pcVar6 = pcVar6 + 1) {
    }
    pcVar5 = pcVar6 + 1;
    *pcVar6 = ')';
  }
  if ((*(ushort *)((int)param_3 + 0x22) & 0xbfff) != 0) {
    *pcVar5 = '<';
    pcVar6 = pcVar5 + 1;
    if ((*(ushort *)((int)param_3 + 0x22) & 0x100) != 0) {
      pcVar6 = pcVar5 + 2;
      pcVar5[1] = 'Z';
    }
    pcVar5 = pcVar6;
    if ((*(ushort *)((int)param_3 + 0x22) & 0x200) != 0) {
      pcVar5 = pcVar6 + 1;
      *pcVar6 = 'R';
    }
    pcVar6 = pcVar5;
    if ((*(ushort *)((int)param_3 + 0x22) & 0x400) != 0) {
      pcVar6 = pcVar5 + 1;
      *pcVar5 = 'O';
    }
    pcVar5 = pcVar6;
    if ((*(ushort *)((int)param_3 + 0x22) & 0x800) != 0) {
      pcVar5 = pcVar6 + 1;
      *pcVar6 = 'D';
    }
    pcVar6 = pcVar5;
    if ((*(ushort *)((int)param_3 + 0x22) & 0x1000) != 0) {
      pcVar6 = pcVar5 + 1;
      *pcVar5 = 'E';
    }
    pcVar5 = pcVar6;
    if ((*(ushort *)((int)param_3 + 0x22) & 0x2000) != 0) {
      pcVar5 = pcVar6 + 1;
      *pcVar6 = 'P';
    }
    pcVar6 = pcVar5;
    if ((*(ushort *)((int)param_3 + 0x22) & 0x8000) != 0) {
      pcVar6 = pcVar5 + 1;
      *pcVar5 = 'M';
    }
    __dest = pcVar6;
    if ((*(ushort *)((int)param_3 + 0x22) & 0x10) != 0) {
      __dest = pcVar6 + 1;
      *pcVar6 = 'U';
    }
    uVar4 = *(ushort *)((int)param_3 + 0x22) & 3;
    if (uVar4 == 3) {
      strcat(__dest,(char *)&_3502);
    }
    else if (uVar4 == 2) {
      strcat(__dest,(char *)&_3501);
    }
    else if (uVar4 == 1) {
      strcat(__dest,(char *)&_3500);
    }
    pcVar5 = __dest + 1;
    *__dest = '>';
  }
  if ((*param_3 & 0x2000) != 0) {
    sprintf(pcVar5,_3503,(ulong)*(byte *)((int)param_3 + 0x26));
    for (; *pcVar5 != '\0'; pcVar5 = pcVar5 + 1) {
    }
  }
  if ((short)param_3[9] != 0) {
    sprintf(pcVar5,_3504,(ulong)(ushort)param_3[9]);
    for (; *pcVar5 != '\0'; pcVar5 = pcVar5 + 1) {
    }
  }
  *pcVar5 = ' ';
  pcVar5[1] = ':';
  lVar3 = FFWCaGetAreaName(1,0,(short)param_3[5]);
  if (lVar3 == 0) {
    uVar4 = (ushort)param_3[5];
    bVar1 = true;
    if ((99 < uVar4) && (uVar4 < 0xfd)) {
      bVar1 = false;
    }
    if (bVar1) {
      pcStack_50 = _3387;
    }
    else {
      uVar2 = (int)(short)(uVar4 - 100) & 0xff;
      if (*(int *)(ffZoneList + uVar2 * 0xc + 8) == 0) {
        pcStack_4c = *(char **)(ffZoneList + uVar2 * 0xc);
      }
      else {
        pcStack_4c = *(char **)(ffZoneList + uVar2 * 0xc + 8);
      }
      pcStack_50 = pcStack_4c;
    }
    strcpy(pcVar5 + 2,pcStack_50);
  }
  else {
    strcpy(pcVar5 + 2,(char *)lVar3);
  }
  return buffer;
}



// ---------------------------------------------------------------------------
// FFWCaAddQueryId
//   symbol: FFWCaAddQueryId
//   rva:    0x001ceff0  size: 104 bytes  tool: ghidra-12.0.4
//   source: main/net/game_prot/wcaQueryBuilder.c
// ---------------------------------------------------------------------------


bool FFWCaAddQueryId(ushort *idInfo,ushort id)

{
  ushort uVar1;
  ushort uVar2;
  
  uVar1 = *idInfo;
  if (uVar1 < 0x14) {
    uVar2 = *idInfo;
    *idInfo = uVar2 + 1;
    idInfo[uVar2 + 1] = id;
  }
  return uVar1 < 0x14;
}



// ---------------------------------------------------------------------------
// FFWCaSetPartyID
//   symbol: FFWCaSetPartyID
//   rva:    0x001cf060  size: 36 bytes  tool: ghidra-12.0.4
//   source: main/net/game_prot/wcaQueryBuilder.c
// ---------------------------------------------------------------------------


void FFWCaSetPartyID(undefined4 *grpInfo,undefined4 id)

{
  *grpInfo = id;
  return;
}



// ---------------------------------------------------------------------------
// FFWCaSetAllianceID
//   symbol: FFWCaSetAllianceID
//   rva:    0x001cf090  size: 36 bytes  tool: ghidra-12.0.4
//   source: main/net/game_prot/wcaQueryBuilder.c
// ---------------------------------------------------------------------------


void FFWCaSetAllianceID(int grpInfo,undefined4 id)

{
  *(undefined4 *)(grpInfo + 4) = id;
  return;
}



// ---------------------------------------------------------------------------
// FFWCaSetComlinkID
//   symbol: FFWCaSetComlinkID
//   rva:    0x001cf0c0  size: 36 bytes  tool: ghidra-12.0.4
//   source: main/net/game_prot/wcaQueryBuilder.c
// ---------------------------------------------------------------------------


void FFWCaSetComlinkID(int grpInfo,undefined4 id)

{
  *(undefined4 *)(grpInfo + 8) = id;
  return;
}



// ---------------------------------------------------------------------------
// FFWCaSetQueryName
//   symbol: FFWCaSetQueryName
//   rva:    0x001cf0f0  size: 260 bytes  tool: ghidra-12.0.4
//   source: main/net/game_prot/wcaQueryBuilder.c
// ---------------------------------------------------------------------------


undefined4 FFWCaSetQueryName(uint *qinfo,byte *name)

{
  undefined4 uVar1;
  uint *puVar2;
  int iVar3;
  
  if ((*qinfo & 1) == 0) {
    *(undefined1 *)(qinfo + 3) = 0;
    *qinfo = *qinfo | 1;
    iVar3 = 0xf;
    puVar2 = qinfo + 3;
    for (; ((0 < iVar3 && (*name != 0)) && ((*name & 0x80) == 0)); name = name + 1) {
      *(byte *)puVar2 = *name;
      iVar3 = iVar3 + -1;
      puVar2 = (uint *)((int)puVar2 + 1);
    }
    *(byte *)puVar2 = 0;
    uVar1 = 1;
  }
  else {
    uVar1 = 0;
  }
  return uVar1;
}



// ---------------------------------------------------------------------------
// FFWCaClrQueryName
//   symbol: FFWCaClrQueryName
//   rva:    0x001cf200  size: 112 bytes  tool: ghidra-12.0.4
//   source: main/net/game_prot/wcaQueryBuilder.c
// ---------------------------------------------------------------------------


bool FFWCaClrQueryName(uint *qinfo)

{
  bool bVar1;
  
  bVar1 = (*qinfo & 1) != 0;
  if (bVar1) {
    *(undefined1 *)(qinfo + 3) = 0;
    *qinfo = *qinfo & 0xfffffffe;
  }
  return bVar1;
}



// ---------------------------------------------------------------------------
// FFWCaSetQueryLevel
//   symbol: FFWCaSetQueryLevel
//   rva:    0x001cf270  size: 216 bytes  tool: ghidra-12.0.4
//   source: main/net/game_prot/wcaQueryBuilder.c
// ---------------------------------------------------------------------------


undefined4 FFWCaSetQueryLevel(uint *qinfo,byte minLevel,byte maxLevel)

{
  undefined4 uVar1;
  
  if ((*qinfo & 0x10) == 0) {
    *(ushort *)(qinfo + 7) = (ushort)minLevel;
    *qinfo = *qinfo | 0x10;
    if (minLevel < maxLevel) {
      minLevel = maxLevel;
    }
    *(ushort *)((int)qinfo + 0x1e) = (ushort)minLevel;
    uVar1 = 1;
  }
  else {
    uVar1 = 0;
  }
  return uVar1;
}



// ---------------------------------------------------------------------------
// FFWCaClrQueryLevel
//   symbol: FFWCaClrQueryLevel
//   rva:    0x001cf350  size: 148 bytes  tool: ghidra-12.0.4
//   source: main/net/game_prot/wcaQueryBuilder.c
// ---------------------------------------------------------------------------


bool FFWCaClrQueryLevel(uint *qinfo)

{
  bool bVar1;
  
  bVar1 = (*qinfo & 0x10) != 0;
  if (bVar1) {
    *(undefined2 *)(qinfo + 7) = 0xffff;
    *qinfo = *qinfo & 0xffffffef;
    *(undefined2 *)((int)qinfo + 0x1e) = 0xffff;
  }
  return bVar1;
}



// ---------------------------------------------------------------------------
// FFWCaSetQueryRank
//   symbol: FFWCaSetQueryRank
//   rva:    0x001cf3f0  size: 216 bytes  tool: ghidra-12.0.4
//   source: main/net/game_prot/wcaQueryBuilder.c
// ---------------------------------------------------------------------------


undefined4 FFWCaSetQueryRank(uint *qinfo,byte minRank,byte maxRank)

{
  undefined4 uVar1;
  
  if ((*qinfo & 0x10000) == 0) {
    *(byte *)(qinfo + 0xf) = minRank;
    *qinfo = *qinfo | 0x10000;
    if (minRank < maxRank) {
      minRank = maxRank;
    }
    *(byte *)((int)qinfo + 0x3d) = minRank;
    uVar1 = 1;
  }
  else {
    uVar1 = 0;
  }
  return uVar1;
}



// ---------------------------------------------------------------------------
// FFWCaClrQueryRank
//   symbol: FFWCaClrQueryRank
//   rva:    0x001cf4d0  size: 156 bytes  tool: ghidra-12.0.4
//   source: main/net/game_prot/wcaQueryBuilder.c
// ---------------------------------------------------------------------------


bool FFWCaClrQueryRank(uint *qinfo)

{
  bool bVar1;
  
  bVar1 = (*qinfo & 0x10000) != 0;
  if (bVar1) {
    *(undefined1 *)(qinfo + 0xf) = 0xff;
    *qinfo = *qinfo & 0xfffeffff;
    *(undefined1 *)((int)qinfo + 0x3d) = 0xff;
  }
  return bVar1;
}



// ---------------------------------------------------------------------------
// FFWCaSetQueryZone
//   symbol: FFWCaSetQueryZone
//   rva:    0x001cf570  size: 436 bytes  tool: ghidra-12.0.4
//   source: main/net/game_prot/wcaQueryBuilder.c
// ---------------------------------------------------------------------------


/* WARNING: Removing unreachable block (ram,0x002cf700) */

undefined4 FFWCaSetQueryZone(uint *qinfo,byte zone)

{
  int iVar1;
  
  if ((*qinfo & 2) != 0) {
    *(undefined2 *)((int)qinfo + 0x22) = 0xffff;
    *qinfo = *qinfo & 0xfffffffd;
  }
  if ((*qinfo & 2) == 0) {
    *(ushort *)((int)qinfo + 0x22) = (ushort)zone;
    *qinfo = *qinfo | 2;
  }
  iVar1 = 0;
  while ((iVar1 < 8 && (0 < *(short *)((int)qinfo + iVar1 * 2 + 0x24)))) {
    if ((ushort)zone == *(ushort *)((int)qinfo + iVar1 * 2 + 0x24)) {
      return 1;
    }
    iVar1 = iVar1 + 1;
  }
  for (iVar1 = 7; 0 < iVar1; iVar1 = iVar1 + -1) {
    *(undefined2 *)((int)qinfo + iVar1 * 2 + 0x24) =
         *(undefined2 *)((int)qinfo + (iVar1 + -1) * 2 + 0x24);
  }
  *(ushort *)(qinfo + 9) = (ushort)zone;
  return 1;
}



// ---------------------------------------------------------------------------
// FFWCaSetQueryDefaultZone
//   symbol: FFWCaSetQueryDefaultZone
//   rva:    0x001cf730  size: 200 bytes  tool: ghidra-12.0.4
//   source: main/net/game_prot/wcaQueryBuilder.c
// ---------------------------------------------------------------------------


bool FFWCaSetQueryDefaultZone(uint *qinfo,byte zone)

{
  bool bVar1;
  
  bVar1 = (*qinfo & 2) == 0;
  if (bVar1) {
    *(ushort *)((int)qinfo + 0x22) = (ushort)zone;
    *qinfo = *qinfo | 2;
    *(ushort *)(qinfo + 9) = (ushort)zone;
    *(undefined2 *)((int)qinfo + 0x26) = 0xffff;
    *(ushort *)((int)qinfo + 0x3e) = *(ushort *)((int)qinfo + 0x3e) | 2;
  }
  return bVar1;
}



// ---------------------------------------------------------------------------
// FFWCaClrQueryZone
//   symbol: FFWCaClrQueryZone
//   rva:    0x001cf800  size: 164 bytes  tool: ghidra-12.0.4
//   source: main/net/game_prot/wcaQueryBuilder.c
// ---------------------------------------------------------------------------


bool FFWCaClrQueryZone(uint *qinfo)

{
  bool bVar1;
  
  bVar1 = (*qinfo & 2) != 0;
  if (bVar1) {
    *(undefined2 *)((int)qinfo + 0x22) = 0xffff;
    *qinfo = *qinfo & 0xfffffffd;
    *(undefined2 *)(qinfo + 9) = 0xffff;
    *(ushort *)((int)qinfo + 0x3e) = *(ushort *)((int)qinfo + 0x3e) & 0xfffd;
  }
  return bVar1;
}



// ---------------------------------------------------------------------------
// FFWCaSetQueryHome
//   symbol: FFWCaSetQueryHome
//   rva:    0x001cf8b0  size: 120 bytes  tool: ghidra-12.0.4
//   source: main/net/game_prot/wcaQueryBuilder.c
// ---------------------------------------------------------------------------


bool FFWCaSetQueryHome(uint *qinfo,byte home)

{
  bool bVar1;
  
  bVar1 = (*qinfo & 4) == 0;
  if (bVar1) {
    *(ushort *)(qinfo + 0xd) = (ushort)home;
    *qinfo = *qinfo | 4;
  }
  return bVar1;
}



// ---------------------------------------------------------------------------
// FFWCaClrQueryHome
//   symbol: FFWCaClrQueryHome
//   rva:    0x001cf930  size: 116 bytes  tool: ghidra-12.0.4
//   source: main/net/game_prot/wcaQueryBuilder.c
// ---------------------------------------------------------------------------


bool FFWCaClrQueryHome(uint *qinfo)

{
  bool bVar1;
  
  bVar1 = (*qinfo & 4) != 0;
  if (bVar1) {
    *(undefined2 *)(qinfo + 0xd) = 0xffff;
    *qinfo = *qinfo & 0xfffffffb;
  }
  return bVar1;
}



// ---------------------------------------------------------------------------
// FFWCaSetQueryJob
//   symbol: FFWCaSetQueryJob
//   rva:    0x001cf9b0  size: 120 bytes  tool: ghidra-12.0.4
//   source: main/net/game_prot/wcaQueryBuilder.c
// ---------------------------------------------------------------------------


bool FFWCaSetQueryJob(uint *qinfo,byte job)

{
  bool bVar1;
  
  bVar1 = (*qinfo & 8) == 0;
  if (bVar1) {
    *(ushort *)((int)qinfo + 0x36) = (ushort)job;
    *qinfo = *qinfo | 8;
  }
  return bVar1;
}



// ---------------------------------------------------------------------------
// FFWCaClrQueryJob
//   symbol: FFWCaClrQueryJob
//   rva:    0x001cfa30  size: 116 bytes  tool: ghidra-12.0.4
//   source: main/net/game_prot/wcaQueryBuilder.c
// ---------------------------------------------------------------------------


bool FFWCaClrQueryJob(uint *qinfo)

{
  bool bVar1;
  
  bVar1 = (*qinfo & 8) != 0;
  if (bVar1) {
    *(undefined2 *)((int)qinfo + 0x36) = 0xffff;
    *qinfo = *qinfo & 0xfffffff7;
  }
  return bVar1;
}



// ---------------------------------------------------------------------------
// FFWCaSetQueryRace
//   symbol: FFWCaSetQueryRace
//   rva:    0x001cfab0  size: 272 bytes  tool: ghidra-12.0.4
//   source: main/net/game_prot/wcaQueryBuilder.c
// ---------------------------------------------------------------------------


bool FFWCaSetQueryRace(uint *qinfo,undefined1 cliRace)

{
  bool bVar1;
  undefined2 uVar2;
  
  uVar2 = 5;
  switch(cliRace) {
  case 1:
  case 2:
    uVar2 = 0;
    break;
  case 3:
  case 4:
    uVar2 = 1;
    break;
  case 5:
  case 6:
    uVar2 = 2;
    break;
  case 7:
    uVar2 = 3;
    break;
  case 8:
    uVar2 = 4;
  }
  bVar1 = (*qinfo & 0x20) == 0;
  if (bVar1) {
    *(undefined2 *)(qinfo + 0xe) = uVar2;
    *qinfo = *qinfo | 0x20;
  }
  return bVar1;
}



// ---------------------------------------------------------------------------
// FFWCaClrQueryRace
//   symbol: FFWCaClrQueryRace
//   rva:    0x001cfbc0  size: 116 bytes  tool: ghidra-12.0.4
//   source: main/net/game_prot/wcaQueryBuilder.c
// ---------------------------------------------------------------------------


bool FFWCaClrQueryRace(uint *qinfo)

{
  bool bVar1;
  
  bVar1 = (*qinfo & 0x20) != 0;
  if (bVar1) {
    *(undefined2 *)(qinfo + 0xe) = 0xffff;
    *qinfo = *qinfo & 0xffffffdf;
  }
  return bVar1;
}



// ---------------------------------------------------------------------------
// FFWCaSetQueryStatus
//   symbol: FFWCaSetQueryStatus
//   rva:    0x001cfc40  size: 116 bytes  tool: ghidra-12.0.4
//   source: main/net/game_prot/wcaQueryBuilder.c
// ---------------------------------------------------------------------------


bool FFWCaSetQueryStatus(uint *qinfo,undefined2 state)

{
  bool bVar1;
  
  bVar1 = (*qinfo & 0x40) == 0;
  if (bVar1) {
    *(undefined2 *)((int)qinfo + 0x3a) = state;
    *qinfo = *qinfo | 0x40;
  }
  return bVar1;
}



// ---------------------------------------------------------------------------
// FFWCaSetQueryComlink
//   symbol: FFWCaSetQueryComlink
//   rva:    0x001cfcc0  size: 116 bytes  tool: ghidra-12.0.4
//   source: main/net/game_prot/wcaQueryBuilder.c
// ---------------------------------------------------------------------------


bool FFWCaSetQueryComlink(uint *qinfo,uint id)

{
  bool bVar1;
  
  bVar1 = (*qinfo & 0x800) == 0;
  if (bVar1) {
    qinfo[0x10] = id;
    *qinfo = *qinfo | 0x800;
  }
  return bVar1;
}



// ---------------------------------------------------------------------------
// FFWCaClrQueryComlink
//   symbol: FFWCaClrQueryComlink
//   rva:    0x001cfd40  size: 112 bytes  tool: ghidra-12.0.4
//   source: main/net/game_prot/wcaQueryBuilder.c
// ---------------------------------------------------------------------------


bool FFWCaClrQueryComlink(uint *qinfo)

{
  bool bVar1;
  
  bVar1 = (*qinfo & 0x800) != 0;
  if (bVar1) {
    qinfo[0x10] = 0;
    *qinfo = *qinfo & 0xfffff7ff;
  }
  return bVar1;
}



// ---------------------------------------------------------------------------
// FFWCaSetQueryFriend
//   symbol: FFWCaSetQueryFriend
//   rva:    0x001cfdb0  size: 100 bytes  tool: ghidra-12.0.4
//   source: main/net/game_prot/wcaQueryBuilder.c
// ---------------------------------------------------------------------------


bool FFWCaSetQueryFriend(uint *qinfo)

{
  bool bVar1;
  
  bVar1 = (*qinfo & 0x1000) == 0;
  if (bVar1) {
    *qinfo = *qinfo | 0x1000;
  }
  return bVar1;
}



// ---------------------------------------------------------------------------
// FFWCaClrQueryFriend
//   symbol: FFWCaClrQueryFriend
//   rva:    0x001cfe20  size: 104 bytes  tool: ghidra-12.0.4
//   source: main/net/game_prot/wcaQueryBuilder.c
// ---------------------------------------------------------------------------


bool FFWCaClrQueryFriend(uint *qinfo)

{
  bool bVar1;
  
  bVar1 = (*qinfo & 0x1000) != 0;
  if (bVar1) {
    *qinfo = *qinfo & 0xffffefff;
  }
  return bVar1;
}



// ---------------------------------------------------------------------------
// FFWCaSetQueryMsgType
//   symbol: FFWCaSetQueryMsgType
//   rva:    0x001cfe90  size: 124 bytes  tool: ghidra-12.0.4
//   source: main/net/game_prot/wcaQueryBuilder.c
// ---------------------------------------------------------------------------


bool FFWCaSetQueryMsgType(uint *qinfo,uint type)

{
  bool bVar1;
  
  bVar1 = (*qinfo & 0x20000) == 0;
  if (bVar1) {
    qinfo[0x11] = type;
    *qinfo = *qinfo | 0x20000;
  }
  return bVar1;
}



// ---------------------------------------------------------------------------
// FFWCaClrQueryMsgType
//   symbol: FFWCaClrQueryMsgType
//   rva:    0x001cff10  size: 120 bytes  tool: ghidra-12.0.4
//   source: main/net/game_prot/wcaQueryBuilder.c
// ---------------------------------------------------------------------------


bool FFWCaClrQueryMsgType(uint *qinfo)

{
  bool bVar1;
  
  bVar1 = (*qinfo & 0x20000) != 0;
  if (bVar1) {
    qinfo[0x11] = 0;
    *qinfo = *qinfo & 0xfffdffff;
  }
  return bVar1;
}

