// AUTOGENERATED by ffxi-decomp. Do not edit by hand.
// version: 972 (sha256=d4622c1cc4a3012c, image_base=0x00100000)
// source:  main/dancer/StOverlay.c
// functions: 6


// ---------------------------------------------------------------------------
// _StOverlayReadFinish
// _StOverlayReadFinish(char *, int, void *)
//   symbol: _StOverlayReadFinish__FPciPv
//   rva:    0x003564d0  size: 408 bytes  tool: ghidra-12.0.4
//   source: main/dancer/StOverlay.c
// ---------------------------------------------------------------------------


/* WARNING: Removing unreachable block (ram,0x004565b0) */
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void _StOverlayReadFinish__FPciPv(int memPtr,int flen)

{
  int iVar1;
  
  if (_s_overlayState == 2) {
    if (_s_overlayAddr != 0) {
      _s_overlayAddr = 0;
    }
    _s_overlayDancer = (StDancer *)0x0;
    _s_overlayState = 0;
  }
  else if (memPtr == *(int *)(memPtr + 8)) {
    iVar1 = *(int *)(memPtr + 0x14);
    FlushCache(2);
    if ((long)iVar1 != 0) {
      memset((void *)(memPtr + flen),0,(long)iVar1);
    }
    __initialize_cpp_rts(*(undefined4 *)(memPtr + 0x18),*(undefined4 *)(memPtr + 0x1c),0,0);
    _s_overlayState = 3;
    _s_overlayAddr = memPtr;
    if (_s_overlayDancer != (StDancer *)0x0) {
      StDancer::OverlayCallback(_s_overlayDancer,0);
    }
  }
  else {
    ErrPrintf(0x53cce0);
    ErrPrintf(0x53cd10,*(undefined4 *)(memPtr + 8));
    ErrPrintf(0x53cd30,memPtr);
    ErrPrintf(0x53cd50);
    ErrPrintf(0x53cda0);
    if (_s_overlayAddr != 0) {
      _s_overlayAddr = 0;
    }
    _s_overlayDancer = (StDancer *)0x0;
    _s_overlayState = 0;
  }
  return;
}



// ---------------------------------------------------------------------------
// StOverlayRequest
//   symbol: StOverlayRequest
//   rva:    0x00356670  size: 440 bytes  tool: ghidra-12.0.4
//   source: main/dancer/StOverlay.c
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined4 StOverlayRequest(undefined4 fileID,undefined4 dancer)

{
  undefined4 uVar1;
  long lVar2;
  undefined8 unaff_s0;
  int iVar3;
  undefined8 unaff_s2;
  long unaff_s5;
  char *unaff_s8_lo;
  undefined4 unaff_s8_hi;
  XiFileBase aXStack_40 [28];
  int iStack_24;
  undefined4 uStack_20;
  undefined4 uStack_10;
  
  uStack_20 = fileID;
  uStack_10 = dancer;
  if ((_s_overlayState == 0) && (_s_overlayAddr == 0)) {
    _s_overlayState = 1;
    _s_overlayDancer = dancer;
    XiFileBase::XiFileBase(aXStack_40);
    lVar2 = XiFileBase::open(aXStack_40,&iStack_24,0x53cdd0);
    if (-1 < lVar2) {
      unaff_s0 = XiFileBase::getFileSize(aXStack_40,_1728);
      unaff_s2 = CONCAT44(unaff_s8_hi,unaff_s8_lo);
      unaff_s5 = XiFileBase::read(aXStack_40,iStack_24,unaff_s8_lo,(int)unaff_s0);
      XiFileBase::close(aXStack_40,iStack_24);
    }
    _StOverlayReadFinish__FPciPv(unaff_s2,unaff_s0);
    if (unaff_s5 < 0) {
      ErrPrintf(0x53ce00,uStack_20);
      iVar3 = -1;
      XiFileBase::~XiFileBase(aXStack_40);
    }
    else {
      XiFileBase::~XiFileBase(aXStack_40);
      iVar3 = 0;
    }
    if (iVar3 == -1) {
      _s_overlayDancer = 0;
      _s_overlayState = 0;
      uVar1 = 0xffffffff;
    }
    else {
      uVar1 = 0;
    }
  }
  else {
    ErrPrintf(0x53ce20);
    uVar1 = 0xffffffff;
  }
  return uVar1;
}



// ---------------------------------------------------------------------------
// StOverlayState
//   symbol: StOverlayState
//   rva:    0x00356830  size: 12 bytes  tool: ghidra-12.0.4
//   source: main/dancer/StOverlay.c
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined4 StOverlayState(void)

{
  return _s_overlayState;
}



// ---------------------------------------------------------------------------
// StOverlayFini
//   symbol: StOverlayFini
//   rva:    0x00356840  size: 148 bytes  tool: ghidra-12.0.4
//   source: main/dancer/StOverlay.c
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void StOverlayFini(void)

{
  if (_s_overlayState == 1) {
    XiFileManager::cancelAll(_g_xiFileManager);
    WarningPrintf(0x53ccc0);
    if (_s_overlayAddr != 0) {
      _s_overlayAddr = 0;
    }
    _s_overlayDancer = 0;
    _s_overlayState = 2;
  }
  else if (_s_overlayState == 3) {
    if (_s_overlayAddr != 0) {
      _s_overlayAddr = 0;
    }
    _s_overlayDancer = 0;
    _s_overlayState = 0;
  }
  return;
}



// ---------------------------------------------------------------------------
// StOverlayGetSize
//   symbol: StOverlayGetSize
//   rva:    0x003568e0  size: 12 bytes  tool: ghidra-12.0.4
//   source: main/dancer/StOverlay.c
// ---------------------------------------------------------------------------


undefined8 StOverlayGetSize(void)

{
  return 0;
}



// ---------------------------------------------------------------------------
// StOverlayGetAddress
//   symbol: StOverlayGetAddress
//   rva:    0x003568f0  size: 12 bytes  tool: ghidra-12.0.4
//   source: main/dancer/StOverlay.c
// ---------------------------------------------------------------------------


undefined8 StOverlayGetAddress(void)

{
  return 0;
}

