// AUTOGENERATED by ffxi-decomp. Do not edit by hand.
// version: 972 (sha256=d4622c1cc4a3012c, image_base=0x00100000)
// source:  main/yk/ykWndAuction.cpp
// functions: 53


// ---------------------------------------------------------------------------
// GetAuctionNum
// GetAuctionNum(int)
//   symbol: GetAuctionNum__Fi
//   rva:    0x003a8d70  size: 160 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndAuction.cpp
// ---------------------------------------------------------------------------


undefined2 GetAuctionNum__Fi(int zone)

{
  int iVar1;
  
  iVar1 = 0;
  while( true ) {
    if (*(short *)(MarketTbl + iVar1 * 4) == 0) {
      return 0;
    }
    if ((long)zone == (long)*(short *)(MarketTbl + iVar1 * 4)) break;
    iVar1 = iVar1 + 1;
  }
  return *(undefined2 *)(MarketTbl + iVar1 * 4 + 2);
}



// ---------------------------------------------------------------------------
// SetFee
// YkAuctionFee::SetFee(unsigned short, int, int)
//   symbol: SetFee__12YkAuctionFeeFUsii
//   rva:    0x003a8e10  size: 284 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndAuction.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void YkAuctionFee::SetFee(YkAuctionFee *this,ushort itemno,int fee,int stack)

{
  long lVar1;
  ushort *puVar2;
  int iVar3;
  
  if (itemno != 0) {
    for (iVar3 = 0; iVar3 < 0x51; iVar3 = iVar3 + 1) {
      lVar1 = KmItem::ItemGet(_g_pKmItemProperty,(byte)iVar3);
      if (lVar1 != 0) {
        puVar2 = (ushort *)lVar1;
        lVar1 = CTkItemData::LoadItemDataNow_NOICON(_g_pTkItemData,(uint)*puVar2);
        if (((lVar1 != 0) && (*puVar2 == itemno)) &&
           (((stack == 1 && (*(int *)(puVar2 + 2) == 1)) ||
            ((stack == 0 && (*(uint *)(puVar2 + 2) == (uint)*(ushort *)((int)lVar1 + 8))))))) {
          (&this->m_fee)[(byte)puVar2[1]] = fee;
        }
      }
    }
  }
  return;
}



// ---------------------------------------------------------------------------
// PrintAuctionResult
// PrintAuctionResult(char)
//   symbol: PrintAuctionResult__Fc
//   rva:    0x003a8f30  size: 424 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndAuction.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void PrintAuctionResult__Fc(char force)

{
  undefined8 uVar1;
  undefined1 auStack_b0 [8];
  undefined2 uStack_a8;
  uint uStack_a4;
  char acStack_7c [28];
  undefined1 auStack_60 [8];
  undefined2 uStack_58;
  uint uStack_54;
  char acStack_2c [28];
  char cStack_10;
  
  if ((g_BetPrint != '\0') &&
     ((_g_BetResTime = _g_BetResTime - (short)uRam00557a44, force != '\0' || (_g_BetResTime < 0)))
     ) {
    cStack_10 = force;
    if (g_BetResult != '\0') {
      if (g_BetResult == '\x03') {
        CTkMsgWinData::AddErr(_g_pMsgWinData,0x6f);
      }
      else if (g_BetResult == '\x02') {
        memset(auStack_60,0,0x50);
        uStack_58 = 0xb2;
        uStack_54 = (uint)_g_BetResItem;
        uVar1 = YkGetMoneyString__Fic(_g_BetResPrice);
        sprintf(acStack_2c,(char *)&_2156,uVar1);
        PutSystemMessage__FP6SYSMES(auStack_60);
      }
      else if (g_BetResult == '\x01') {
        memset(auStack_b0,0,0x50);
        uStack_a8 = 0xb1;
        uStack_a4 = (uint)_g_BetResItem;
        uVar1 = YkGetMoneyString__Fic(_g_BetResPrice);
        sprintf(acStack_7c,(char *)&_2156,uVar1);
        PutSystemMessage__FP6SYSMES(auStack_b0);
      }
    }
    if (_g_pTkHelp != 0) {
      KaHelpMes::ResetLoadMes((KaHelpMes *)(_g_pTkHelp + 0x20),0x80000000);
    }
    g_BetPrint = '\0';
  }
  return;
}



// ---------------------------------------------------------------------------
// RecvAuctionResult
// RecvAuctionResult(GP_SERV_AUC *)
//   symbol: RecvAuctionResult__FP11GP_SERV_AUC
//   rva:    0x003a90e0  size: 288 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndAuction.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void RecvAuctionResult__FP11GP_SERV_AUC(int pRecv)

{
  char cVar1;
  
  cVar1 = *(char *)(pRecv + 6);
  if ((cVar1 == -0x1b) || (cVar1 == -0x1c)) {
    g_BetResult = 3;
  }
  else if (cVar1 == '\x02') {
    g_BetResult = 0;
  }
  else if (cVar1 == '\x01') {
    g_BetResult = 1;
  }
  else {
    g_BetResult = 2;
  }
  g_Betted = 0;
  g_BetPrint = 1;
  _g_BetResItem = *(ushort *)(pRecv + 0xc);
  _g_BetResPrice = *(int *)(pRecv + 8);
  _g_BetResTime = (short)((int)((uint)_g_BetResItem * _g_BetResPrice) % 0x78) + 0xb4;
  if ((*(int *)(_g_pYkWndAuctionMain + 8) == 0) ||
     (*(char *)(*(int *)(_g_pYkWndAuctionMain + 8) + 0x6e) != '\0')) {
    PrintAuctionResult__Fc(1);
  }
  return;
}



// ---------------------------------------------------------------------------
// RecvAuctionFee
// RecvAuctionFee(GP_SERV_AUC *)
//   symbol: RecvAuctionFee__FP11GP_SERV_AUC
//   rva:    0x003a9200  size: 316 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndAuction.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void RecvAuctionFee__FP11GP_SERV_AUC(int pRecv)

{
  short sVar1;
  YkAuctionFee *pYVar2;
  long lVar3;
  int iVar4;
  
  if (_g_pAuctionFee != (YkAuctionFee *)0x0) {
    if (*(char *)(pRecv + 6) == '\x01') {
      YkAuctionFee::SetFee
                (_g_pAuctionFee,*(ushort *)(pRecv + 0xe),*(int *)(pRecv + 8),
                 *(int *)(pRecv + 0x10));
    }
    else {
      if (*(char *)(pRecv + 6) == -0xd) {
        CTkMsgWinData::AddErr(_g_pMsgWinData,0x6c);
      }
      pYVar2 = _g_pAuctionFee;
      sVar1 = *(short *)(pRecv + 0xe);
      if (sVar1 != 0) {
        for (iVar4 = 0; iVar4 < 0x51; iVar4 = iVar4 + 1) {
          lVar3 = KmItem::ItemGet(_g_pKmItemProperty,(byte)iVar4);
          if ((lVar3 != 0) && (*(short *)lVar3 == sVar1)) {
            (&pYVar2->m_fee)[*(byte *)((short *)lVar3 + 1)] = -1;
          }
        }
      }
    }
  }
  return;
}



// ---------------------------------------------------------------------------
// 
// YkWndAuctionItem::~YkWndAuctionItem(void)
//   symbol: __dt__16YkWndAuctionItemFv
//   rva:    0x003a9340  size: 268 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndAuction.cpp
// ---------------------------------------------------------------------------


/* WARNING: Unknown calling convention -- yet parameter storage is locked */

YkWndAuctionItem * YkWndAuctionItem::~YkWndAuctionItem(YkWndAuctionItem *this)

{
  short in_a1_lo;
  
  if (this != (YkWndAuctionItem *)0x0) {
    *(undefined1 **)&this->field_0x4 = __vt__16YkWndAuctionItem;
    if (this->m_ownitem != (YkWndListItem *)0x0) {
      if (this->m_ownitem != (YkWndListItem *)0x0) {
        __dla__FPv(&this->m_ownitem[-1].field_0x60);
      }
      this->m_ownitem = (YkWndListItem *)0x0;
    }
    if (this->m_ownuser != (_YK_SEARCH_DATA *)0x0) {
      if (this->m_ownuser != (_YK_SEARCH_DATA *)0x0) {
        __dla__FPv(&this->m_ownuser[-1].field_0x24);
      }
      this->m_ownuser = (_YK_SEARCH_DATA *)0x0;
    }
    if (this != (YkWndAuctionItem *)0x0) {
      *(undefined1 **)&this->field_0x4 = __vt__15YkWndSearchList;
      YkWndList::~YkWndList((YkWndList *)this);
    }
    if (0 < in_a1_lo) {
      __dl__FPv(this);
    }
  }
  return this;
}



// ---------------------------------------------------------------------------
// MakeListOwn
// YkWndAuctionItem::MakeListOwn(void)
//   symbol: MakeListOwn__16YkWndAuctionItemFv
//   rva:    0x003a9450  size: 1720 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndAuction.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void YkWndAuctionItem::MakeListOwn(YkWndAuctionItem *this)

{
  char cVar1;
  YkWndListItem *pYVar2;
  int iVar3;
  undefined4 uVar4;
  undefined8 uVar5;
  long lVar6;
  char *pcVar7;
  int iVar8;
  ulong arg4;
  void *pvVar9;
  int iVar10;
  long lVar11;
  char *pcStack_1c;
  char *pcStack_14;
  
  if (_pGlobalNowZone != 0) {
    if (this->m_ownitem == (YkWndListItem *)0x0) {
      uVar5 = __nwa__FUi(0x390);
      pYVar2 = (YkWndListItem *)__construct_new_array(uVar5,0x3d0790,0,0x70,8);
      this->m_ownitem = pYVar2;
    }
    lVar6 = 0;
    if (*(int *)&this->field_0x8 != 0) {
      lVar6 = CTkMenuCtrlData::GetDrawCtrlFrame(*(CTkMenuCtrlData **)&this->field_0x8);
    }
    *(undefined2 *)&this->m_ownmax = 0;
    for (pvVar9 = (void *)0x0; (int)pvVar9 < 8; pvVar9 = (void *)((int)pvVar9 + 1)) {
      iVar3 = _pGlobalNowZone + (int)pvVar9 * 0x28;
      pcVar7 = (char *)(iVar3 + 0x198ec);
      pYVar2 = this->m_ownitem + *(short *)&this->m_ownmax;
      if (((*pcVar7 != '\0') && (*pcVar7 != '\x06')) && (*pcVar7 != '\a')) {
        if ((*(char *)((int)pvVar9 + (int)(&this->field_0x0 + 0x2fc)) == '\0') &&
           ((((cVar1 = *pcVar7, cVar1 == '\r' || (cVar1 == '\f')) ||
             ((cVar1 == '\x0f' || ((cVar1 == '\x0e' || (cVar1 == '\x03')))))) &&
            (lVar11 = SendAuction_LotCheck(pvVar9), lVar11 != 0)))) {
          *(char *)((int)pvVar9 + (int)(&this->field_0x0 + 0x2fc)) = '\x01';
        }
        cVar1 = *pcVar7;
        if ((cVar1 == '\x16') || (cVar1 == '\r')) {
          arg4 = 0x80204080;
          pcVar7 = (char *)XiStrGet(0xe,0x41);
          pYVar2->m_help = pcVar7;
        }
        else if (cVar1 == '\x0e') {
          arg4 = 0x80505050;
          pcVar7 = (char *)XiStrGet(0xe,0x3d);
          pYVar2->m_help = pcVar7;
        }
        else if (cVar1 == '\v') {
          arg4 = 0x80204080;
          pcVar7 = (char *)XiStrGet(0xe,0x3f);
          pYVar2->m_help = pcVar7;
        }
        else if ((cVar1 == '\x15') || (cVar1 == '\f')) {
          arg4 = 0x80409090;
          pcVar7 = (char *)XiStrGet(0xe,0x40);
          pYVar2->m_help = pcVar7;
        }
        else if (cVar1 == '\x0f') {
          arg4 = 0x80505050;
          pcVar7 = (char *)XiStrGet(0xe,0x3c);
          pYVar2->m_help = pcVar7;
        }
        else if (cVar1 == '\n') {
          arg4 = 0x80409090;
          pcVar7 = (char *)XiStrGet(0xe,0x3e);
          pYVar2->m_help = pcVar7;
        }
        else {
          iVar8 = (int)lVar6;
          if (cVar1 == '\x03') {
            for (iVar10 = 0; *(short *)(MarketTbl + iVar10 * 4) != 0; iVar10 = iVar10 + 1) {
              if ((long)*(int *)(_pGlobalNowZone + 0x25138) ==
                  (long)*(short *)(MarketTbl + iVar10 * 4)) {
                lVar11 = (long)*(short *)(MarketTbl + iVar10 * 4 + 2);
                goto LAB_004a9724;
              }
            }
            lVar11 = 0;
LAB_004a9724:
            if (*(int *)(iVar3 + 0x19908) == lVar11) {
              arg4 = 0x80509050;
            }
            else {
              arg4 = 0x80505050;
            }
            if (lVar6 == 0) {
              pcVar7 = (char *)0x0;
            }
            else if (*(int *)(iVar8 + 0x3c) == 0) {
              pcVar7 = *(char **)(iVar8 + 0x28);
            }
            else {
              pcVar7 = *(char **)(iVar8 + 0x3c);
            }
            pYVar2->m_help = pcVar7;
          }
          else {
            arg4 = 0x80505050;
            if (lVar6 == 0) {
              pcStack_14 = (char *)0x0;
            }
            else {
              if (*(int *)(iVar8 + 0x3c) == 0) {
                pcStack_1c = *(char **)(iVar8 + 0x28);
              }
              else {
                pcStack_1c = *(char **)(iVar8 + 0x3c);
              }
              pcStack_14 = pcStack_1c;
            }
            pYVar2->m_help = pcStack_14;
          }
        }
        YkWndListItem::Set
                  (pYVar2,0,'\f',(void *)(uint)*(ushort *)(iVar3 + 0x19900),0x80808080);
        YkWndListItem::Set
                  (pYVar2,3,'\x06',(void *)(*(int *)(iVar3 + 0x19904) + 1),0x80808080);
        YkWndListItem::Set(pYVar2,1,'\x0e',(void *)(uint)*(ushort *)(iVar3 + 0x19900),arg4)
        ;
        if (*(char *)(iVar3 + 0x19902) == '\x01') {
          YkWndListItem::Set(pYVar2,2,'\0',(void *)0x0,0x80808080);
        }
        else {
          YkWndListItem::Set
                    (pYVar2,2,'\x10',(void *)(uint)*(ushort *)(iVar3 + 0x19900),0x80808080);
        }
        YkWndListItem::Set
                  (pYVar2,5,'\n',(&this->m_market)[*(int *)(iVar3 + 0x19908)],0x80808080);
        pYVar2->m_user = pvVar9;
        *(short *)&this->m_ownmax = *(short *)&this->m_ownmax + 1;
      }
    }
    YkWndList::SetItem(this,this->m_ownitem,*(undefined2 *)&this->m_ownmax);
    if (*(short *)&this->m_ownmax == 0) {
      uVar4 = XiStrGet(7,0x69);
      *(undefined4 *)&this->field_0x3c = uVar4;
      this->field_0x40 = 0x20;
      this->field_0x41 = 0x18;
    }
    this->m_lastcurok = '\x01';
    this->m_reload = '\0';
  }
  return;
}



// ---------------------------------------------------------------------------
// Open
// YkWndAuctionItem::Open(int, char)
//   symbol: Open__16YkWndAuctionItemFic
//   rva:    0x003a9b10  size: 488 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndAuction.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void YkWndAuctionItem::Open(YkWndAuctionItem *this,int mode,char fromhis)

{
  undefined4 uVar1;
  char *arg1_00;
  long lVar2;
  YmMenuShapeFile *this_00;
  int iVar3;
  char cStack_20;
  
  cStack_20 = (char)mode;
  this->m_mode = cStack_20;
  if (this->m_mode == '\0') {
    if (fromhis == '\0') {
      YkWndSearchList::OpenSearch((YkWndSearchList *)this,4,&this->field_0x22c,'\0','\x01');
    }
    else {
      YkWndSearchList::OpenSearch((YkWndSearchList *)this,7,&this->field_0x22c,'\0','\x01');
    }
  }
  else if (((this->m_mode == '\x01') && (*(int *)(_g_pYkWndAuctionMain + 8) != 0)) &&
          (*(char *)(*(int *)(_g_pYkWndAuctionMain + 8) + 0x6e) == '\0')) {
    for (iVar3 = 0; iVar3 < 8; iVar3 = iVar3 + 1) {
      (&this->m_owncheck)[iVar3] = '\0';
    }
    lVar2 = GetMenuRes__Fi(4);
    if (lVar2 != 0) {
      this_00 = (YmMenuShapeFile *)lVar2;
      uVar1 = YmMenuShapeFile::operator[](this_00,0x49);
      *(undefined4 *)&this->field_0x2e4 = uVar1;
      uVar1 = YmMenuShapeFile::operator[](this_00,0x4b);
      *(undefined4 *)&this->field_0x2e8 = uVar1;
      uVar1 = YmMenuShapeFile::operator[](this_00,0x4a);
      *(undefined4 *)&this->field_0x2ec = uVar1;
      uVar1 = YmMenuShapeFile::operator[](this_00,0x68);
      *(undefined4 *)&this->field_0x2f0 = uVar1;
    }
    arg1_00 = (char *)XiStrGet(0xd,0x12);
    CTkTitle::SetMessage(_g_pTkTitle,arg1_00,2);
    YkWndAuctionItem::MakeListOwn(this);
    (**(code **)(*(int *)&this->field_0x4 + 0x78))();
  }
  return;
}



// ---------------------------------------------------------------------------
// OpenWindow
// YkWndAuctionItem::OpenWindow(void)
//   symbol: OpenWindow__16YkWndAuctionItemFv
//   rva:    0x003a9d00  size: 168 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndAuction.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void YkWndAuctionItem::OpenWindow(YkWndAuctionItem *this)

{
  YkWndList::SetLine(this,10);
  *(undefined2 *)&this->field_0x16 = 6;
  *(undefined1 **)&this->field_0x30 = ykauctionitemoffset;
  *(undefined2 *)&this->field_0x26 = 0x12;
  *(undefined2 *)&this->field_0x2c = 0;
  *(undefined2 *)&this->field_0x2e = 4;
  CTkItemInfo::Open(_g_pTkItemInfo,0,'\x01','\0');
  CTkMenuMng::CreateDrawMenu((CTkMenuMng *)&g_TkMenuMng,_2376,'\x01','\0');
  this->m_lastcurok = '\0';
  return;
}



// ---------------------------------------------------------------------------
// CloseWindow
// YkWndAuctionItem::CloseWindow(void)
//   symbol: CloseWindow__16YkWndAuctionItemFv
//   rva:    0x003a9db0  size: 488 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndAuction.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void YkWndAuctionItem::CloseWindow(YkWndAuctionItem *this)

{
  undefined2 uVar1;
  long lVar2;
  
  if ((*(int *)&this->field_0x38 != 0) && (this->m_mode != '\x01')) {
    lVar2 = YkWndSearchList::GetCurData((YkWndSearchList *)this);
    if (lVar2 != 0) {
      *(undefined2 *)&this->m_lastitem = *(undefined2 *)((int)lVar2 + 4);
    }
    uVar1 = YkWndList::GetCurPos((YkWndList *)this);
    *(undefined2 *)&this->m_lastcur = uVar1;
  }
  CTkMenuMng::DestroyDrawMenu
            ((CTkMenuMng *)&g_TkMenuMng,*(CTkMenuCtrlData **)(_g_pTkItemInfo + 8),'\x01');
  CTkMenuMng::DestroyDrawMenu((CTkMenuMng *)&g_TkMenuMng,_2376);
  CTkMenuMng::DestroyDrawMenu((CTkMenuMng *)&g_TkMenuMng,_2401);
  CTkMenuMng::DestroyDrawMenu((CTkMenuMng *)&g_TkMenuMng,_2402);
  CTkMenuMng::DestroyDrawMenu((CTkMenuMng *)&g_TkMenuMng,_2403);
  CTkMenuMng::DestroyDrawMenu((CTkMenuMng *)&g_TkMenuMng,_2404);
  if (this->m_ownitem != (YkWndListItem *)0x0) {
    if (this->m_ownitem != (YkWndListItem *)0x0) {
      __dla__FPv(&this->m_ownitem[-1].field_0x60);
    }
    this->m_ownitem = (YkWndListItem *)0x0;
  }
  if (this->m_ownuser != (_YK_SEARCH_DATA *)0x0) {
    if (this->m_ownuser != (_YK_SEARCH_DATA *)0x0) {
      __dla__FPv(&this->m_ownuser[-1].field_0x24);
    }
    this->m_ownuser = (_YK_SEARCH_DATA *)0x0;
  }
  CTkTitle::SetMessage(_g_pTkTitle,(char *)0x0,2);
  return;
}



// ---------------------------------------------------------------------------
// EditLine
// YkWndAuctionItem::EditLine(YkWndListItem *, _YK_SEARCH_DATA *)
//   symbol: EditLine__16YkWndAuctionItemFP13YkWndListItemP15_YK_SEARCH_DATA
//   rva:    0x003a9fa0  size: 340 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndAuction.cpp
// ---------------------------------------------------------------------------


/* WARNING: Unknown calling convention -- yet parameter storage is locked */

undefined4
YkWndAuctionItem::EditLine
          (YkWndAuctionItem *this,YkWndListItem *item,_YK_SEARCH_DATA *user)

{
  if (*(int *)user == 2) {
    YkWndListItem::Set((YkWndListItem *)item,3,'\x05',*(void **)(user + 8),0x80808080);
    YkWndListItem::Set
              ((YkWndListItem *)item,1,'\x0f',(void *)(uint)*(ushort *)(user + 4),0x80808080);
  }
  else if (*(int *)user == 3) {
    YkWndListItem::Set((YkWndListItem *)item,3,'\x05',*(void **)(user + 0xc),0x80808080);
    YkWndListItem::Set
              ((YkWndListItem *)item,2,'\x10',(void *)(uint)*(ushort *)(user + 4),0x80808080);
    YkWndListItem::Set
              ((YkWndListItem *)item,1,'\x0e',(void *)(uint)*(ushort *)(user + 4),0x80505090);
  }
  YkWndListItem::Set
            ((YkWndListItem *)item,0,'\f',(void *)(uint)*(ushort *)(user + 4),0x80808080);
  return 1;
}



// ---------------------------------------------------------------------------
// EndLine
// YkWndAuctionItem::EndLine(void)
//   symbol: EndLine__16YkWndAuctionItemFv
//   rva:    0x003aa100  size: 484 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndAuction.cpp
// ---------------------------------------------------------------------------


/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void YkWndAuctionItem::EndLine(YkWndAuctionItem *this)

{
  short sVar1;
  bool bVar2;
  int iVar3;
  
  if (-1 < *(short *)&this->m_lastcur) {
    sVar1 = *(short *)&this->m_lastcur;
    bVar2 = false;
    if ((*(int *)&this->field_0x38 != 0) && (sVar1 < *(short *)&this->field_0x20)) {
      bVar2 = true;
    }
    if (bVar2) {
      iVar3 = *(int *)&this->field_0x38 + sVar1 * 0x70;
    }
    else {
      iVar3 = 0;
    }
    if (iVar3 == 0) {
      iVar3 = 0;
    }
    else {
      bVar2 = false;
      if ((*(int *)&this->field_0x38 != 0) && (sVar1 < *(short *)&this->field_0x20)) {
        bVar2 = true;
      }
      if (bVar2) {
        iVar3 = *(int *)&this->field_0x38 + sVar1 * 0x70;
      }
      else {
        iVar3 = 0;
      }
      iVar3 = *(int *)(iVar3 + 0x68);
    }
    if ((iVar3 != 0) && ((ulong)*(ushort *)(iVar3 + 4) == (long)*(short *)&this->m_lastitem)) {
      YkWndList::SetCurPos((YkWndList *)this,(int)*(short *)&this->m_lastcur,0);
    }
  }
  this->m_lastcurok = '\x01';
  return;
}



// ---------------------------------------------------------------------------
// OnCalc
// YkWndAuctionItem::OnCalc(char)
//   symbol: OnCalc__16YkWndAuctionItemFc
//   rva:    0x003aa2f0  size: 704 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndAuction.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void YkWndAuctionItem::OnCalc(YkWndAuctionItem *this,char active)

{
  bool bVar1;
  long lVar2;
  int *piVar3;
  int iVar4;
  
  if (this->m_mode == '\x01') {
    YkWndAuctionItem::MakeListOwn(this);
  }
  if (*(int *)&_g_pTkItemInfo->field_0x8 == 0) {
    CTkItemInfo::Open(_g_pTkItemInfo,0,'\x01','\0');
  }
  if (active != '\0') {
    if (this->m_mode == '\x01') {
      if (*(int *)&this->field_0x8 == 0) {
        iVar4 = 0;
      }
      else if (_pGlobalNowZone == 0) {
        iVar4 = 0;
      }
      else {
        lVar2 = YkWndList::GetCurPos((YkWndList *)this);
        if ((((this->m_ownitem == (YkWndListItem *)0x0) || (lVar2 < 0)) ||
            (*(short *)&this->m_ownmax <= lVar2)) || (7 < lVar2)) {
          iVar4 = 0;
        }
        else {
          iVar4 = _pGlobalNowZone + (int)this->m_ownitem[(int)lVar2].m_user * 0x28 + 0x198ec;
        }
      }
      if (iVar4 == 0) {
        CTkItemInfo::SetItemInfo(_g_pTkItemInfo);
      }
      else {
        CTkItemInfo::SetItemInfo(_g_pTkItemInfo,*(ushort *)(iVar4 + 0x14),0,0);
      }
    }
    else {
      lVar2 = YkWndSearchList::GetCurData((YkWndSearchList *)this);
      bVar1 = false;
      if ((*(int *)&this->field_0x38 != 0) && (0 < *(short *)&this->field_0x20)) {
        bVar1 = true;
      }
      if (bVar1) {
        iVar4 = *(int *)&this->field_0x38;
      }
      else {
        iVar4 = 0;
      }
      if (((iVar4 == 0) || (lVar2 == 0)) ||
         ((piVar3 = (int *)lVar2, *piVar3 != 2 && (*piVar3 != 3)))) {
        CTkItemInfo::SetItemInfo(_g_pTkItemInfo);
      }
      else {
        CTkItemInfo::SetItemInfo(_g_pTkItemInfo,*(ushort *)(piVar3 + 1),0,0);
      }
    }
  }
  return;
}



// ---------------------------------------------------------------------------
// OnKeyOK
// YkWndAuctionItem::OnKeyOK(short)
//   symbol: OnKeyOK__16YkWndAuctionItemFs
//   rva:    0x003aa5b0  size: 1208 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndAuction.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined4 YkWndAuctionItem::OnKeyOK(YkWndSearchList *this)

{
  char cVar1;
  undefined4 uVar2;
  int iVar3;
  long lVar4;
  int *piVar5;
  int iVar6;
  undefined1 auStack_e0 [8];
  undefined2 uStack_d8;
  uint uStack_d4;
  undefined1 auStack_90 [8];
  undefined2 uStack_88;
  uint uStack_84;
  int iStack_34;
  int iStack_30;
  int iStack_2c;
  int iStack_28;
  int iStack_24;
  YkWndSearchList *pYStack_20;
  
  pYStack_20 = this;
  if (this[1].field_0x2 == '\0') {
    YmSePlayBeep__Fv();
    uVar2 = 1;
  }
  else {
    if (*(char *)(this + 1) == '\x01') {
      if (*(int *)&this->field_0x8 == 0) {
        iVar6 = 0;
      }
      else if (_pGlobalNowZone == 0) {
        iVar6 = 0;
      }
      else {
        lVar4 = YkWndList::GetCurPos((YkWndList *)this);
        if ((((*(int *)&pYStack_20[1].field_0x24 == 0) || (lVar4 < 0)) ||
            (*(short *)&pYStack_20[1].field_0x4 <= lVar4)) || (7 < lVar4)) {
          iVar6 = 0;
        }
        else {
          iStack_30 = *(int *)(*(int *)&pYStack_20[1].field_0x24 + (int)lVar4 * 0x70 + 0x68);
          iVar6 = _pGlobalNowZone + iStack_30 * 0x28 + 0x198ec;
          iStack_2c = iStack_30;
        }
      }
      if (iVar6 == 0) {
        CTkItemInfo::SetItemInfo(_g_pTkItemInfo);
      }
      else {
        CTkItemInfo::SetItemInfo(_g_pTkItemInfo,*(ushort *)(iVar6 + 0x14),0,0);
      }
    }
    else {
      lVar4 = YkWndSearchList::GetCurData(this);
      if ((lVar4 == 0) || ((piVar5 = (int *)lVar4, *piVar5 != 2 && (*piVar5 != 3)))) {
        CTkItemInfo::SetItemInfo(_g_pTkItemInfo);
      }
      else {
        CTkItemInfo::SetItemInfo(_g_pTkItemInfo,*(ushort *)(piVar5 + 1),0,0);
      }
    }
    if (g_Betted == '\0') {
      if (*(char *)(pYStack_20 + 1) == '\x01') {
        if (*(int *)&pYStack_20->field_0x8 == 0) {
          iVar6 = -1;
        }
        else {
          lVar4 = YkWndList::GetCurPos((YkWndList *)pYStack_20);
          if (((*(int *)&pYStack_20[1].field_0x24 == 0) || (lVar4 < 0)) ||
             ((*(short *)&pYStack_20[1].field_0x4 <= lVar4 || (7 < lVar4)))) {
            iVar6 = -1;
          }
          else {
            iStack_34 = *(int *)&pYStack_20[1].field_0x24 + (int)lVar4 * 0x70;
            iVar6 = *(int *)(iStack_34 + 0x68);
            iStack_28 = iVar6;
            iStack_24 = iVar6;
          }
        }
        if (iVar6 < 0) {
          YmSePlayBeep__Fv();
        }
        else {
          iVar3 = _pGlobalNowZone + iVar6 * 0x28;
          cVar1 = *(char *)(iVar3 + 0x198ec);
          if (cVar1 == '\x03') {
            CTkMenuMng::CreateDrawMenu((CTkMenuMng *)&g_TkMenuMng,_2402,'\x01','\0');
          }
          else if (((cVar1 == '\v') || (cVar1 == '\r')) || (cVar1 == '\x16')) {
            memset(auStack_90,0,0x50);
            uStack_88 = 0xae;
            uStack_84 = (uint)*(ushort *)(iVar3 + 0x19900);
            PutSystemMessage__FP6SYSMES(auStack_90);
            SendAuction_Clear(iVar6);
          }
          else if (((cVar1 == '\n') || (cVar1 == '\f')) || (cVar1 == '\x15')) {
            memset(auStack_e0,0,0x50);
            uStack_d8 = 0xad;
            uStack_d4 = (uint)*(ushort *)(iVar3 + 0x19900);
            PutSystemMessage__FP6SYSMES(auStack_e0);
            SendAuction_Clear(iVar6);
          }
        }
      }
      else {
        lVar4 = YkWndSearchList::GetCurData(pYStack_20);
        if (lVar4 != 0) {
          CTkMenuMng::CreateDrawMenu((CTkMenuMng *)&g_TkMenuMng,_2401,'\x01','\0');
        }
      }
      uVar2 = 1;
    }
    else {
      CTkMsgWinData::AddErr(_g_pMsgWinData,0x6d);
      uVar2 = 0;
    }
  }
  return uVar2;
}



// ---------------------------------------------------------------------------
// OpenWindow
// YkWndAuctionHistory::OpenWindow(void)
//   symbol: OpenWindow__19YkWndAuctionHistoryFv
//   rva:    0x003aaa70  size: 160 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndAuction.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void YkWndAuctionHistory::OpenWindow(YkWndAuctionHistory *this)

{
  YkWndList::SetLine(this,10);
  *(undefined2 *)&this->field_0x16 = 5;
  *(undefined1 **)&this->field_0x30 = ykauctionhisoffset;
  *(undefined2 *)&this->field_0x26 = 0x12;
  *(undefined2 *)&this->field_0x2c = 0;
  *(undefined2 *)&this->field_0x2e = 4;
  CTkItemInfo::Open(_g_pTkItemInfo,0,'\x01','\0');
  CTkMenuMng::CreateDrawMenu((CTkMenuMng *)&g_TkMenuMng,_2549,'\x01','\0');
  return;
}



// ---------------------------------------------------------------------------
// CloseWindow
// YkWndAuctionHistory::CloseWindow(void)
//   symbol: CloseWindow__19YkWndAuctionHistoryFv
//   rva:    0x003aab10  size: 168 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndAuction.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void YkWndAuctionHistory::CloseWindow(YkWndAuctionHistory *this)

{
  CTkMenuMng::DestroyDrawMenu
            ((CTkMenuMng *)&g_TkMenuMng,*(CTkMenuCtrlData **)(_g_pTkItemInfo + 8),'\x01');
  CTkMenuMng::DestroyDrawMenu((CTkMenuMng *)&g_TkMenuMng,_2549);
  CTkMenuMng::DestroyDrawMenu((CTkMenuMng *)&g_TkMenuMng,_2401);
  if (-1 < *(short *)&this->m_retmode) {
    YkWndAuctionItem::Open(_g_pYkWndAuctionItem,(int)*(short *)&this->m_retmode,'\x01');
  }
  return;
}



// ---------------------------------------------------------------------------
// EditLine
// YkWndAuctionHistory::EditLine(YkWndListItem *, _YK_SEARCH_DATA *)
//   symbol: EditLine__19YkWndAuctionHistoryFP13YkWndListItemP15_YK_SEARCH_DATA
//   rva:    0x003aabc0  size: 252 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndAuction.cpp
// ---------------------------------------------------------------------------


/* WARNING: Unknown calling convention -- yet parameter storage is locked */

undefined4
YkWndAuctionHistory::EditLine
          (YkWndAuctionHistory *this,YkWndListItem *item,_YK_SEARCH_DATA *user)

{
  void *arg3;
  
  YkWndListItem::Set((YkWndListItem *)item,0,'\x03',*(void **)(user + 8),0x80808080);
  YkWndListItem::Set((YkWndListItem *)item,1,'\x13',user + 0xc,0x80808080);
  arg3 = (void *)XiStrGet(9,0x3b);
  YkWndListItem::Set((YkWndListItem *)item,2,'\x02',arg3,0x80808080);
  YkWndListItem::Set((YkWndListItem *)item,3,'\x13',user + 0x1c,0x80808080);
  YkWndListItem::Set
            ((YkWndListItem *)item,4,'\x06',(void *)(*(int *)(user + 4) + 1),0x80808080);
  return 1;
}



// ---------------------------------------------------------------------------
// OnCalc
// YkWndAuctionHistory::OnCalc(char)
//   symbol: OnCalc__19YkWndAuctionHistoryFc
//   rva:    0x003aacc0  size: 112 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndAuction.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void YkWndAuctionHistory::OnCalc(YkWndAuctionHistory *this,char isActive)

{
  if (*(int *)&_g_pTkItemInfo->field_0x8 == 0) {
    CTkItemInfo::Open(_g_pTkItemInfo,0,'\x01','\0');
  }
  if (isActive != '\0') {
    CTkItemInfo::SetItemInfo(_g_pTkItemInfo,this->m_itemno,0,0);
  }
  return;
}



// ---------------------------------------------------------------------------
// OnInitialUpdatePrimitive
// YkWndAuctionOwn::OnInitialUpdatePrimitive(void)
//   symbol: OnInitialUpdatePrimitive__15YkWndAuctionOwnFv
//   rva:    0x003aad30  size: 652 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndAuction.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void YkWndAuctionOwn::OnInitialUpdatePrimitive(YkWndAuctionOwn *this)

{
  YkWndList *pYVar1;
  undefined8 uVar2;
  int iVar3;
  char *pcVar4;
  long lVar5;
  
  pYVar1 = _g_pYkWndAuctionItem;
  if (_pGlobalNowZone != 0) {
    if (*(int *)&_g_pYkWndAuctionItem->field_0x8 == 0) {
      pcVar4 = (char *)0x0;
    }
    else if (_pGlobalNowZone == 0) {
      pcVar4 = (char *)0x0;
    }
    else {
      lVar5 = YkWndList::GetCurPos(_g_pYkWndAuctionItem);
      if ((((*(int *)&pYVar1[0xb].field_0xc == 0) || (lVar5 < 0)) ||
          (*(short *)&pYVar1[10].m_offset <= lVar5)) || (7 < lVar5)) {
        pcVar4 = (char *)0x0;
      }
      else {
        pcVar4 = (char *)(_pGlobalNowZone +
                          *(int *)(*(int *)&pYVar1[0xb].field_0xc + (int)lVar5 * 0x70 + 0x68) * 0x28
                         + 0x198ec);
      }
    }
    if (*pcVar4 != '\x03') {
      CTkMenuCtrlData::SetButtonStatus(*(undefined4 *)(this + 8),5,2);
    }
    for (iVar3 = 0; *(short *)(MarketTbl + iVar3 * 4) != 0; iVar3 = iVar3 + 1) {
      if ((long)*(int *)(_pGlobalNowZone + 0x25138) == (long)*(short *)(MarketTbl + iVar3 * 4)) {
        lVar5 = (long)*(short *)(MarketTbl + iVar3 * 4 + 2);
        goto LAB_004aaef4;
      }
    }
    lVar5 = 0;
LAB_004aaef4:
    if (*(int *)(pcVar4 + 0x1c) == lVar5) {
      uVar2 = XiStrGet(0xe,0x43);
      CTkMenuCtrlData::SetButtonHelpString(*(undefined4 *)(this + 8),2,uVar2);
    }
    else {
      CTkMenuCtrlData::SetButtonStatus(*(undefined4 *)(this + 8),5,1);
      CTkMenuCtrlData::SetButtonStatus(*(undefined4 *)(this + 8),5,2);
      uVar2 = XiStrGet(0xe,0x44);
      CTkMenuCtrlData::SetButtonHelpString(*(undefined4 *)(this + 8),2,uVar2);
    }
  }
  return;
}



// ---------------------------------------------------------------------------
// CancelYnCallBack
// CancelYnCallBack(void *, char)
//   symbol: CancelYnCallBack__FPvc
//   rva:    0x003aafc0  size: 120 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndAuction.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void CancelYnCallBack__FPvc(undefined4 user,char yes)

{
  if (yes != '\0') {
    SendAuction_LotCancel(user);
    *(undefined1 *)(_g_pYkWndAuctionItem + 0x2d5) = 1;
  }
  return;
}



// ---------------------------------------------------------------------------
// OnKeyDown
// YkWndAuctionOwn::OnKeyDown(short, short)
//   symbol: OnKeyDown__15YkWndAuctionOwnFss
//   rva:    0x003ab040  size: 720 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndAuction.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void YkWndAuctionOwn::OnKeyDown(int this,short idx,short param_3)

{
  char cVar1;
  YkWndSearchList *pYVar2;
  int iVar3;
  long lVar4;
  
  pYVar2 = _g_pYkWndAuctionItem;
  if ((_g_pYkWndAuctionItem == (YkWndSearchList *)0x0) || (idx == 5)) {
    if (*(int *)&_g_pYkWndAuctionItem->field_0x8 == 0) {
      iVar3 = -1;
    }
    else {
      lVar4 = YkWndList::GetCurPos((YkWndList *)_g_pYkWndAuctionItem);
      if ((((*(int *)&pYVar2[1].field_0x24 == 0) || (lVar4 < 0)) ||
          (*(short *)&pYVar2[1].field_0x4 <= lVar4)) || (7 < lVar4)) {
        iVar3 = -1;
      }
      else {
        iVar3 = *(int *)(*(int *)&pYVar2[1].field_0x24 + (int)lVar4 * 0x70 + 0x68);
      }
    }
    if (-1 < iVar3) {
      iVar3 = _pGlobalNowZone + iVar3 * 0x28;
      if (param_3 == 2) {
        if (*(char *)(iVar3 + 0x198ec) == '\x03') {
          XiStrGet(9,0x3a);
          YkWndYesno::Open(_g_pYkWndYesno);
        }
        else {
          YmSePlayBeep__Fv();
        }
      }
      else if (param_3 == 1) {
        lVar4 = IsSearchBusy__Fv();
        if (lVar4 == 0) {
          if (_g_pYkWndAuctionHistory != (YkWndSearchList *)0x0) {
            YkWndSearchList::CloseSearch(_g_pYkWndAuctionItem);
            pYVar2 = _g_pYkWndAuctionHistory;
            cVar1 = *(char *)(iVar3 + 0x19902);
            *(undefined2 *)(_g_pYkWndAuctionHistory + 1) = *(undefined2 *)(iVar3 + 0x19900);
            *(undefined2 *)&pYVar2[1].field_0x2 = 1;
            if (cVar1 == '\x01') {
              YkWndSearchList::OpenSearch
                        (pYVar2,5,(void *)(uint)*(ushort *)(pYVar2 + 1),'\0','\0');
            }
            else {
              YkWndSearchList::OpenSearch
                        (pYVar2,6,(void *)(uint)*(ushort *)(pYVar2 + 1),'\0','\0');
            }
          }
        }
        else {
          YmSePlayBeep__Fv();
        }
      }
      CTkMenuMng::DestroyDrawMenu
                ((CTkMenuMng *)&g_TkMenuMng,*(CTkMenuCtrlData **)(this + 8),'\x01');
    }
  }
  return;
}



// ---------------------------------------------------------------------------
// OnInitialUpdatePrimitive
// YkWndAuctionMarket::OnInitialUpdatePrimitive(void)
//   symbol: OnInitialUpdatePrimitive__18YkWndAuctionMarketFv
//   rva:    0x003ab310  size: 348 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndAuction.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void YkWndAuctionMarket::OnInitialUpdatePrimitive(YkWndAuctionMarket *this)

{
  short sVar1;
  bool bVar2;
  long lVar3;
  int *piVar4;
  
  bVar2 = false;
  lVar3 = YkWndSearchList::GetCurData(_g_pYkWndAuctionItem);
  piVar4 = (int *)lVar3;
  if ((lVar3 != 0) &&
     (lVar3 = CTkItemData::LoadItemDataNow_NOICON(_g_pTkItemData,(uint)*(ushort *)(piVar4 + 1))
     , lVar3 != 0)) {
    sVar1 = *(short *)((int)lVar3 + 4);
    if (sVar1 == 5) {
      bVar2 = true;
    }
    else if ((sVar1 == 4) && (*(short *)((int)lVar3 + 0x14) != 0x30)) {
      bVar2 = true;
    }
  }
  if (((*piVar4 == 2) && (piVar4[2] != 0)) || ((*piVar4 == 3 && (piVar4[3] != 0)))) {
    this->m_bet = '\x01';
  }
  else {
    CTkMenuCtrlData::SetButtonStatus(*(undefined4 *)&this->field_0x8,5,2);
    this->m_bet = '\0';
  }
  if (!bVar2) {
    CTkMenuCtrlData::SetButtonStatus(*(undefined4 *)&this->field_0x8,5,3);
  }
  return;
}



// ---------------------------------------------------------------------------
// OnDrawCalc
// YkWndAuctionMarket::OnDrawCalc(char)
//   symbol: OnDrawCalc__18YkWndAuctionMarketFc
//   rva:    0x003ab470  size: 176 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndAuction.cpp
// ---------------------------------------------------------------------------


/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void YkWndAuctionMarket::OnDrawCalc(YkWndAuctionMarket *this,char arg1)

{
  long lVar1;
  
  if (g_BetPrint == '\0') {
    if ((this->m_bet != '\0') &&
       (lVar1 = CTkMenuCtrlData::GetButtonStatus(*(CTkMenuCtrlData **)&this->field_0x8,2),
       lVar1 == 5)) {
      CTkMenuCtrlData::SetButtonStatus(*(undefined4 *)&this->field_0x8,0xb,2);
    }
  }
  else {
    lVar1 = CTkMenuCtrlData::GetButtonStatus(*(CTkMenuCtrlData **)&this->field_0x8,2);
    if (lVar1 != 5) {
      CTkMenuCtrlData::SetButtonStatus(*(undefined4 *)&this->field_0x8,5,2);
    }
  }
  return;
}



// ---------------------------------------------------------------------------
// BetYnCallBack
// BetYnCallBack(void *, char)
//   symbol: BetYnCallBack__FPvc
//   rva:    0x003ab520  size: 336 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndAuction.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void BetYnCallBack__FPvc(undefined4 user,char yes)

{
  int iVar1;
  
  if (yes != '\0') {
    for (iVar1 = 0; iVar1 < 8; iVar1 = iVar1 + 1) {
      if (*(char *)(_pGlobalNowZone + iVar1 * 0x28 + 0x198ec) == '\0') goto LAB_004ab5b4;
    }
    iVar1 = -1;
LAB_004ab5b4:
    if (iVar1 < 0) {
      CTkMsgWinData::AddErr(_g_pMsgWinData,0x6b);
    }
    else {
      SendAuction_Bid(iVar1,user,_g_BetPrice,_g_BetCount);
      g_Betted = 1;
      if (_g_pTkHelp != 0) {
        KaHelpMes::SetLoadMes((KaHelpMes *)(_g_pTkHelp + 0x20),0x80000000);
      }
    }
  }
  CTkItemInfo::Open(_g_pTkItemInfo,0,'\x01','\0');
  CTkMenuMng::DestroyDrawMenu((CTkMenuMng *)&g_TkMenuMng,_2703);
  return;
}



// ---------------------------------------------------------------------------
// BetCallBack
// BetCallBack(int, void *)
//   symbol: BetCallBack__FiPv
//   rva:    0x003ab670  size: 644 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndAuction.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void BetCallBack__FiPv(int num,int *user)

{
  bool bVar1;
  char *__format;
  long lVar2;
  undefined8 uVar3;
  undefined8 uVar4;
  CTkItemDataMenber *this;
  
  if (num < 1) {
    CTkItemInfo::Open(_g_pTkItemInfo,0,'\x01','\0');
    CTkMenuMng::DestroyDrawMenu((CTkMenuMng *)&g_TkMenuMng,_2703);
  }
  else {
    lVar2 = CTkItemData::GetItemDataMenber(_g_pTkItemData,(uint)*(ushort *)(user + 1));
    _g_BetCount = (uint)(*user != 3);
    _g_BetPrice = num;
    if (lVar2 != 0) {
      this = (CTkItemDataMenber *)lVar2;
      lVar2 = CTkItemData::IsLoaded(_g_pTkItemData,(CTkItemDataMenber *)this)
      ;
      if (lVar2 != 0) {
        bVar1 = false;
        if ((this->m_pStackMax != (ushort *)0x0) && (1 < *this->m_pStackMax)) {
          bVar1 = true;
        }
        if ((bVar1) && (*user == 3)) {
          uVar3 = CTkItemDataMenber::GetLongItemsName(this);
        }
        else {
          uVar3 = CTkItemDataMenber::GetLongItemName(this);
        }
        uVar4 = YkGetMoneyString__Fic(num);
        XiStrSnprintfStr(0x6a72f0,0x40,10,0x1e,2,uVar3,uVar4);
        XiStrGet(0xd,0x12);
        YkWndYesno::Open(_g_pYkWndYesno);
        return;
      }
    }
    __format = (char *)XiStrGet(10,0x2c);
    uVar3 = YkGetMoneyString__Fic(num);
    sprintf(&betstr1,__format,uVar3);
    XiStrGet(0xd,0x12);
    YkWndYesno::Open(_g_pYkWndYesno);
  }
  return;
}



// ---------------------------------------------------------------------------
// OnKeyDown
// YkWndAuctionMarket::OnKeyDown(short, short)
//   symbol: OnKeyDown__18YkWndAuctionMarketFss
//   rva:    0x003ab900  size: 756 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndAuction.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void YkWndAuctionMarket::OnKeyDown(int this,short idx,short param_3)

{
  short sVar1;
  int iVar2;
  int iVar3;
  YkWndSearchList *this_00;
  long lVar4;
  long lVar5;
  int *piVar6;
  
  if ((_g_pYkWndAuctionItem != (YkWndSearchList *)0x0) && (idx != 5)) {
    return;
  }
  lVar4 = YkWndSearchList::GetCurData(_g_pYkWndAuctionItem);
  if (lVar4 == 0) {
    return;
  }
  piVar6 = (int *)lVar4;
  if (param_3 == 3) {
    lVar4 = CTkItemData::GetItemDataMenber(_g_pTkItemData,(uint)*(ushort *)(piVar6 + 1));
    if (lVar4 == 0) {
      return;
    }
    lVar5 = CTkItemData::IsLoaded(_g_pTkItemData,(CTkItemDataMenber *)lVar4);
    if (lVar5 == 0) {
      return;
    }
    sVar1 = **(short **)((CTkItemDataMenber *)lVar4 + 0xc08);
    if (sVar1 == 5) {
      CTkMenuMng::CreateDrawMenu((CTkMenuMng *)&g_TkMenuMng,_2404,'\x01','\0');
    }
    else if (sVar1 == 4) {
      CTkMenuMng::CreateDrawMenu((CTkMenuMng *)&g_TkMenuMng,_2403,'\x01','\0');
    }
  }
  else if (param_3 == 2) {
    CTkMoneyCtrl::Open(_g_pTkMoneyCtrl,0,0);
    CTkMenuMng::CreateDrawMenu((CTkMenuMng *)&g_TkMenuMng,_2703,'\x01','\0');
    if (*piVar6 == 3) {
      CTkItemInfo::Open(_g_pTkItemInfo,2,'\0','\x01');
    }
    else {
      CTkItemInfo::Open(_g_pTkItemInfo,2,'\0','\0');
    }
  }
  else if (param_3 == 1) {
    lVar4 = IsSearchBusy__Fv();
    if (lVar4 != 0) {
      YmSePlayBeep__Fv();
      return;
    }
    if (_g_pYkWndAuctionHistory != (YkWndSearchList *)0x0) {
      iVar3 = piVar6[1];
      iVar2 = *piVar6;
      YkWndSearchList::CloseSearch(_g_pYkWndAuctionItem);
      this_00 = _g_pYkWndAuctionHistory;
      *(short *)(_g_pYkWndAuctionHistory + 1) = (short)iVar3;
      *(undefined2 *)&this_00[1].field_0x2 = 0;
      if (iVar2 == 3) {
        YkWndSearchList::OpenSearch
                  (this_00,6,(void *)(uint)*(ushort *)(this_00 + 1),'\0','\0');
      }
      else {
        YkWndSearchList::OpenSearch
                  (this_00,5,(void *)(uint)*(ushort *)(this_00 + 1),'\0','\0');
      }
    }
  }
  CTkMenuMng::DestroyDrawMenu
            ((CTkMenuMng *)&g_TkMenuMng,*(CTkMenuCtrlData **)(this + 8),'\x01');
  return;
}



// ---------------------------------------------------------------------------
// OnCreate
// YkWndItemCtrlAuction::OnCreate(CTkMenuCtrlData *)
//   symbol: OnCreate__20YkWndItemCtrlAuctionFP15CTkMenuCtrlData
//   rva:    0x003abc00  size: 84 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndAuction.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void YkWndItemCtrlAuction::OnCreate
               (YkWndItemCtrlAuction *this,CTkMenuCtrlData *arg1)

{
  char *arg1_00;
  
  this->m_select = '\0';
  if (_g_pTkHelp != (CTkHelp *)0x0) {
    arg1_00 = (char *)XiStrGet(0xe,0x36);
    CTkHelp::SetHelpString(_g_pTkHelp,arg1_00,2);
  }
  return;
}



// ---------------------------------------------------------------------------
// OnDestroy
// YkWndItemCtrlAuction::OnDestroy(CTkMenuCtrlData *)
//   symbol: OnDestroy__20YkWndItemCtrlAuctionFP15CTkMenuCtrlData
//   rva:    0x003abc60  size: 56 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndAuction.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void YkWndItemCtrlAuction::OnDestroy
               (YkWndItemCtrlAuction *this,CTkMenuCtrlData *arg1)

{
  if (_g_pTkHelp != (CTkHelp *)0x0) {
    CTkHelp::SetHelpString(_g_pTkHelp,(char *)0x0,2);
  }
  return;
}



// ---------------------------------------------------------------------------
// DispFilter
// YkWndItemCtrlAuction::DispFilter(GC_ITEM_DATA *, CTkItemDataMenber *)
//   symbol: DispFilter__20YkWndItemCtrlAuctionFP12GC_ITEM_DATAP17CTkItemDataMenber
//   rva:    0x003abca0  size: 520 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndAuction.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

undefined8
YkWndItemCtrlAuction::DispFilter
          (YkWndItemCtrlAuction *this,GC_ITEM_DATA *pID,CTkItemDataMenber *pIDM)

{
  GC_ITEM_DATA GVar1;
  short sVar2;
  undefined8 uVar3;
  long lVar4;
  int iVar5;
  
  sVar2 = *(short *)pID;
  if (((sVar2 == 0x203) || (sVar2 == 0x202)) || (sVar2 == 0x201)) {
    uVar3 = 0x80505050;
  }
  else if (pID[8] == (GC_ITEM_DATA)0x19) {
    uVar3 = 0x80505050;
  }
  else {
    lVar4 = CTkEquip::IsEquipment(_g_pTkEquip,(byte)pID[2]);
    if (lVar4 == 0) {
      if ((**(ushort **)(pIDM + 0xc10) & 0x40) == 0) {
        if ((this->m_select == '\0') || ((GC_ITEM_DATA)this->m_selectidx != pID[2])) {
          if (_g_pAuctionFee != 0) {
            GVar1 = pID[2];
            if ((byte)GVar1 < 0x51) {
              if (*(int *)(_g_pAuctionFee + (uint)(byte)GVar1 * 4) < 0) {
                iVar5 = -2;
              }
              else {
                iVar5 = *(int *)(_g_pAuctionFee + (uint)(byte)GVar1 * 4);
              }
            }
            else {
              iVar5 = -1;
            }
            if (-1 < iVar5) {
              return 0x80409090;
            }
          }
          uVar3 = 0x80808080;
        }
        else {
          uVar3 = 0x80204080;
        }
      }
      else {
        uVar3 = 0x80505050;
      }
    }
    else {
      uVar3 = 0x80505050;
    }
  }
  return uVar3;
}



// ---------------------------------------------------------------------------
// PriceYnCallBack
// PriceYnCallBack(void *, char)
//   symbol: PriceYnCallBack__FPvc
//   rva:    0x003abeb0  size: 304 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndAuction.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void PriceYnCallBack__FPvc(int user,char yes)

{
  int iVar1;
  
  for (iVar1 = 0; iVar1 < 7; iVar1 = iVar1 + 1) {
    if (*(char *)(_pGlobalNowZone + iVar1 * 0x28 + 0x198ec) == '\0') goto LAB_004abf44;
  }
  iVar1 = -1;
LAB_004abf44:
  if ((yes == '\0') || (iVar1 < 0)) {
    if (iVar1 < 0) {
      CTkMsgWinData::AddErr(_g_pMsgWinData,0x6c);
    }
    CTkMenuMng::ActiveDrawMenu
              ((CTkMenuMng *)&g_TkMenuMng,*(CTkMenuCtrlData **)&_g_pYkWndItem->field_0x8,'\0');
  }
  else {
    SendAuction_LotIn(iVar1,*(undefined1 *)(user + 2),_g_price,_g_count);
    if (*(byte *)(user + 2) < 0x51) {
      *(undefined4 *)(_g_pAuctionFee + (uint)*(byte *)(user + 2) * 4) = 0xffffffff;
    }
    YkWndItem::Close(_g_pYkWndItem);
  }
  *(undefined1 *)(_g_pItemCtrlAuction + 4) = 0;
  if (_g_pTkHelp != (CTkHelp *)0x0) {
    CTkHelp::SetHelpString(_g_pTkHelp,(char *)0x0,2);
  }
  return;
}



// ---------------------------------------------------------------------------
// PriceCallBack
// PriceCallBack(int, void *)
//   symbol: PriceCallBack__FiPv
//   rva:    0x003ac060  size: 348 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndAuction.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void PriceCallBack__FiPv(int num)

{
  char *num;
  
  if (num < 1) {
    _g_price = -1;
    if (_g_pTkHelp != (CTkHelp *)0x0) {
      CTkHelp::SetHelpString(_g_pTkHelp,(char *)0x0,2);
    }
    *(undefined1 *)(_g_pItemCtrlAuction + 4) = 0;
  }
  else {
    _g_price = num;
    YkWndYesno::Open(_g_pYkWndShopSellYn);
    if (_g_pTkHelp != (CTkHelp *)0x0) {
      num = (char *)XiStrGet(0xe,0x38);
      CTkHelp::SetHelpString(_g_pTkHelp,num,2);
    }
  }
  CTkMenuMng::DestroyDrawMenu((CTkMenuMng *)&g_TkMenuMng,_2703);
  return;
}



// ---------------------------------------------------------------------------
// OnKey
// YkWndItemCtrlAuction::OnKey(short, short, unsigned char, GC_ITEM_DATA *)
//   symbol: OnKey__20YkWndItemCtrlAuctionFssUcP12GC_ITEM_DATA
//   rva:    0x003ac150  size: 1172 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndAuction.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void YkWndItemCtrlAuction::OnKey
               (int this,short pID,undefined8 param_3,undefined8 param_4,ushort *param_5)

{
  byte bVar1;
  bool bVar2;
  char *pcVar3;
  long lVar4;
  CTkItemDataMenber *type;
  int iVar5;
  char acStack_1e0 [256];
  char acStack_e0 [132];
  int iStack_5c;
  int iStack_58;
  uint uStack_54;
  int iStack_50;
  short sStack_40;
  ushort *puStack_10;
  
  iStack_50 = this;
  sStack_40 = pID;
  puStack_10 = param_5;
  if (pID == 6) {
    YkWndItem::Close(_g_pYkWndItem);
  }
  else if ((pID == 5) &&
          (lVar4 = CTkItemData::GetItemDataMenber(_g_pTkItemData,(uint)*param_5), lVar4 != 0))
  {
    type = (CTkItemDataMenber *)lVar4;
    lVar4 = CTkItemData::IsLoaded(_g_pTkItemData,type);
    iVar5 = _g_pAuctionFee;
    if (lVar4 != 0) {
      bVar2 = false;
      if ((*(int *)(type + 0xc14) != 0) && (1 < **(ushort **)(type + 0xc14))) {
        bVar2 = true;
      }
      if (((bVar2) && ((uint)**(ushort **)(type + 0xc14) != *(uint *)(puStack_10 + 2))) &&
         (*(int *)(puStack_10 + 2) != 1)) {
        pcVar3 = (char *)XiStrGet(10,0x1b);
        sprintf(acStack_e0,pcVar3,(ulong)**(ushort **)(type + 0xc14));
        CTkMsgWinData::AddErrorString(_g_pMsgWinData,acStack_e0);
        YmSePlayBeep__Fv();
      }
      else {
        bVar1 = (byte)puStack_10[1];
        if (bVar1 < 0x51) {
          if (*(int *)(_g_pAuctionFee + (uint)bVar1 * 4) < 0) {
            if ((*(int *)(_g_pAuctionFee + (uint)bVar1 * 4) == -1) &&
               (lVar4 = gcItemIndex(0,bVar1), lVar4 != 0)) {
              SendAuction_AskCommit(0,0,*(undefined2 *)lVar4,*(int *)((undefined2 *)lVar4 + 2) == 1)
              ;
              *(undefined4 *)(iVar5 + (uint)bVar1 * 4) = 0xfffffffe;
            }
            iVar5 = -2;
          }
          else {
            iVar5 = *(int *)(_g_pAuctionFee + (uint)bVar1 * 4);
          }
        }
        else {
          iVar5 = -1;
        }
        lVar4 = gcItemIndex();
        if (lVar4 == 0) {
          iStack_58 = 0;
        }
        else {
          iStack_58 = *(int *)((int)lVar4 + 4);
        }
        iStack_5c = iStack_58;
        if (iVar5 == -2) {
          CTkMsgWinData::AddMsg(_g_pMsgWinData,0x3c);
          YmSePlayClick__Fv();
        }
        else if (iVar5 == -1) {
          YmSePlayBeep__Fv();
        }
        else {
          if (*(uint *)(puStack_10 + 2) < 2) {
            pcVar3 = (char *)XiStrGet(10,0x1c);
            sprintf(acStack_1e0,pcVar3,iVar5);
          }
          else {
            pcVar3 = (char *)XiStrGet(10,0x1d);
            sprintf(acStack_1e0,pcVar3,*(undefined4 *)(puStack_10 + 2),iVar5);
          }
          CTkMsgWinData::AddSystemString(_g_pMsgWinData,acStack_1e0);
          if (iStack_5c < iVar5) {
            CTkMsgWinData::AddMsg(_g_pMsgWinData,0x3d);
            YmSePlayBeep__Fv();
          }
          else {
            *(undefined1 *)(iStack_50 + 4) = 1;
            *(char *)(iStack_50 + 5) = (char)puStack_10[1];
            if (_g_pTkHelp != (CTkHelp *)0x0) {
              pcVar3 = (char *)XiStrGet(0xe,0x37);
              CTkHelp::SetHelpString(_g_pTkHelp,pcVar3,2);
            }
            CTkMenuMng::CreateDrawMenu((CTkMenuMng *)&g_TkMenuMng,_2703,'\x01','\0');
            uStack_54 = (uint)(*(int *)(puStack_10 + 2) == 1);
            _g_count = uStack_54;
            CTkMoneyCtrl::Open(_g_pTkMoneyCtrl,0,999999999);
            YmSePlayClick__Fv();
          }
        }
      }
    }
  }
  return;
}



// ---------------------------------------------------------------------------
// 
// YkWndAuctionMain::YkWndAuctionMain(void)
//   symbol: __ct__16YkWndAuctionMainFv
//   rva:    0x003ac5f0  size: 3060 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndAuction.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

YkWndAuctionMain * YkWndAuctionMain::YkWndAuctionMain(YkWndAuctionMain *this)

{
  CTkObject *pCVar1;
  YkWndList *pYVar2;
  long lVar3;
  int iStack_c8;
  
  CTkObject::CTkObject((CTkObject *)this);
  *(undefined1 **)&this->field_0x4 = __vt__16CTkMenuPrimitive;
  *(undefined2 *)&this->field_0xe = 0xffff;
  *(undefined4 *)&this->field_0x8 = 0;
  (**(code **)(*(int *)&this->field_0x4 + 0xc))();
  this->field_0xc = 1;
  *(undefined1 **)&this->field_0x4 = __vt__16YkWndAuctionMain;
  pCVar1 = _g_pYkWndAuctionSub;
  if (_g_pYkWndAuctionSub == (CTkObject *)0x0) {
    lVar3 = __nw__FUi(0x14);
    pCVar1 = (CTkObject *)lVar3;
    if (lVar3 != 0) {
      CTkObject::CTkObject(pCVar1);
      pCVar1[1] = (CTkObject)__vt__16CTkMenuPrimitive;
      *(undefined2 *)&pCVar1[3].m_RecSub1 = 0xffff;
      pCVar1[2].m_RecKind = (short)0x0;
      pCVar1[2].field_0x1 = 0;
      pCVar1[2].m_RecSub1 = (short)0x0;
      pCVar1[2].field_0x3 = 0;
      (**(code **)((int)pCVar1[1] + 0xc))();
      pCVar1[3].m_RecKind = (short)0x1;
      pCVar1[1] = (CTkObject)__vt__18YkWndAuctionMenuEq;
      pCVar1[1] = (CTkObject)__vt__15YkWndAuctionSub;
    }
  }
  _g_pYkWndAuctionSub = pCVar1;
  pCVar1 = _g_pYkWndAuctionMenuWep;
  if (_g_pYkWndAuctionMenuWep == (CTkObject *)0x0) {
    lVar3 = __nw__FUi(0x14);
    pCVar1 = (CTkObject *)lVar3;
    if (lVar3 != 0) {
      CTkObject::CTkObject(pCVar1);
      pCVar1[1] = (CTkObject)__vt__16CTkMenuPrimitive;
      *(undefined2 *)&pCVar1[3].m_RecSub1 = 0xffff;
      pCVar1[2].m_RecKind = (short)0x0;
      pCVar1[2].field_0x1 = 0;
      pCVar1[2].m_RecSub1 = (short)0x0;
      pCVar1[2].field_0x3 = 0;
      (**(code **)((int)pCVar1[1] + 0xc))();
      pCVar1[3].m_RecKind = (short)0x1;
      pCVar1[1] = (CTkObject)__vt__18YkWndAuctionMenuEq;
      pCVar1[1] = (CTkObject)__vt__19YkWndAuctionMenuWep;
    }
  }
  _g_pYkWndAuctionMenuWep = pCVar1;
  pCVar1 = _g_pYkWndAuctionMenuBullet;
  if (_g_pYkWndAuctionMenuBullet == (CTkObject *)0x0) {
    lVar3 = __nw__FUi(0x14);
    pCVar1 = (CTkObject *)lVar3;
    if (lVar3 != 0) {
      CTkObject::CTkObject(pCVar1);
      pCVar1[1] = (CTkObject)__vt__16CTkMenuPrimitive;
      *(undefined2 *)&pCVar1[3].m_RecSub1 = 0xffff;
      pCVar1[2].m_RecKind = (short)0x0;
      pCVar1[2].field_0x1 = 0;
      pCVar1[2].m_RecSub1 = (short)0x0;
      pCVar1[2].field_0x3 = 0;
      (**(code **)((int)pCVar1[1] + 0xc))();
      pCVar1[3].m_RecKind = (short)0x1;
      pCVar1[1] = (CTkObject)__vt__18YkWndAuctionMenuEq;
      pCVar1[1] = (CTkObject)__vt__22YkWndAuctionMenuBullet;
    }
  }
  _g_pYkWndAuctionMenuBullet = pCVar1;
  pCVar1 = _g_pYkWndAuctionMenuArm;
  if (_g_pYkWndAuctionMenuArm == (CTkObject *)0x0) {
    lVar3 = __nw__FUi(0x14);
    pCVar1 = (CTkObject *)lVar3;
    if (lVar3 != 0) {
      CTkObject::CTkObject(pCVar1);
      pCVar1[1] = (CTkObject)__vt__16CTkMenuPrimitive;
      *(undefined2 *)&pCVar1[3].m_RecSub1 = 0xffff;
      pCVar1[2].m_RecKind = (short)0x0;
      pCVar1[2].field_0x1 = 0;
      pCVar1[2].m_RecSub1 = (short)0x0;
      pCVar1[2].field_0x3 = 0;
      (**(code **)((int)pCVar1[1] + 0xc))();
      pCVar1[3].m_RecKind = (short)0x1;
      pCVar1[1] = (CTkObject)__vt__18YkWndAuctionMenuEq;
      pCVar1[1] = (CTkObject)__vt__19YkWndAuctionMenuArm;
    }
  }
  _g_pYkWndAuctionMenuArm = pCVar1;
  pCVar1 = _g_pYkWndAuctionMenuMgc;
  if (_g_pYkWndAuctionMenuMgc == (CTkObject *)0x0) {
    lVar3 = __nw__FUi(0x14);
    pCVar1 = (CTkObject *)lVar3;
    if (lVar3 != 0) {
      CTkObject::CTkObject(pCVar1);
      pCVar1[1] = (CTkObject)__vt__16CTkMenuPrimitive;
      *(undefined2 *)&pCVar1[3].m_RecSub1 = 0xffff;
      pCVar1[2].m_RecKind = (short)0x0;
      pCVar1[2].field_0x1 = 0;
      pCVar1[2].m_RecSub1 = (short)0x0;
      pCVar1[2].field_0x3 = 0;
      (**(code **)((int)pCVar1[1] + 0xc))();
      pCVar1[3].m_RecKind = (short)0x1;
      pCVar1[1] = (CTkObject)__vt__18YkWndAuctionMenuEq;
      pCVar1[1] = (CTkObject)__vt__19YkWndAuctionMenuMgc;
    }
  }
  _g_pYkWndAuctionMenuMgc = pCVar1;
  pCVar1 = _g_pYkWndAuctionMenuMat;
  if (_g_pYkWndAuctionMenuMat == (CTkObject *)0x0) {
    lVar3 = __nw__FUi(0x14);
    pCVar1 = (CTkObject *)lVar3;
    if (lVar3 != 0) {
      CTkObject::CTkObject(pCVar1);
      pCVar1[1] = (CTkObject)__vt__16CTkMenuPrimitive;
      *(undefined2 *)&pCVar1[3].m_RecSub1 = 0xffff;
      pCVar1[2].m_RecKind = (short)0x0;
      pCVar1[2].field_0x1 = 0;
      pCVar1[2].m_RecSub1 = (short)0x0;
      pCVar1[2].field_0x3 = 0;
      (**(code **)((int)pCVar1[1] + 0xc))();
      pCVar1[3].m_RecKind = (short)0x1;
      pCVar1[1] = (CTkObject)__vt__18YkWndAuctionMenuEq;
      pCVar1[1] = (CTkObject)__vt__19YkWndAuctionMenuMat;
    }
  }
  _g_pYkWndAuctionMenuMat = pCVar1;
  pCVar1 = _g_pYkWndAuctionMenuFood;
  if (_g_pYkWndAuctionMenuFood == (CTkObject *)0x0) {
    lVar3 = __nw__FUi(0x14);
    pCVar1 = (CTkObject *)lVar3;
    if (lVar3 != 0) {
      CTkObject::CTkObject(pCVar1);
      pCVar1[1] = (CTkObject)__vt__16CTkMenuPrimitive;
      *(undefined2 *)&pCVar1[3].m_RecSub1 = 0xffff;
      pCVar1[2].m_RecKind = (short)0x0;
      pCVar1[2].field_0x1 = 0;
      pCVar1[2].m_RecSub1 = (short)0x0;
      pCVar1[2].field_0x3 = 0;
      (**(code **)((int)pCVar1[1] + 0xc))();
      pCVar1[3].m_RecKind = (short)0x1;
      pCVar1[1] = (CTkObject)__vt__18YkWndAuctionMenuEq;
      pCVar1[1] = (CTkObject)__vt__20YkWndAuctionMenuFood;
    }
  }
  _g_pYkWndAuctionMenuFood = pCVar1;
  pCVar1 = _g_pYkWndAuctionMenuDish;
  if (_g_pYkWndAuctionMenuDish == (CTkObject *)0x0) {
    lVar3 = __nw__FUi(0x14);
    pCVar1 = (CTkObject *)lVar3;
    if (lVar3 != 0) {
      CTkObject::CTkObject(pCVar1);
      pCVar1[1] = (CTkObject)__vt__16CTkMenuPrimitive;
      *(undefined2 *)&pCVar1[3].m_RecSub1 = 0xffff;
      pCVar1[2].m_RecKind = (short)0x0;
      pCVar1[2].field_0x1 = 0;
      pCVar1[2].m_RecSub1 = (short)0x0;
      pCVar1[2].field_0x3 = 0;
      (**(code **)((int)pCVar1[1] + 0xc))();
      pCVar1[3].m_RecKind = (short)0x1;
      pCVar1[1] = (CTkObject)__vt__18YkWndAuctionMenuEq;
      pCVar1[1] = (CTkObject)__vt__20YkWndAuctionMenuDish;
    }
  }
  _g_pYkWndAuctionMenuDish = pCVar1;
  pCVar1 = _g_pYkWndAuctionMenuEtc;
  if (_g_pYkWndAuctionMenuEtc == (CTkObject *)0x0) {
    lVar3 = __nw__FUi(0x14);
    pCVar1 = (CTkObject *)lVar3;
    if (lVar3 != 0) {
      CTkObject::CTkObject(pCVar1);
      pCVar1[1] = (CTkObject)__vt__16CTkMenuPrimitive;
      *(undefined2 *)&pCVar1[3].m_RecSub1 = 0xffff;
      pCVar1[2].m_RecKind = (short)0x0;
      pCVar1[2].field_0x1 = 0;
      pCVar1[2].m_RecSub1 = (short)0x0;
      pCVar1[2].field_0x3 = 0;
      (**(code **)((int)pCVar1[1] + 0xc))();
      pCVar1[3].m_RecKind = (short)0x1;
      pCVar1[1] = (CTkObject)__vt__18YkWndAuctionMenuEq;
      pCVar1[1] = (CTkObject)__vt__19YkWndAuctionMenuEtc;
    }
  }
  _g_pYkWndAuctionMenuEtc = pCVar1;
  pYVar2 = _g_pYkWndAuctionItem;
  if (_g_pYkWndAuctionItem == (YkWndList *)0x0) {
    lVar3 = __nw__FUi(0x304);
    pYVar2 = (YkWndList *)lVar3;
    if (lVar3 != 0) {
      YkWndList::YkWndList(pYVar2,'\0');
      *(undefined1 **)&pYVar2->field_0x4 = __vt__15YkWndSearchList;
      *(undefined1 **)&pYVar2->field_0x4 = __vt__16YkWndAuctionItem;
      pYVar2[10].field_0x2d = 1;
      *(undefined4 *)&pYVar2[0xb].field_0xc = 0;
      *(undefined4 *)&pYVar2[0xb].field_0x8 = 0;
      *(undefined2 *)((int)&pYVar2[10].m_offset + 2) = 0;
      pYVar2[10].m_dy = (short)0x0;
      for (iStack_c8 = 0; iStack_c8 < 5; iStack_c8 = iStack_c8 + 1) {
        (&pYVar2[10].m_list)[iStack_c8] = (YkWndListItem *)0x0;
      }
    }
  }
  _g_pYkWndAuctionItem = pYVar2;
  pYVar2 = _g_pYkWndAuctionHistory;
  if (_g_pYkWndAuctionHistory == (YkWndList *)0x0) {
    lVar3 = __nw__FUi(0x2d8);
    pYVar2 = (YkWndList *)lVar3;
    if (lVar3 != 0) {
      YkWndList::YkWndList(pYVar2,'\0');
      *(undefined1 **)&pYVar2->field_0x4 = __vt__15YkWndSearchList;
      *(undefined1 **)&pYVar2->field_0x4 = __vt__19YkWndAuctionHistory;
    }
  }
  _g_pYkWndAuctionHistory = pYVar2;
  pCVar1 = _g_pYkWndAuctionMarket;
  if (_g_pYkWndAuctionMarket == (CTkObject *)0x0) {
    lVar3 = __nw__FUi(0x18);
    pCVar1 = (CTkObject *)lVar3;
    if (lVar3 != 0) {
      CTkObject::CTkObject(pCVar1);
      pCVar1[1] = (CTkObject)__vt__16CTkMenuPrimitive;
      *(undefined2 *)&pCVar1[3].m_RecSub1 = 0xffff;
      pCVar1[2].m_RecKind = (short)0x0;
      pCVar1[2].field_0x1 = 0;
      pCVar1[2].m_RecSub1 = (short)0x0;
      pCVar1[2].field_0x3 = 0;
      (**(code **)((int)pCVar1[1] + 0xc))();
      pCVar1[3].m_RecKind = (short)0x1;
      pCVar1[1] = (CTkObject)__vt__18YkWndAuctionMarket;
    }
  }
  _g_pYkWndAuctionMarket = pCVar1;
  pCVar1 = _g_pYkWndAuctionOwn;
  if (_g_pYkWndAuctionOwn == (CTkObject *)0x0) {
    lVar3 = __nw__FUi(0x14);
    pCVar1 = (CTkObject *)lVar3;
    if (lVar3 != 0) {
      CTkObject::CTkObject(pCVar1);
      pCVar1[1] = (CTkObject)__vt__16CTkMenuPrimitive;
      *(undefined2 *)&pCVar1[3].m_RecSub1 = 0xffff;
      pCVar1[2].m_RecKind = (short)0x0;
      pCVar1[2].field_0x1 = 0;
      pCVar1[2].m_RecSub1 = (short)0x0;
      pCVar1[2].field_0x3 = 0;
      (**(code **)((int)pCVar1[1] + 0xc))();
      pCVar1[3].m_RecKind = (short)0x1;
      pCVar1[1] = (CTkObject)__vt__15YkWndAuctionOwn;
    }
  }
  _g_pYkWndAuctionOwn = pCVar1;
  pCVar1 = _g_pYkWndAuctionWepSort;
  if (_g_pYkWndAuctionWepSort == (CTkObject *)0x0) {
    lVar3 = __nw__FUi(0x14);
    pCVar1 = (CTkObject *)lVar3;
    if (lVar3 != 0) {
      CTkObject::CTkObject(pCVar1);
      pCVar1[1] = (CTkObject)__vt__16CTkMenuPrimitive;
      *(undefined2 *)&pCVar1[3].m_RecSub1 = 0xffff;
      pCVar1[2].m_RecKind = (short)0x0;
      pCVar1[2].field_0x1 = 0;
      pCVar1[2].m_RecSub1 = (short)0x0;
      pCVar1[2].field_0x3 = 0;
      (**(code **)((int)pCVar1[1] + 0xc))();
      pCVar1[3].m_RecKind = (short)0x1;
      pCVar1[1] = (CTkObject)__vt__18YkWndAuctionMenuEq;
      pCVar1[1] = (CTkObject)__vt__19YkWndAuctionWepSort;
    }
  }
  _g_pYkWndAuctionWepSort = pCVar1;
  pCVar1 = _g_pYkWndAuctionArmSort;
  if (_g_pYkWndAuctionArmSort == (CTkObject *)0x0) {
    lVar3 = __nw__FUi(0x14);
    pCVar1 = (CTkObject *)lVar3;
    if (lVar3 != 0) {
      CTkObject::CTkObject(pCVar1);
      pCVar1[1] = (CTkObject)__vt__16CTkMenuPrimitive;
      *(undefined2 *)&pCVar1[3].m_RecSub1 = 0xffff;
      pCVar1[2].m_RecKind = (short)0x0;
      pCVar1[2].field_0x1 = 0;
      pCVar1[2].m_RecSub1 = (short)0x0;
      pCVar1[2].field_0x3 = 0;
      (**(code **)((int)pCVar1[1] + 0xc))();
      pCVar1[3].m_RecKind = (short)0x1;
      pCVar1[1] = (CTkObject)__vt__18YkWndAuctionMenuEq;
      pCVar1[1] = (CTkObject)__vt__19YkWndAuctionArmSort;
    }
  }
  _g_pYkWndAuctionArmSort = pCVar1;
  if (_g_pItemCtrlAuction == (undefined4 *)0x0) {
    lVar3 = __nw__FUi(8);
    _g_pItemCtrlAuction = (undefined4 *)0x0;
    if (lVar3 != 0) {
      _g_pItemCtrlAuction = (undefined4 *)lVar3;
      *_g_pItemCtrlAuction = __vt__13YkWndItemCtrl;
      *_g_pItemCtrlAuction = __vt__20YkWndItemCtrlAuction;
    }
  }
  return this;
}



// ---------------------------------------------------------------------------
// 
// YkWndAuctionMain::~YkWndAuctionMain(void)
//   symbol: __dt__16YkWndAuctionMainFv
//   rva:    0x003ad280  size: 1128 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndAuction.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

YkWndAuctionMain * YkWndAuctionMain::~YkWndAuctionMain(YkWndAuctionMain *this)

{
  short in_a1_lo;
  
  if (this != (YkWndAuctionMain *)0x0) {
    *(undefined1 **)&this->field_0x4 = __vt__16YkWndAuctionMain;
    if (_g_pYkWndAuctionSub != 0) {
      if (_g_pYkWndAuctionSub != 0) {
        (**(code **)(*(int *)(_g_pYkWndAuctionSub + 4) + 8))(_g_pYkWndAuctionSub,1);
      }
      _g_pYkWndAuctionSub = 0;
    }
    if (_g_pYkWndAuctionMenuWep != 0) {
      if (_g_pYkWndAuctionMenuWep != 0) {
        (**(code **)(*(int *)(_g_pYkWndAuctionMenuWep + 4) + 8))(_g_pYkWndAuctionMenuWep,1);
      }
      _g_pYkWndAuctionMenuWep = 0;
    }
    if (_g_pYkWndAuctionMenuBullet != 0) {
      if (_g_pYkWndAuctionMenuBullet != 0) {
        (**(code **)(*(int *)(_g_pYkWndAuctionMenuBullet + 4) + 8))(_g_pYkWndAuctionMenuBullet,1);
      }
      _g_pYkWndAuctionMenuBullet = 0;
    }
    if (_g_pYkWndAuctionMenuArm != 0) {
      if (_g_pYkWndAuctionMenuArm != 0) {
        (**(code **)(*(int *)(_g_pYkWndAuctionMenuArm + 4) + 8))(_g_pYkWndAuctionMenuArm,1);
      }
      _g_pYkWndAuctionMenuArm = 0;
    }
    if (_g_pYkWndAuctionMenuMgc != 0) {
      if (_g_pYkWndAuctionMenuMgc != 0) {
        (**(code **)(*(int *)(_g_pYkWndAuctionMenuMgc + 4) + 8))(_g_pYkWndAuctionMenuMgc,1);
      }
      _g_pYkWndAuctionMenuMgc = 0;
    }
    if (_g_pYkWndAuctionMenuMat != 0) {
      if (_g_pYkWndAuctionMenuMat != 0) {
        (**(code **)(*(int *)(_g_pYkWndAuctionMenuMat + 4) + 8))(_g_pYkWndAuctionMenuMat,1);
      }
      _g_pYkWndAuctionMenuMat = 0;
    }
    if (_g_pYkWndAuctionMenuFood != 0) {
      if (_g_pYkWndAuctionMenuFood != 0) {
        (**(code **)(*(int *)(_g_pYkWndAuctionMenuFood + 4) + 8))(_g_pYkWndAuctionMenuFood,1);
      }
      _g_pYkWndAuctionMenuFood = 0;
    }
    if (_g_pYkWndAuctionMenuDish != 0) {
      if (_g_pYkWndAuctionMenuDish != 0) {
        (**(code **)(*(int *)(_g_pYkWndAuctionMenuDish + 4) + 8))(_g_pYkWndAuctionMenuDish,1);
      }
      _g_pYkWndAuctionMenuDish = 0;
    }
    if (_g_pYkWndAuctionMenuEtc != 0) {
      if (_g_pYkWndAuctionMenuEtc != 0) {
        (**(code **)(*(int *)(_g_pYkWndAuctionMenuEtc + 4) + 8))(_g_pYkWndAuctionMenuEtc,1);
      }
      _g_pYkWndAuctionMenuEtc = 0;
    }
    if (_g_pYkWndAuctionItem != 0) {
      if (_g_pYkWndAuctionItem != 0) {
        (**(code **)(*(int *)(_g_pYkWndAuctionItem + 4) + 8))(_g_pYkWndAuctionItem,1);
      }
      _g_pYkWndAuctionItem = 0;
    }
    if (_g_pYkWndAuctionHistory != 0) {
      if (_g_pYkWndAuctionHistory != 0) {
        (**(code **)(*(int *)(_g_pYkWndAuctionHistory + 4) + 8))(_g_pYkWndAuctionHistory,1);
      }
      _g_pYkWndAuctionHistory = 0;
    }
    if (_g_pYkWndAuctionMarket != 0) {
      if (_g_pYkWndAuctionMarket != 0) {
        (**(code **)(*(int *)(_g_pYkWndAuctionMarket + 4) + 8))(_g_pYkWndAuctionMarket,1);
      }
      _g_pYkWndAuctionMarket = 0;
    }
    if (_g_pYkWndAuctionOwn != 0) {
      if (_g_pYkWndAuctionOwn != 0) {
        (**(code **)(*(int *)(_g_pYkWndAuctionOwn + 4) + 8))(_g_pYkWndAuctionOwn,1);
      }
      _g_pYkWndAuctionOwn = 0;
    }
    if (_g_pYkWndAuctionWepSort != 0) {
      if (_g_pYkWndAuctionWepSort != 0) {
        (**(code **)(*(int *)(_g_pYkWndAuctionWepSort + 4) + 8))(_g_pYkWndAuctionWepSort,1);
      }
      _g_pYkWndAuctionWepSort = 0;
    }
    if (_g_pYkWndAuctionArmSort != 0) {
      if (_g_pYkWndAuctionArmSort != 0) {
        (**(code **)(*(int *)(_g_pYkWndAuctionArmSort + 4) + 8))(_g_pYkWndAuctionArmSort,1);
      }
      _g_pYkWndAuctionArmSort = 0;
    }
    if (_g_pItemCtrlAuction != 0) {
      __dl__FPv(_g_pItemCtrlAuction);
      _g_pItemCtrlAuction = 0;
    }
    if (this != (YkWndAuctionMain *)0x0) {
      *(undefined1 **)&this->field_0x4 = __vt__16CTkMenuPrimitive;
      CTkObject::~CTkObject((CTkObject *)this);
    }
    if (0 < in_a1_lo) {
      __dl__FPv(this);
    }
  }
  return this;
}



// ---------------------------------------------------------------------------
// OnInitialUpdatePrimitive
// YkWndAuctionMain::OnInitialUpdatePrimitive(void)
//   symbol: OnInitialUpdatePrimitive__16YkWndAuctionMainFv
//   rva:    0x003ae030  size: 160 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndAuction.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void YkWndAuctionMain::OnInitialUpdatePrimitive(YkWndAuctionMain *this)

{
  long lVar1;
  int iVar2;
  
  g_Betted = 0;
  g_BetPrint = 0;
  SendAuction_work(0xffffffffffffffff);
  if (_g_pAuctionFee == 0) {
    lVar1 = __nw__FUi(0x144);
    _g_pAuctionFee = (int)lVar1;
    if (lVar1 != 0) {
      for (iVar2 = 0; iVar2 < 0x51; iVar2 = iVar2 + 1) {
        *(undefined4 *)(_g_pAuctionFee + iVar2 * 4) = 0xffffffff;
      }
    }
  }
  return;
}



// ---------------------------------------------------------------------------
// OnDestroyPrimitive
// YkWndAuctionMain::OnDestroyPrimitive(void)
//   symbol: OnDestroyPrimitive__16YkWndAuctionMainFv
//   rva:    0x003ae0d0  size: 616 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndAuction.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void YkWndAuctionMain::OnDestroyPrimitive(YkWndAuctionMain *this)

{
  PrintAuctionResult__Fc(1);
  if (_g_pTkHelp != 0) {
    KaHelpMes::ResetLoadMes((KaHelpMes *)(_g_pTkHelp + 0x20),0x80000000);
  }
  CTkMoneyCtrl::Close(_g_pTkMoneyCtrl);
  CTkMenuMng::DestroyDrawMenu((CTkMenuMng *)&g_TkMenuMng,_2703);
  CTkMenuMng::DestroyDrawMenu
            ((CTkMenuMng *)&g_TkMenuMng,*(CTkMenuCtrlData **)(_g_pYkWndShopSellYn + 8),'\x01');
  CTkMenuMng::DestroyDrawMenu
            ((CTkMenuMng *)&g_TkMenuMng,*(CTkMenuCtrlData **)(_g_pYkWndYesno + 8),'\x01');
  YkWndItem::Close(_g_pYkWndItem);
  *(undefined2 *)(_g_pYkWndAuctionHistory + 0x2d6) = 0xffff;
  YkWndSearchList::ClearAllCache(_g_pYkWndAuctionItem);
  CTkMenuMng::DestroyDrawMenu((CTkMenuMng *)&g_TkMenuMng,_3443);
  CTkMenuMng::DestroyDrawMenu((CTkMenuMng *)&g_TkMenuMng,_3444);
  CTkMenuMng::DestroyDrawMenu((CTkMenuMng *)&g_TkMenuMng,_3445);
  CTkMenuMng::DestroyDrawMenu((CTkMenuMng *)&g_TkMenuMng,_3446);
  CTkMenuMng::DestroyDrawMenu((CTkMenuMng *)&g_TkMenuMng,_3447);
  CTkMenuMng::DestroyDrawMenu((CTkMenuMng *)&g_TkMenuMng,_3448);
  CTkMenuMng::DestroyDrawMenu((CTkMenuMng *)&g_TkMenuMng,_3449);
  CTkMenuMng::DestroyDrawMenu((CTkMenuMng *)&g_TkMenuMng,_3450);
  CTkMenuMng::DestroyDrawMenu((CTkMenuMng *)&g_TkMenuMng,_3451);
  CTkMenuMng::DestroyDrawMenu((CTkMenuMng *)&g_TkMenuMng,_2376);
  CTkMenuMng::DestroyDrawMenu((CTkMenuMng *)&g_TkMenuMng,_2549);
  CTkMenuMng::DestroyDrawMenu((CTkMenuMng *)&g_TkMenuMng,_2401);
  CTkMenuMng::DestroyDrawMenu((CTkMenuMng *)&g_TkMenuMng,_2402);
  CTkMenuMng::DestroyDrawMenu((CTkMenuMng *)&g_TkMenuMng,_2403);
  CTkMenuMng::DestroyDrawMenu((CTkMenuMng *)&g_TkMenuMng,_2404);
  if (_g_pAuctionFee != 0) {
    __dl__FPv(_g_pAuctionFee);
    _g_pAuctionFee = 0;
  }
  return;
}



// ---------------------------------------------------------------------------
// Open
// YkWndAuctionMain::Open(void)
//   symbol: Open__16YkWndAuctionMainFv
//   rva:    0x003ae340  size: 396 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndAuction.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

undefined4 YkWndAuctionMain::Open(YkWndAuctionMain *this)

{
  undefined4 uVar1;
  uint uVar2;
  long lVar3;
  
  lVar3 = CTkMenuMng::IsPropertyWindow((CTkMenuMng *)&g_TkMenuMng,0x20000);
  if ((lVar3 == 0) && (*(int *)(_g_pTkInputCtrl + 0x54) == 0)) {
    uVar2 = gcZoneActIndex();
    uVar2 = uVar2 & 0xffff;
    if (uVar2 == 0) {
      uVar1 = 0;
    }
    else {
      this->m_pos = *(float *)(*(int *)(&ActerBuffPtr + uVar2 * 4) + 0x10);
      *(undefined4 *)&this->field_0x24 = *(undefined4 *)(*(int *)(&ActerBuffPtr + uVar2 * 4) + 0x14)
      ;
      *(undefined4 *)&this->field_0x28 = *(undefined4 *)(*(int *)(&ActerBuffPtr + uVar2 * 4) + 0x18)
      ;
      CTkMenuMng::CreateDrawMenu((CTkMenuMng *)&g_TkMenuMng,_3471,'\x01','\0');
      uVar1 = 1;
    }
  }
  else {
    CTkMsgWinData::AddErrMsg(_g_pMsgWinData,3);
    uVar1 = 0;
  }
  return uVar1;
}



// ---------------------------------------------------------------------------
// OnDrawCalc
// YkWndAuctionMain::OnDrawCalc(char)
//   symbol: OnDrawCalc__16YkWndAuctionMainFc
//   rva:    0x003ae4d0  size: 404 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndAuction.cpp
// ---------------------------------------------------------------------------


/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void YkWndAuctionMain::OnDrawCalc(YkWndAuctionMain *this,char arg1)

{
  uint uVar1;
  float fVar2;
  float fVar3;
  
  uVar1 = gcZoneActIndex(this,arg1);
  uVar1 = uVar1 & 0xffff;
  if ((uVar1 != 0) &&
     (fVar2 = *(float *)(*(int *)(&ActerBuffPtr + uVar1 * 4) + 0x10) - this->m_pos,
     fVar3 = *(float *)(*(int *)(&ActerBuffPtr + uVar1 * 4) + 0x18) - *(float *)&this->field_0x28,
     36.0 < fVar2 * fVar2 + fVar3 * fVar3)) {
    CTkMenuMng::DestroyDrawMenu
              ((CTkMenuMng *)&g_TkMenuMng,*(CTkMenuCtrlData **)&this->field_0x8,'\x01');
  }
  PrintAuctionResult__Fc();
  return;
}



// ---------------------------------------------------------------------------
// OnKeyDown
// YkWndAuctionMain::OnKeyDown(short, short)
//   symbol: OnKeyDown__16YkWndAuctionMainFss
//   rva:    0x003ae670  size: 236 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndAuction.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void YkWndAuctionMain::OnKeyDown(undefined8 type,short idx,short param_3)

{
  char *type;
  long lVar1;
  
  if (idx == 5) {
    if (param_3 == 3) {
      lVar1 = SendAuction_Info();
      if (lVar1 == 0) {
        YmSePlayBeep__Fv();
      }
    }
    else if (param_3 == 2) {
      type = (char *)XiStrGet(0xd,0x12);
      CTkTitle::SetMessage(_g_pTkTitle,type,2);
      YkWndItem::Open(_g_pYkWndItem,_g_pItemCtrlAuction);
    }
    else if (param_3 == 1) {
      CTkMenuMng::CreateDrawMenu((CTkMenuMng *)&g_TkMenuMng,_3443,'\x01','\0');
    }
  }
  return;
}



// ---------------------------------------------------------------------------
// OnActive
// YkWndAuctionMenuEq::OnActive(unsigned char)
//   symbol: OnActive__18YkWndAuctionMenuEqFUc
//   rva:    0x003ae760  size: 60 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndAuction.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void YkWndAuctionMenuEq::OnActive(YkWndAuctionMenuEq *this,byte active)

{
  if ((active != 0) && (_g_pYkWndAuctionItem != 0)) {
    *(undefined2 *)(_g_pYkWndAuctionItem + 0x2da) = 0;
  }
  return;
}



// ---------------------------------------------------------------------------
// OnKeyDown
// YkWndAuctionMenuEq::OnKeyDown(short, short)
//   symbol: OnKeyDown__18YkWndAuctionMenuEqFss
//   rva:    0x003ae7a0  size: 128 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndAuction.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void YkWndAuctionMenuEq::OnKeyDown(int this,short idx,undefined2 param_3)

{
  long lVar1;
  
  if ((_g_pYkWndAuctionItem == 0) || (idx == 5)) {
    lVar1 = IsSearchBusy__Fv();
    if (lVar1 == 0) {
      (**(code **)(*(int *)(this + 4) + 0x58))(this,param_3);
    }
    else {
      YmSePlayBeep__Fv();
    }
  }
  return;
}



// ---------------------------------------------------------------------------
// OnOK
// YkWndAuctionSub::OnOK(short)
//   symbol: OnOK__15YkWndAuctionSubFs
//   rva:    0x003ae820  size: 1220 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndAuction.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void YkWndAuctionSub::OnOK(undefined8 idx,undefined2 param_2)

{
  FFWCaAuctionQInfo *pFVar1;
  FFWCaAuctionQInfo *pFVar2;
  int iVar3;
  undefined2 uVar4;
  
  pFVar2 = (FFWCaAuctionQInfo *)&_g_pYkWndAuctionItem->field_0x22c;
  switch(param_2) {
  case 1:
    CTkMenuMng::CreateDrawMenu((CTkMenuMng *)&g_TkMenuMng,_3444,'\x01','\0');
    break;
  case 2:
    CTkMenuMng::CreateDrawMenu((CTkMenuMng *)&g_TkMenuMng,_3446,'\x01','\0');
    break;
  case 3:
    CTkMenuMng::CreateDrawMenu((CTkMenuMng *)&g_TkMenuMng,_3447,'\x01','\0');
    break;
  case 4:
    if (_pGlobalNowZone != 0) {
      pFVar1 = (FFWCaAuctionQInfo *)&_g_pYkWndAuctionItem->field_0x22c;
      YkWndSearchList::InitAucInfo((YkWndSearchList *)_g_pYkWndAuctionItem);
      for (iVar3 = 0; *(short *)(MarketTbl + iVar3 * 4) != 0; iVar3 = iVar3 + 1) {
        if ((long)*(int *)(_pGlobalNowZone + 0x25138) == (long)*(short *)(MarketTbl + iVar3 * 4)) {
          uVar4 = *(undefined2 *)(MarketTbl + iVar3 * 4 + 2);
          goto LAB_004aec7c;
        }
      }
      uVar4 = 0;
LAB_004aec7c:
      FFWCaSetAuctionMarket(pFVar1,uVar4);
    }
    FFWCaSetAuctionCategory(pFVar2,0x21);
    YkWndAuctionItem::Open(_g_pYkWndAuctionItem,0,'\0');
    break;
  case 5:
    if (_pGlobalNowZone != 0) {
      pFVar1 = (FFWCaAuctionQInfo *)&_g_pYkWndAuctionItem->field_0x22c;
      YkWndSearchList::InitAucInfo((YkWndSearchList *)_g_pYkWndAuctionItem);
      for (iVar3 = 0; *(short *)(MarketTbl + iVar3 * 4) != 0; iVar3 = iVar3 + 1) {
        if ((long)*(int *)(_pGlobalNowZone + 0x25138) == (long)*(short *)(MarketTbl + iVar3 * 4)) {
          uVar4 = *(undefined2 *)(MarketTbl + iVar3 * 4 + 2);
          goto LAB_004aea5c;
        }
      }
      uVar4 = 0;
LAB_004aea5c:
      FFWCaSetAuctionMarket(pFVar1,uVar4);
    }
    FFWCaSetAuctionCategory(pFVar2,0x22);
    YkWndAuctionItem::Open(_g_pYkWndAuctionItem,0,'\0');
    break;
  case 6:
    CTkMenuMng::CreateDrawMenu((CTkMenuMng *)&g_TkMenuMng,_3448,'\x01','\0');
    break;
  case 7:
    CTkMenuMng::CreateDrawMenu((CTkMenuMng *)&g_TkMenuMng,_3449,'\x01','\0');
    break;
  case 8:
    if (_pGlobalNowZone != 0) {
      pFVar1 = (FFWCaAuctionQInfo *)&_g_pYkWndAuctionItem->field_0x22c;
      YkWndSearchList::InitAucInfo((YkWndSearchList *)_g_pYkWndAuctionItem);
      for (iVar3 = 0; *(short *)(MarketTbl + iVar3 * 4) != 0; iVar3 = iVar3 + 1) {
        if ((long)*(int *)(_pGlobalNowZone + 0x25138) == (long)*(short *)(MarketTbl + iVar3 * 4)) {
          uVar4 = *(undefined2 *)(MarketTbl + iVar3 * 4 + 2);
          goto LAB_004aeb6c;
        }
      }
      uVar4 = 0;
LAB_004aeb6c:
      FFWCaSetAuctionMarket(pFVar1,uVar4);
    }
    FFWCaSetAuctionCategory(pFVar2,0x23);
    YkWndAuctionItem::Open(_g_pYkWndAuctionItem,0,'\0');
    break;
  case 9:
    CTkMenuMng::CreateDrawMenu((CTkMenuMng *)&g_TkMenuMng,_3451,'\x01','\0');
  }
  return;
}



// ---------------------------------------------------------------------------
// OnOK
// YkWndAuctionMenuWep::OnOK(short)
//   symbol: OnOK__19YkWndAuctionMenuWepFs
//   rva:    0x003aecf0  size: 456 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndAuction.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void YkWndAuctionMenuWep::OnOK(undefined8 idx,short param_2)

{
  int iVar1;
  undefined2 uVar2;
  FFWCaAuctionQInfo *pFVar3;
  
  if (param_2 == 0xf) {
    CTkMenuMng::CreateDrawMenu((CTkMenuMng *)&g_TkMenuMng,_3445,'\x01','\0');
  }
  else {
    if (_pGlobalNowZone != 0) {
      pFVar3 = (FFWCaAuctionQInfo *)&_g_pYkWndAuctionItem->field_0x22c;
      YkWndSearchList::InitAucInfo((YkWndSearchList *)_g_pYkWndAuctionItem);
      for (iVar1 = 0; *(short *)(MarketTbl + iVar1 * 4) != 0; iVar1 = iVar1 + 1) {
        if ((long)*(int *)(_pGlobalNowZone + 0x25138) == (long)*(short *)(MarketTbl + iVar1 * 4)) {
          uVar2 = *(undefined2 *)(MarketTbl + iVar1 * 4 + 2);
          goto LAB_004aee18;
        }
      }
      uVar2 = 0;
LAB_004aee18:
      FFWCaSetAuctionMarket(pFVar3,uVar2);
    }
    FFWCaSetAuctionCategory
              ((FFWCaAuctionQInfo *)&_g_pYkWndAuctionItem->field_0x22c,(&DAT_0051b2ff)[param_2]);
    YkWndAuctionItem::Open(_g_pYkWndAuctionItem,0,'\0');
  }
  return;
}



// ---------------------------------------------------------------------------
// OnOK
// YkWndAuctionMenuBullet::OnOK(short)
//   symbol: OnOK__22YkWndAuctionMenuBulletFs
//   rva:    0x003aeec0  size: 388 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndAuction.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void YkWndAuctionMenuBullet::OnOK(undefined8 idx,short param_2)

{
  int iVar1;
  undefined2 uVar2;
  FFWCaAuctionQInfo *pFVar3;
  
  if (_pGlobalNowZone != 0) {
    pFVar3 = (FFWCaAuctionQInfo *)&_g_pYkWndAuctionItem->field_0x22c;
    YkWndSearchList::InitAucInfo((YkWndSearchList *)_g_pYkWndAuctionItem);
    for (iVar1 = 0; *(short *)(MarketTbl + iVar1 * 4) != 0; iVar1 = iVar1 + 1) {
      if ((long)*(int *)(_pGlobalNowZone + 0x25138) == (long)*(short *)(MarketTbl + iVar1 * 4)) {
        uVar2 = *(undefined2 *)(MarketTbl + iVar1 * 4 + 2);
        goto LAB_004aefa8;
      }
    }
    uVar2 = 0;
LAB_004aefa8:
    FFWCaSetAuctionMarket(pFVar3,uVar2);
  }
  FFWCaSetAuctionCategory
            ((FFWCaAuctionQInfo *)&_g_pYkWndAuctionItem->field_0x22c,
             *(undefined1 *)((int)&PTR_DAT_0054d5f3 + (int)param_2));
  YkWndAuctionItem::Open(_g_pYkWndAuctionItem,0,'\0');
  return;
}



// ---------------------------------------------------------------------------
// OnOK
// YkWndAuctionMenuArm::OnOK(short)
//   symbol: OnOK__19YkWndAuctionMenuArmFs
//   rva:    0x003af050  size: 392 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndAuction.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void YkWndAuctionMenuArm::OnOK(undefined8 idx,short param_2)

{
  int iVar1;
  undefined2 uVar2;
  FFWCaAuctionQInfo *pFVar3;
  
  if (_pGlobalNowZone != 0) {
    pFVar3 = (FFWCaAuctionQInfo *)&_g_pYkWndAuctionItem->field_0x22c;
    YkWndSearchList::InitAucInfo((YkWndSearchList *)_g_pYkWndAuctionItem);
    for (iVar1 = 0; *(short *)(MarketTbl + iVar1 * 4) != 0; iVar1 = iVar1 + 1) {
      if ((long)*(int *)(_pGlobalNowZone + 0x25138) == (long)*(short *)(MarketTbl + iVar1 * 4)) {
        uVar2 = *(undefined2 *)(MarketTbl + iVar1 * 4 + 2);
        goto LAB_004af138;
      }
    }
    uVar2 = 0;
LAB_004af138:
    FFWCaSetAuctionMarket(pFVar3,uVar2);
  }
  FFWCaSetAuctionCategory
            ((FFWCaAuctionQInfo *)&_g_pYkWndAuctionItem->field_0x22c,AucWepCateTbl[param_2 + 0xf]);
  YkWndAuctionItem::Open(_g_pYkWndAuctionItem,0,'\0');
  return;
}



// ---------------------------------------------------------------------------
// OnOK
// YkWndAuctionMenuMgc::OnOK(short)
//   symbol: OnOK__19YkWndAuctionMenuMgcFs
//   rva:    0x003af1e0  size: 388 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndAuction.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void YkWndAuctionMenuMgc::OnOK(undefined8 idx,short param_2)

{
  int iVar1;
  undefined2 uVar2;
  FFWCaAuctionQInfo *pFVar3;
  
  if (_pGlobalNowZone != 0) {
    pFVar3 = (FFWCaAuctionQInfo *)&_g_pYkWndAuctionItem->field_0x22c;
    YkWndSearchList::InitAucInfo((YkWndSearchList *)_g_pYkWndAuctionItem);
    for (iVar1 = 0; *(short *)(MarketTbl + iVar1 * 4) != 0; iVar1 = iVar1 + 1) {
      if ((long)*(int *)(_pGlobalNowZone + 0x25138) == (long)*(short *)(MarketTbl + iVar1 * 4)) {
        uVar2 = *(undefined2 *)(MarketTbl + iVar1 * 4 + 2);
        goto LAB_004af2c8;
      }
    }
    uVar2 = 0;
LAB_004af2c8:
    FFWCaSetAuctionMarket(pFVar3,uVar2);
  }
  FFWCaSetAuctionCategory
            ((FFWCaAuctionQInfo *)&_g_pYkWndAuctionItem->field_0x22c,
             *(undefined1 *)((int)&PTR_DAT_0054d5f7 + (int)param_2));
  YkWndAuctionItem::Open(_g_pYkWndAuctionItem,0,'\0');
  return;
}



// ---------------------------------------------------------------------------
// OnOK
// YkWndAuctionMenuMat::OnOK(short)
//   symbol: OnOK__19YkWndAuctionMenuMatFs
//   rva:    0x003af370  size: 388 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndAuction.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void YkWndAuctionMenuMat::OnOK(undefined8 idx,short param_2)

{
  int iVar1;
  undefined2 uVar2;
  FFWCaAuctionQInfo *pFVar3;
  
  if (_pGlobalNowZone != 0) {
    pFVar3 = (FFWCaAuctionQInfo *)&_g_pYkWndAuctionItem->field_0x22c;
    YkWndSearchList::InitAucInfo((YkWndSearchList *)_g_pYkWndAuctionItem);
    for (iVar1 = 0; *(short *)(MarketTbl + iVar1 * 4) != 0; iVar1 = iVar1 + 1) {
      if ((long)*(int *)(_pGlobalNowZone + 0x25138) == (long)*(short *)(MarketTbl + iVar1 * 4)) {
        uVar2 = *(undefined2 *)(MarketTbl + iVar1 * 4 + 2);
        goto LAB_004af458;
      }
    }
    uVar2 = 0;
LAB_004af458:
    FFWCaSetAuctionMarket(pFVar3,uVar2);
  }
  FFWCaSetAuctionCategory
            ((FFWCaAuctionQInfo *)&_g_pYkWndAuctionItem->field_0x22c,(&DAT_0054d5ff)[param_2]);
  YkWndAuctionItem::Open(_g_pYkWndAuctionItem,0,'\0');
  return;
}



// ---------------------------------------------------------------------------
// OnOK
// YkWndAuctionMenuFood::OnOK(short)
//   symbol: OnOK__20YkWndAuctionMenuFoodFs
//   rva:    0x003af500  size: 472 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndAuction.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void YkWndAuctionMenuFood::OnOK(undefined8 idx,short param_2)

{
  int iVar1;
  undefined2 uVar2;
  FFWCaAuctionQInfo *pFVar3;
  
  if (param_2 == 1) {
    CTkMenuMng::CreateDrawMenu((CTkMenuMng *)&g_TkMenuMng,_3450,'\x01','\0');
  }
  else {
    if (_pGlobalNowZone != 0) {
      pFVar3 = (FFWCaAuctionQInfo *)&_g_pYkWndAuctionItem->field_0x22c;
      YkWndSearchList::InitAucInfo((YkWndSearchList *)_g_pYkWndAuctionItem);
      for (iVar1 = 0; *(short *)(MarketTbl + iVar1 * 4) != 0; iVar1 = iVar1 + 1) {
        if ((long)*(int *)(_pGlobalNowZone + 0x25138) == (long)*(short *)(MarketTbl + iVar1 * 4)) {
          uVar2 = *(undefined2 *)(MarketTbl + iVar1 * 4 + 2);
          goto LAB_004af628;
        }
      }
      uVar2 = 0;
LAB_004af628:
      FFWCaSetAuctionMarket(pFVar3,uVar2);
    }
    pFVar3 = (FFWCaAuctionQInfo *)&_g_pYkWndAuctionItem->field_0x22c;
    FFWCaSetAuctionCategory(pFVar3,(&DAT_0054d607)[param_2]);
    FFWCaSetItemQuerySort(pFVar3,9);
    YkWndAuctionItem::Open(_g_pYkWndAuctionItem,0,'\0');
  }
  return;
}



// ---------------------------------------------------------------------------
// OnOK
// YkWndAuctionMenuDish::OnOK(short)
//   symbol: OnOK__20YkWndAuctionMenuDishFs
//   rva:    0x003af6e0  size: 408 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndAuction.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void YkWndAuctionMenuDish::OnOK(undefined8 idx,short param_2)

{
  int iVar1;
  undefined2 uVar2;
  FFWCaAuctionQInfo *pFVar3;
  
  if (_pGlobalNowZone != 0) {
    pFVar3 = (FFWCaAuctionQInfo *)&_g_pYkWndAuctionItem->field_0x22c;
    YkWndSearchList::InitAucInfo((YkWndSearchList *)_g_pYkWndAuctionItem);
    for (iVar1 = 0; *(short *)(MarketTbl + iVar1 * 4) != 0; iVar1 = iVar1 + 1) {
      if ((long)*(int *)(_pGlobalNowZone + 0x25138) == (long)*(short *)(MarketTbl + iVar1 * 4)) {
        uVar2 = *(undefined2 *)(MarketTbl + iVar1 * 4 + 2);
        goto LAB_004af7c8;
      }
    }
    uVar2 = 0;
LAB_004af7c8:
    FFWCaSetAuctionMarket(pFVar3,uVar2);
  }
  pFVar3 = (FFWCaAuctionQInfo *)&_g_pYkWndAuctionItem->field_0x22c;
  FFWCaSetAuctionCategory(pFVar3,(&DAT_0054d60f)[param_2]);
  FFWCaSetItemQuerySort(pFVar3,9,0);
  YkWndAuctionItem::Open(_g_pYkWndAuctionItem,0,'\0');
  return;
}



// ---------------------------------------------------------------------------
// OnOK
// YkWndAuctionMenuEtc::OnOK(short)
//   symbol: OnOK__19YkWndAuctionMenuEtcFs
//   rva:    0x003af880  size: 388 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndAuction.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void YkWndAuctionMenuEtc::OnOK(undefined8 idx,short param_2)

{
  int iVar1;
  undefined2 uVar2;
  FFWCaAuctionQInfo *pFVar3;
  
  if (_pGlobalNowZone != 0) {
    pFVar3 = (FFWCaAuctionQInfo *)&_g_pYkWndAuctionItem->field_0x22c;
    YkWndSearchList::InitAucInfo((YkWndSearchList *)_g_pYkWndAuctionItem);
    for (iVar1 = 0; *(short *)(MarketTbl + iVar1 * 4) != 0; iVar1 = iVar1 + 1) {
      if ((long)*(int *)(_pGlobalNowZone + 0x25138) == (long)*(short *)(MarketTbl + iVar1 * 4)) {
        uVar2 = *(undefined2 *)(MarketTbl + iVar1 * 4 + 2);
        goto LAB_004af968;
      }
    }
    uVar2 = 0;
LAB_004af968:
    FFWCaSetAuctionMarket(pFVar3,uVar2);
  }
  FFWCaSetAuctionCategory
            ((FFWCaAuctionQInfo *)&_g_pYkWndAuctionItem->field_0x22c,(&DAT_0054d617)[param_2]);
  YkWndAuctionItem::Open(_g_pYkWndAuctionItem,0,'\0');
  return;
}



// ---------------------------------------------------------------------------
// OnOK
// YkWndAuctionWepSort::OnOK(short)
//   symbol: OnOK__19YkWndAuctionWepSortFs
//   rva:    0x003afa10  size: 516 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndAuction.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void YkWndAuctionWepSort::OnOK(int this,short param_2)

{
  undefined1 *puVar1;
  
  puVar1 = &_g_pYkWndAuctionItem->field_0x22c;
  if (param_2 == 6) {
    if (*(int *)(&ActerBuffPtr + (uint)*(ushort *)(_pGlobalNowZone + 0x29292) * 4) == 0) {
      YmSePlayBeep__Fv();
      return;
    }
    FFWCaSetItemQueryValueWithSort
              (puVar1,3,*(undefined1 *)
                         (*(int *)(&ActerBuffPtr + (uint)*(ushort *)(_pGlobalNowZone + 0x29292) * 4)
                         + 0xc3),0,0);
  }
  else if (param_2 == 5) {
    if (cRam005c944c == '\0') {
      YmSePlayBeep__Fv();
      return;
    }
    FFWCaSetItemQueryValueWithSort(puVar1,4,uRam005c9308,0,0);
  }
  else if (param_2 == 4) {
    FFWCaSetItemQuerySort(puVar1,2,0xffffffffffffffff);
  }
  else if (param_2 == 3) {
    FFWCaSetItemQuerySort(puVar1,6);
  }
  else if (param_2 == 2) {
    FFWCaSetItemQuerySort(puVar1,5,0xffffffffffffffff);
  }
  YkWndAuctionItem::Open(_g_pYkWndAuctionItem,0,'\0');
  CTkMenuMng::DestroyDrawMenu((CTkMenuMng *)&g_TkMenuMng,_2403);
  CTkMenuMng::DestroyDrawMenu
            ((CTkMenuMng *)&g_TkMenuMng,*(CTkMenuCtrlData **)(this + 8),'\x01');
  return;
}



// ---------------------------------------------------------------------------
// OnOK
// YkWndAuctionArmSort::OnOK(short)
//   symbol: OnOK__19YkWndAuctionArmSortFs
//   rva:    0x003afc20  size: 516 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndAuction.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void YkWndAuctionArmSort::OnOK(int this,short param_2)

{
  undefined1 *puVar1;
  
  puVar1 = &_g_pYkWndAuctionItem->field_0x22c;
  if (param_2 == 6) {
    if (*(int *)(&ActerBuffPtr + (uint)*(ushort *)(_pGlobalNowZone + 0x29292) * 4) == 0) {
      YmSePlayBeep__Fv();
      return;
    }
    FFWCaSetItemQueryValueWithSort
              (puVar1,3,*(undefined1 *)
                         (*(int *)(&ActerBuffPtr + (uint)*(ushort *)(_pGlobalNowZone + 0x29292) * 4)
                         + 0xc3),0,0);
  }
  else if (param_2 == 5) {
    if (cRam005c944c == '\0') {
      YmSePlayBeep__Fv();
      return;
    }
    FFWCaSetItemQueryValueWithSort(puVar1,4,uRam005c9308,0,0);
  }
  else if (param_2 == 4) {
    FFWCaSetItemQuerySort(puVar1,2,0xffffffffffffffff);
  }
  else if (param_2 == 3) {
    FFWCaSetItemQuerySort(puVar1,8,0xffffffffffffffff);
  }
  else if (param_2 == 2) {
    FFWCaSetItemQuerySort(puVar1,7,0xffffffffffffffff);
  }
  YkWndAuctionItem::Open(_g_pYkWndAuctionItem,0,'\0');
  CTkMenuMng::DestroyDrawMenu((CTkMenuMng *)&g_TkMenuMng,_2404);
  CTkMenuMng::DestroyDrawMenu
            ((CTkMenuMng *)&g_TkMenuMng,*(CTkMenuCtrlData **)(this + 8),'\x01');
  return;
}



// ---------------------------------------------------------------------------
// IsChase
// YkWndItemCtrlAuction::IsChase(void)
//   symbol: IsChase__20YkWndItemCtrlAuctionFv
//   rva:    0x003afe30  size: 20 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndAuction.cpp
// ---------------------------------------------------------------------------


/* WARNING: Unknown calling convention -- yet parameter storage is locked */

undefined4 YkWndItemCtrlAuction::IsChase(YkWndItemCtrlAuction *this)

{
  return 1;
}

