// AUTOGENERATED by ffxi-decomp. Do not edit by hand.
// version: 972 (sha256=d4622c1cc4a3012c, image_base=0x00100000)
// source:  main/yk/ykWndMessage.cpp
// functions: 36


// ---------------------------------------------------------------------------
// ykGetMessageTypeID
// ykGetMessageTypeID(int)
//   symbol: ykGetMessageTypeID__Fi
//   rva:    0x00395080  size: 176 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndMessage.cpp
// ---------------------------------------------------------------------------


undefined4 ykGetMessageTypeID__Fi(int type)

{
  undefined4 uVar1;
  
  if (type == 0x1e) {
    uVar1 = 6;
  }
  else if (type == 3) {
    uVar1 = 4;
  }
  else if (type == 10) {
    uVar1 = 3;
  }
  else if (type == 9) {
    uVar1 = 2;
  }
  else if (type == 1) {
    uVar1 = 1;
  }
  else if (type == 0) {
    uVar1 = 0;
  }
  else {
    uVar1 = 5;
  }
  return uVar1;
}



// ---------------------------------------------------------------------------
// YkSendCheckCallBack
// YkSendCheckCallBack(void *, unsigned short, FFPolMsg_STATUS, unsigned char *)
//   symbol: YkSendCheckCallBack__FPvUs15FFPolMsg_STATUSPUc
//   rva:    0x00395130  size: 196 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndMessage.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined4
YkSendCheckCallBack__FPvUs15FFPolMsg_STATUSPUc(int user,undefined8 status,int param_3)

{
  char *__format;
  char acStack_60 [32];
  int iStack_40;
  int iStack_20;
  
  g_busy = 0;
  iStack_40 = user;
  iStack_20 = param_3;
  if (param_3 == 1) {
    if (_g_pTkHelp != 0) {
      KaHelpMes::ResetLoadMes((KaHelpMes *)(_g_pTkHelp + 0x20),0x10);
    }
  }
  else if (param_3 == 0) {
    CTkMsgWinData::AddMsg(_g_pMsgWinData,user);
  }
  else {
    __format = (char *)XiStrGet(10,0x2d);
    sprintf(acStack_60,__format,iStack_20);
    CTkMsgWinData::AddErrorString(_g_pMsgWinData,acStack_60);
  }
  return 1;
}



// ---------------------------------------------------------------------------
// YkRecvCheckCallBack
// YkRecvCheckCallBack(void *, unsigned short, FFPolMsg_STATUS, unsigned short, const FFPolMsg_MsgStruct *)
//   symbol: YkRecvCheckCallBack__FPvUs15FFPolMsg_STATUSUsPC18FFPolMsg_MsgStruct
//   rva:    0x00395200  size: 148 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndMessage.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined4
YkRecvCheckCallBack__FPvUs15FFPolMsg_STATUSUsPC18FFPolMsg_MsgStruct
          (int user,undefined8 status,int param_3)

{
  g_busy = 0;
  if ((param_3 == 0) &&
     (CTkMsgWinData::AddMsg(_g_pMsgWinData,user), _g_pYkWndMessageList != 0)) {
    *(undefined1 *)(_g_pYkWndMessageList + 0x5c) = 1;
  }
  if (_g_pTkHelp != 0) {
    KaHelpMes::ResetLoadMes((KaHelpMes *)(_g_pTkHelp + 0x20),0x10);
  }
  return 1;
}



// ---------------------------------------------------------------------------
// YkReplyCheckCallBack
// YkReplyCheckCallBack(void *, unsigned short, FFPolMsg_STATUS, unsigned char *)
//   symbol: YkReplyCheckCallBack__FPvUs15FFPolMsg_STATUSPUc
//   rva:    0x003952a0  size: 208 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndMessage.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined4
YkReplyCheckCallBack__FPvUs15FFPolMsg_STATUSPUc(int user,undefined8 status,int param_3)

{
  char acStack_60 [32];
  int iStack_40;
  int iStack_20;
  
  g_busy = 0;
  iStack_40 = user;
  iStack_20 = param_3;
  if (param_3 != 1) {
    if (param_3 != 0) {
      sprintf(acStack_60,_2081,param_3);
      CTkMsgWinData::AddErrorString(_g_pMsgWinData,acStack_60);
      return 1;
    }
    CTkMsgWinData::AddMsg(_g_pMsgWinData,user);
    if (_g_pYkWndMessageList != 0) {
      *(undefined1 *)(_g_pYkWndMessageList + 0x5c) = 1;
    }
  }
  if (_g_pTkHelp != 0) {
    KaHelpMes::ResetLoadMes((KaHelpMes *)(_g_pTkHelp + 0x20),0x10);
  }
  return 1;
}



// ---------------------------------------------------------------------------
// YkFriendCheckCallBack
// YkFriendCheckCallBack(void *, unsigned short, FFPolMsg_STATUS, unsigned char *)
//   symbol: YkFriendCheckCallBack__FPvUs15FFPolMsg_STATUSPUc
//   rva:    0x00395370  size: 264 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndMessage.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined4
YkFriendCheckCallBack__FPvUs15FFPolMsg_STATUSPUc(undefined4 user,undefined8 status,int param_3)

{
  char acStack_60 [32];
  undefined4 uStack_40;
  int iStack_20;
  
  g_busy = 0;
  uStack_40 = user;
  iStack_20 = param_3;
  if (param_3 == 1) {
    if (_g_pTkHelp != 0) {
      KaHelpMes::ResetLoadMes((KaHelpMes *)(_g_pTkHelp + 0x20),0x10);
    }
  }
  else if (param_3 == 10) {
    YkWndMessage::SendFriend(_g_pYkWndMessage);
  }
  else if (param_3 == 0) {
    if ((char)user == '\0') {
      YkWndMessage::SendNormal(_g_pYkWndMessage);
    }
    else {
      CTkMsgWinData::AddErr(_g_pMsgWinData,0xa0);
    }
  }
  else {
    sprintf(acStack_60,_2098,param_3);
    CTkMsgWinData::AddErrorString(_g_pMsgWinData,acStack_60);
  }
  return 1;
}



// ---------------------------------------------------------------------------
// EditCallBack
// YkWndMessage::EditCallBack(FS_TEXTINPUT, char *, void *)
//   symbol: EditCallBack__12YkWndMessageF12FS_TEXTINPUTPcPv
//   rva:    0x00395480  size: 108 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndMessage.cpp
// ---------------------------------------------------------------------------


void YkWndMessage::EditCallBack(int this,undefined8 user,int param_3)

{
  if (this == 0) {
    (**(code **)(*(int *)(param_3 + 4) + 0x20))(param_3,0x11);
  }
  else {
    (**(code **)(*(int *)(param_3 + 4) + 0x20))(param_3,6);
  }
  return;
}



// ---------------------------------------------------------------------------
// 
// YkWndMessage::YkWndMessage(void)
//   symbol: __ct__12YkWndMessageFv
//   rva:    0x003954f0  size: 644 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndMessage.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

YkWndMessage * YkWndMessage::YkWndMessage(YkWndMessage *this)

{
  int iVar1;
  long lVar2;
  CTkObject *pCVar3;
  
  CTkObject::CTkObject((CTkObject *)this);
  *(undefined1 **)&this->field_0x4 = __vt__16CTkMenuPrimitive;
  *(undefined2 *)&this->field_0xe = 0xffff;
  *(undefined4 *)&this->field_0x8 = 0;
  (**(code **)(*(int *)&this->field_0x4 + 0xc))();
  this->field_0xc = 1;
  *(undefined1 **)&this->field_0x4 = __vt__12YkWndMessage;
  this->m_edit = (XiTextInputContext *)0x0;
  this->m_message = '\0';
  this->m_png = (char *)0x0;
  this->m_pngsize = 0;
  this->m_face = -1;
  this->m_time = 0;
  iVar1 = _g_pYkWndMessageList;
  if (_g_pYkWndMessageList == 0) {
    lVar2 = __nw__FUi(0x70);
    iVar1 = 0;
    if (lVar2 != 0) {
      iVar1 = YkWndMessageList::YkWndMessageList((YkWndMessageList *)lVar2);
    }
  }
  _g_pYkWndMessageList = iVar1;
  pCVar3 = _g_pYkWndMessageReply1;
  if (_g_pYkWndMessageReply1 == (CTkObject *)0x0) {
    lVar2 = __nw__FUi(0x68);
    pCVar3 = (CTkObject *)lVar2;
    if (lVar2 != 0) {
      CTkObject::CTkObject(pCVar3);
      pCVar3[1] = (CTkObject)__vt__16CTkMenuPrimitive;
      *(undefined2 *)&pCVar3[3].m_RecSub1 = 0xffff;
      pCVar3[2].m_RecKind = (short)0x0;
      pCVar3[2].field_0x1 = 0;
      pCVar3[2].m_RecSub1 = (short)0x0;
      pCVar3[2].field_0x3 = 0;
      (**(code **)((int)pCVar3[1] + 0xc))();
      pCVar3[3].m_RecKind = (short)0x1;
      pCVar3[1] = (CTkObject)__vt__17YkWndMessageReply;
      pCVar3[1] = (CTkObject)__vt__18YkWndMessageReply1;
    }
  }
  _g_pYkWndMessageReply1 = pCVar3;
  pCVar3 = _g_pYkWndMessageReply2;
  if (_g_pYkWndMessageReply2 == (CTkObject *)0x0) {
    lVar2 = __nw__FUi(0x68);
    pCVar3 = (CTkObject *)lVar2;
    if (lVar2 != 0) {
      CTkObject::CTkObject(pCVar3);
      pCVar3[1] = (CTkObject)__vt__16CTkMenuPrimitive;
      *(undefined2 *)&pCVar3[3].m_RecSub1 = 0xffff;
      pCVar3[2].m_RecKind = (short)0x0;
      pCVar3[2].field_0x1 = 0;
      pCVar3[2].m_RecSub1 = (short)0x0;
      pCVar3[2].field_0x3 = 0;
      (**(code **)((int)pCVar3[1] + 0xc))();
      pCVar3[3].m_RecKind = (short)0x1;
      pCVar3[1] = (CTkObject)__vt__17YkWndMessageReply;
      pCVar3[1] = (CTkObject)__vt__18YkWndMessageReply2;
    }
  }
  _g_pYkWndMessageReply2 = pCVar3;
  return this;
}



// ---------------------------------------------------------------------------
// 
// YkWndMessage::~YkWndMessage(void)
//   symbol: __dt__12YkWndMessageFv
//   rva:    0x00395810  size: 528 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndMessage.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

YkWndMessage * YkWndMessage::~YkWndMessage(YkWndMessage *this)

{
  XiTextInputContext *pXVar1;
  short in_a1_lo;
  
  if (this != (YkWndMessage *)0x0) {
    *(undefined1 **)&this->field_0x4 = __vt__12YkWndMessage;
    if (this->m_edit != (XiTextInputContext *)0x0) {
      if (this->m_edit != (XiTextInputContext *)0x0) {
        pXVar1 = this->m_edit;
        if (pXVar1 != (XiTextInputContext *)0x0) {
          (**(code **)(*(int *)pXVar1 + 0x20))(pXVar1,1);
        }
        this->m_edit = (XiTextInputContext *)0x0;
      }
      XiTextInputManager::textInputManagerOn
                (_g_xiTextInputManager,(XiTextInputContext *)0x0);
      if (*(int *)&this->field_0x8 != 0) {
        *(undefined1 *)(*(int *)&this->field_0x8 + 0x62) = 1;
      }
    }
    if (_g_pYkWndMessageList != 0) {
      if (_g_pYkWndMessageList != 0) {
        (**(code **)(*(int *)(_g_pYkWndMessageList + 4) + 8))(_g_pYkWndMessageList,1);
      }
      _g_pYkWndMessageList = 0;
    }
    if (_g_pYkWndMessageReply1 != 0) {
      if (_g_pYkWndMessageReply1 != 0) {
        (**(code **)(*(int *)(_g_pYkWndMessageReply1 + 4) + 8))(_g_pYkWndMessageReply1,1);
      }
      _g_pYkWndMessageReply1 = 0;
    }
    if (_g_pYkWndMessageReply2 != 0) {
      if (_g_pYkWndMessageReply2 != 0) {
        (**(code **)(*(int *)(_g_pYkWndMessageReply2 + 4) + 8))(_g_pYkWndMessageReply2,1);
      }
      _g_pYkWndMessageReply2 = 0;
    }
    if (this->m_png != (char *)0x0) {
      __dla__FPv(this->m_png);
      this->m_png = (char *)0x0;
    }
    if (this != (YkWndMessage *)0x0) {
      *(undefined1 **)&this->field_0x4 = __vt__16CTkMenuPrimitive;
      CTkObject::~CTkObject((CTkObject *)this);
    }
    if (0 < in_a1_lo) {
      __dl__FPv(this);
    }
  }
  return this;
}



// ---------------------------------------------------------------------------
// OnInitialUpdatePrimitive
// YkWndMessage::OnInitialUpdatePrimitive(void)
//   symbol: OnInitialUpdatePrimitive__12YkWndMessageFv
//   rva:    0x00395b80  size: 448 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndMessage.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void YkWndMessage::OnInitialUpdatePrimitive(YkWndMessage *this)

{
  XiTextInputContext *pXVar1;
  long lVar2;
  short sStack_18;
  short sStack_16;
  YkWndMessage *pYStack_10;
  
  pYStack_10 = this;
  CTkMenuCtrlData::GetWindowLocate
            (*(CTkMenuCtrlData **)&this->field_0x8,(TKRECT *)&sStack_18);
  *(short *)&pYStack_10->m_x = sStack_18 + 2;
  *(short *)&pYStack_10->m_y = sStack_16 + 2;
  if ((*(short *)&pYStack_10->m_mode == 2) || (*(short *)&pYStack_10->m_mode == 7)) {
    if (pYStack_10->m_edit == (XiTextInputContext *)0x0) {
      lVar2 = __nw__FUi(0x6b4);
      pXVar1 = (XiTextInputContext *)0x0;
      if (lVar2 != 0) {
        pXVar1 = (XiTextInputContext *)
                 XiTextInputContext::XiTextInputContext
                           (lVar2,6,0xf,pYStack_10,0x495480,&(pYStack_10->m_info).name,0x14a,0xf);
      }
      pYStack_10->m_edit = pXVar1;
    }
  }
  else if (pYStack_10->m_edit == (XiTextInputContext *)0x0) {
    lVar2 = __nw__FUi(0x6b4);
    pXVar1 = (XiTextInputContext *)0x0;
    if (lVar2 != 0) {
      pXVar1 = (XiTextInputContext *)
               XiTextInputContext::XiTextInputContext
                         (lVar2,7,300,pYStack_10,0x495480,0x53ea88,0x14a,0xf);
    }
    pYStack_10->m_edit = pXVar1;
  }
  XiTextInputManager::textInputManagerOff(_g_xiTextInputManager);
  XiTextInputManager::textInputManagerOn
            (_g_xiTextInputManager,(XiTextInputContext *)pYStack_10->m_edit);
  *(undefined1 *)(*(int *)&pYStack_10->field_0x8 + 0x62) = 0;
  *(undefined1 *)(_g_pDrawMessageWindow + 0x2c) = 1;
  return;
}



// ---------------------------------------------------------------------------
// OnDestroyPrimitive
// YkWndMessage::OnDestroyPrimitive(void)
//   symbol: OnDestroyPrimitive__12YkWndMessageFv
//   rva:    0x00395d40  size: 208 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndMessage.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void YkWndMessage::OnDestroyPrimitive(YkWndMessage *this)

{
  XiTextInputContext *pXVar1;
  
  if (this->m_edit != (XiTextInputContext *)0x0) {
    if (this->m_edit != (XiTextInputContext *)0x0) {
      pXVar1 = this->m_edit;
      if (pXVar1 != (XiTextInputContext *)0x0) {
        (**(code **)(*(int *)pXVar1 + 0x20))(pXVar1,1);
      }
      this->m_edit = (XiTextInputContext *)0x0;
    }
    XiTextInputManager::textInputManagerOn
              (_g_xiTextInputManager,(XiTextInputContext *)0x0);
    if (*(int *)&this->field_0x8 != 0) {
      *(undefined1 *)(*(int *)&this->field_0x8 + 0x62) = 1;
    }
  }
  this->m_message = '\0';
  *(undefined1 *)(_g_pDrawMessageWindow + 0x2c) = 0;
  return;
}



// ---------------------------------------------------------------------------
// OnDrawPrimitive
// YkWndMessage::OnDrawPrimitive(void)
//   symbol: OnDrawPrimitive__12YkWndMessageFv
//   rva:    0x00395e10  size: 444 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndMessage.cpp
// ---------------------------------------------------------------------------


/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void YkWndMessage::OnDrawPrimitive(YkWndMessage *this)

{
  char *pcVar1;
  int iVar2;
  undefined8 uVar3;
  long lVar4;
  short sVar5;
  
  if (this->m_edit != (XiTextInputContext *)0x0) {
    sVar5 = *(short *)&this->m_x;
    if ((*(short *)&this->m_mode == 2) || (*(short *)&this->m_mode == 7)) {
      uVar3 = XiStrGet(9,0x22);
      mojishadow__FiiPCcUi(sVar5,*(undefined2 *)&this->m_y,uVar3,0xffffffff80a06040);
      sVar5 = sVar5 + 0x78;
    }
    lVar4 = CTkMenuMng::IsDrawWindow((CTkMenuMng *)&g_TkMenuMng,_2330);
    if (lVar4 == 0) {
      pcVar1 = (char *)XiTextInputContext::getDisplayString(this->m_edit);
      iVar2 = XiTextInputContext::getDisplayStringLen(this->m_edit);
      XiTextInputContext::displayText
                (this->m_edit,pcVar1,iVar2,(int)sVar5,(int)*(short *)&this->m_y,0x14a,'\x01');
    }
    else {
      pcVar1 = (char *)XiTextInputContext::getDisplayString(this->m_edit);
      iVar2 = XiTextInputContext::getDisplayStringLen(this->m_edit);
      XiTextInputContext::displayText
                (this->m_edit,pcVar1,iVar2,(int)sVar5,(int)*(short *)&this->m_y,0x10e,'\x01');
    }
    XiTextInputContext::unlockEnterKey(this->m_edit);
  }
  return;
}



// ---------------------------------------------------------------------------
// OnKeyDown
// YkWndMessage::OnKeyDown(short, short)
//   symbol: OnKeyDown__12YkWndMessageFss
//   rva:    0x00395fd0  size: 2072 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndMessage.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void YkWndMessage::OnKeyDown(int this,short param_2)

{
  undefined2 uVar1;
  int *piVar2;
  char *pcVar3;
  undefined4 uVar4;
  int iVar5;
  size_t sVar6;
  long lVar7;
  undefined8 uVar8;
  long unaff_s1;
  char acStack_1b0 [64];
  undefined1 auStack_170 [128];
  undefined1 auStack_f0 [132];
  undefined4 uStack_6c;
  int iStack_68;
  int iStack_60;
  int iStack_5c;
  uint uStack_58;
  uint uStack_54;
  uint uStack_50;
  uint uStack_4c;
  uint uStack_48;
  uint uStack_44;
  uint uStack_40;
  uint uStack_3c;
  uint uStack_38;
  uint uStack_34;
  int iStack_30;
  short sStack_20;
  
  iStack_30 = this;
  sStack_20 = param_2;
  if (param_2 == 8) {
    XiTextInputManager::doKeydown(_g_xiTextInputManager,3);
  }
  else if (param_2 == 3) {
    XiTextInputManager::doKeydown(_g_xiTextInputManager,5);
  }
  else if (param_2 == 4) {
    XiTextInputManager::doKeydown(_g_xiTextInputManager,4);
  }
  else if (param_2 == 6) {
    if (*(int *)(this + 0x1c) != 0) {
      piVar2 = *(int **)(this + 0x1c);
      if (piVar2 != (int *)0x0) {
        (**(code **)(*piVar2 + 0x20))(piVar2,1);
      }
      *(undefined4 *)(iStack_30 + 0x1c) = 0;
    }
    XiTextInputManager::textInputManagerOn
              (_g_xiTextInputManager,(XiTextInputContext *)0x0);
    if (*(int *)(iStack_30 + 8) != 0) {
      iStack_5c = *(int *)(iStack_30 + 8);
      *(undefined1 *)(iStack_5c + 0x62) = 1;
    }
    CTkMenuMng::DestroyDrawMenu((CTkMenuMng *)&g_TkMenuMng,_2410);
  }
  else if (param_2 == 5) {
    XiTextInputManager::doKeydown(_g_xiTextInputManager,1);
  }
  else if (param_2 == 0x11) {
    pcVar3 = (char *)XiTextInputContext::getString(*(XiTextInputContext **)(this + 0x1c),'\x01')
    ;
    strncpy((char *)(iStack_30 + 0x53),pcVar3,300);
    *(undefined1 *)(iStack_30 + 0x17e) = 0;
    sVar6 = strlen((char *)(iStack_30 + 0x53));
    uStack_6c = (undefined4)sVar6;
    if (*(int *)(iStack_30 + 0x1c) != 0) {
      piVar2 = *(int **)(iStack_30 + 0x1c);
      if (piVar2 != (int *)0x0) {
        (**(code **)(*piVar2 + 0x20))(piVar2,1);
      }
      *(undefined4 *)(iStack_30 + 0x1c) = 0;
    }
    XiTextInputManager::textInputManagerOn
              (_g_xiTextInputManager,(XiTextInputContext *)0x0);
    if (*(int *)(iStack_30 + 8) != 0) {
      iStack_60 = *(int *)(iStack_30 + 8);
      *(undefined1 *)(iStack_60 + 0x62) = 1;
    }
    lVar7 = NT_SYS::getPOLCON((NT_SYS *)g_pNtSys);
    if (((lVar7 == 0) || (sVar6 = strlen((char *)(iStack_30 + 0x53)), sVar6 == 0)) ||
       (_pGlobalNowZone == 0)) {
      CTkMenuMng::DestroyDrawMenu((CTkMenuMng *)&g_TkMenuMng,_2410);
    }
    else {
      switch(*(undefined2 *)(iStack_30 + 0x14)) {
      case 0:
        uStack_58 = *(uint *)(g_pNtSys + 0x80);
        uStack_54 = uStack_58;
        uVar4 = NT_SYS::getWorld((NT_SYS *)g_pNtSys,uStack_58);
        uVar1 = *(undefined2 *)(iStack_30 + 0x1a8);
        uVar8 = XiStrGet(9,0x1c);
        unaff_s1 = gcPMsgSendMessageToFriend
                             (*(undefined4 *)(iStack_30 + 0x1ac),(int)CONCAT42(uVar4,uVar1),
                              iStack_30 + 0x188,uVar8,iStack_30 + 0x53,0x495130,0x11);
        break;
      case 1:
        uVar8 = XiStrGet(9,0x1c);
        unaff_s1 = gcPMsgSendMessageToPolUser2
                             (*(undefined8 *)(iStack_30 + 0x1b8),*(undefined4 *)(iStack_30 + 0x1c0),
                              uVar8,iStack_30 + 0x53,0x495130,0x11);
        break;
      case 2:
        for (pcVar3 = (char *)(iStack_30 + 0x53); *pcVar3 != '\0'; pcVar3 = pcVar3 + 1) {
          if (*pcVar3 == '\a') {
            *pcVar3 = '\0';
          }
        }
        sqPlayOnlineMessageGetMessageFixedFormString(1,auStack_170,0x7f);
        uStack_50 = *(uint *)(g_pNtSys + 0x80);
        uStack_4c = uStack_50;
        uVar4 = NT_SYS::getWorld((NT_SYS *)g_pNtSys,uStack_50);
        unaff_s1 = gcPMsgSendFriendRequest
                             (*(undefined4 *)(iStack_30 + 0x1ac),
                              (int)CONCAT42(uVar4,*(undefined2 *)(iStack_30 + 0x1a8)),
                              iStack_30 + 0x53,auStack_170,iStack_30 + 0x188,0x495130,0x14);
        break;
      case 3:
        uStack_48 = *(uint *)(g_pNtSys + 0x80);
        uStack_44 = uStack_48;
        iVar5 = NT_SYS::getWorld((NT_SYS *)g_pNtSys,uStack_48);
        lVar7 = NT_SYS::getWorldNameForKita((NT_SYS *)g_pNtSys,iVar5);
        if (lVar7 == 0) {
          sprintf(acStack_1b0,(char *)&_2412,_pGlobalNowZone + 0x25184);
        }
        else {
          sprintf(acStack_1b0,_2411,_pGlobalNowZone + 0x25184,lVar7);
        }
        uStack_40 = *(uint *)(g_pNtSys + 0x80);
        uStack_3c = uStack_40;
        uVar4 = NT_SYS::getWorld((NT_SYS *)g_pNtSys,uStack_40);
        unaff_s1 = gcPMsgSendKnockMessage
                             (*(undefined4 *)(iStack_30 + 0x1ac),
                              (int)CONCAT42(uVar4,*(undefined2 *)(iStack_30 + 0x1a8)),0,acStack_1b0,
                              iStack_30 + 0x53,*(undefined4 *)(iStack_30 + 0x1f0),
                              *(undefined4 *)(iStack_30 + 500),0x495130);
        break;
      case 4:
        uStack_38 = *(uint *)(g_pNtSys + 0x80);
        uStack_34 = uStack_38;
        iVar5 = NT_SYS::getWorld((NT_SYS *)g_pNtSys,uStack_38);
        lVar7 = NT_SYS::getWorldNameForKita((NT_SYS *)g_pNtSys,iVar5);
        if (lVar7 == 0) {
          sprintf(acStack_1b0,(char *)&_2412,_pGlobalNowZone + 0x25184);
        }
        else {
          sprintf(acStack_1b0,_2411,_pGlobalNowZone + 0x25184,lVar7);
        }
        unaff_s1 = gcPMsgSendKnockMessage2
                             (*(undefined8 *)(iStack_30 + 0x1b8),*(undefined4 *)(iStack_30 + 0x1c0),
                              acStack_1b0,iStack_30 + 0x53,*(undefined4 *)(iStack_30 + 0x1f0),
                              *(undefined4 *)(iStack_30 + 500),0x495130,0x13);
        break;
      case 5:
        uVar8 = XiStrGet(9,0x1f);
        unaff_s1 = gcPMsgReplyMessage2(*(undefined8 *)(iStack_30 + 0x1c8),
                                       *(undefined8 *)(iStack_30 + 0x1b8),uVar8,iStack_30 + 0x53,
                                       0x4952a0,0x12);
        break;
      case 7:
        sqPlayOnlineMessageGetMessageFixedFormString(1,auStack_170,0x7f);
        sqPlayOnlineMessageGetMessageFixedFormString(9,auStack_f0,0x7f);
        unaff_s1 = gcPMsgReplyFriendAcceptAndRequest4
                             (*(undefined8 *)(iStack_30 + 0x1c8),*(undefined8 *)(iStack_30 + 0x1b8),
                              iStack_30 + 0x53,auStack_f0,auStack_170,0x4952a0,0x17);
      }
      if (unaff_s1 == 0) {
        if (_g_pTkHelp != 0) {
          iStack_68 = _g_pTkHelp;
          KaHelpMes::SetLoadMes((KaHelpMes *)(_g_pTkHelp + 0x20),0x10);
        }
        g_busy = 1;
      }
      CTkMenuMng::DestroyDrawMenu((CTkMenuMng *)&g_TkMenuMng,_2410);
    }
  }
  return;
}



// ---------------------------------------------------------------------------
// SendNormal
// YkWndMessage::SendNormal(void)
//   symbol: SendNormal__12YkWndMessageFv
//   rva:    0x003967f0  size: 124 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndMessage.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void YkWndMessage::SendNormal(YkWndMessage *this)

{
  long lVar1;
  
  if (g_busy == '\0') {
    lVar1 = NT_SYS::getPOLCON((NT_SYS *)g_pNtSys);
    if (lVar1 != 0) {
      *(undefined2 *)&this->m_mode = 0;
      CTkMenuMng::CreateDrawMenu((CTkMenuMng *)&g_TkMenuMng,_2410,'\x01','\0');
    }
  }
  else {
    CTkMsgWinData::AddErr(_g_pMsgWinData,0x79);
  }
  return;
}



// ---------------------------------------------------------------------------
// SendFriend
// YkWndMessage::SendFriend(void)
//   symbol: SendFriend__12YkWndMessageFv
//   rva:    0x00396870  size: 128 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndMessage.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void YkWndMessage::SendFriend(YkWndMessage *this)

{
  long lVar1;
  
  if (g_busy == '\0') {
    lVar1 = NT_SYS::getPOLCON((NT_SYS *)g_pNtSys);
    if (lVar1 != 0) {
      *(undefined2 *)&this->m_mode = 2;
      CTkMenuMng::CreateDrawMenu((CTkMenuMng *)&g_TkMenuMng,_2410,'\x01','\0');
    }
  }
  else {
    CTkMsgWinData::AddErr(_g_pMsgWinData,0x79);
  }
  return;
}



// ---------------------------------------------------------------------------
// Send
// YkWndMessage::Send(FFWCaReplyInfo *, char)
//   symbol: Send__12YkWndMessageFP14FFWCaReplyInfoc
//   rva:    0x003968f0  size: 520 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndMessage.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void YkWndMessage::Send(YkWndMessage *this,FFWCaReplyInfo *info,char unknownonly)

{
  FFWCaReplyInfo FVar1;
  FFWCaReplyInfo FVar2;
  undefined2 uVar3;
  undefined4 uVar4;
  long lVar5;
  int iVar6;
  FFWCaReplyInfo *pFVar7;
  FFWCaReplyInfo *pFVar8;
  
  if (g_busy == '\0') {
    lVar5 = NT_SYS::getPOLCON((NT_SYS *)g_pNtSys);
    if (lVar5 != 0) {
      (this->m_info).defs = *(uint *)info;
      pFVar8 = info + 4;
      pFVar7 = (FFWCaReplyInfo *)&(this->m_info).name;
      iVar6 = 8;
      do {
        FVar1 = *pFVar8;
        FVar2 = pFVar8[1];
        pFVar8 = pFVar8 + 2;
        iVar6 = iVar6 + -1;
        *pFVar7 = FVar1;
        pFVar7[1] = FVar2;
        pFVar7 = pFVar7 + 2;
      } while (0 < iVar6);
      (this->m_info).zone = *(ushort *)(info + 0x14);
      (this->m_info).home = *(ushort *)(info + 0x16);
      uVar3 = *(undefined2 *)(info + 0x1a);
      (this->m_info).job = *(ushort *)(info + 0x18);
      *(undefined2 *)&(this->m_info).field_0x1a = uVar3;
      uVar3 = *(undefined2 *)(info + 0x1e);
      (this->m_info).level = *(ushort *)(info + 0x1c);
      *(undefined2 *)&(this->m_info).field_0x1e = uVar3;
      (this->m_info).race = *(ushort *)(info + 0x20);
      (this->m_info).status = *(ushort *)(info + 0x22);
      (this->m_info).id = *(ushort *)(info + 0x24);
      (this->m_info).comlinkFlag = (byte)info[0x26];
      (this->m_info).rank = (byte)info[0x27];
      (this->m_info).globalID = *(uint *)(info + 0x28);
      (this->m_info).msgType = *(uint *)(info + 0x2c);
      uVar4 = NT_SYS::getWorld((NT_SYS *)g_pNtSys,*(uint *)(g_pNtSys + 0x80));
      lVar5 = gcPMsgFriendCheck2(*(undefined4 *)(info + 0x28),
                                 (int)CONCAT42(uVar4,*(undefined2 *)(info + 0x24)),0,0x495370,unknownonly);
      if (lVar5 == 0) {
        g_busy = '\x01';
      }
    }
  }
  else {
    CTkMsgWinData::AddErr(_g_pMsgWinData,0x79);
  }
  return;
}



// ---------------------------------------------------------------------------
// Send
// YkWndMessage::Send(unsigned long, int)
//   symbol: Send__12YkWndMessageFUli
//   rva:    0x00396b00  size: 160 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndMessage.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void YkWndMessage::Send(YkWndMessage *this,ulong polid,int hnnum)

{
  long lVar1;
  
  if (g_busy == '\0') {
    lVar1 = NT_SYS::getPOLCON((NT_SYS *)g_pNtSys);
    if (lVar1 != 0) {
      *(ulong *)&this->m_pid = polid;
      this->m_hnnum = hnnum;
      *(undefined2 *)&this->m_mode = 1;
      CTkMenuMng::CreateDrawMenu((CTkMenuMng *)&g_TkMenuMng,_2410,'\x01','\0');
    }
  }
  else {
    CTkMsgWinData::AddErr(_g_pMsgWinData,0x79);
  }
  return;
}



// ---------------------------------------------------------------------------
// Knock
// YkWndMessage::Knock(FFWCaReplyInfo *, int, int)
//   symbol: Knock__12YkWndMessageFP14FFWCaReplyInfoii
//   rva:    0x00396ba0  size: 1108 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndMessage.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void YkWndMessage::Knock
               (YkWndMessage *this,FFWCaReplyInfo *info,int race,int face)

{
  FFWCaReplyInfo FVar1;
  FFWCaReplyInfo FVar2;
  undefined2 uVar3;
  int iVar4;
  int iVar5;
  char *pcVar6;
  undefined4 uVar7;
  uint uVar8;
  long lVar9;
  FFWCaReplyInfo *pFVar10;
  FFWCaReplyInfo *pFVar11;
  char acStack_190 [64];
  char acStack_150 [268];
  uint uStack_44;
  YkWndMessage *pYStack_40;
  FFWCaReplyInfo *pFStack_30;
  int iStack_20;
  int iStack_10;
  
  pYStack_40 = this;
  pFStack_30 = info;
  iStack_20 = race;
  iStack_10 = face;
  if (g_busy == '\0') {
    lVar9 = NT_SYS::getPOLCON((NT_SYS *)g_pNtSys);
    if ((lVar9 != 0) && (iVar4 = ntTimeGetSec(), 0x1d < iVar4 - pYStack_40->m_time)) {
      iVar4 = iStack_10 + (iStack_20 + -1) * 8 + 0x15a6;
      if (pYStack_40->m_face != iVar4) {
        iVar5 = XiFileManager::getFileSize(_g_xiFileManager,iVar4);
        pYStack_40->m_pngsize = iVar5;
        if (pYStack_40->m_png == (char *)0x0) {
          pcVar6 = (char *)__nwa__FUi(pYStack_40->m_pngsize);
          pYStack_40->m_png = pcVar6;
        }
        lVar9 = XiFileManager::readFileNow
                          (_g_xiFileManager,iVar4,pYStack_40->m_png,pYStack_40->m_pngsize,0);
        if (lVar9 < 0) {
          if (pYStack_40->m_png != (char *)0x0) {
            __dla__FPv(pYStack_40->m_png);
            pYStack_40->m_png = (char *)0x0;
          }
          pYStack_40->m_pngsize = 0;
          pYStack_40->m_face = -1;
        }
        else {
          pYStack_40->m_face = iVar4;
        }
      }
      *(undefined2 *)&pYStack_40->m_mode = 3;
      (pYStack_40->m_info).defs = *(uint *)pFStack_30;
      pFVar11 = pFStack_30 + 4;
      pFVar10 = (FFWCaReplyInfo *)&(pYStack_40->m_info).name;
      iVar4 = 8;
      do {
        FVar1 = *pFVar11;
        FVar2 = pFVar11[1];
        pFVar11 = pFVar11 + 2;
        iVar4 = iVar4 + -1;
        *pFVar10 = FVar1;
        pFVar10[1] = FVar2;
        pFVar10 = pFVar10 + 2;
      } while (0 < iVar4);
      (pYStack_40->m_info).zone = *(ushort *)(pFStack_30 + 0x14);
      (pYStack_40->m_info).home = *(ushort *)(pFStack_30 + 0x16);
      uVar3 = *(undefined2 *)(pFStack_30 + 0x1a);
      (pYStack_40->m_info).job = *(ushort *)(pFStack_30 + 0x18);
      *(undefined2 *)&(pYStack_40->m_info).field_0x1a = uVar3;
      uVar3 = *(undefined2 *)(pFStack_30 + 0x1e);
      (pYStack_40->m_info).level = *(ushort *)(pFStack_30 + 0x1c);
      *(undefined2 *)&(pYStack_40->m_info).field_0x1e = uVar3;
      (pYStack_40->m_info).race = *(ushort *)(pFStack_30 + 0x20);
      (pYStack_40->m_info).status = *(ushort *)(pFStack_30 + 0x22);
      (pYStack_40->m_info).id = *(ushort *)(pFStack_30 + 0x24);
      (pYStack_40->m_info).comlinkFlag = (byte)pFStack_30[0x26];
      (pYStack_40->m_info).rank = (byte)pFStack_30[0x27];
      (pYStack_40->m_info).globalID = *(uint *)(pFStack_30 + 0x28);
      (pYStack_40->m_info).msgType = *(uint *)(pFStack_30 + 0x2c);
      iVar4 = NT_SYS::getWorld((NT_SYS *)g_pNtSys,*(uint *)(g_pNtSys + 0x80));
      lVar9 = NT_SYS::getWorldNameForKita((NT_SYS *)g_pNtSys,iVar4);
      if (lVar9 == 0) {
        sprintf(acStack_190,(char *)&_2412,_pGlobalNowZone + 0x25184);
      }
      else {
        sprintf(acStack_190,_2411,_pGlobalNowZone + 0x25184,lVar9);
      }
      pcVar6 = (char *)XiStrGet(10,0x21);
      sprintf(acStack_150,pcVar6,_pGlobalNowZone + 0x25184);
      uStack_44 = *(uint *)(g_pNtSys + 0x80);
      uVar7 = NT_SYS::getWorld((NT_SYS *)g_pNtSys,uStack_44);
      lVar9 = gcPMsgSendKnockMessage
                        ((pYStack_40->m_info).globalID,(int)CONCAT42(uVar7,(pYStack_40->m_info).id),
                         0,acStack_190,acStack_150,pYStack_40->m_png,pYStack_40->m_pngsize,0x495130)
      ;
      if (lVar9 == 0) {
        if (_g_pTkHelp != 0) {
          KaHelpMes::SetLoadMes((KaHelpMes *)(_g_pTkHelp + 0x20),0x10);
        }
        g_busy = '\x01';
        uVar8 = ntTimeGetSec();
        pYStack_40->m_time = uVar8;
      }
    }
  }
  else {
    CTkMsgWinData::AddErr(_g_pMsgWinData,0x79);
  }
  return;
}



// ---------------------------------------------------------------------------
// OnInitialUpdatePrimitive
// YkWndMessageReply::OnInitialUpdatePrimitive(void)
//   symbol: OnInitialUpdatePrimitive__17YkWndMessageReplyFv
//   rva:    0x00397000  size: 48 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndMessage.cpp
// ---------------------------------------------------------------------------


/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void YkWndMessageReply::OnInitialUpdatePrimitive(YkWndMessageReply *this)

{
  (**(code **)(*(int *)&this->field_0x4 + 0x5c))();
  return;
}



// ---------------------------------------------------------------------------
// IgnoreYNCallBack1
// IgnoreYNCallBack1(void *, char)
//   symbol: IgnoreYNCallBack1__FPvc
//   rva:    0x00397040  size: 312 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndMessage.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void IgnoreYNCallBack1__FPvc(int user,char yes)

{
  long lVar1;
  
  if (yes != '\0') {
    lVar1 = gcFriendSearchPolIdHn(*(undefined8 *)(user + 0x20),*(undefined1 *)(user + 0x5c));
    if (lVar1 == 0) {
      lVar1 = gcFriendRegist(1,0,*(undefined8 *)(user + 0x20),*(undefined1 *)(user + 0x5c),
                             user + 0x30);
      if (lVar1 != 0) {
        CTkMsgWinData::AddMsg(_g_pMsgWinData,0x18);
      }
    }
    else {
      lVar1 = gcFriendReRegist(1,0,lVar1);
      if (lVar1 != 0) {
        CTkMsgWinData::AddMsg(_g_pMsgWinData,0x18);
      }
    }
    lVar1 = gcFriendServUpdateStart();
    if (((-1 < lVar1) && (lVar1 = NT_SYS::getPOLCON((NT_SYS *)g_pNtSys), lVar1 != 0)) &&
       (lVar1 = gcPMsgMarkMessage2(*(undefined8 *)(user + 0x18),*(undefined8 *)(user + 0x20),
                                   0x495200,0x19), lVar1 == 0)) {
      g_busy = 1;
    }
    CTkMenuMng::DestroyDrawMenu((CTkMenuMng *)&g_TkMenuMng,_2603);
  }
  return;
}



// ---------------------------------------------------------------------------
// IgnoreYNCallBack2
// IgnoreYNCallBack2(void *, char)
//   symbol: IgnoreYNCallBack2__FPvc
//   rva:    0x00397180  size: 484 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndMessage.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void IgnoreYNCallBack2__FPvc(int user,char yes)

{
  int iVar1;
  long lVar2;
  undefined8 uVar3;
  undefined8 uVar4;
  undefined1 auStack_b0 [136];
  undefined8 uStack_28;
  int iStack_20;
  char cStack_10;
  
  if (yes != '\0') {
    iStack_20 = user;
    cStack_10 = yes;
    lVar2 = gcFriendSearchPolIdHn(*(undefined8 *)(user + 0x20),*(undefined1 *)(user + 0x5c));
    if (lVar2 == 0) {
      lVar2 = gcFriendRegist(1,0,*(undefined8 *)(user + 0x20),*(undefined1 *)(user + 0x5c),
                             user + 0x30);
      if (lVar2 != 0) {
        CTkMsgWinData::AddMsg(_g_pMsgWinData,0x18);
      }
    }
    else {
      lVar2 = gcFriendReRegist(1,0,lVar2);
      if (lVar2 != 0) {
        CTkMsgWinData::AddMsg(_g_pMsgWinData,0x18);
      }
    }
    lVar2 = gcFriendServUpdateStart();
    iVar1 = _g_pYkWndMessage;
    if ((-1 < lVar2) && (_g_pYkWndMessage != 0)) {
      uVar4 = *(undefined8 *)(user + 0x20);
      uVar3 = *(undefined8 *)(user + 0x18);
      uStack_28 = uVar3;
      if (g_busy == '\0') {
        *(undefined2 *)(_g_pYkWndMessage + 0x14) = 8;
        uStack_28._0_4_ = (undefined4)uVar3;
        *(undefined4 *)(iVar1 + 0x1c8) = (undefined4)uStack_28;
        uStack_28._4_4_ = (undefined4)((ulong)uVar3 >> 0x20);
        *(undefined4 *)(iVar1 + 0x1cc) = uStack_28._4_4_;
        *(undefined8 *)(iVar1 + 0x1c8) = uVar3;
        *(undefined8 *)(iVar1 + 0x1b8) = uVar4;
        sqPlayOnlineMessageGetMessageFixedFormString(10,auStack_b0,0x7f);
        lVar2 = gcPMsgReplyFriendReject3
                          (*(undefined8 *)(iVar1 + 0x1c8),*(undefined8 *)(iVar1 + 0x1b8),auStack_b0,
                           iVar1 + 0x53,0x4952a0,0x16);
        if (lVar2 == 0) {
          if (_g_pTkHelp != 0) {
            KaHelpMes::SetLoadMes((KaHelpMes *)(_g_pTkHelp + 0x20),0x10);
          }
          g_busy = '\x01';
        }
      }
      else {
        CTkMsgWinData::AddErr(_g_pMsgWinData,0x79);
      }
    }
    CTkMenuMng::DestroyDrawMenu((CTkMenuMng *)&g_TkMenuMng,_2631);
  }
  return;
}



// ---------------------------------------------------------------------------
// OnCreate
// YkWndMessageReply1::OnCreate(void)
//   symbol: OnCreate__18YkWndMessageReply1Fv
//   rva:    0x00397370  size: 220 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndMessage.cpp
// ---------------------------------------------------------------------------


/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void YkWndMessageReply1::OnCreate(YkWndMessageReply1 *this)

{
  long lVar1;
  
  lVar1 = gcFriendRegistPossibleCheck(1,*(undefined8 *)(this + 0x20),this[0x5c]);
  if (lVar1 < 0) {
    CTkMenuCtrlData::SetButtonStatus(*(undefined4 *)(this + 8),5,3);
  }
  switch(*(undefined4 *)(this + 0x14)) {
  case 2:
  case 3:
    CTkMenuCtrlData::SetButtonStatus(*(undefined4 *)(this + 8),5,1);
    break;
  case 4:
  case 5:
  case 6:
    CTkMenuCtrlData::SetButtonStatus(*(undefined4 *)(this + 8),5,3);
    CTkMenuCtrlData::SetButtonStatus(*(undefined4 *)(this + 8),5,1);
  }
  return;
}



// ---------------------------------------------------------------------------
// OnKeyDown
// YkWndMessageReply1::OnKeyDown(short, short)
//   symbol: OnKeyDown__18YkWndMessageReply1Fss
//   rva:    0x00397450  size: 536 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndMessage.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void YkWndMessageReply1::OnKeyDown(int this,short idx,short param_3)

{
  int iVar1;
  char *type;
  undefined8 uVar2;
  long lVar3;
  undefined8 uVar4;
  undefined4 uStack_38;
  undefined4 uStack_34;
  
  iVar1 = _g_pYkWndMessage;
  if (idx != 5) {
    return;
  }
  if (param_3 == 5) {
    lVar3 = NT_SYS::getPOLCON((NT_SYS *)g_pNtSys);
    if ((lVar3 != 0) &&
       (lVar3 = gcPMsgMarkMessage2(*(undefined8 *)(this + 0x18),*(undefined8 *)(this + 0x20),
                                   0x495200,0x19), lVar3 == 0)) {
      g_busy = '\x01';
    }
  }
  else if (param_3 != 4) {
    if (param_3 == 3) {
      XiStrGet(9,0x1a);
      YkWndYesno::Open(_g_pYkWndYesno);
      return;
    }
    if (param_3 == 2) {
      if (_g_pTkHelp != (CTkHelp *)0x0) {
        type = (char *)XiStrGet(7,0x77);
        CTkHelp::SetHelpString(_g_pTkHelp,type,1);
      }
      YmSePlayBeep__Fv();
      return;
    }
    if ((param_3 == 1) && (_g_pYkWndMessage != 0)) {
      uVar4 = *(undefined8 *)(this + 0x20);
      uVar2 = *(undefined8 *)(this + 0x18);
      if (g_busy == '\0') {
        *(undefined2 *)(_g_pYkWndMessage + 0x14) = 5;
        uStack_38 = (undefined4)uVar2;
        *(undefined4 *)(iVar1 + 0x1c8) = uStack_38;
        uStack_34 = (undefined4)((ulong)uVar2 >> 0x20);
        *(undefined4 *)(iVar1 + 0x1cc) = uStack_34;
        *(undefined8 *)(iVar1 + 0x1c8) = uVar2;
        *(undefined8 *)(iVar1 + 0x1b8) = uVar4;
        CTkMenuMng::CreateDrawMenu((CTkMenuMng *)&g_TkMenuMng,_2410,'\x01','\0');
      }
      else {
        CTkMsgWinData::AddErr(_g_pMsgWinData,0x79);
      }
    }
  }
  CTkMenuMng::DestroyDrawMenu((CTkMenuMng *)&g_TkMenuMng,_2603);
  return;
}



// ---------------------------------------------------------------------------
// OnCreate
// YkWndMessageReply2::OnCreate(void)
//   symbol: OnCreate__18YkWndMessageReply2Fv
//   rva:    0x00397670  size: 92 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndMessage.cpp
// ---------------------------------------------------------------------------


/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void YkWndMessageReply2::OnCreate(YkWndMessageReply2 *this)

{
  long lVar1;
  
  lVar1 = gcFriendRegistPossibleCheck(1,*(undefined8 *)(this + 0x20),this[0x5c]);
  if (lVar1 < 0) {
    CTkMenuCtrlData::SetButtonStatus(*(undefined4 *)(this + 8),5,6);
  }
  return;
}



// ---------------------------------------------------------------------------
// OnKeyDown
// YkWndMessageReply2::OnKeyDown(short, short)
//   symbol: OnKeyDown__18YkWndMessageReply2Fss
//   rva:    0x003976d0  size: 1424 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndMessage.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void YkWndMessageReply2::OnKeyDown(int this,short idx,undefined2 param_3)

{
  int iVar1;
  char *pcVar2;
  undefined8 uVar3;
  long lVar4;
  undefined8 uVar5;
  undefined1 auStack_1e0 [128];
  undefined1 auStack_160 [128];
  undefined1 auStack_e0 [136];
  undefined8 uStack_58;
  undefined8 uStack_50;
  undefined8 uStack_48;
  undefined8 uStack_40;
  CTkHelp *pCStack_38;
  CTkHelp *pCStack_34;
  int iStack_30;
  short sStack_20;
  undefined2 uStack_10;
  
  iVar1 = _g_pYkWndMessage;
  if (idx == 5) {
    iStack_30 = this;
    sStack_20 = idx;
    uStack_10 = param_3;
    switch(param_3) {
    case 1:
      if (_g_pYkWndMessage != 0) {
        lVar4 = gcFriendRegistPossibleCheck
                          (0,*(undefined8 *)(this + 0x20),*(undefined1 *)(this + 0x5c));
        iVar1 = _g_pYkWndMessage;
        if (lVar4 < 0) {
          uVar3 = *(undefined8 *)(iStack_30 + 0x20);
          uStack_48 = *(undefined8 *)(iStack_30 + 0x18);
          sqPlayOnlineMessageGetMessageFixedFormString(9,auStack_e0,0x7f);
          if (g_busy == '\0') {
            *(undefined2 *)(iVar1 + 0x14) = 6;
            *(undefined4 *)(iVar1 + 0x1c8) = (undefined4)uStack_48;
            *(undefined4 *)(iVar1 + 0x1cc) = uStack_48._4_4_;
            *(undefined8 *)(iVar1 + 0x1c8) = uStack_48;
            *(undefined8 *)(iVar1 + 0x1b8) = uVar3;
            lVar4 = gcPMsgReplyFriendAccept3
                              (*(undefined8 *)(iVar1 + 0x1c8),*(undefined8 *)(iVar1 + 0x1b8),
                               auStack_e0,iVar1 + 0x53,0x4952a0,0x15);
            if (lVar4 == 0) {
              if (_g_pTkHelp != (CTkHelp *)0x0) {
                pCStack_34 = _g_pTkHelp;
                KaHelpMes::SetLoadMes(&_g_pTkHelp->m_helpMes,0x10);
              }
              g_busy = '\x01';
            }
          }
          else {
            CTkMsgWinData::AddErr(_g_pMsgWinData,0x79);
          }
        }
        else {
          uVar5 = *(undefined8 *)(iStack_30 + 0x20);
          uVar3 = *(undefined8 *)(iStack_30 + 0x18);
          uStack_40 = uVar3;
          if (g_busy == '\0') {
            *(undefined2 *)(_g_pYkWndMessage + 0x14) = 7;
            uStack_40._0_4_ = (undefined4)uVar3;
            *(undefined4 *)(iVar1 + 0x1c8) = (undefined4)uStack_40;
            uStack_40._4_4_ = (undefined4)((ulong)uVar3 >> 0x20);
            *(undefined4 *)(iVar1 + 0x1cc) = uStack_40._4_4_;
            *(undefined8 *)(iVar1 + 0x1c8) = uVar3;
            *(undefined8 *)(iVar1 + 0x1b8) = uVar5;
            if (iStack_30 == -0x30) {
              *(undefined1 *)(iVar1 + 0x188) = 0;
            }
            else {
              strncpy((char *)(iVar1 + 0x188),(char *)(iStack_30 + 0x30),0x10);
              *(undefined1 *)(iVar1 + 0x197) = 0;
            }
            lVar4 = NT_SYS::getPOLCON((NT_SYS *)g_pNtSys);
            if (lVar4 != 0) {
              CTkMenuMng::CreateDrawMenu((CTkMenuMng *)&g_TkMenuMng,_2410,'\x01','\0');
            }
          }
          else {
            CTkMsgWinData::AddErr(_g_pMsgWinData,0x79);
          }
        }
      }
      break;
    case 2:
      if (_g_pYkWndMessage != 0) {
        uVar3 = *(undefined8 *)(this + 0x20);
        uStack_58 = *(undefined8 *)(this + 0x18);
        sqPlayOnlineMessageGetMessageFixedFormString(9,auStack_1e0,0x7f);
        if (g_busy == '\0') {
          *(undefined2 *)(iVar1 + 0x14) = 6;
          *(undefined4 *)(iVar1 + 0x1c8) = (undefined4)uStack_58;
          *(undefined4 *)(iVar1 + 0x1cc) = uStack_58._4_4_;
          *(undefined8 *)(iVar1 + 0x1c8) = uStack_58;
          *(undefined8 *)(iVar1 + 0x1b8) = uVar3;
          lVar4 = gcPMsgReplyFriendAccept3
                            (*(undefined8 *)(iVar1 + 0x1c8),*(undefined8 *)(iVar1 + 0x1b8),
                             auStack_1e0,iVar1 + 0x53,0x4952a0,0x15);
          if (lVar4 == 0) {
            if (_g_pTkHelp != (CTkHelp *)0x0) {
              KaHelpMes::SetLoadMes(&_g_pTkHelp->m_helpMes,0x10);
            }
            g_busy = '\x01';
          }
        }
        else {
          CTkMsgWinData::AddErr(_g_pMsgWinData,0x79);
        }
      }
      break;
    case 3:
      if (_g_pYkWndMessage != 0) {
        uVar5 = *(undefined8 *)(this + 0x20);
        uVar3 = *(undefined8 *)(this + 0x18);
        uStack_50 = uVar3;
        if (g_busy == '\0') {
          *(undefined2 *)(_g_pYkWndMessage + 0x14) = 8;
          uStack_50._0_4_ = (undefined4)uVar3;
          *(undefined4 *)(iVar1 + 0x1c8) = (undefined4)uStack_50;
          uStack_50._4_4_ = (undefined4)((ulong)uVar3 >> 0x20);
          *(undefined4 *)(iVar1 + 0x1cc) = uStack_50._4_4_;
          *(undefined8 *)(iVar1 + 0x1c8) = uVar3;
          *(undefined8 *)(iVar1 + 0x1b8) = uVar5;
          sqPlayOnlineMessageGetMessageFixedFormString(10,auStack_160,0x7f);
          lVar4 = gcPMsgReplyFriendReject3
                            (*(undefined8 *)(iVar1 + 0x1c8),*(undefined8 *)(iVar1 + 0x1b8),
                             auStack_160,iVar1 + 0x53,0x4952a0,0x16);
          if (lVar4 == 0) {
            if (_g_pTkHelp != (CTkHelp *)0x0) {
              pCStack_38 = _g_pTkHelp;
              KaHelpMes::SetLoadMes(&_g_pTkHelp->m_helpMes,0x10);
            }
            g_busy = '\x01';
          }
        }
        else {
          CTkMsgWinData::AddErr(_g_pMsgWinData,0x79);
        }
      }
      break;
    case 4:
      if (_g_pTkHelp != (CTkHelp *)0x0) {
        pcVar2 = (char *)XiStrGet(7,0x76);
        CTkHelp::SetHelpString(_g_pTkHelp,pcVar2,1);
      }
      YmSePlayBeep__Fv();
      return;
    case 5:
      if (_g_pTkHelp != (CTkHelp *)0x0) {
        pcVar2 = (char *)XiStrGet(7,0x77);
        CTkHelp::SetHelpString(_g_pTkHelp,pcVar2,1);
      }
      YmSePlayBeep__Fv();
      return;
    case 6:
      XiStrGet(9,0x1a);
      YkWndYesno::Open(_g_pYkWndYesno);
      return;
    case 8:
      if (_g_pTkHelp != (CTkHelp *)0x0) {
        pcVar2 = (char *)XiStrGet(7,0x75);
        CTkHelp::SetHelpString(_g_pTkHelp,pcVar2,1);
      }
      YmSePlayBeep__Fv();
      return;
    }
    CTkMenuMng::DestroyDrawMenu((CTkMenuMng *)&g_TkMenuMng,_2631);
    return;
  }
  return;
}



// ---------------------------------------------------------------------------
// YkListCallBack
// YkListCallBack(void *, unsigned short, FFPolMsg_STATUS, unsigned short, const FFPolMsg_MsgStruct *)
//   symbol: YkListCallBack__FPvUs15FFPolMsg_STATUSUsPC18FFPolMsg_MsgStruct
//   rva:    0x00397c60  size: 832 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndMessage.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined4
YkListCallBack__FPvUs15FFPolMsg_STATUSUsPC18FFPolMsg_MsgStruct
          (YkWndMessageList *user,undefined2 type,int status,undefined8 msg,
          undefined8 *param_5)

{
  int iVar1;
  undefined4 uVar2;
  long lVar3;
  undefined4 *puVar4;
  YkWndListItem *pYStack_58;
  _YK_MESSAGE_DATA *p_Stack_54;
  YkWndMessageList *pYStack_50;
  undefined2 uStack_40;
  int iStack_30;
  undefined8 *puStack_10;
  
  g_busy = 0;
  if (*(int *)(_g_pYkWndMessageList + 8) == 0) {
    uVar2 = 0;
  }
  else {
    pYStack_50 = user;
    uStack_40 = type;
    iStack_30 = status;
    puStack_10 = param_5;
    if (status == 0) {
      YkWndMessageList::GetData
                (user,(YkWndListItem **)&pYStack_58,&p_Stack_54);
      if (p_Stack_54 == (_YK_MESSAGE_DATA *)0x0) {
        return 0;
      }
      *(undefined4 *)p_Stack_54 = *(undefined4 *)puStack_10;
      *(undefined4 *)(p_Stack_54 + 4) = *(undefined4 *)((int)puStack_10 + 4);
      *(undefined8 *)p_Stack_54 = *puStack_10;
      *(undefined8 *)(p_Stack_54 + 8) = **(undefined8 **)(puStack_10 + 3);
      memcpy(p_Stack_54 + 0x10,*(void **)(puStack_10 + 1),0xf);
      p_Stack_54[0x1f] = (_YK_MESSAGE_DATA)0x0;
      memcpy(p_Stack_54 + 0x20,*(void **)((int)puStack_10 + 0xc),0xf);
      p_Stack_54[0x2f] = (_YK_MESSAGE_DATA)0x0;
      iVar1 = ykGetMessageTypeID__Fi(uStack_40);
      *(undefined1 **)(p_Stack_54 + 0x48) = ykmessagetype + iVar1 * 8;
      *(ulong *)(p_Stack_54 + 0x50) = (ulong)*(uint *)(*(int *)(puStack_10 + 3) + 0x34);
      lVar3 = YkLocalTime__Fl(*(undefined8 *)(p_Stack_54 + 0x50));
      if (lVar3 == 0) {
        sprintf((char *)(p_Stack_54 + 0x30),_2803);
      }
      else {
        puVar4 = (undefined4 *)lVar3;
        sprintf((char *)(p_Stack_54 + 0x30),_2802,(int)puVar4[5] % 100,puVar4[4] + 1,puVar4[3],
                puVar4[2],puVar4[1],*puVar4);
      }
      YkWndListItem::Set(pYStack_58,1,'\x16',p_Stack_54 + 0x10,0x80808080);
      YkWndListItem::Set(pYStack_58,2,'\x16',p_Stack_54 + 0x20,0x80808080);
      YkWndListItem::Set(pYStack_58,3,'\x01',*(void **)(p_Stack_54 + 0x48),0x80808080);
      YkWndListItem::Set(pYStack_58,4,'\x01',p_Stack_54 + 0x30,0x80808080);
      pYStack_58->m_user = p_Stack_54;
      YkWndMessageList::SetData(user);
    }
    else if (status == 1) {
      if (user->m_idx == 0) {
        uVar2 = XiStrGet(7,0x68);
        *(undefined4 *)&user->field_0x3c = uVar2;
        user->field_0x40 = 0x20;
        user->field_0x41 = 0x18;
      }
      if (_g_pTkHelp != 0) {
        KaHelpMes::ResetLoadMes((KaHelpMes *)(_g_pTkHelp + 0x20),0x10);
      }
    }
    uVar2 = 1;
  }
  return uVar2;
}



// ---------------------------------------------------------------------------
// YkRecvCallBack
// YkRecvCallBack(void *, unsigned short, FFPolMsg_STATUS, unsigned short, const FFPolMsg_MsgStruct *)
//   symbol: YkRecvCallBack__FPvUs15FFPolMsg_STATUSUsPC18FFPolMsg_MsgStruct
//   rva:    0x00397fa0  size: 1344 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndMessage.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void YkRecvCallBack__FPvUs15FFPolMsg_STATUSUsPC18FFPolMsg_MsgStruct
               (undefined8 type,short status,int msg,undefined8 param_4,undefined8 *param_5)

{
  void *pvVar1;
  int iVar2;
  int iVar3;
  size_t sVar4;
  undefined8 uVar5;
  int iVar6;
  char acStack_230 [432];
  undefined8 uStack_80;
  undefined8 uStack_78;
  undefined8 uStack_70;
  undefined8 uStack_68;
  undefined2 uStack_5c;
  undefined1 uStack_5a;
  void *pvStack_58;
  int iStack_54;
  short sStack_40;
  int iStack_30;
  undefined8 *puStack_10;
  
  g_busy = 0;
  sStack_40 = status;
  iStack_30 = msg;
  puStack_10 = param_5;
  if (msg == 0) {
    if (status == 0x1e) {
      iVar6 = 6;
    }
    else if (status == 3) {
      iVar6 = 4;
    }
    else if (status == 10) {
      iVar6 = 3;
    }
    else if (status == 9) {
      iVar6 = 2;
    }
    else if (status == 1) {
      iVar6 = 1;
    }
    else if (status == 0) {
      iVar6 = 0;
    }
    else {
      iVar6 = 5;
    }
    if (iVar6 == 5) {
      CTkMsgWinData::AddErr(_g_pMsgWinData,0x5f);
    }
    else {
      uStack_5c = _2811;
      uStack_5a = DAT_0054d5e2;
      sprintf(acStack_230,_2879,*(undefined4 *)(param_5 + 1));
      CTkMsgWinData::AddString
                (_g_pMsgWinData,acStack_230,(TK_DATAHEDDER *)&uStack_5c,'\0','\x01');
      if (((iVar6 == 6) || (iVar6 == 4)) || (iVar6 == 0)) {
        sVar4 = strlen(*(char **)(puStack_10 + 2));
        if (sVar4 < 0x12d) {
          sprintf(acStack_230,_2880,*(undefined4 *)(puStack_10 + 2));
          VulgarFilter__FPc(acStack_230);
          CTkMsgWinData::AddString
                    (_g_pMsgWinData,acStack_230,(TK_DATAHEDDER *)&uStack_5c,'\0','\x01');
        }
        sVar4 = strlen(*(char **)((int)puStack_10 + 0x14));
        if (sVar4 < 0x12d) {
          sprintf(acStack_230,_2881,*(undefined4 *)((int)puStack_10 + 0x14));
          VulgarFilter__FPc(acStack_230);
          CTkMsgWinData::AddString
                    (_g_pMsgWinData,acStack_230,(TK_DATAHEDDER *)&uStack_5c,'\0','\x01');
        }
      }
      else {
        strcpy(acStack_230,_2882);
        sVar4 = strlen(acStack_230);
        sqPlayOnlineMessageGetMessageFixedFormString(sStack_40,acStack_230 + (int)sVar4,300);
        CTkMsgWinData::AddString
                  (_g_pMsgWinData,acStack_230,(TK_DATAHEDDER *)&uStack_5c,'\0','\x01');
      }
      iVar3 = _g_pYkWndMessageReply2;
      iVar2 = _g_pYkWndMessageReply1;
      if (*(int *)(_g_pYkWndMessageList + 8) != 0) {
        if ((long)((ulong)*(byte *)(*(int *)(puStack_10 + 3) + 0x43) << 0x3e) < 0) {
          if (_g_pYkWndMessageReply1 != 0) {
            pvVar1 = *(void **)(puStack_10 + 3);
            uVar5 = *puStack_10;
            uStack_80._0_4_ = (undefined4)uVar5;
            *(undefined4 *)(_g_pYkWndMessageReply1 + 0x18) = (undefined4)uStack_80;
            uStack_80._4_4_ = (undefined4)((ulong)uVar5 >> 0x20);
            *(undefined4 *)(iVar2 + 0x1c) = uStack_80._4_4_;
            *(undefined8 *)(iVar2 + 0x18) = uVar5;
            *(undefined4 *)(iVar2 + 0x14) = 5;
            uStack_80 = uVar5;
            memcpy((void *)(iVar2 + 0x20),pvVar1,0x48);
            (**(code **)(*(int *)(iVar2 + 4) + 0x58))();
          }
        }
        else if (sStack_40 == 1) {
          if (_g_pYkWndMessageReply2 != 0) {
            pvVar1 = *(void **)(puStack_10 + 3);
            uVar5 = *puStack_10;
            uStack_70._0_4_ = (undefined4)uVar5;
            *(undefined4 *)(_g_pYkWndMessageReply2 + 0x18) = (undefined4)uStack_70;
            uStack_70._4_4_ = (undefined4)((ulong)uVar5 >> 0x20);
            *(undefined4 *)(iVar3 + 0x1c) = uStack_70._4_4_;
            *(undefined8 *)(iVar3 + 0x18) = uVar5;
            *(int *)(iVar3 + 0x14) = iVar6;
            uStack_70 = uVar5;
            memcpy((void *)(iVar3 + 0x20),pvVar1,0x48);
            (**(code **)(*(int *)(iVar3 + 4) + 0x58))();
          }
        }
        else if (sStack_40 == 0) {
          if (_g_pYkWndMessageReply1 != 0) {
            pvVar1 = *(void **)(puStack_10 + 3);
            uVar5 = *puStack_10;
            uStack_78._0_4_ = (undefined4)uVar5;
            *(undefined4 *)(_g_pYkWndMessageReply1 + 0x18) = (undefined4)uStack_78;
            uStack_78._4_4_ = (undefined4)((ulong)uVar5 >> 0x20);
            *(undefined4 *)(iVar2 + 0x1c) = uStack_78._4_4_;
            *(undefined8 *)(iVar2 + 0x18) = uVar5;
            *(int *)(iVar2 + 0x14) = iVar6;
            uStack_78 = uVar5;
            memcpy((void *)(iVar2 + 0x20),pvVar1,0x48);
            (**(code **)(*(int *)(iVar2 + 4) + 0x58))();
          }
        }
        else if (_g_pYkWndMessageReply1 != 0) {
          pvStack_58 = *(void **)(puStack_10 + 3);
          uVar5 = *puStack_10;
          uStack_68._0_4_ = (undefined4)uVar5;
          *(undefined4 *)(_g_pYkWndMessageReply1 + 0x18) = (undefined4)uStack_68;
          uStack_68._4_4_ = (undefined4)((ulong)uVar5 >> 0x20);
          *(undefined4 *)(iVar2 + 0x1c) = uStack_68._4_4_;
          *(undefined8 *)(iVar2 + 0x18) = uVar5;
          *(int *)(iVar2 + 0x14) = iVar6;
          uStack_68 = uVar5;
          memcpy((void *)(iVar2 + 0x20),pvStack_58,0x48);
          (**(code **)(*(int *)(iVar2 + 4) + 0x58))();
        }
      }
    }
  }
  else if ((msg == 1) && (_g_pTkHelp != 0)) {
    iStack_54 = _g_pTkHelp;
    KaHelpMes::ResetLoadMes((KaHelpMes *)(_g_pTkHelp + 0x20),0x10);
  }
  return;
}



// ---------------------------------------------------------------------------
// GetData
// YkWndMessageList::GetData(YkWndListItem * *, _YK_MESSAGE_DATA * *)
//   symbol: GetData__16YkWndMessageListFPP13YkWndListItemPP16_YK_MESSAGE_DATA
//   rva:    0x003984e0  size: 200 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndMessage.cpp
// ---------------------------------------------------------------------------


/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void YkWndMessageList::GetData
               (YkWndMessageList *this,YkWndListItem **wk,_YK_MESSAGE_DATA **data)

{
  if (((this->m_item == (YkWndListItem *)0x0) || (this->m_user == (_YK_MESSAGE_DATA *)0x0)) ||
     (this->m_max <= this->m_idx)) {
    *wk = (YkWndListItem *)0x0;
    *data = (_YK_MESSAGE_DATA *)0x0;
  }
  else {
    *wk = (YkWndListItem *)(this->m_item + this->m_idx);
    *data = (_YK_MESSAGE_DATA *)(this->m_user + this->m_idx);
  }
  return;
}



// ---------------------------------------------------------------------------
// SetData
// YkWndMessageList::SetData(void)
//   symbol: SetData__16YkWndMessageListFv
//   rva:    0x003985b0  size: 964 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndMessage.cpp
// ---------------------------------------------------------------------------


/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void YkWndMessageList::SetData(YkWndMessageList *this)

{
  char cVar1;
  undefined1 uVar2;
  char cVar3;
  void *pvVar4;
  undefined4 uVar5;
  char *pcVar6;
  undefined8 uVar7;
  undefined8 uVar8;
  int iVar9;
  int iVar10;
  int iVar11;
  char *pcVar12;
  undefined8 *puVar13;
  undefined4 *puVar14;
  YkWndListItem *pYVar15;
  YkWndListItem *pYVar16;
  uint *puVar17;
  void **ppvVar18;
  uint *puVar19;
  void **ppvVar20;
  YkWndListItem *pYVar21;
  YkWndListItem *pYVar22;
  char acStack_a0 [8];
  undefined8 auStack_98 [8];
  undefined4 auStack_58 [8];
  void *pvStack_38;
  char *pcStack_34;
  YkWndListItem *pYStack_24;
  void *pvStack_20;
  void *pvStack_1c;
  void *pvStack_18;
  void *pvStack_14;
  YkWndMessageList *pYStack_10;
  
  pYStack_10 = this;
  if (1 < this->m_idx) {
    pvStack_20 = this->m_item[this->m_idx].m_user;
    pvStack_1c = pvStack_20;
    for (iVar11 = this->m_idx; 1 < iVar11; iVar11 = iVar11 + -1) {
      pYStack_24 = this->m_item + iVar11 + -1;
      pvStack_18 = this->m_item[iVar11 + -1].m_user;
      pvStack_14 = pvStack_18;
      if (*(long *)((int)pvStack_18 + 0x50) < *(long *)((int)pvStack_20 + 0x50)) break;
    }
    if (iVar11 < this->m_idx) {
      pYVar15 = this->m_item + this->m_idx;
      pcVar12 = acStack_a0;
      iVar9 = 4;
      pYVar16 = pYVar15;
      do {
        pcVar6 = &pYVar16->m_type;
        cVar1 = pYVar16->field_0x1;
        pYVar16 = (YkWndListItem *)&pYVar16->field_0x2;
        iVar9 = iVar9 + -1;
        *pcVar12 = *pcVar6;
        pcVar12[1] = cVar1;
        pcVar12 = pcVar12 + 2;
      } while (0 < iVar9);
      puVar17 = &pYVar15->m_color;
      puVar13 = auStack_98;
      iVar9 = 4;
      do {
        uVar8 = *(undefined8 *)puVar17;
        uVar7 = *(undefined8 *)(puVar17 + 2);
        puVar17 = puVar17 + 4;
        iVar9 = iVar9 + -1;
        *puVar13 = uVar8;
        puVar13[1] = uVar7;
        puVar13 = puVar13 + 2;
      } while (0 < iVar9);
      ppvVar18 = &pYVar15->m_data;
      puVar14 = auStack_58;
      iVar9 = 4;
      do {
        pvVar4 = *ppvVar18;
        uVar5 = ppvVar18[1];
        ppvVar18 = ppvVar18 + 2;
        iVar9 = iVar9 + -1;
        *puVar14 = pvVar4;
        puVar14[1] = uVar5;
        puVar14 = puVar14 + 2;
      } while (0 < iVar9);
      pvStack_38 = pYVar15->m_user;
      pcStack_34 = pYVar15->m_help;
      for (iVar9 = pYStack_10->m_idx; iVar11 < iVar9; iVar9 = iVar9 + -1) {
        pYVar22 = pYStack_10->m_item + iVar9 + -1;
        pYVar21 = pYStack_10->m_item + iVar9;
        iVar10 = 4;
        pYVar16 = pYVar22;
        pYVar15 = pYVar21;
        do {
          pcVar12 = &pYVar16->m_type;
          uVar2 = pYVar16->field_0x1;
          pYVar16 = (YkWndListItem *)&pYVar16->field_0x2;
          iVar10 = iVar10 + -1;
          pYVar15->m_type = *pcVar12;
          pYVar15->field_0x1 = uVar2;
          pYVar15 = (YkWndListItem *)&pYVar15->field_0x2;
        } while (0 < iVar10);
        puVar19 = &pYVar22->m_color;
        puVar17 = &pYVar21->m_color;
        iVar10 = 4;
        do {
          uVar8 = *(undefined8 *)puVar19;
          uVar7 = *(undefined8 *)(puVar19 + 2);
          puVar19 = puVar19 + 4;
          iVar10 = iVar10 + -1;
          *(undefined8 *)puVar17 = uVar8;
          *(undefined8 *)(puVar17 + 2) = uVar7;
          puVar17 = puVar17 + 4;
        } while (0 < iVar10);
        ppvVar20 = &pYVar22->m_data;
        ppvVar18 = &pYVar21->m_data;
        iVar10 = 4;
        do {
          pvVar4 = *ppvVar20;
          uVar5 = ppvVar20[1];
          ppvVar20 = ppvVar20 + 2;
          iVar10 = iVar10 + -1;
          *ppvVar18 = pvVar4;
          ppvVar18[1] = (void *)uVar5;
          ppvVar18 = ppvVar18 + 2;
        } while (0 < iVar10);
        pYVar21->m_user = pYVar22->m_user;
        pYVar21->m_help = pYVar22->m_help;
      }
      pYVar15 = pYStack_10->m_item + iVar11;
      pcVar12 = acStack_a0;
      iVar11 = 4;
      pYVar16 = pYVar15;
      do {
        cVar1 = *pcVar12;
        cVar3 = pcVar12[1];
        pcVar12 = pcVar12 + 2;
        iVar11 = iVar11 + -1;
        pYVar16->m_type = cVar1;
        pYVar16->field_0x1 = cVar3;
        pYVar16 = (YkWndListItem *)&pYVar16->field_0x2;
      } while (0 < iVar11);
      puVar13 = auStack_98;
      puVar17 = &pYVar15->m_color;
      iVar11 = 4;
      do {
        uVar8 = *puVar13;
        uVar7 = puVar13[1];
        puVar13 = puVar13 + 2;
        iVar11 = iVar11 + -1;
        *(undefined8 *)puVar17 = uVar8;
        *(undefined8 *)(puVar17 + 2) = uVar7;
        puVar17 = puVar17 + 4;
      } while (0 < iVar11);
      puVar14 = auStack_58;
      ppvVar18 = &pYVar15->m_data;
      iVar11 = 4;
      do {
        pvVar4 = (void *)*puVar14;
        uVar5 = puVar14[1];
        puVar14 = puVar14 + 2;
        iVar11 = iVar11 + -1;
        *ppvVar18 = pvVar4;
        ppvVar18[1] = (void *)uVar5;
        ppvVar18 = ppvVar18 + 2;
      } while (0 < iVar11);
      pYVar15->m_user = pvStack_38;
      pYVar15->m_help = pcStack_34;
    }
  }
  iVar11 = pYStack_10->m_idx + 1;
  pYStack_10->m_idx = iVar11;
  YkWndList::SetItem(pYStack_10,pYStack_10->m_item,(short)iVar11);
  return;
}



// ---------------------------------------------------------------------------
// MakeList
// YkWndMessageList::MakeList(unsigned long, int)
//   symbol: MakeList__16YkWndMessageListFUli
//   rva:    0x00398980  size: 796 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndMessage.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

undefined4 YkWndMessageList::MakeList(YkWndMessageList *this,ulong polid,int hnnum)

{
  int iVar1;
  uint uVar2;
  YkWndListItem *pYVar3;
  _YK_MESSAGE_DATA *p_Var4;
  long lVar5;
  undefined8 uVar6;
  
  if (g_busy == '\0') {
    if (this->m_user != (_YK_MESSAGE_DATA *)0x0) {
      __dla__FPv(this->m_user);
      this->m_user = (_YK_MESSAGE_DATA *)0x0;
    }
    if (this->m_item != (YkWndListItem *)0x0) {
      if (this->m_item != (YkWndListItem *)0x0) {
        __dla__FPv(&this->m_item[-1].field_0x60);
      }
      this->m_item = (YkWndListItem *)0x0;
    }
    lVar5 = NT_SYS::getPOLCON((NT_SYS *)g_pNtSys);
    if (lVar5 != 0) {
      uVar2 = gcPMsgNumberOfUnreadMessage();
      this->m_max = (uVar2 & 0xffff) + 8;
      if (this->m_item == (YkWndListItem *)0x0) {
        iVar1 = this->m_max;
        uVar6 = __nwa__FUi(iVar1 * 0x70 + 0x10);
        pYVar3 = (YkWndListItem *)__construct_new_array(uVar6,0x3d0790,0,0x70,iVar1);
        this->m_item = pYVar3;
      }
      if (this->m_user == (_YK_MESSAGE_DATA *)0x0) {
        p_Var4 = (_YK_MESSAGE_DATA *)__nwa__FUi(this->m_max * 0x58);
        this->m_user = p_Var4;
      }
      this->m_idx = 0;
      if (((this->m_item == (YkWndListItem *)0x0) || (this->m_user == (_YK_MESSAGE_DATA *)0x0)) ||
         (this->m_max <= this->m_idx)) {
        pYVar3 = (YkWndListItem *)0x0;
        p_Var4 = (_YK_MESSAGE_DATA *)0x0;
      }
      else {
        pYVar3 = this->m_item + this->m_idx;
        p_Var4 = this->m_user + this->m_idx;
      }
      YkWndListItem::Set(pYVar3,0,'\x11',this->m_icon,0x80808080);
      p_Var4->type = (char *)0x0;
      pYVar3->m_user = p_Var4;
      YkWndMessageList::SetData(this);
      if (polid == 0) {
        lVar5 = gcPMsgListAllMessage(0x497c60,this);
      }
      else {
        lVar5 = gcPMsgListMessage2(polid,hnnum,0x497c60,this);
      }
      if (lVar5 == 0) {
        if (_g_pTkHelp != 0) {
          KaHelpMes::SetLoadMes((KaHelpMes *)(_g_pTkHelp + 0x20),0x10);
        }
        gcPMsgResetReceivedMessageCounter();
        g_busy = 1;
        return 1;
      }
    }
  }
  return 0;
}



// ---------------------------------------------------------------------------
// 
// YkWndMessageList::YkWndMessageList(void)
//   symbol: __ct__16YkWndMessageListFv
//   rva:    0x00398ca0  size: 100 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndMessage.cpp
// ---------------------------------------------------------------------------


/* WARNING: Unknown calling convention -- yet parameter storage is locked */

YkWndMessageList * YkWndMessageList::YkWndMessageList(YkWndMessageList *this)

{
  YkWndList::YkWndList((YkWndList *)this,'\0');
  *(undefined1 **)&this->field_0x4 = __vt__16YkWndMessageList;
  this->m_max = -1;
  this->m_item = (YkWndListItem *)0x0;
  this->m_user = (_YK_MESSAGE_DATA *)0x0;
  this->m_reload = '\0';
  return this;
}



// ---------------------------------------------------------------------------
// 
// YkWndMessageList::~YkWndMessageList(void)
//   symbol: __dt__16YkWndMessageListFv
//   rva:    0x00398d10  size: 124 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndMessage.cpp
// ---------------------------------------------------------------------------


/* WARNING: Unknown calling convention -- yet parameter storage is locked */

YkWndMessageList * YkWndMessageList::~YkWndMessageList(YkWndMessageList *this)

{
  short in_a1_lo;
  
  if (this != (YkWndMessageList *)0x0) {
    *(undefined1 **)&this->field_0x4 = __vt__16YkWndMessageList;
    YkWndMessageList::Close(this);
    YkWndList::~YkWndList((YkWndList *)this);
    if (0 < in_a1_lo) {
      __dl__FPv(this);
    }
  }
  return this;
}



// ---------------------------------------------------------------------------
// OnDestroy
// YkWndMessageList::OnDestroy(void)
//   symbol: OnDestroy__16YkWndMessageListFv
//   rva:    0x00398d90  size: 40 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndMessage.cpp
// ---------------------------------------------------------------------------


/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void YkWndMessageList::OnDestroy(YkWndMessageList *this)

{
  YkWndMessageList::Close(this);
  return;
}



// ---------------------------------------------------------------------------
// Open
// YkWndMessageList::Open(unsigned long, int)
//   symbol: Open__16YkWndMessageListFUli
//   rva:    0x00398dc0  size: 360 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndMessage.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

undefined4 YkWndMessageList::Open(YkWndMessageList *this,ulong polid,int hnnum)

{
  YmMenuShapeFile *pYVar1;
  CShape *pCVar2;
  undefined4 uVar3;
  long lVar4;
  
  YkWndMessageList::Close(this);
  pYVar1 = (YmMenuShapeFile *)GetMenuRes__Fi(1);
  pCVar2 = (CShape *)YmMenuShapeFile::operator[](pYVar1,0x113);
  this->m_icon = pCVar2;
  pYVar1 = (YmMenuShapeFile *)GetMenuRes__Fi(1);
  pCVar2 = (CShape *)YmMenuShapeFile::operator[](pYVar1,0x4b);
  this->m_curres = pCVar2;
  *(CShape **)&this->field_0x34 = this->m_curres;
  YkWndList::SetLine(this,0xf);
  *(undefined2 *)&this->field_0x16 = 5;
  *(undefined1 **)&this->field_0x30 = ykmessagelist_offset;
  *(undefined2 *)&this->field_0x26 = 0x10;
  *(ulong *)&this->m_pid = polid;
  this->m_hnnum = hnnum;
  lVar4 = YkWndMessageList::MakeList(this,polid,hnnum);
  if (lVar4 == 0) {
    uVar3 = 0;
  }
  else {
    CTkMenuMng::CreateDrawMenu((CTkMenuMng *)&g_TkMenuMng,_3027,'\x01','\0');
    if (_g_pTkTitleHandle != 0) {
      CTkMenuMng::CreateDrawMenu((CTkMenuMng *)&g_TkMenuMng,_3028,'\x01','\0');
    }
    uVar3 = 1;
  }
  return uVar3;
}



// ---------------------------------------------------------------------------
// Close
// YkWndMessageList::Close(void)
//   symbol: Close__16YkWndMessageListFv
//   rva:    0x00398f30  size: 340 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndMessage.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void YkWndMessageList::Close(YkWndMessageList *this)

{
  if (_g_pTkTitleHandle != 0) {
    CTkMenuMng::DestroyDrawMenu((CTkMenuMng *)&g_TkMenuMng,_3028);
  }
  CTkMenuMng::DestroyDrawMenu((CTkMenuMng *)&g_TkMenuMng,_3027);
  CTkMenuMng::DestroyDrawMenu((CTkMenuMng *)&g_TkMenuMng,_2603);
  CTkMenuMng::DestroyDrawMenu((CTkMenuMng *)&g_TkMenuMng,_2631);
  *(undefined4 *)&this->field_0x34 = 0;
  YkWndList::SetItem(this,0,0);
  *(undefined4 *)&this->field_0x3c = 0;
  this->field_0x40 = 0x20;
  this->field_0x41 = 0x18;
  if (this->m_user != (_YK_MESSAGE_DATA *)0x0) {
    __dla__FPv(this->m_user);
    this->m_user = (_YK_MESSAGE_DATA *)0x0;
  }
  if (this->m_item != (YkWndListItem *)0x0) {
    if (this->m_item != (YkWndListItem *)0x0) {
      __dla__FPv(&this->m_item[-1].field_0x60);
    }
    this->m_item = (YkWndListItem *)0x0;
  }
  if (_g_pTkHelp != 0) {
    KaHelpMes::ResetLoadMes((KaHelpMes *)(_g_pTkHelp + 0x20),0x10);
  }
  return;
}



// ---------------------------------------------------------------------------
// OnCalc
// YkWndMessageList::OnCalc(char)
//   symbol: OnCalc__16YkWndMessageListFc
//   rva:    0x00399090  size: 116 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndMessage.cpp
// ---------------------------------------------------------------------------


/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void YkWndMessageList::OnCalc(YkWndMessageList *this,char arg1)

{
  long lVar1;
  
  lVar1 = gcPMsgNumberOfReceivedMessage(this,arg1);
  if (lVar1 != 0) {
    this->m_reload = '\x01';
  }
  if ((this->m_reload != '\0') &&
     (lVar1 = YkWndMessageList::MakeList(this,*(ulong *)&this->m_pid,this->m_hnnum),
     lVar1 != 0)) {
    this->m_reload = '\0';
  }
  return;
}



// ---------------------------------------------------------------------------
// OnKeyOK
// YkWndMessageList::OnKeyOK(short)
//   symbol: OnKeyOK__16YkWndMessageListFs
//   rva:    0x00399110  size: 356 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndMessage.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined4 YkWndMessageList::OnKeyOK(YkWndList *this)

{
  undefined4 uVar1;
  int iVar2;
  long lVar3;
  undefined8 *puVar4;
  
  if (g_busy == '\0') {
    if (((*(int *)(this + 1) < 0) ||
        (iVar2._0_1_ = this[1].m_end, iVar2._1_1_ = this[1].field_0x1d,
        iVar2._2_1_ = this[1].m_listcur, iVar2._3_1_ = this[1].field_0x1f, iVar2 == 0)) ||
       (lVar3 = YkWndList::GetCurPos(this), lVar3 < 0)) {
      puVar4 = (undefined8 *)0x0;
    }
    else {
      iVar2 = YkWndList::GetCurPos(this);
      puVar4 = *(undefined8 **)(*(int *)&this[1].m_end + iVar2 * 0x70 + 0x68);
    }
    if (puVar4 == (undefined8 *)0x0) {
      uVar1 = 0;
    }
    else if ((*(int *)(puVar4 + 9) == 0) ||
            (lVar3 = gcPMsgReadMessage2(*puVar4,puVar4[1],0x497fa0,this), lVar3 != 0)) {
      uVar1 = 0;
    }
    else {
      if (_g_pTkHelp != 0) {
        KaHelpMes::SetLoadMes((KaHelpMes *)(_g_pTkHelp + 0x20),0x10);
      }
      g_busy = '\x01';
      uVar1 = 1;
    }
  }
  else {
    CTkMsgWinData::AddErr(_g_pMsgWinData,0x79);
    uVar1 = 0;
  }
  return uVar1;
}

