// AUTOGENERATED by ffxi-decomp. Do not edit by hand.
// version: 972 (sha256=d4622c1cc4a3012c, image_base=0x00100000)
// source:  main/yk/ykWndGuild.cpp
// functions: 23


// ---------------------------------------------------------------------------
// RecvGuildBuy
// RecvGuildBuy(GC_ZONE *, GP_GAME_PACKET_HEAD *, _GP_GUILD_TRADE *)
//   symbol: RecvGuildBuy__FP7GC_ZONEP19GP_GAME_PACKET_HEADP15_GP_GUILD_TRADE
//   rva:    0x00366670  size: 384 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndGuild.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined4
RecvGuildBuy__FP7GC_ZONEP19GP_GAME_PACKET_HEADP15_GP_GUILD_TRADE
          (undefined8 pData,undefined8 param_2,int param_3)

{
  long lVar1;
  undefined1 auStack_80 [8];
  undefined2 uStack_78;
  uint uStack_74;
  undefined4 uStack_70;
  int iStack_10;
  
  iStack_10 = param_3;
  if (*(short *)(param_3 + 4) == 0) {
    if (*(char *)(param_3 + 7) == -5) {
      CTkMsgWinData::AddErr(_g_pMsgWinData,0xa2);
    }
    else if (*(char *)(param_3 + 7) == -3) {
      CTkMsgWinData::AddErr(_g_pMsgWinData,0x99);
    }
    else {
      CTkMsgWinData::AddErr(_g_pMsgWinData,0x9a);
    }
  }
  else if (*(char *)(param_3 + 7) == '\0') {
    CTkMsgWinData::AddErr(_g_pMsgWinData,0x80);
  }
  else {
    lVar1 = (long)*(char *)(param_3 + 7);
    if (lVar1 < 0) {
      lVar1 = (long)-(int)*(char *)(param_3 + 7);
    }
    memset(auStack_80,0,0x50);
    if (lVar1 < 2) {
      uStack_78 = 0xa6;
    }
    else {
      uStack_78 = 0xa5;
      uStack_70 = (undefined4)lVar1;
    }
    uStack_74 = (uint)*(ushort *)(iStack_10 + 4);
    PutSystemMessage__FP6SYSMES(auStack_80);
    if (*(char *)(iStack_10 + 7) < '\0') {
      CTkMsgWinData::AddErr(_g_pMsgWinData,0x82);
    }
  }
  return 1;
}



// ---------------------------------------------------------------------------
// RecvGuildSell
// RecvGuildSell(GC_ZONE *, GP_GAME_PACKET_HEAD *, _GP_GUILD_TRADE *)
//   symbol: RecvGuildSell__FP7GC_ZONEP19GP_GAME_PACKET_HEADP15_GP_GUILD_TRADE
//   rva:    0x003667f0  size: 288 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndGuild.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined4
RecvGuildSell__FP7GC_ZONEP19GP_GAME_PACKET_HEADP15_GP_GUILD_TRADE
          (undefined8 pData,undefined8 param_2,int param_3)

{
  long lVar1;
  undefined1 auStack_80 [8];
  undefined2 uStack_78;
  uint uStack_74;
  undefined4 uStack_70;
  int iStack_10;
  
  iStack_10 = param_3;
  if (*(short *)(param_3 + 4) == 0) {
    CTkMsgWinData::AddErr(_g_pMsgWinData,0x9a);
  }
  else if (*(char *)(param_3 + 7) == '\0') {
    CTkMsgWinData::AddErr(_g_pMsgWinData,0x81);
  }
  else {
    lVar1 = (long)*(char *)(param_3 + 7);
    if (lVar1 < 0) {
      lVar1 = (long)-(int)*(char *)(param_3 + 7);
    }
    memset(auStack_80,0,0x50);
    if (lVar1 < 2) {
      uStack_78 = 0xa8;
    }
    else {
      uStack_78 = 0xa7;
      uStack_70 = (undefined4)lVar1;
    }
    uStack_74 = (uint)*(ushort *)(iStack_10 + 4);
    PutSystemMessage__FP6SYSMES(auStack_80);
    if (*(char *)(iStack_10 + 7) < '\0') {
      CTkMsgWinData::AddErr(_g_pMsgWinData,0x83);
    }
  }
  return 1;
}



// ---------------------------------------------------------------------------
// DispFilter
// YkWndGuildBuyCtrl::DispFilter(GC_ITEM_DATA *, CTkItemDataMenber *)
//   symbol: DispFilter__17YkWndGuildBuyCtrlFP12GC_ITEM_DATAP17CTkItemDataMenber
//   rva:    0x00366910  size: 308 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndGuild.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

undefined8
YkWndGuildBuyCtrl::DispFilter
          (YkWndGuildBuyCtrl *this,GC_ITEM_DATA *pID,CTkItemDataMenber *pIDM)

{
  long lVar1;
  
  if ((*(int *)(pIDM + 0xc5c) != 0) && (**(short **)(pIDM + 0xc5c) != 0)) {
    lVar1 = CTkEquip::IsEquipmentNo(_g_pTkEquip,*(ushort *)pID);
    if (lVar1 != 0) {
      return 0x80509050;
    }
    lVar1 = CTkEquip::CanEquipment(_g_pTkEquip,pIDM);
    if (lVar1 != 0) {
      return 0x80409090;
    }
  }
  if ((*(int *)(pIDM + 0xc08) != 0) && (**(short **)(pIDM + 0xc08) == 7)) {
    lVar1 = KaMenuMagicCheckHave__FPUc(*(undefined4 *)(pIDM + 0xc20));
    if (lVar1 != 0) {
      return 0x80509050;
    }
    lVar1 = KaMenuMagicCheckUse__FPUc(*(undefined4 *)(pIDM + 0xc20));
    if (lVar1 != 0) {
      return 0x80409090;
    }
  }
  return 0x80808080;
}



// ---------------------------------------------------------------------------
// MakeList
// YkWndGuildBuyCtrl::MakeList(YkWndList *, int)
//   symbol: MakeList__17YkWndGuildBuyCtrlFP9YkWndListi
//   rva:    0x00366a50  size: 932 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndGuild.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void YkWndGuildBuyCtrl::MakeList(YkWndGuildBuyCtrl *this,YkWndList *owner,int money)

{
  short sVar1;
  int iVar2;
  undefined2 uVar3;
  undefined4 uVar4;
  undefined8 uVar5;
  long lVar6;
  long lVar7;
  ulong uVar8;
  YkWndListItem *this_00;
  ulong uVar9;
  ushort auStack_60 [22];
  ushort *puStack_34;
  YkWndGuildBuyCtrl *pYStack_30;
  YkWndList *pYStack_20;
  int iStack_10;
  
  pYStack_30 = this;
  pYStack_20 = owner;
  iStack_10 = money;
  (**(code **)(*(int *)&this->field_0xc + 8))();
  uVar3 = gcGuildMaxList();
  *(undefined2 *)&pYStack_30->field_0x2 = uVar3;
  if (*(short *)&pYStack_30->field_0x2 < 1) {
    YkWndList::SetItem(pYStack_20);
  }
  else {
    if (*(int *)&pYStack_30->field_0x4 != 0) {
      if (*(int *)&pYStack_30->field_0x4 != 0) {
        __dla__FPv(*(int *)&pYStack_30->field_0x4 + -0x10);
      }
      *(undefined4 *)&pYStack_30->field_0x4 = 0;
    }
    if (*(int *)&pYStack_30->field_0x4 == 0) {
      sVar1 = *(short *)&pYStack_30->field_0x2;
      uVar5 = __nwa__FUi(sVar1 * 0x70 + 0x10);
      uVar4 = __construct_new_array(uVar5,0x3d0790,0,0x70,sVar1);
      *(undefined4 *)&pYStack_30->field_0x4 = uVar4;
    }
    *(ushort *)pYStack_30 = 0;
    for (uVar9 = 0; (long)uVar9 < (long)*(short *)&pYStack_30->field_0x2;
        uVar9 = (ulong)((int)uVar9 + 1)) {
      lVar6 = gcGuildGetList(0,uVar9 & 0xff,&puStack_34);
      if (lVar6 == 0) {
        this_00 = (YkWndListItem *)
                  (*(int *)&pYStack_30->field_0x4 + (short)*(ushort *)pYStack_30 * 0x70);
        YkWndListItem::Set(this_00,0,'\f',(void *)(uint)*puStack_34,0x80808080);
        lVar6 = YkIsHaveItem__F18SAVE_ITEM_CATEGORYUs(0,*puStack_34);
        if (lVar6 == 0) {
          uVar8 = 0x80808080;
        }
        else {
          uVar8 = 0x80606060;
        }
        iVar2 = *(int *)(puStack_34 + 2);
        YkWndListItem::Set
                  (this_00,2,'\x06',(void *)((uint)((ulong)((long)iVar2 << 0x21) >> 0x21) + 1),uVar8
                  );
        this_00->m_user = puStack_34;
        lVar6 = CTkItemData::GetItemDataMenber(_g_pTkItemData,(uint)*puStack_34);
        if (lVar6 != 0) {
          lVar7 = CTkItemData::IsLoaded
                            (_g_pTkItemData,(CTkItemDataMenber *)lVar6);
          if (lVar7 != 0) {
            auStack_60[0] = *puStack_34;
            uVar8 = (**(code **)(*(int *)&pYStack_30->field_0xc + 0x24))
                              (pYStack_30,auStack_60,lVar6);
            if ((pYStack_30->m_select != '\0') &&
               ((ushort)pYStack_30->m_selectidx == *(ushort *)pYStack_30)) {
              uVar8 = 0x80204080;
            }
            if (((long)iStack_10 < (long)((long)iVar2 & 0x7fffffffU)) ||
               ((char)puStack_34[1] == '\0')) {
              uVar8 = 0x80505050;
            }
            YkWndListItem::Set
                      (this_00,1,'\x01',*(void **)((CTkItemDataMenber *)lVar6 + 0xc20),uVar8);
          }
        }
        *(ushort *)pYStack_30 = *(ushort *)pYStack_30 + 1;
      }
    }
    YkWndList::SetItem
              (pYStack_20,*(undefined4 *)&pYStack_30->field_0x4,*(ushort *)pYStack_30);
  }
  return;
}



// ---------------------------------------------------------------------------
// OnCalc
// YkWndGuildBuyCtrl::OnCalc(char, unsigned char)
//   symbol: OnCalc__17YkWndGuildBuyCtrlFcUc
//   rva:    0x00366e00  size: 312 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndGuild.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void YkWndGuildBuyCtrl::OnCalc(YkWndGuildBuyCtrl *this,char isActive,byte idx)

{
  ushort *puVar1;
  
  if ((((isActive != '\0') && (_g_pTkItemInfo != (CTkItemInfo *)0x0)) && (*(int *)&this->field_0x4 != 0)
      ) && ((short)(ushort)idx < *(short *)this)) {
    puVar1 = *(ushort **)(*(int *)&this->field_0x4 + (uint)idx * 0x70 + 0x68);
    if (*(int *)&_g_pTkItemInfo->field_0x8 == 0) {
      CTkItemInfo::Open(_g_pTkItemInfo,1,'\x01','\0');
    }
    if (puVar1 == (ushort *)0x0) {
      CTkItemInfo::SetItemInfo(_g_pTkItemInfo);
    }
    else {
      CTkItemInfo::SetItemInfo(_g_pTkItemInfo,*puVar1,0,0);
    }
  }
  return;
}



// ---------------------------------------------------------------------------
// GBuyYnCallBack
// GBuyYnCallBack(void *, char)
//   symbol: GBuyYnCallBack__FPvc
//   rva:    0x00366f40  size: 144 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndGuild.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void GBuyYnCallBack__FPvc(undefined2 *user,char yes)

{
  if ((yes != '\0') && (-1 < (int)_g_buynum)) {
    gcGuildTrade(0,*user,0,_g_buynum & 0xff);
  }
  *(undefined1 *)(_g_pGuildBuyCtrl + 0x10) = 0;
  CTkMenuMng::ActiveDrawMenu
            ((CTkMenuMng *)&g_TkMenuMng,*(CTkMenuCtrlData **)(_g_pYkWndShop + 8),'\0');
  return;
}



// ---------------------------------------------------------------------------
// GBuyCallBack
// GBuyCallBack(int, void *)
//   symbol: GBuyCallBack__FiPv
//   rva:    0x00366fd0  size: 124 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndGuild.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void GBuyCallBack__FiPv(int num)

{
  if (num < 1) {
    _g_buynum = -1;
    *(undefined1 *)(_g_pGuildBuyCtrl + 0x10) = 0;
  }
  else {
    _g_buynum = num;
    YkWndYesno::Open(_g_pYkWndShopBuyYn);
  }
  return;
}



// ---------------------------------------------------------------------------
// OnOK
// YkWndGuildBuyCtrl::OnOK(unsigned char, int)
//   symbol: OnOK__17YkWndGuildBuyCtrlFUci
//   rva:    0x00367050  size: 516 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndGuild.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

undefined4 YkWndGuildBuyCtrl::OnOK(YkWndGuildBuyCtrl *this,byte idx,int money)

{
  ushort *puVar1;
  int iVar2;
  uint arg2_00;
  long lVar3;
  long lVar4;
  ulong uVar5;
  uint uVar6;
  
  if ((*(int *)&this->field_0x4 != 0) && ((short)(ushort)idx < *(short *)this)) {
    puVar1 = *(ushort **)(*(int *)&this->field_0x4 + (uint)idx * 0x70 + 0x68);
    iVar2 = *(int *)(puVar1 + 2);
    uVar5 = (long)iVar2 & 0x7fffffff;
    if (((long)uVar5 <= (long)money) &&
       (((char)puVar1[1] != '\0' &&
        (lVar3 = CTkItemData::GetItemDataMenber(_g_pTkItemData,(uint)*puVar1), lVar3 != 0)))) {
      lVar4 = CTkItemData::IsLoaded
                        (_g_pTkItemData,(CTkItemDataMenber *)lVar3);
      if (lVar4 != 0) {
        this->m_select = '\x01';
        this->m_selectidx = idx;
        arg2_00 = (uint)**(ushort **)((CTkItemDataMenber *)lVar3 + 0xc14);
        uVar6 = arg2_00;
        if ((uVar5 != 0) &&
           (uVar6 = money / (int)(uint)((ulong)((long)iVar2 << 0x21) >> 0x21), uVar5 == 0)) {
          trap(7);
        }
        if ((int)uVar6 < (int)arg2_00) {
          arg2_00 = uVar6;
        }
        if ((int)(uint)(byte)puVar1[1] < (int)arg2_00) {
          arg2_00 = (uint)(byte)puVar1[1];
        }
        if (arg2_00 != 0) {
          CTkItemCtrl::Open(_g_pTkItemCtrl,1,arg2_00);
          return 1;
        }
        return 0;
      }
    }
  }
  return 0;
}



// ---------------------------------------------------------------------------
// MakeList
// YkWndGuildSellListCtrl::MakeList(YkWndList *, int)
//   symbol: MakeList__22YkWndGuildSellListCtrlFP9YkWndListi
//   rva:    0x00367260  size: 916 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndGuild.cpp
// ---------------------------------------------------------------------------


/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void YkWndGuildSellListCtrl::MakeList
               (YkWndGuildSellListCtrl *this,YkWndList *owner,int arg2)

{
  short sVar1;
  undefined4 uVar2;
  void *arg3;
  undefined8 uVar3;
  long lVar4;
  YkWndListItem *pYVar5;
  ulong uVar6;
  ulong arg4;
  ushort *puStack_34;
  YkWndGuildSellListCtrl *pYStack_30;
  YkWndList *pYStack_20;
  
  pYStack_30 = this;
  pYStack_20 = owner;
  (**(code **)(*(int *)&this->field_0xc + 8))(this,owner,arg2);
  sVar1 = gcGuildMaxList(1);
  *(short *)&pYStack_30->field_0x2 = sVar1 + 1;
  if (*(short *)&pYStack_30->field_0x2 < 1) {
    YkWndList::SetItem(pYStack_20);
  }
  else {
    if (*(int *)&pYStack_30->field_0x4 != 0) {
      if (*(int *)&pYStack_30->field_0x4 != 0) {
        __dla__FPv(*(int *)&pYStack_30->field_0x4 + -0x10);
      }
      *(undefined4 *)&pYStack_30->field_0x4 = 0;
    }
    if (*(int *)&pYStack_30->field_0x4 == 0) {
      sVar1 = *(short *)&pYStack_30->field_0x2;
      uVar3 = __nwa__FUi(sVar1 * 0x70 + 0x10);
      uVar2 = __construct_new_array(uVar3,0x3d0790,0,0x70,sVar1);
      *(undefined4 *)&pYStack_30->field_0x4 = uVar2;
    }
    *(short *)pYStack_30 = 0;
    pYVar5 = (YkWndListItem *)(*(int *)&pYStack_30->field_0x4 + *(short *)pYStack_30 * 0x70);
    arg3 = (void *)XiStrGet(9,0x2c);
    YkWndListItem::Set(pYVar5,1,'\x01',arg3,0x80808080);
    pYVar5->m_user = (void *)0x1;
    *(short *)pYStack_30 = *(short *)pYStack_30 + 1;
    for (uVar6 = 0; (long)uVar6 < (long)*(short *)&pYStack_30->field_0x2;
        uVar6 = (ulong)((int)uVar6 + 1)) {
      lVar4 = gcGuildGetList(1,uVar6 & 0xff,&puStack_34);
      if ((lVar4 == 0) &&
         (pYVar5 = (YkWndListItem *)(*(int *)&pYStack_30->field_0x4 + *(short *)pYStack_30 * 0x70),
         (*(uint *)(puStack_34 + 2) & 0x80000000) == 0)) {
        lVar4 = YkIsHaveItem__F18SAVE_ITEM_CATEGORYUs(0,*puStack_34);
        if (lVar4 == 0) {
          arg4 = 0x80505050;
        }
        else {
          arg4 = 0x80808080;
        }
        if (*(byte *)((int)puStack_34 + 3) <= (byte)puStack_34[1]) {
          arg4 = 0x80505050;
        }
        YkWndListItem::Set(pYVar5,1,'\x0e',(void *)(uint)*puStack_34,arg4);
        YkWndListItem::Set(pYVar5,0,'\f',(void *)(uint)*puStack_34,0x80808080);
        YkWndListItem::Set
                  (pYVar5,2,'\x06',
                   (void *)((uint)((ulong)((long)*(int *)(puStack_34 + 2) << 0x21) >> 0x21) + 1),
                   0x80808080);
        pYVar5->m_user = puStack_34;
        *(short *)pYStack_30 = *(short *)pYStack_30 + 1;
      }
    }
    YkWndList::SetItem
              (pYStack_20,*(undefined4 *)&pYStack_30->field_0x4,*(short *)pYStack_30);
  }
  return;
}



// ---------------------------------------------------------------------------
// OnCalc
// YkWndGuildSellListCtrl::OnCalc(char, unsigned char)
//   symbol: OnCalc__22YkWndGuildSellListCtrlFcUc
//   rva:    0x00367600  size: 324 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndGuild.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void YkWndGuildSellListCtrl::OnCalc(YkWndGuildSellListCtrl *this,char isActive,byte idx)

{
  ushort *puVar1;
  
  if ((((isActive != '\0') && (_g_pTkItemInfo != (CTkItemInfo *)0x0)) && (*(int *)&this->field_0x4 != 0)
      ) && ((short)(ushort)idx < *(short *)this)) {
    puVar1 = *(ushort **)(*(int *)&this->field_0x4 + (uint)idx * 0x70 + 0x68);
    if (*(int *)&_g_pTkItemInfo->field_0x8 == 0) {
      CTkItemInfo::Open(_g_pTkItemInfo,1,'\x01','\0');
    }
    if ((puVar1 == (ushort *)0x0) || (puVar1 == (ushort *)0x1)) {
      CTkItemInfo::SetItemInfo(_g_pTkItemInfo);
    }
    else {
      CTkItemInfo::SetItemInfo(_g_pTkItemInfo,*puVar1,0,0);
    }
  }
  return;
}



// ---------------------------------------------------------------------------
// OnOK
// YkWndGuildSellListCtrl::OnOK(unsigned char, int)
//   symbol: OnOK__22YkWndGuildSellListCtrlFUci
//   rva:    0x00367750  size: 424 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndGuild.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

undefined4 YkWndGuildSellListCtrl::OnOK(YkWndGuildSellListCtrl *this,byte idx,int arg2)

{
  undefined2 *puVar1;
  undefined4 uVar2;
  long lVar3;
  
  if ((*(int *)&this->field_0x4 == 0) || (*(short *)this <= (short)(ushort)idx)) {
    uVar2 = 0;
  }
  else {
    puVar1 = *(undefined2 **)(*(int *)&this->field_0x4 + (uint)idx * 0x70 + 0x68);
    if (puVar1 == (undefined2 *)0x0) {
      uVar2 = 0;
    }
    else if (puVar1 == (undefined2 *)0x1) {
      this->m_select = '\x01';
      this->m_selectidx = idx;
      *(undefined2 *)(_g_pGuildSellCtrl + 0x12) = 0;
      YkWndShop::Open(_g_pYkWndShop,_g_pGuildSellCtrl);
      uVar2 = 1;
    }
    else {
      lVar3 = YkIsHaveItem__F18SAVE_ITEM_CATEGORYUs(0,*puVar1,arg2);
      if (lVar3 == 0) {
        uVar2 = 0;
      }
      else if (*(byte *)(puVar1 + 1) < *(byte *)((int)puVar1 + 3)) {
        this->m_select = '\x01';
        this->m_selectidx = idx;
        *(undefined2 *)(_g_pGuildSellCtrl + 0x12) = *puVar1;
        YkWndShop::Open(_g_pYkWndShop,_g_pGuildSellCtrl);
        uVar2 = 1;
      }
      else {
        uVar2 = 0;
      }
    }
  }
  return uVar2;
}



// ---------------------------------------------------------------------------
// SearchSell
// YkWndGuildSellCtrl::SearchSell(unsigned short)
//   symbol: SearchSell__18YkWndGuildSellCtrlFUs
//   rva:    0x00367900  size: 160 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndGuild.cpp
// ---------------------------------------------------------------------------


/* WARNING: Unknown calling convention -- yet parameter storage is locked */

ushort * YkWndGuildSellCtrl::SearchSell(YkWndGuildSellCtrl *this,ushort itemno)

{
  int iVar1;
  long lVar2;
  uint uVar3;
  ushort *apuStack_24 [5];
  ushort uStack_10;
  
  uStack_10 = itemno;
  iVar1 = gcGuildMaxList(1);
  uVar3 = 0;
  while( true ) {
    if (iVar1 <= (int)uVar3) {
      return (ushort *)0x0;
    }
    lVar2 = gcGuildGetList(1,uVar3 & 0xff,apuStack_24);
    if ((lVar2 == 0) && (*apuStack_24[0] == uStack_10)) break;
    uVar3 = uVar3 + 1;
  }
  return apuStack_24[0];
}



// ---------------------------------------------------------------------------
// DispFilter
// YkWndGuildSellCtrl::DispFilter(GC_ITEM_DATA *, CTkItemDataMenber *)
//   symbol: DispFilter__18YkWndGuildSellCtrlFP12GC_ITEM_DATAP17CTkItemDataMenber
//   rva:    0x003679a0  size: 508 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndGuild.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

undefined8
YkWndGuildSellCtrl::DispFilter
          (YkWndGuildSellCtrl *this,GC_ITEM_DATA *pID,CTkItemDataMenber *pIDM)

{
  short sVar1;
  undefined8 uVar2;
  long lVar3;
  
  if ((this->m_itemno == 0) || (this->m_itemno == *(ushort *)pID)) {
    sVar1 = *(short *)pID;
    if ((sVar1 == 0x203) || ((sVar1 == 0x202 || (sVar1 == 0x201)))) {
      uVar2 = 0x80505050;
    }
    else if (pID[8] == (GC_ITEM_DATA)0x19) {
      uVar2 = 0x80505050;
    }
    else {
      lVar3 = CTkEquip::IsEquipment(_g_pTkEquip,(byte)pID[2]);
      if (lVar3 == 0) {
        if ((**(ushort **)(pIDM + 0xc10) & 0x1000) == 0) {
          lVar3 = YkWndGuildSellCtrl::SearchSell(this,*(ushort *)pID);
          if (lVar3 == 0) {
            uVar2 = 0x80505050;
          }
          else if ((this->m_select == '\0') || ((GC_ITEM_DATA)this->m_selectidx != pID[2])) {
            uVar2 = 0x80808080;
          }
          else {
            uVar2 = 0x80204080;
          }
        }
        else {
          uVar2 = 0x80505050;
        }
      }
      else {
        uVar2 = 0x80505050;
      }
    }
  }
  else {
    uVar2 = 0;
  }
  return uVar2;
}



// ---------------------------------------------------------------------------
// MakeList
// YkWndGuildSellCtrl::MakeList(YkWndList *, int)
//   symbol: MakeList__18YkWndGuildSellCtrlFP9YkWndListi
//   rva:    0x00367ba0  size: 996 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndGuild.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void YkWndGuildSellCtrl::MakeList(YkWndGuildSellCtrl *this,YkWndList *owner,int arg2)

{
  short sVar1;
  ulong uVar2;
  undefined8 uVar3;
  long lVar4;
  long lVar5;
  long lVar6;
  ushort *arg3;
  YkWndListItem *this_00;
  long lVar7;
  uint uVar8;
  ushort *puStack_44;
  ushort *puStack_40;
  int iStack_3c;
  undefined4 uStack_38;
  ushort uStack_34;
  byte bStack_32;
  byte bStack_31;
  YkWndGuildSellCtrl *pYStack_30;
  YkWndList *pYStack_20;
  
  pYStack_30 = this;
  pYStack_20 = owner;
  (**(code **)(*(int *)&this->field_0xc + 8))(this,owner,arg2);
  *(undefined2 *)&pYStack_30->field_0x2 = 0;
  uVar2 = gcZoneFlg();
  if (((uVar2 & 0x1000) != 0) || (uVar2 = gcZoneFlg(), (uVar2 & 0x800) != 0)) {
    bStack_32 = (&_g_pKmItemProperty->m_ItemNum)[*(int *)&_g_pKmItemProperty->m_SortKey];
    *(ushort *)&pYStack_30->field_0x2 = (ushort)bStack_32;
    bStack_31 = bStack_32;
  }
  if (*(short *)&pYStack_30->field_0x2 == 0) {
    YkWndList::SetItem(pYStack_20);
  }
  else {
    if (*(int *)&pYStack_30->field_0x4 != 0) {
      if (*(int *)&pYStack_30->field_0x4 != 0) {
        __dla__FPv(*(int *)&pYStack_30->field_0x4 + -0x10);
      }
      *(undefined4 *)&pYStack_30->field_0x4 = 0;
    }
    if (*(int *)&pYStack_30->field_0x4 == 0) {
      sVar1 = *(short *)&pYStack_30->field_0x2;
      uVar3 = __nwa__FUi(sVar1 * 0x70 + 0x10);
      uStack_38 = __construct_new_array(uVar3,0x3d0790,0,0x70,sVar1);
      *(undefined4 *)&pYStack_30->field_0x4 = uStack_38;
    }
    *(short *)pYStack_30 = 0;
    for (lVar7 = 0; lVar7 < *(short *)&pYStack_30->field_0x2; lVar7 = (long)((int)lVar7 + 1)) {
      lVar4 = KmItem::ItemGet(_g_pKmItemProperty,(byte)lVar7);
      if (lVar4 != 0) {
        this_00 = (YkWndListItem *)(*(int *)&pYStack_30->field_0x4 + *(short *)pYStack_30 * 0x70);
        arg3 = (ushort *)lVar4;
        if (((char)arg3[1] != '\0') &&
           (lVar5 = CTkItemData::GetItemDataMenber(_g_pTkItemData,(uint)*arg3), lVar5 != 0)) {
          lVar6 = CTkItemData::IsLoaded
                            (_g_pTkItemData,(CTkItemDataMenber *)lVar5);
          if ((lVar6 != 0) &&
             (uVar2 = (**(code **)(*(int *)&pYStack_30->field_0xc + 0x24))(pYStack_30,lVar4,lVar5),
             uVar2 != 0)) {
            YkWndListItem::Set(this_00,0,'\r',arg3,0x80808080);
            YkWndListItem::Set
                      (this_00,1,'\x01',*(void **)((CTkItemDataMenber *)lVar5 + 0xc20),uVar2);
            uStack_34 = *arg3;
            iStack_3c = gcGuildMaxList(1);
            for (uVar8 = 0; (int)uVar8 < iStack_3c; uVar8 = uVar8 + 1) {
              lVar4 = gcGuildGetList(1,uVar8 & 0xff,&puStack_40);
              if ((lVar4 == 0) && (*puStack_40 == uStack_34)) {
                puStack_44 = puStack_40;
                goto LAB_00467eb0;
              }
            }
            puStack_44 = (ushort *)0x0;
LAB_00467eb0:
            if (puStack_44 != (ushort *)0x0) {
              YkWndListItem::Set
                        (this_00,2,'\x06',
                         (void *)((uint)((ulong)((long)*(int *)(puStack_44 + 2) << 0x21) >> 0x21) +
                                 1),0x80808080);
            }
            this_00->m_user = arg3;
            *(short *)pYStack_30 = *(short *)pYStack_30 + 1;
          }
        }
      }
    }
    YkWndList::SetItem
              (pYStack_20,*(undefined4 *)&pYStack_30->field_0x4,*(short *)pYStack_30);
  }
  return;
}



// ---------------------------------------------------------------------------
// GSellYnCallBack
// GSellYnCallBack(void *, char)
//   symbol: GSellYnCallBack__FPvc
//   rva:    0x00367f90  size: 164 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndGuild.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void GSellYnCallBack__FPvc(undefined2 *user,char yes)

{
  if (((yes != '\0') && (-1 < (int)_g_sellnum)) && ((int)_g_sellnum <= *(int *)(user + 2))) {
    gcGuildTrade(1,*user,*(undefined1 *)(user + 1),_g_sellnum & 0xff);
  }
  *(undefined1 *)(_g_pGuildSellCtrl + 0x10) = 0;
  CTkMenuMng::ActiveDrawMenu
            ((CTkMenuMng *)&g_TkMenuMng,*(CTkMenuCtrlData **)(_g_pYkWndShop + 8),'\0');
  return;
}



// ---------------------------------------------------------------------------
// GSellCallBack
// GSellCallBack(int, void *)
//   symbol: GSellCallBack__FiPv
//   rva:    0x00368040  size: 124 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndGuild.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void GSellCallBack__FiPv(int num)

{
  if (num < 1) {
    _g_sellnum = -1;
    *(undefined1 *)(_g_pGuildSellCtrl + 0x10) = 0;
  }
  else {
    _g_sellnum = num;
    YkWndYesno::Open(_g_pYkWndShopSellYn);
  }
  return;
}



// ---------------------------------------------------------------------------
// OnOK
// YkWndGuildSellCtrl::OnOK(unsigned char, int)
//   symbol: OnOK__18YkWndGuildSellCtrlFUci
//   rva:    0x003680c0  size: 428 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndGuild.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

undefined4 YkWndGuildSellCtrl::OnOK(YkWndGuildSellCtrl *this,byte idx,int arg2)

{
  ushort *puVar1;
  undefined4 uVar2;
  long lVar3;
  long lVar4;
  
  if ((*(int *)&this->field_0x4 == 0) || (*(short *)this <= (short)(ushort)idx)) {
    uVar2 = 0;
  }
  else {
    puVar1 = *(ushort **)(*(int *)&this->field_0x4 + (uint)idx * 0x70 + 0x68);
    if (puVar1 == (ushort *)0x0) {
      uVar2 = 0;
    }
    else {
      lVar3 = CTkItemData::GetItemDataMenber(_g_pTkItemData,(uint)*puVar1);
      if ((lVar3 == 0) ||
         (lVar4 = CTkItemData::IsLoaded
                            (_g_pTkItemData,(CTkItemDataMenber *)lVar3), lVar4 == 0)) {
        uVar2 = 0;
      }
      else {
        lVar3 = (**(code **)(*(int *)&this->field_0xc + 0x24))(this,puVar1,lVar3);
        if ((lVar3 == 0) || (lVar3 == 0x80505050)) {
          uVar2 = 0;
        }
        else {
          this->m_select = '\x01';
          this->m_selectidx = (byte)puVar1[1];
          CTkItemCtrl::Open(_g_pTkItemCtrl,1,*(int *)(puVar1 + 2));
          uVar2 = 1;
        }
      }
    }
  }
  return uVar2;
}



// ---------------------------------------------------------------------------
// OnCancel
// YkWndGuildSellCtrl::OnCancel(void)
//   symbol: OnCancel__18YkWndGuildSellCtrlFv
//   rva:    0x00368270  size: 44 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndGuild.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

undefined8 YkWndGuildSellCtrl::OnCancel(YkWndGuildSellCtrl *this)

{
  YkWndShop::Open(_g_pYkWndShop,_g_pGuildSellListCtrl);
  return 0;
}



// ---------------------------------------------------------------------------
// 
// YkWndGuildMain::YkWndGuildMain(void)
//   symbol: __ct__14YkWndGuildMainFv
//   rva:    0x003682a0  size: 540 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndGuild.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

YkWndGuildMain * YkWndGuildMain::YkWndGuildMain(YkWndGuildMain *this)

{
  long lVar1;
  
  CTkObject::CTkObject((CTkObject *)this);
  *(undefined1 **)&this->field_0x4 = __vt__16CTkMenuPrimitive;
  *(undefined2 *)&this->field_0xe = 0xffff;
  *(undefined4 *)&this->field_0x8 = 0;
  (**(code **)(*(int *)&this->field_0x4 + 0xc))();
  this->field_0xc = 1;
  *(undefined1 **)&this->field_0x4 = __vt__14YkWndGuildMain;
  if (_g_pGuildBuyCtrl == 0) {
    lVar1 = __nw__FUi(0x14);
    _g_pGuildBuyCtrl = 0;
    if (lVar1 != 0) {
      _g_pGuildBuyCtrl = (int)lVar1;
      *(undefined1 **)(_g_pGuildBuyCtrl + 0xc) = __vt__13YkWndShopCtrl;
      *(undefined4 *)(_g_pGuildBuyCtrl + 4) = 0;
      *(undefined1 *)(_g_pGuildBuyCtrl + 8) = 0;
      *(undefined1 **)(_g_pGuildBuyCtrl + 0xc) = __vt__17YkWndGuildBuyCtrl;
      *(undefined4 *)(_g_pGuildBuyCtrl + 4) = 0;
    }
  }
  if (_g_pGuildSellListCtrl == 0) {
    lVar1 = __nw__FUi(0x14);
    _g_pGuildSellListCtrl = 0;
    if (lVar1 != 0) {
      _g_pGuildSellListCtrl = (int)lVar1;
      *(undefined1 **)(_g_pGuildSellListCtrl + 0xc) = __vt__13YkWndShopCtrl;
      *(undefined4 *)(_g_pGuildSellListCtrl + 4) = 0;
      *(undefined1 *)(_g_pGuildSellListCtrl + 8) = 0;
      *(undefined1 **)(_g_pGuildSellListCtrl + 0xc) = __vt__22YkWndGuildSellListCtrl;
      *(undefined4 *)(_g_pGuildSellListCtrl + 4) = 0;
      *(undefined1 *)(_g_pGuildSellListCtrl + 0x10) = 0;
    }
  }
  if (_g_pGuildSellCtrl == 0) {
    lVar1 = __nw__FUi(0x14);
    _g_pGuildSellCtrl = 0;
    if (lVar1 != 0) {
      _g_pGuildSellCtrl = (int)lVar1;
      *(undefined1 **)(_g_pGuildSellCtrl + 0xc) = __vt__13YkWndShopCtrl;
      *(undefined4 *)(_g_pGuildSellCtrl + 4) = 0;
      *(undefined1 *)(_g_pGuildSellCtrl + 8) = 0;
      *(undefined1 **)(_g_pGuildSellCtrl + 0xc) = __vt__18YkWndGuildSellCtrl;
      *(undefined4 *)(_g_pGuildSellCtrl + 4) = 0;
    }
  }
  return this;
}



// ---------------------------------------------------------------------------
// 
// YkWndGuildMain::~YkWndGuildMain(void)
//   symbol: __dt__14YkWndGuildMainFv
//   rva:    0x003684c0  size: 476 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndGuild.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

YkWndGuildMain * YkWndGuildMain::~YkWndGuildMain(YkWndGuildMain *this)

{
  int iVar1;
  short in_a1_lo;
  
  if (this != (YkWndGuildMain *)0x0) {
    *(undefined1 **)&this->field_0x4 = __vt__14YkWndGuildMain;
    iVar1 = _g_pGuildBuyCtrl;
    if (_g_pGuildBuyCtrl != 0) {
      if (_g_pGuildBuyCtrl != 0) {
        *(undefined1 **)(_g_pGuildBuyCtrl + 0xc) = __vt__17YkWndGuildBuyCtrl;
        if (*(int *)(iVar1 + 4) != 0) {
          if (*(int *)(iVar1 + 4) != 0) {
            __dla__FPv(*(int *)(iVar1 + 4) + -0x10);
          }
          *(undefined4 *)(iVar1 + 4) = 0;
        }
        __dl__FPv(iVar1);
      }
      _g_pGuildBuyCtrl = 0;
    }
    iVar1 = _g_pGuildSellListCtrl;
    if (_g_pGuildSellListCtrl != 0) {
      if (_g_pGuildSellListCtrl != 0) {
        *(undefined1 **)(_g_pGuildSellListCtrl + 0xc) = __vt__22YkWndGuildSellListCtrl;
        if (*(int *)(iVar1 + 4) != 0) {
          if (*(int *)(iVar1 + 4) != 0) {
            __dla__FPv(*(int *)(iVar1 + 4) + -0x10);
          }
          *(undefined4 *)(iVar1 + 4) = 0;
        }
        __dl__FPv(iVar1);
      }
      _g_pGuildSellListCtrl = 0;
    }
    iVar1 = _g_pGuildSellCtrl;
    if (_g_pGuildSellCtrl != 0) {
      if (_g_pGuildSellCtrl != 0) {
        *(undefined1 **)(_g_pGuildSellCtrl + 0xc) = __vt__18YkWndGuildSellCtrl;
        if (*(int *)(iVar1 + 4) != 0) {
          if (*(int *)(iVar1 + 4) != 0) {
            __dla__FPv(*(int *)(iVar1 + 4) + -0x10);
          }
          *(undefined4 *)(iVar1 + 4) = 0;
        }
        __dl__FPv(iVar1);
      }
      _g_pGuildSellCtrl = 0;
    }
    if (this != (YkWndGuildMain *)0x0) {
      *(undefined1 **)&this->field_0x4 = __vt__16CTkMenuPrimitive;
      CTkObject::~CTkObject((CTkObject *)this);
    }
    if (0 < in_a1_lo) {
      __dl__FPv(this);
    }
  }
  return this;
}



// ---------------------------------------------------------------------------
// OnDrawCalc
// YkWndGuildMain::OnDrawCalc(char)
//   symbol: OnDrawCalc__14YkWndGuildMainFc
//   rva:    0x003686a0  size: 392 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndGuild.cpp
// ---------------------------------------------------------------------------


/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void YkWndGuildMain::OnDrawCalc(YkWndGuildMain *this,char arg1)

{
  uint uVar1;
  float fVar2;
  float fVar3;
  
  uVar1 = gcZoneActIndex(this,arg1);
  uVar1 = uVar1 & 0xffff;
  if ((uVar1 != 0) &&
     (fVar2 = *(float *)(*(int *)(&ActerBuffPtr + uVar1 * 4) + 0x10) - this->m_pos,
     fVar3 = *(float *)(*(int *)(&ActerBuffPtr + uVar1 * 4) + 0x18) - *(float *)&this->field_0x28,
     36.0 < fVar2 * fVar2 + fVar3 * fVar3)) {
    (**(code **)(*(int *)&this->field_0x4 + 0x20))(this,6,0);
  }
  return;
}



// ---------------------------------------------------------------------------
// OnKeyDown
// YkWndGuildMain::OnKeyDown(short, short)
//   symbol: OnKeyDown__14YkWndGuildMainFss
//   rva:    0x00368830  size: 372 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndGuild.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void YkWndGuildMain::OnKeyDown(int this,short idx,short param_3)

{
  long lVar1;
  
  if (idx == 6) {
    YkWndShop::Close(_g_pYkWndShop);
    CTkMenuMng::DestroyDrawMenu
              ((CTkMenuMng *)&g_TkMenuMng,*(CTkMenuCtrlData **)(this + 8),'\x01');
  }
  else if (idx == 5) {
    if (param_3 == 2) {
      lVar1 = gcGuildMaxList(1);
      if (lVar1 < 1) {
        lVar1 = gcGuildNewList(1);
        if (lVar1 == 0) {
          YkWndShop::Open(_g_pYkWndShop,_g_pGuildSellListCtrl);
        }
        else {
          YmSePlayBeep__Fv();
        }
      }
      else {
        YkWndShop::Open(_g_pYkWndShop,_g_pGuildSellListCtrl);
      }
    }
    else if (param_3 == 1) {
      lVar1 = gcGuildMaxList();
      if (lVar1 < 1) {
        lVar1 = gcGuildNewList();
        if (lVar1 == 0) {
          YkWndShop::Open(_g_pYkWndShop,_g_pGuildBuyCtrl);
        }
        else {
          YmSePlayBeep__Fv();
        }
      }
      else {
        YkWndShop::Open(_g_pYkWndShop,_g_pGuildBuyCtrl);
      }
    }
  }
  return;
}



// ---------------------------------------------------------------------------
// RecvGuildOpen
// YkWndGuildMain::RecvGuildOpen(GC_ZONE *, GP_GAME_PACKET_HEAD *, _GP_GUILD_OPEN *)
//   symbol: RecvGuildOpen__14YkWndGuildMainFP7GC_ZONEP19GP_GAME_PACKET_HEADP14_GP_GUILD_OPEN
//   rva:    0x003689b0  size: 860 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndGuild.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

undefined4
YkWndGuildMain::RecvGuildOpen
          (YkWndGuildMain *this,GC_ZONE *pData,GP_GAME_PACKET_HEAD *arg2,_GP_GUILD_OPEN *arg3)

{
  GP_GAME_PACKET_HEAD GVar1;
  int iVar2;
  int iVar3;
  uint uVar4;
  char *pcVar5;
  long lVar6;
  undefined8 uVar7;
  uint uVar8;
  uint unaff_s3_lo;
  uint uVar9;
  uint unaff_s7_lo;
  char acStack_140 [264];
  undefined4 *puStack_38;
  undefined4 *puStack_34;
  GP_GAME_PACKET_HEAD *pGStack_10;
  
  GVar1 = arg2[4];
  pGStack_10 = arg2;
  if (GVar1 == (GP_GAME_PACKET_HEAD)0x2) {
    if ((*(int *)(_g_pYkWndGuildMain + 8) != 0) || ((*(uint *)(arg2 + 8) & 0x80000000) == 0)) {
      uVar4 = *(uint *)(arg2 + 8);
      if ((uVar4 & 0x7fffffff) < 8) {
        pcVar5 = (char *)XiStrGet(10,0x1a,arg2,arg3);
        uVar7 = XiStrGet(0x11,uVar4 & 0x7fffffff);
        sprintf(acStack_140,pcVar5,uVar7);
        CTkMsgWinData::AddSystemString(_g_pMsgWinData,acStack_140);
      }
      (**(code **)(*(int *)(_g_pYkWndGuildMain + 4) + 0x20))(_g_pYkWndGuildMain,6);
    }
  }
  else if (GVar1 == (GP_GAME_PACKET_HEAD)0x1) {
    if ((*(int *)(_g_pYkWndGuildMain + 8) != 0) || ((*(uint *)(arg2 + 8) & 0x80000000) == 0)) {
      for (uVar4 = 0;
          (uVar8 = unaff_s3_lo, uVar9 = unaff_s3_lo, (int)uVar4 < 0x18 &&
          (uVar8 = uVar4, uVar9 = uVar4, (*(uint *)(arg2 + 8) & 1 << (uVar4 & 0x1f)) == 0));
          uVar4 = uVar4 + 1) {
      }
      for (; (uVar4 = unaff_s7_lo, (int)uVar8 < 0x18 &&
             (uVar4 = uVar8, (*(uint *)(arg2 + 8) & 1 << (uVar8 & 0x1f)) != 0)); uVar8 = uVar8 + 1)
      {
      }
      pcVar5 = (char *)XiStrGet(10,0x19,arg2,arg3);
      sprintf(acStack_140,pcVar5,uVar9,uVar4);
      CTkMsgWinData::AddSystemString(_g_pMsgWinData,acStack_140);
      (**(code **)(*(int *)(_g_pYkWndGuildMain + 4) + 0x20))(_g_pYkWndGuildMain,6);
    }
  }
  else {
    if (GVar1 != (GP_GAME_PACKET_HEAD)0x0) {
      (**(code **)(*(int *)(_g_pYkWndGuildMain + 4) + 0x20))(_g_pYkWndGuildMain,6);
      return 0;
    }
    lVar6 = CTkMenuMng::IsPropertyWindow((CTkMenuMng *)&g_TkMenuMng,0x20000);
    if ((lVar6 != 0) || (*(int *)(_g_pTkInputCtrl + 0x54) != 0)) {
      CTkMsgWinData::AddErrMsg(_g_pMsgWinData,3);
      return 0;
    }
    uVar4 = gcZoneActIndex();
    iVar3 = _g_pYkWndGuildMain;
    if ((uVar4 & 0xffff) != 0) {
      iVar2 = *(int *)(&ActerBuffPtr + (uVar4 & 0xffff) * 4);
      puStack_38 = (undefined4 *)(iVar2 + 0x10);
      *(undefined4 *)(_g_pYkWndGuildMain + 0x20) = *puStack_38;
      *(undefined4 *)(iVar3 + 0x24) = *(undefined4 *)(iVar2 + 0x14);
      *(undefined4 *)(iVar3 + 0x28) = *(undefined4 *)(iVar2 + 0x18);
      puStack_34 = puStack_38;
      CTkMenuMng::CreateDrawMenu((CTkMenuMng *)&g_TkMenuMng,_2579,'\x01','\0');
    }
  }
  return 1;
}

