// AUTOGENERATED by ffxi-decomp. Do not edit by hand.
// version: 972 (sha256=d4622c1cc4a3012c, image_base=0x00100000)
// source:  main/yk/ykWndImage.cpp
// functions: 16


// ---------------------------------------------------------------------------
// CheckMagnet
// YkWndImage::CheckMagnet(float)
//   symbol: CheckMagnet__10YkWndImageFf
//   rva:    0x002c97e0  size: 584 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndImage.cpp
// ---------------------------------------------------------------------------


/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void YkWndImage::CheckMagnet(YkWndImage *this,float pow)

{
  int iVar1;
  int iVar2;
  int iVar3;
  _YK_WNDITEM *p_Var4;
  _YK_WNDITEM *p_Var5;
  long lVar6;
  int iVar7;
  int iVar8;
  
  p_Var5 = (_YK_WNDITEM *)0x0;
  iVar1 = fptosi((float)(int)*(short *)&this->m_idiffx +
                 this->m_zx + (float)(int)*(short *)&this->m_cx / this->m_scale + 0.5);
  iVar2 = fptosi((float)(int)*(short *)&this->m_idiffy +
                 this->m_zy + (float)(int)*(short *)&this->m_cy / this->m_scale + 0.5);
  iVar3 = fptosi(pow * pow + 0.5);
  for (lVar6 = 0; lVar6 < *(short *)&this->m_itemmax; lVar6 = (long)((int)lVar6 + 1)) {
    p_Var4 = this->m_item + (int)lVar6;
    if (((((p_Var4->stat & 1U) != 0) && ((p_Var4->stat & 0x20U) == 0)) &&
        (iVar7 = *(short *)&p_Var4->x - iVar1, iVar8 = *(short *)&p_Var4->y - iVar2,
        iVar7 = iVar7 * iVar7 + iVar8 * iVar8, 0x18 < iVar7)) && (iVar7 < iVar3)) {
      p_Var5 = p_Var4;
      iVar3 = iVar7;
    }
  }
  if (p_Var5 != (_YK_WNDITEM *)0x0) {
    YkWndImage::SetPosAuto
              (this,(float)(int)*(short *)&p_Var5->x,(float)(int)*(short *)&p_Var5->y);
  }
  return;
}



// ---------------------------------------------------------------------------
// MovePos
// YkWndImage::MovePos(float, float, char)
//   symbol: MovePos__10YkWndImageFffc
//   rva:    0x002c9a30  size: 2028 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndImage.cpp
// ---------------------------------------------------------------------------


/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void YkWndImage::MovePos(YkWndImage *this,float dx,float dy,char zoom)

{
  short sVar1;
  short sVar2;
  undefined2 uVar3;
  long lVar4;
  long lVar5;
  int iVar6;
  float fVar7;
  float fVar8;
  float fStack_50;
  float fStack_4c;
  float fStack_48;
  float fStack_44;
  
  if ((((zoom != '\0') || ((*(ushort *)&this->m_stat & 0x100) == 0)) ||
      ((*(ushort *)&this->m_stat & 0x200) != 0)) || ((*(ushort *)&this->m_stat & 8) != 0)) {
    this->m_zx = this->m_zx + dx / this->m_scale;
    this->m_zy = this->m_zy + dy / this->m_scale;
    if ((*(ushort *)&this->m_stat & 0x200) != 0) {
      this->m_zx = this->m_zx + dx / this->m_scale;
      this->m_zy = this->m_zy + dy / this->m_scale;
    }
    if (this->m_image == (CShape **)0x0) {
      return;
    }
    goto LAB_003ca118;
  }
  fStack_50 = 0.0;
  fStack_4c = 0.0;
  fVar7 = (float)(int)*(short *)&this->m_cx + dx;
  fVar8 = (float)(int)*(short *)&this->m_cy + dy;
  lVar4 = fptosi(fVar7);
  lVar5 = fptosi(this->m_mincx);
  if (lVar4 < lVar5) {
LAB_003c9b7c:
    if (dx < 0.0) {
      fStack_48 = dx / this->m_scale - 0.5;
    }
    else {
      fStack_48 = dx / this->m_scale + 0.5;
    }
    sVar1 = fptosi(fStack_48);
    if ((float)(int)sVar1 < 0.0) {
      iVar6 = -(int)sVar1;
    }
    else {
      iVar6 = (int)sVar1;
    }
    if ((float)iVar6 <= 1.0) {
      if (dx < 0.0) {
        sVar1 = -1;
      }
      else {
        sVar1 = 1;
      }
    }
    *(short *)&this->m_cx = *(short *)&this->m_cx + sVar1;
  }
  else {
    lVar4 = fptosi(fVar7);
    lVar5 = fptosi(this->m_maxcx);
    if (lVar5 < lVar4) goto LAB_003c9b7c;
    uVar3 = fptosi(fVar7);
    *(undefined2 *)&this->m_cx = uVar3;
  }
  lVar4 = fptosi(fVar8);
  lVar5 = fptosi(this->m_mincy);
  if (lVar4 < lVar5) {
LAB_003c9d28:
    if (dy < 0.0) {
      fStack_44 = dy / this->m_scale - 0.5;
    }
    else {
      fStack_44 = dy / this->m_scale + 0.5;
    }
    sVar1 = fptosi(fStack_44);
    if ((float)(int)sVar1 < 0.0) {
      iVar6 = -(int)sVar1;
    }
    else {
      iVar6 = (int)sVar1;
    }
    if ((float)iVar6 <= 1.0) {
      if (dy < 0.0) {
        sVar1 = -1;
      }
      else {
        sVar1 = 1;
      }
    }
    *(short *)&this->m_cy = *(short *)&this->m_cy + sVar1;
  }
  else {
    lVar4 = fptosi(fVar8);
    lVar5 = fptosi(this->m_maxcy);
    if (lVar5 < lVar4) goto LAB_003c9d28;
    uVar3 = fptosi(fVar8);
    *(undefined2 *)&this->m_cy = uVar3;
  }
  if (this->m_image == (CShape **)0x0) {
    return;
  }
  sVar1 = *(short *)&this->m_cx;
  sVar2 = fptosi(this->m_mincx);
  if (sVar1 < sVar2) {
    fStack_50 = (float)(int)*(short *)&this->m_cx - this->m_mincx;
    uVar3 = fptosi(this->m_mincx);
    *(undefined2 *)&this->m_cx = uVar3;
  }
  else {
    sVar1 = *(short *)&this->m_cx;
    sVar2 = fptosi(this->m_maxcx);
    if (sVar2 < sVar1) {
      fStack_50 = (float)(int)*(short *)&this->m_cx - this->m_maxcx;
      uVar3 = fptosi(this->m_maxcx);
      *(undefined2 *)&this->m_cx = uVar3;
    }
  }
  sVar1 = *(short *)&this->m_cy;
  sVar2 = fptosi(this->m_mincy);
  if (sVar1 < sVar2) {
    fStack_4c = (float)(int)*(short *)&this->m_cy - this->m_mincy;
    uVar3 = fptosi(this->m_mincy);
    *(undefined2 *)&this->m_cy = uVar3;
  }
  else {
    sVar1 = *(short *)&this->m_cy;
    sVar2 = fptosi(this->m_maxcy);
    if (sVar2 < sVar1) {
      fStack_4c = (float)(int)*(short *)&this->m_cy - this->m_maxcy;
      uVar3 = fptosi(this->m_maxcy);
      *(undefined2 *)&this->m_cy = uVar3;
    }
  }
  this->m_zx = this->m_zx + fStack_50;
  this->m_zy = this->m_zy + fStack_4c;
LAB_003ca118:
  if (this->m_zx < this->m_minx) {
    this->m_zx = this->m_minx;
  }
  else if (this->m_maxx < this->m_zx) {
    this->m_zx = this->m_maxx;
  }
  if (this->m_zy < this->m_miny) {
    this->m_zy = this->m_miny;
  }
  else if (this->m_maxy < this->m_zy) {
    this->m_zy = this->m_maxy;
  }
  return;
}



// ---------------------------------------------------------------------------
// CalcLimit
// YkWndImage::CalcLimit(void)
//   symbol: CalcLimit__10YkWndImageFv
//   rva:    0x002ca220  size: 732 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndImage.cpp
// ---------------------------------------------------------------------------


/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void YkWndImage::CalcLimit(YkWndImage *this)

{
  short sVar1;
  int iVar2;
  
  if (this->m_image != (CShape **)0x0) {
    this->m_minx = 0.0;
    this->m_miny = 0.0;
    sVar1 = sRam00557a60;
    iVar2 = YmMenuShape::GetWidth((YmMenuShape *)*this->m_image);
    this->m_maxx = (this->m_scale * (float)iVar2 - (float)(int)sVar1) / this->m_scale;
    sVar1 = sRam00557a62;
    iVar2 = YmMenuShape::GetHeight((YmMenuShape *)*this->m_image);
    this->m_maxy = (this->m_scale * (float)iVar2 - (float)(int)sVar1) / this->m_scale;
    if (this->m_maxx < 0.0) {
      this->m_maxx = 0.0;
    }
    if (this->m_maxy < 0.0) {
      this->m_maxy = 0.0;
    }
    this->m_mincx = ((float)(int)sRam00557a60 / 512.0) * 40.0;
    this->m_mincy = ((float)(int)sRam00557a60 / 512.0) * 65.0;
    this->m_maxcx = (float)(int)sRam00557a60 - 150.0;
    this->m_maxcy = (float)(int)sRam00557a62 - 180.0;
    this->m_minx = this->m_minx + this->m_diffx;
    this->m_miny = this->m_miny + this->m_diffy;
    this->m_maxx = this->m_maxx + this->m_diffx;
    this->m_maxy = this->m_maxy + this->m_diffy;
  }
  return;
}



// ---------------------------------------------------------------------------
// 
// YkWndImage::YkWndImage(CShape * *, short, short, short, float)
//   symbol: __ct__10YkWndImageFPP6CShapesssf
//   rva:    0x002ca500  size: 724 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndImage.cpp
// ---------------------------------------------------------------------------


CTkObject *
YkWndImage::YkWndImage
          (CTkObject param_1,CTkObject *this,CTkObject arg1,undefined2 param_4,short param_5,
          short param_6)

{
  undefined2 uVar1;
  
  CTkObject::CTkObject(this);
  this[1] = (CTkObject)__vt__16CTkMenuPrimitive;
  *(undefined2 *)&this[3].m_RecSub1 = 0xffff;
  this[2].m_RecKind = (short)0x0;
  this[2].field_0x1 = 0;
  this[2].m_RecSub1 = (short)0x0;
  this[2].field_0x3 = 0;
  (**(code **)((int)this[1] + 0xc))();
  this[3].m_RecKind = (short)0x1;
  this[1] = (CTkObject)__vt__10YkWndImage;
  *(undefined2 *)(this + 5) = 0xc0;
  *(undefined2 *)&this[5].m_RecSub1 = 0xffff;
  *(undefined2 *)(this + 6) = 0;
  *(undefined2 *)&this[6].m_RecSub1 = 0;
  *(short *)(this + 8) = param_5;
  *(short *)&this[8].m_RecSub1 = param_6;
  this[0x15].m_RecKind = (short)0x0;
  this[0x15].field_0x1 = 0;
  this[0x15].m_RecSub1 = (short)0x0;
  this[0x15].field_0x3 = 0;
  this[0x16].m_RecKind = (short)0x0;
  this[0x16].field_0x1 = 0;
  this[0x16].m_RecSub1 = (short)0x0;
  this[0x16].field_0x3 = 0;
  this[0xd].m_RecKind = (short)0x0;
  this[0xd].field_0x1 = 0;
  this[0xd].m_RecSub1 = (short)0x0;
  this[0xd].field_0x3 = 0;
  this[0xf].m_RecKind = (short)0x0;
  this[0xf].field_0x1 = 0;
  this[0xf].m_RecSub1 = (short)0x0;
  this[0xf].field_0x3 = 0x44;
  this[0xe].m_RecKind = (short)0x0;
  this[0xe].field_0x1 = 0;
  this[0xe].m_RecSub1 = (short)0x0;
  this[0xe].field_0x3 = 0;
  this[0x10].m_RecKind = (short)0x0;
  this[0x10].field_0x1 = 0;
  this[0x10].m_RecSub1 = (short)0x0;
  this[0x10].field_0x3 = 0x44;
  this[9] = (CTkObject)(float)(int)param_5;
  this[10] = (CTkObject)(float)(int)param_6;
  uVar1 = fptosi(((float)(int)sRam00557a60 / 512.0) * 200.0);
  *(undefined2 *)(this + 7) = uVar1;
  uVar1 = fptosi(((float)(int)sRam00557a60 / 512.0) * 160.0);
  *(undefined2 *)&this[7].m_RecSub1 = uVar1;
  this[0x17] = param_1;
  this[0x1b] = param_1;
  *(undefined2 *)(this + 0x1c) = 0;
  *(undefined2 *)&this[0x1c].m_RecSub1 = 0;
  this[0x28].m_RecKind = (short)0x0;
  this[0x28].field_0x1 = 0;
  this[0x28].m_RecSub1 = (short)0x0;
  this[0x28].field_0x3 = 0;
  this[0x29].m_RecKind = (short)0x0;
  this[0x29].field_0x1 = 0;
  this[0x29].m_RecSub1 = (short)0x0;
  this[0x29].field_0x3 = 0;
  this[0x25].m_RecSub1 = (short)0x0;
  *(undefined2 *)(this + 0x26) = 0xff;
  this[0x25].field_0x3 = 0;
  *(undefined2 *)&this[0x26].m_RecSub1 = 0;
  this[0x27].m_RecKind = (short)0xff;
  this[0x27].field_0x1 = 0xff;
  this[0x27].m_RecSub1 = (short)0xff;
  this[0x27].field_0x3 = 0xff;
  *(undefined2 *)&this[0x1e].m_RecSub1 = param_4;
  this[0x21] = arg1;
  *(undefined2 *)(this + 0x1e) = 0;
  this[0x20].m_RecKind = (short)0x0;
  this[0x20].field_0x1 = 0;
  this[0x20].m_RecSub1 = (short)0x0;
  this[0x20].field_0x3 = 0;
  *(undefined2 *)(this + 0x1f) = 0;
  this[0x22].m_RecKind = (short)0x0;
  this[0x22].field_0x1 = 0;
  this[0x22].m_RecSub1 = (short)0x0;
  this[0x22].field_0x3 = 0;
  *(undefined2 *)&this[0x1f].m_RecSub1 = 0;
  this[0x23].m_RecKind = (short)0x0;
  this[0x23].field_0x1 = 0;
  this[0x23].m_RecSub1 = (short)0x0;
  this[0x23].field_0x3 = 0;
  this[0x25].m_RecKind = (short)0x0;
  this[0x24].m_RecKind = (short)0x0;
  this[0x24].field_0x1 = 0;
  this[0x24].m_RecSub1 = (short)0x0;
  this[0x24].field_0x3 = 0;
  return this;
}



// ---------------------------------------------------------------------------
// OnInitialUpdatePrimitive
// YkWndImage::OnInitialUpdatePrimitive(void)
//   symbol: OnInitialUpdatePrimitive__10YkWndImageFv
//   rva:    0x002ca7e0  size: 444 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndImage.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void * YkWndImage::OnInitialUpdatePrimitive(YkWndImage *this)

{
  undefined2 uVar1;
  void *pvVar2;
  int iStack_18;
  int iStack_14;
  YkWndImage *pYStack_10;
  
  pYStack_10 = this;
  uVar1 = fptosi(((float)(int)sRam00557a60 / 512.0) * 200.0);
  *(undefined2 *)&pYStack_10->m_cx = uVar1;
  uVar1 = fptosi(((float)(int)sRam00557a60 / 512.0) * 160.0);
  *(undefined2 *)&pYStack_10->m_cy = uVar1;
  *(ushort *)&pYStack_10->m_stat = *(ushort *)&pYStack_10->m_stat & 0xff3f;
  pYStack_10->m_closetime = 0xffffffff;
  *(undefined2 *)&pYStack_10->m_alpha = 0xff;
  YkWndImage::SetAlphaAuto(pYStack_10,0,0x10);
  *(undefined1 *)(*(int *)&pYStack_10->field_0x8 + 0x69) = 0;
  *(undefined1 *)(*(int *)&pYStack_10->field_0x8 + 0x62) = 0;
  CTkMenuCtrlData::SetCursolLocate
            (*(undefined4 *)&pYStack_10->field_0x8,0xffffffffffffff9c,0xffffffffffffff9c);
  *(undefined1 *)(*(int *)&pYStack_10->field_0x8 + 0x81) = 0;
  SetKeyLevel__FUi(0x26);
  iStack_18 = (int)*(short *)&pYStack_10->m_cx;
  iStack_14 = (int)*(short *)&pYStack_10->m_cy;
  pvVar2 = memcpy((void *)(_g_pTkMouse + 0x34),&iStack_18,8);
  return pvVar2;
}



// ---------------------------------------------------------------------------
// OnDestroyPrimitive
// YkWndImage::OnDestroyPrimitive(void)
//   symbol: OnDestroyPrimitive__10YkWndImageFv
//   rva:    0x002ca9a0  size: 132 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndImage.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void YkWndImage::OnDestroyPrimitive(YkWndImage *this)

{
  CTkMouse::ResetMouseMoveCenter(_g_pTkMouse);
  YkWndImage::SetAnimeCursor(this,(YmMenuShapeFile *)0x0);
  SetKeyLevel__FUi(0xffff);
  CTkHelp::SetHelpString(_g_pTkHelp,(char *)0x0,2);
  CTkTitle::SetMessage(_g_pTkTitle,(char *)0x0,2);
  CTkMenuMng::OpenDrawMenu
            ((CTkMenuMng *)&g_TkMenuMng,*(CTkMenuCtrlData **)(_g_pTkTarget + 8));
  return;
}



// ---------------------------------------------------------------------------
// CloseImageSet
// YkWndImage::CloseImageSet(void)
//   symbol: CloseImageSet__10YkWndImageFv
//   rva:    0x002caa30  size: 232 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndImage.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void YkWndImage::CloseImageSet(YkWndImage *this)

{
  int iVar1;
  
  if ((*(ushort *)&this->m_stat & 0x40) == 0) {
    *(ushort *)&this->m_stat = *(ushort *)&this->m_stat | 0x40;
    iVar1 = xiGetTime();
    this->m_closetime = iVar1 + 3;
    if (*(int *)&this->field_0x8 != 0) {
      *(undefined1 *)(*(int *)&this->field_0x8 + 0x62) = 0;
      *(undefined1 *)(*(int *)&this->field_0x8 + 0x80) = 0;
    }
    *(undefined2 *)&this->m_alpha = 0;
    CTkHelp::SetHelpString(_g_pTkHelp,(char *)0x0,2);
    CTkTitle::SetMessage(_g_pTkTitle,(char *)0x0,2);
    this->m_help = (char *)0x0;
    this->m_title = (char *)0x0;
    YkWndImage::SetAlphaAuto(this,0xff,0x10);
  }
  return;
}



// ---------------------------------------------------------------------------
// PrintItem
// YkWndImage::PrintItem(_YK_WNDITEM *)
//   symbol: PrintItem__10YkWndImageFP11_YK_WNDITEM
//   rva:    0x002cab20  size: 2600 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndImage.cpp
// ---------------------------------------------------------------------------


/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void YkWndImage::PrintItem(YkWndImage *this,_YK_WNDITEM *pItem)

{
  _YK_WNDITEM _Var1;
  short sVar2;
  short sVar3;
  ushort uVar4;
  short sVar5;
  uint arg5;
  int iVar6;
  int iVar7;
  long lVar8;
  long lVar9;
  long lVar10;
  short sVar11;
  
  if ((pItem != (_YK_WNDITEM *)0x0) && (pItem[3] != (_YK_WNDITEM)0x0)) {
    arg5 = (uint)(byte)pItem[3] * 0x1000000 + 0x808080;
    sVar2 = fptosi(this->m_scale *
                   ((float)((int)*(short *)(pItem + 4) - (int)*(short *)&this->m_idiffx) - this->m_zx
                   ) + 0.5);
    sVar3 = fptosi(this->m_scale *
                   ((float)((int)*(short *)(pItem + 6) - (int)*(short *)&this->m_idiffy) - this->m_zy
                   ) + 0.5);
    if ((-1 < (char)pItem[1]) && ((long)(char)pItem[1] < (long)*(short *)&this->m_iconmax)) {
      if (((byte)*pItem & 0x10) == 0) {
        lVar8 = YmMenuShape::GetWidth((YmMenuShape *)this->m_icon[(char)pItem[1]]);
        iVar6 = (int)lVar8;
        if (lVar8 < 0) {
          iVar6 = iVar6 + 1;
        }
        sVar2 = sVar2 - (short)(iVar6 >> 1);
        lVar8 = YmMenuShape::GetHeight((YmMenuShape *)this->m_icon[(char)pItem[1]]);
        iVar6 = (int)lVar8;
        if (lVar8 < 0) {
          iVar6 = iVar6 + 1;
        }
        sVar3 = sVar3 - (short)(iVar6 >> 1);
      }
      if (((byte)*pItem & 2) == 0) {
        YmMenuShape::ExtraDraw
                  ((YmMenuShape *)this->m_icon[(char)pItem[1]],(int)sVar2,(int)sVar3,1.0,1.0,arg5,
                   '\0',0x44,0);
      }
      else {
        YmMenuShape::DrawRotate
                  ((YmMenuShape *)this->m_icon[(char)pItem[1]],(int)sVar2,(int)sVar3,
                   *(float *)(pItem + 0x10),arg5,0x44,1.0,'\x01');
      }
    }
    if ((((byte)*pItem & 8) == 0) && (*(int *)(pItem + 0x14) != 0)) {
      _Var1 = pItem[3];
      lVar8 = *(long *)(StrColorTbl + *(short *)(pItem + 0xe) * 8);
      if (((byte)*pItem & 0x40) == 0) {
        sVar2 = sVar2 + *(short *)(pItem + 8);
        sVar3 = sVar3 + *(short *)(pItem + 10);
      }
      else {
        uVar4 = *(ushort *)(pItem + 0xc);
        lVar9 = (**(code **)(*(int *)&this->field_0x4 + 0x5c))(this,*(undefined4 *)(pItem + 0x14));
        if (iRam005c5e28 != 1) {
          uVar4 = (short)uVar4 >> 8;
        }
        iVar6 = (int)lVar9;
        sVar5 = (short)(iVar6 >> 1);
        sVar11 = (short)(iVar6 >> 2);
        switch(uVar4 & 0xff) {
        case 0:
          lVar10 = YmMenuShape::GetWidth((YmMenuShape *)this->m_icon[(char)pItem[1]]);
          iVar7 = (int)lVar10;
          if (lVar10 < 0) {
            iVar7 = iVar7 + 1;
          }
          if (lVar9 < 0) {
            sVar5 = (short)(iVar6 + 1 >> 1);
          }
          sVar2 = sVar2 - (sVar5 - (short)(iVar7 >> 1));
          sVar5 = (**(code **)(*(int *)&this->field_0x4 + 0x60))();
          sVar3 = sVar3 - (sVar5 + 1);
          break;
        case 1:
          lVar10 = YmMenuShape::GetWidth((YmMenuShape *)this->m_icon[(char)pItem[1]]);
          iVar7 = (int)lVar10;
          if (lVar10 < 0) {
            iVar7 = iVar7 + 1;
          }
          if (lVar9 < 0) {
            sVar5 = (short)(iVar6 + 1 >> 1);
          }
          sVar2 = sVar2 - (sVar5 - (short)(iVar7 >> 1));
          sVar5 = YmMenuShape::GetHeight((YmMenuShape *)this->m_icon[(char)pItem[1]]);
          sVar3 = sVar3 + sVar5 + 1;
          break;
        case 2:
          sVar2 = sVar2 - ((short)lVar9 + 3);
          break;
        case 3:
          sVar5 = YmMenuShape::GetWidth((YmMenuShape *)this->m_icon[(char)pItem[1]]);
          sVar2 = sVar2 + sVar5 + 2;
          break;
        case 4:
          lVar10 = YmMenuShape::GetWidth((YmMenuShape *)this->m_icon[(char)pItem[1]]);
          iVar7 = (int)lVar10;
          if (lVar10 < 0) {
            iVar7 = iVar7 + 1;
          }
          if (lVar9 < 0) {
            sVar11 = (short)(iVar6 + 3 >> 2);
          }
          sVar2 = sVar2 - (sVar11 * 3 - (short)(iVar7 >> 1));
          sVar5 = (**(code **)(*(int *)&this->field_0x4 + 0x60))();
          sVar3 = sVar3 - (sVar5 + 1);
          break;
        case 5:
          lVar10 = YmMenuShape::GetWidth((YmMenuShape *)this->m_icon[(char)pItem[1]]);
          iVar7 = (int)lVar10;
          if (lVar10 < 0) {
            iVar7 = iVar7 + 1;
          }
          if (lVar9 < 0) {
            sVar11 = (short)(iVar6 + 3 >> 2);
          }
          sVar2 = sVar2 - (sVar11 - (short)(iVar7 >> 1));
          sVar5 = (**(code **)(*(int *)&this->field_0x4 + 0x60))();
          sVar3 = sVar3 - (sVar5 + 1);
          break;
        case 6:
          lVar10 = YmMenuShape::GetWidth((YmMenuShape *)this->m_icon[(char)pItem[1]]);
          iVar7 = (int)lVar10;
          if (lVar10 < 0) {
            iVar7 = iVar7 + 1;
          }
          if (lVar9 < 0) {
            sVar11 = (short)(iVar6 + 3 >> 2);
          }
          sVar2 = sVar2 - (sVar11 * 3 - (short)(iVar7 >> 1));
          sVar5 = YmMenuShape::GetHeight((YmMenuShape *)this->m_icon[(char)pItem[1]]);
          sVar3 = sVar3 + sVar5 + 1;
          break;
        case 7:
          lVar10 = YmMenuShape::GetWidth((YmMenuShape *)this->m_icon[(char)pItem[1]]);
          iVar7 = (int)lVar10;
          if (lVar10 < 0) {
            iVar7 = iVar7 + 1;
          }
          if (lVar9 < 0) {
            sVar11 = (short)(iVar6 + 3 >> 2);
          }
          sVar2 = sVar2 - (sVar11 - (short)(iVar7 >> 1));
          sVar5 = YmMenuShape::GetHeight((YmMenuShape *)this->m_icon[(char)pItem[1]]);
          sVar3 = sVar3 + sVar5 + 1;
          break;
        default:
          sVar5 = YmMenuShape::GetWidth((YmMenuShape *)this->m_icon[(char)pItem[1]]);
          sVar2 = sVar2 + sVar5 + 2;
        }
      }
      (**(code **)(*(int *)&this->field_0x4 + 0x58))
                (this,sVar2,sVar3,*(undefined4 *)(pItem + 0x14),
                 (ulong)(byte)_Var1 * 0x1000000 + lVar8);
    }
  }
  return;
}



// ---------------------------------------------------------------------------
// OnDrawPrimitive
// YkWndImage::OnDrawPrimitive(void)
//   symbol: OnDrawPrimitive__10YkWndImageFv
//   rva:    0x002cb5e0  size: 1344 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndImage.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void YkWndImage::OnDrawPrimitive(YkWndImage *this)

{
  int iVar1;
  short sVar2;
  short sVar3;
  int iVar4;
  int iVar5;
  long lVar6;
  uint uVar7;
  
  if (this->m_image != (CShape **)0x0) {
    lVar6 = 0;
    while (lVar6 < *(short *)&this->m_imagemax) {
      iVar5 = (int)lVar6;
      if (*(short *)&this->m_alpha == 0) {
        sVar2 = fptosi(-this->m_zx * this->m_scale + 0.5);
        sVar3 = fptosi(-this->m_zy * this->m_scale + 0.5);
        YmMenuShape::ExtraDraw
                  ((YmMenuShape *)this->m_image[iVar5],(int)sVar2,(int)sVar3,this->m_scale,
                   this->m_scale,0x78404040,'\0',0x44,0);
      }
      else {
        iVar1 = -((int)*(short *)&this->m_alpha & 0xffU);
        iVar4 = iVar1 + 0xff;
        if (iVar4 < 0) {
          iVar4 = iVar1 + 0x100;
        }
        uVar7 = iVar4 >> 1;
        if (0x80 < uVar7) {
          uVar7 = 0x80;
        }
        sVar2 = fptosi(-this->m_zx * this->m_scale + 0.5);
        sVar3 = fptosi(-this->m_zy * this->m_scale + 0.5);
        YmMenuShape::ExtraDraw
                  ((YmMenuShape *)this->m_image[iVar5],(int)sVar2,(int)sVar3,this->m_scale,
                   this->m_scale,uVar7 << 0x18 | 0x404040,'\0',0x44,0);
      }
      lVar6 = (long)(iVar5 + 1);
    }
  }
  if (*(short *)&this->m_alpha == 0) {
    for (lVar6 = 0; lVar6 < *(short *)&this->m_itemmax; lVar6 = (long)((int)lVar6 + 1)) {
      YkWndImage::PrintItem(this,(_YK_WNDITEM *)(this->m_item + (int)lVar6));
    }
    for (lVar6 = 0; lVar6 < this->m_extitemmax; lVar6 = (long)((int)lVar6 + 1)) {
      YkWndImage::PrintItem(this,(_YK_WNDITEM *)(this->m_extitem + (int)lVar6));
    }
  }
  if (this->m_filter != (CShape **)0x0) {
    for (lVar6 = 0; lVar6 < *(short *)&this->m_filtermax; lVar6 = (long)((int)lVar6 + 1)) {
      YmMenuShape::ExtraDraw
                ((YmMenuShape *)this->m_filter[(int)lVar6],0,0,4.0,4.0,0x80404040,'\0',0x44,0);
    }
  }
  if (((*(short *)&this->m_alpha == 0) && (-1 < *(short *)&this->m_cur)) &&
     (*(short *)&this->m_cur < *(short *)&this->m_iconmax)) {
    YmMenuShape::Draw
              ((YmMenuShape *)this->m_icon[*(short *)&this->m_cur],
               (int)*(short *)&this->m_cx + (int)*(short *)&this->m_curdx,
               (int)*(short *)&this->m_cy + (int)*(short *)&this->m_curdy,0x80808080,0,0);
  }
  if ((*(short *)&this->m_alpha == 0) && (this->m_animecur != '\0')) {
    CTkMenuCtrlData::SetCursolLocate
              (*(undefined4 *)&this->field_0x8,*(short *)&this->m_cx + *(short *)&this->m_curdx,
               *(short *)&this->m_cy + *(short *)&this->m_curdy);
  }
  if (this->m_help != (char *)0x0) {
    CTkHelp::SetHelpString(_g_pTkHelp,this->m_help,2);
  }
  if (this->m_title != (char *)0x0) {
    CTkTitle::SetMessage(_g_pTkTitle,this->m_title,2);
  }
  return;
}



// ---------------------------------------------------------------------------
// CalcAlpha
// YkWndImage::CalcAlpha(_YK_WNDITEM *)
//   symbol: CalcAlpha__10YkWndImageFP11_YK_WNDITEM
//   rva:    0x002cbb20  size: 312 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndImage.cpp
// ---------------------------------------------------------------------------


/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void YkWndImage::CalcAlpha(YkWndImage *this,_YK_WNDITEM *pItem)

{
  long lVar1;
  
  if (pItem != (_YK_WNDITEM *)0x0) {
    if (((byte)*pItem & 1) == 0) {
      lVar1 = fptosi((float)(byte)pItem[3] - 12.0,this);
      if ((lVar1 < 0) && (lVar1 = 0, ((byte)*pItem & 4) != 0)) {
        *pItem = (_YK_WNDITEM)((byte)*pItem | 1);
      }
    }
    else {
      lVar1 = fptosi((float)(byte)pItem[3] + 12.0,this);
      if ((0x80 < lVar1) && (lVar1 = 0x80, ((byte)*pItem & 4) != 0)) {
        *pItem = (_YK_WNDITEM)((byte)*pItem & 0xfe);
      }
    }
    pItem[3] = SUB81(lVar1,0);
  }
  return;
}



// ---------------------------------------------------------------------------
// OnDrawCalc
// YkWndImage::OnDrawCalc(char)
//   symbol: OnDrawCalc__10YkWndImageFc
//   rva:    0x002cbc60  size: 4644 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndImage.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void YkWndImage::OnDrawCalc(YkWndImage *this,char isActive)

{
  undefined1 uVar1;
  undefined2 uVar2;
  undefined2 uVar3;
  uint uVar4;
  long lVar5;
  int iVar6;
  int iStack_80;
  int iStack_7c;
  int iStack_78;
  int iStack_74;
  float fStack_70;
  float fStack_6c;
  float fStack_68;
  float fStack_64;
  float fStack_60;
  float fStack_5c;
  float fStack_58;
  float fStack_54;
  float fStack_50;
  float fStack_4c;
  float fStack_48;
  float fStack_44;
  float fStack_40;
  float fStack_3c;
  float fStack_38;
  float fStack_34;
  float fStack_30;
  float fStack_2c;
  float fStack_28;
  float fStack_24;
  YkWndImage *pYStack_20;
  char cStack_10;
  
  pYStack_20 = this;
  cStack_10 = isActive;
  if ((*(ushort *)&this->m_stat & 0x40) == 0) {
    lVar5 = CTkMenuPrimitive::IsDrawWindow(_g_pTkTarget);
    if (lVar5 != 0) {
      CTkMenuMng::CloseDrawMenu
                ((CTkMenuMng *)&g_TkMenuMng,(CTkMenuCtrlData *)_g_pTkTarget->m_pParentMCD,'\x01',
                 '\x01','\0','\0');
    }
  }
  else if ((((*(ushort *)&this->m_stat & 0x38) == 0) ||
           (uVar4 = xiGetTime(), pYStack_20->m_closetime <= uVar4)) &&
          ((*(ushort *)&pYStack_20->m_stat & 0x80) == 0)) {
    (**(code **)(*(int *)&pYStack_20->field_0x4 + 0x68))();
    *(ushort *)&pYStack_20->m_stat = *(ushort *)&pYStack_20->m_stat | 0x80;
  }
  if ((*(ushort *)&pYStack_20->m_stat & 0x20) != 0) {
    if ((int)*(short *)&pYStack_20->m_alpha - (int)*(short *)&pYStack_20->m_talpha < 0) {
      iVar6 = -((int)*(short *)&pYStack_20->m_alpha - (int)*(short *)&pYStack_20->m_talpha);
    }
    else {
      iVar6 = (int)*(short *)&pYStack_20->m_alpha - (int)*(short *)&pYStack_20->m_talpha;
    }
    if (iVar6 < (int)(uint)pYStack_20->m_aspeed) {
      *(ushort *)&pYStack_20->m_stat = *(ushort *)&pYStack_20->m_stat & 0xffdf;
      uVar1 = pYStack_20->field_0x9b;
      pYStack_20->m_alpha = pYStack_20->m_talpha;
      pYStack_20->field_0x99 = uVar1;
    }
    else if (*(short *)&pYStack_20->m_talpha < *(short *)&pYStack_20->m_alpha) {
      *(ushort *)&pYStack_20->m_alpha =
           *(short *)&pYStack_20->m_alpha - (ushort)pYStack_20->m_aspeed;
    }
    else {
      *(ushort *)&pYStack_20->m_alpha =
           *(short *)&pYStack_20->m_alpha + (ushort)pYStack_20->m_aspeed;
    }
  }
  if ((*(ushort *)&pYStack_20->m_stat & 0x10) == 0) {
    if ((*(ushort *)&pYStack_20->m_stat & 2) != 0) {
      lVar5 = GetKey__FUi7KEYTYPE7TRGTYPEi(0x26,0x7d,1,0xffffffffffffffff);
      if ((lVar5 == 0) &&
         ((lVar5 = GetKey__FUi7KEYTYPE7TRGTYPEi(0x26,0xa4,4,0xffffffffffffffff), lVar5 == 0 ||
          (lVar5 = GetKey__FUi7KEYTYPE7TRGTYPEi(0x26,0xa5,4,0xffffffffffffffff), lVar5 == 0)))) {
        fStack_6c = (float)GetAnalogKey__FUi7KEYTYPE(0x26,0x7c);
        fStack_6c = DAT_0054d028 * fStack_6c;
        fStack_50 = pYStack_20->m_scale;
        pYStack_20->m_scale = pYStack_20->m_scale + -fStack_6c;
        if (pYStack_20->m_scale < pYStack_20->m_minscale) {
          pYStack_20->m_scale = pYStack_20->m_minscale;
        }
        if (pYStack_20->m_maxscale < pYStack_20->m_scale) {
          pYStack_20->m_scale = pYStack_20->m_maxscale;
        }
        YkWndImage::CalcLimit(pYStack_20);
        fStack_48 = (float)((int)*(short *)&pYStack_20->m_cx + (int)*(short *)&pYStack_20->m_curdx)
                    / fStack_50 -
                    (float)((int)*(short *)&pYStack_20->m_cx + (int)*(short *)&pYStack_20->m_curdx)
                    / pYStack_20->m_scale;
        fStack_4c = (float)((int)*(short *)&pYStack_20->m_cy + (int)*(short *)&pYStack_20->m_curdy)
                    / fStack_50 -
                    (float)((int)*(short *)&pYStack_20->m_cy + (int)*(short *)&pYStack_20->m_curdy)
                    / pYStack_20->m_scale;
        YkWndImage::MovePos
                  (pYStack_20,fStack_48 * pYStack_20->m_scale,fStack_4c * pYStack_20->m_scale,'\x01'
                  );
      }
      else {
        YkWndImage::SetScaleAuto(pYStack_20,pYStack_20->m_defscale);
      }
    }
  }
  else {
    fStack_68 = DAT_0054c2ac * (pYStack_20->m_tscale - pYStack_20->m_scale);
    fStack_44 = fStack_68;
    if (fStack_68 < 0.0) {
      fStack_44 = -fStack_68;
    }
    if (fStack_44 < DAT_0054d024) {
      pYStack_20->m_scale = pYStack_20->m_tscale;
      *(ushort *)&pYStack_20->m_stat = *(ushort *)&pYStack_20->m_stat & 0xffef;
    }
    fStack_5c = pYStack_20->m_scale;
    pYStack_20->m_scale = pYStack_20->m_scale + fStack_68;
    if (pYStack_20->m_scale < pYStack_20->m_minscale) {
      pYStack_20->m_scale = pYStack_20->m_minscale;
    }
    if (pYStack_20->m_maxscale < pYStack_20->m_scale) {
      pYStack_20->m_scale = pYStack_20->m_maxscale;
    }
    YkWndImage::CalcLimit(pYStack_20);
    fStack_54 = (float)((int)*(short *)&pYStack_20->m_cx + (int)*(short *)&pYStack_20->m_curdx) /
                fStack_5c -
                (float)((int)*(short *)&pYStack_20->m_cx + (int)*(short *)&pYStack_20->m_curdx) /
                pYStack_20->m_scale;
    fStack_58 = (float)((int)*(short *)&pYStack_20->m_cy + (int)*(short *)&pYStack_20->m_curdy) /
                fStack_5c -
                (float)((int)*(short *)&pYStack_20->m_cy + (int)*(short *)&pYStack_20->m_curdy) /
                pYStack_20->m_scale;
    YkWndImage::MovePos
              (pYStack_20,fStack_54 * pYStack_20->m_scale,fStack_58 * pYStack_20->m_scale,'\x01');
  }
  lVar5 = GetKey__FUi7KEYTYPE7TRGTYPEi(0x26,0x9a,4,0xffffffffffffffff);
  if (lVar5 == 0) {
    *(ushort *)&pYStack_20->m_stat = *(ushort *)&pYStack_20->m_stat & 0xfdff;
  }
  else {
    *(ushort *)&pYStack_20->m_stat = *(ushort *)&pYStack_20->m_stat | 0x200;
  }
  if ((*(ushort *)&pYStack_20->m_stat & 8) != 0) {
    fStack_64 = pYStack_20->m_zx;
    fStack_60 = pYStack_20->m_zy;
    fStack_70 = pYStack_20->m_tx -
                ((float)(int)*(short *)&pYStack_20->m_idiffx +
                pYStack_20->m_zx + (float)(int)*(short *)&pYStack_20->m_cx / pYStack_20->m_scale +
                0.5);
    fStack_6c = pYStack_20->m_ty -
                ((float)(int)*(short *)&pYStack_20->m_idiffy +
                pYStack_20->m_zy + (float)(int)*(short *)&pYStack_20->m_cy / pYStack_20->m_scale +
                0.5);
    if ((pYStack_20->m_scale / 0.5 < fStack_70) || (pYStack_20->m_scale / 0.5 < fStack_6c)) {
      fStack_70 = fStack_70 * 0.5;
      fStack_6c = fStack_6c * 0.5;
    }
    YkWndImage::MovePos(pYStack_20,fStack_70,fStack_6c,'\0');
    if ((fStack_64 - pYStack_20->m_zx) * (fStack_64 - pYStack_20->m_zx) +
        (fStack_60 - pYStack_20->m_zy) * (fStack_60 - pYStack_20->m_zy) < DAT_0054cec8) {
      fStack_70 = pYStack_20->m_scale *
                  (pYStack_20->m_tx -
                  ((float)(int)*(short *)&pYStack_20->m_idiffx +
                  pYStack_20->m_zx + (float)(int)*(short *)&pYStack_20->m_cx / pYStack_20->m_scale +
                  0.5));
      fStack_6c = pYStack_20->m_scale *
                  (pYStack_20->m_ty -
                  ((float)(int)*(short *)&pYStack_20->m_idiffy +
                  pYStack_20->m_zy + (float)(int)*(short *)&pYStack_20->m_cy / pYStack_20->m_scale +
                  0.5));
      YkWndImage::MovePos(pYStack_20,fStack_70,fStack_6c,'\0');
      if ((*(ushort *)&pYStack_20->m_stat & 0x100) != 0) {
        uVar2 = fptosi(pYStack_20->m_scale *
                       ((pYStack_20->m_ty - (float)(int)*(short *)&pYStack_20->m_idiffy) -
                       pYStack_20->m_zy) + 0.5);
        uVar3 = fptosi(pYStack_20->m_scale *
                       ((pYStack_20->m_tx - (float)(int)*(short *)&pYStack_20->m_idiffx) -
                       pYStack_20->m_zx) + 0.5);
        *(undefined2 *)&pYStack_20->m_cx = uVar3;
        *(undefined2 *)&pYStack_20->m_cy = uVar2;
      }
      *(ushort *)&pYStack_20->m_stat = *(ushort *)&pYStack_20->m_stat & 0xfff7;
      *(undefined1 *)(*(int *)&pYStack_20->field_0x8 + 0x62) = 1;
    }
    goto LAB_003ccd1c;
  }
  if ((*(ushort *)&pYStack_20->m_stat & 1) == 0) goto LAB_003ccd1c;
  if ((*(ushort *)&pYStack_20->m_stat & 0x100) == 0) {
    fStack_70 = (float)GetAnalogKey__FUi7KEYTYPE(0x26,0x79);
    fStack_70 = fStack_70 * 15.0;
    fStack_6c = (float)GetAnalogKey__FUi7KEYTYPE(0x26,0x7a);
    fStack_6c = fStack_6c * 15.0;
  }
  else {
    fStack_70 = (float)GetAnalogKey__FUi7KEYTYPE(0x26,0x9d);
    fStack_70 = pYStack_20->m_actcurspeed * fStack_70;
    fStack_6c = (float)GetAnalogKey__FUi7KEYTYPE(0x26,0x9e);
    fStack_6c = pYStack_20->m_actcurspeed * fStack_6c;
    if (fStack_70 < 0.0) {
      fStack_40 = -fStack_70;
    }
    else {
      fStack_40 = fStack_70;
    }
    if (fStack_40 < 2.0) {
      fStack_3c = fStack_6c;
      if (fStack_6c < 0.0) {
        fStack_3c = -fStack_6c;
      }
      if (fStack_3c < 2.0) {
        if ((_g_pTkMouse->m_enableDraw != '\0') && (cStack_10 != '\0')) {
          if (_g_pTkMouse != (CTkMouse *)0x0) {
            iStack_80 = (_g_pTkMouse->m_mousept).x;
            iStack_7c = (_g_pTkMouse->m_mousept).y;
          }
          fStack_70 = (float)(iStack_80 - *(short *)&pYStack_20->m_cx);
          fStack_6c = (float)(iStack_7c - *(short *)&pYStack_20->m_cy);
        }
        if (fStack_70 < 0.0) {
          fStack_38 = -fStack_70;
        }
        else {
          fStack_38 = fStack_70;
        }
        if (fStack_38 < 2.0) {
          if (fStack_6c < 0.0) {
            fStack_34 = -fStack_6c;
          }
          else {
            fStack_34 = fStack_6c;
          }
          if (fStack_34 < 2.0) goto LAB_003ccaac;
        }
        fStack_70 = fStack_70 * pYStack_20->m_scale;
        fStack_6c = fStack_6c * pYStack_20->m_scale;
      }
    }
  }
LAB_003ccaac:
  if (fStack_70 < 0.0) {
    fStack_30 = -fStack_70;
  }
  else {
    fStack_30 = fStack_70;
  }
  if (fStack_30 < 2.0) {
    fStack_70 = 0.0;
  }
  if (fStack_6c < 0.0) {
    fStack_2c = -fStack_6c;
  }
  else {
    fStack_2c = fStack_6c;
  }
  if (fStack_2c < 2.0) {
    fStack_6c = 0.0;
  }
  if (pYStack_20->m_reverse == '\0') {
    YkWndImage::MovePos(pYStack_20,-fStack_70,-fStack_6c,'\0');
  }
  else {
    YkWndImage::MovePos(pYStack_20,fStack_70,fStack_6c,'\0');
  }
  if (fStack_70 < 0.0) {
    fStack_28 = -fStack_70;
  }
  else {
    fStack_28 = fStack_70;
  }
  fStack_70 = fStack_28;
  if (fStack_6c < 0.0) {
    fStack_24 = -fStack_6c;
  }
  else {
    fStack_24 = fStack_6c;
  }
  fStack_6c = fStack_24;
  if ((((*(ushort *)&pYStack_20->m_stat & 4) != 0) && (fStack_28 < 4.5)) && (fStack_24 < 4.5)) {
    YkWndImage::CheckMagnet(pYStack_20,8.0);
  }
  lVar5 = GetKey__FUi7KEYTYPE7TRGTYPEi(0x26,0x7e,1,0xffffffffffffffff);
  if (lVar5 != 0) {
    YkWndImage::SetPosAuto
              (pYStack_20,(float)(int)*(short *)&pYStack_20->m_rx,
               (float)(int)*(short *)&pYStack_20->m_ry);
  }
LAB_003ccd1c:
  if (*(short *)&pYStack_20->m_alpha == 0) {
    if (pYStack_20->m_item != (_YK_WNDITEM *)0x0) {
      for (lVar5 = 0; lVar5 < *(short *)&pYStack_20->m_itemmax; lVar5 = (long)((int)lVar5 + 1)) {
        YkWndImage::CalcAlpha
                  (pYStack_20,(_YK_WNDITEM *)(pYStack_20->m_item + (int)lVar5));
      }
    }
    YkWndImage::CalcAlpha(pYStack_20,(_YK_WNDITEM *)pYStack_20->m_extitem);
  }
  if (((*(ushort *)&pYStack_20->m_stat & 0x100) != 0) && (cStack_10 != '\0')) {
    iStack_78 = (int)*(short *)&pYStack_20->m_cx;
    iStack_74 = (int)*(short *)&pYStack_20->m_cy;
    CTkMouse::SetMousePoint(_g_pTkMouse,(tagPOINT *)&iStack_78,0.0);
    if ((fStack_70 != 0.0) || (fStack_6c != 0.0)) {
      CTkMouse::SetDrawStatus(_g_pTkMouse,'\0');
    }
  }
  return;
}



// ---------------------------------------------------------------------------
// SetPosAuto
// YkWndImage::SetPosAuto(float, float)
//   symbol: SetPosAuto__10YkWndImageFff
//   rva:    0x002cce90  size: 536 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndImage.cpp
// ---------------------------------------------------------------------------


/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void YkWndImage::SetPosAuto(YkWndImage *this,float tx,float ty)

{
  float fVar1;
  float fVar2;
  
  fVar1 = tx - ((float)(int)*(short *)&this->m_idiffx +
                 this->m_zx + (float)(int)*(short *)&this->m_cx / this->m_scale + 0.5);
  fVar2 = ty - ((float)(int)*(short *)&this->m_idiffy +
                 this->m_zy + (float)(int)*(short *)&this->m_cy / this->m_scale + 0.5);
  if (DAT_0054cec8 <= fVar1 * fVar1 + fVar2 * fVar2) {
    if (this->m_zx < this->m_minx) {
      this->m_zx = this->m_minx;
    }
    else if (this->m_maxx < this->m_zx) {
      this->m_zx = this->m_maxx;
    }
    if (this->m_zy < this->m_miny) {
      this->m_zy = this->m_miny;
    }
    else if (this->m_maxy < this->m_zy) {
      this->m_zy = this->m_maxy;
    }
    this->m_tx = tx;
    this->m_ty = ty;
    *(ushort *)&this->m_stat = *(ushort *)&this->m_stat | 8;
    *(undefined1 *)(*(int *)&this->field_0x8 + 0x62) = 0;
  }
  return;
}



// ---------------------------------------------------------------------------
// SetScaleAuto
// YkWndImage::SetScaleAuto(float)
//   symbol: SetScaleAuto__10YkWndImageFf
//   rva:    0x002cd0b0  size: 52 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndImage.cpp
// ---------------------------------------------------------------------------


/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void YkWndImage::SetScaleAuto(YkWndImage *this,float ts)

{
  this->m_tscale = ts;
  *(ushort *)&this->m_stat = *(ushort *)&this->m_stat | 0x10;
  return;
}



// ---------------------------------------------------------------------------
// SetAlphaAuto
// YkWndImage::SetAlphaAuto(short, unsigned char)
//   symbol: SetAlphaAuto__10YkWndImageFsUc
//   rva:    0x002cd0f0  size: 104 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndImage.cpp
// ---------------------------------------------------------------------------


void YkWndImage::SetAlphaAuto(int this,undefined2 speed,char param_3)

{
  *(undefined2 *)(this + 0x9a) = speed;
  if (param_3 == '\0') {
    *(undefined1 *)(this + 0x97) = 1;
  }
  else {
    *(char *)(this + 0x97) = param_3;
  }
  *(ushort *)(this + 0x14) = *(ushort *)(this + 0x14) | 0x20;
  return;
}



// ---------------------------------------------------------------------------
// GetCurItem
// YkWndImage::GetCurItem(void)
//   symbol: GetCurItem__10YkWndImageFv
//   rva:    0x002cd160  size: 496 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndImage.cpp
// ---------------------------------------------------------------------------


/* WARNING: Unknown calling convention -- yet parameter storage is locked */

_YK_WNDITEM * YkWndImage::GetCurItem(YkWndImage *this)

{
  short sVar1;
  _YK_WNDITEM *p_Var2;
  int iVar3;
  int iVar4;
  long lVar5;
  
  lVar5 = 0;
  do {
    if (*(short *)&this->m_itemmax <= lVar5) {
      return (_YK_WNDITEM *)0x0;
    }
    p_Var2 = this->m_item + (int)lVar5;
    if ((p_Var2->stat & 1U) != 0) {
      sVar1 = fptosi((float)(int)*(short *)&this->m_idiffx +
                     this->m_zx + (float)(int)*(short *)&this->m_cx / this->m_scale + 0.5);
      iVar3 = (int)*(short *)&p_Var2->x - (int)sVar1;
      sVar1 = fptosi((float)(int)*(short *)&this->m_idiffy +
                     this->m_zy + (float)(int)*(short *)&this->m_cy / this->m_scale + 0.5);
      iVar4 = (int)*(short *)&p_Var2->y - (int)sVar1;
      if (iVar3 < 0) {
        iVar3 = -iVar3;
      }
      if (iVar4 < 0) {
        iVar4 = -iVar4;
      }
      if ((iVar3 < 5) && (iVar4 < 5)) {
        return p_Var2;
      }
    }
    lVar5 = (long)((int)lVar5 + 1);
  } while( true );
}



// ---------------------------------------------------------------------------
// SetAnimeCursor
// YkWndImage::SetAnimeCursor(YmMenuShapeFile *)
//   symbol: SetAnimeCursor__10YkWndImageFP15YmMenuShapeFile
//   rva:    0x002cd350  size: 176 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndImage.cpp
// ---------------------------------------------------------------------------


/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void YkWndImage::SetAnimeCursor(YkWndImage *this,YmMenuShapeFile *cur)

{
  if (*(int *)&this->field_0x8 == 0) {
    this->m_animecur = '\0';
  }
  else if (cur == (YmMenuShapeFile *)0x0) {
    *(undefined1 *)(*(int *)&this->field_0x8 + 0x62) = 0;
    this->m_animecur = '\0';
  }
  else {
    CTkMenuCtrlData::SetCursolShape(*(undefined4 *)&this->field_0x8,cur,0,1)
    ;
    *(undefined1 *)(*(int *)&this->field_0x8 + 0x62) = 1;
    this->m_animecur = '\x01';
  }
  return;
}

