// AUTOGENERATED by ffxi-decomp. Do not edit by hand.
// version: 972 (sha256=d4622c1cc4a3012c, image_base=0x00100000)
// source:  main/yk/ykWndPasswd.cpp
// functions: 8


// ---------------------------------------------------------------------------
// Clear
// YkWndPasswd::Clear(void)
//   symbol: Clear__11YkWndPasswdFv
//   rva:    0x0034b150  size: 44 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndPasswd.cpp
// ---------------------------------------------------------------------------


/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void YkWndPasswd::Clear(YkWndPasswd *this)

{
  *(undefined4 *)&this->field_0x14 = 0;
  this->m_user = (void *)0x0;
  this->m_pass = '\0';
  return;
}



// ---------------------------------------------------------------------------
// PassEditCallBack
// YkWndPasswd::PassEditCallBack(FS_TEXTINPUT, char *, void *)
//   symbol: PassEditCallBack__11YkWndPasswdF12FS_TEXTINPUTPcPv
//   rva:    0x0034b180  size: 56 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndPasswd.cpp
// ---------------------------------------------------------------------------


void YkWndPasswd::PassEditCallBack
               (undefined8 user,undefined8 param_2,int param_3)

{
  (**(code **)(*(int *)(param_3 + 4) + 0x20))(param_3,0x11);
  return;
}



// ---------------------------------------------------------------------------
// Open
// YkWndPasswd::Open(void)
//   symbol: Open__11YkWndPasswdFPFPvPc_vPv
//   rva:    0x0034b1c0  size: 152 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndPasswd.cpp
// ---------------------------------------------------------------------------


/* WARNING: Unknown calling convention -- yet parameter storage is locked */

undefined4 YkWndPasswd::Open(YkWndPasswd *this)

{
  undefined4 uVar1;
  undefined4 in_a1_lo;
  void *in_a2_lo;
  
  if (*(int *)&this->field_0x14 == 0) {
    *(undefined4 *)&this->field_0x14 = in_a1_lo;
    this->m_user = in_a2_lo;
    CTkMenuMng::CreateDrawMenu((CTkMenuMng *)&g_TkMenuMng,_2021,'\x01','\0');
    if (*(int *)&this->field_0x8 == 0) {
      uVar1 = 0;
    }
    else {
      uVar1 = 1;
    }
  }
  else {
    uVar1 = 0;
  }
  return uVar1;
}



// ---------------------------------------------------------------------------
// Close
// YkWndPasswd::Close(void)
//   symbol: Close__11YkWndPasswdFv
//   rva:    0x0034b260  size: 56 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndPasswd.cpp
// ---------------------------------------------------------------------------


/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void YkWndPasswd::Close(YkWndPasswd *this)

{
  CTkMenuMng::DestroyDrawMenu
            ((CTkMenuMng *)&g_TkMenuMng,*(CTkMenuCtrlData **)&this->field_0x8,'\x01');
  return;
}



// ---------------------------------------------------------------------------
// OnInitialUpdatePrimitive
// YkWndPasswd::OnInitialUpdatePrimitive(void)
//   symbol: OnInitialUpdatePrimitive__11YkWndPasswdFv
//   rva:    0x0034b2a0  size: 196 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndPasswd.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void YkWndPasswd::OnInitialUpdatePrimitive(YkWndPasswd *this)

{
  XiTextInputContext *pXVar1;
  long lVar2;
  
  if (this->m_edit == (XiTextInputContext *)0x0) {
    lVar2 = __nw__FUi(0x6b4);
    pXVar1 = (XiTextInputContext *)0x0;
    if (lVar2 != 0) {
      pXVar1 = (XiTextInputContext *)
               XiTextInputContext::XiTextInputContext
                         (lVar2,6,0x10,this,0x44b180,0x53c8e8,0x14a,0xf);
    }
    this->m_edit = pXVar1;
  }
  XiTextInputManager::textInputManagerOff(_g_xiTextInputManager);
  XiTextInputManager::textInputManagerOn
            (_g_xiTextInputManager,(XiTextInputContext *)this->m_edit);
  *(undefined1 *)(_g_pDrawMessageWindow + 0x2c) = 1;
  return;
}



// ---------------------------------------------------------------------------
// OnDestroyPrimitive
// YkWndPasswd::OnDestroyPrimitive(void)
//   symbol: OnDestroyPrimitive__11YkWndPasswdFv
//   rva:    0x0034b370  size: 176 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndPasswd.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void YkWndPasswd::OnDestroyPrimitive(YkWndPasswd *this)

{
  XiTextInputContext *pXVar1;
  
  *(undefined4 *)&this->field_0x14 = 0;
  this->m_user = (void *)0x0;
  this->m_pass = '\0';
  if (this->m_edit != (XiTextInputContext *)0x0) {
    if (this->m_edit != (XiTextInputContext *)0x0) {
      pXVar1 = this->m_edit;
      if (pXVar1 != (XiTextInputContext *)0x0) {
        (**(code **)(*(int *)pXVar1 + 0x20))(pXVar1,1);
      }
      this->m_edit = (XiTextInputContext *)0x0;
    }
    XiTextInputManager::textInputManagerOn
              (_g_xiTextInputManager,(XiTextInputContext *)0x0);
  }
  *(undefined1 *)(_g_pDrawMessageWindow + 0x2c) = 0;
  return;
}



// ---------------------------------------------------------------------------
// OnDrawPrimitive
// YkWndPasswd::OnDrawPrimitive(void)
//   symbol: OnDrawPrimitive__11YkWndPasswdFv
//   rva:    0x0034b420  size: 204 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndPasswd.cpp
// ---------------------------------------------------------------------------


/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void YkWndPasswd::OnDrawPrimitive(YkWndPasswd *this)

{
  char *arg1;
  int arg2;
  short sStack_18;
  short sStack_16;
  YkWndPasswd *pYStack_10;
  
  pYStack_10 = this;
  CTkMenuCtrlData::GetWindowLocate
            (*(CTkMenuCtrlData **)&this->field_0x8,(TKRECT *)&sStack_18);
  if (pYStack_10->m_edit != (XiTextInputContext *)0x0) {
    arg1 = (char *)XiTextInputContext::getDisplayString(pYStack_10->m_edit);
    arg2 = XiTextInputContext::getDisplayStringLen(pYStack_10->m_edit);
    XiTextInputContext::displayText
              (pYStack_10->m_edit,arg1,arg2,(int)(short)(sStack_18 + 0x50),
               (int)(short)(sStack_16 + 4),200,'\x01');
  }
  return;
}



// ---------------------------------------------------------------------------
// OnKeyDown
// YkWndPasswd::OnKeyDown(short, short)
//   symbol: OnKeyDown__11YkWndPasswdFss
//   rva:    0x0034b4f0  size: 404 bytes  tool: ghidra-12.0.4
//   source: main/yk/ykWndPasswd.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void YkWndPasswd::OnKeyDown(int this,short param_2)

{
  int *piVar1;
  char *__src;
  
  if (param_2 == 3) {
    XiTextInputManager::doKeydown(_g_xiTextInputManager,5);
  }
  else if (param_2 == 4) {
    XiTextInputManager::doKeydown(_g_xiTextInputManager,4);
  }
  else if (param_2 == 5) {
    XiTextInputManager::doKeydown(_g_xiTextInputManager,1);
  }
  else if (param_2 == 0x11) {
    __src = (char *)XiTextInputContext::getString(*(XiTextInputContext **)(this + 0x30),'\0');
    strcpy((char *)(this + 0x1c),__src);
    if (*(int *)(this + 0x30) != 0) {
      piVar1 = *(int **)(this + 0x30);
      if (piVar1 != (int *)0x0) {
        (**(code **)(*piVar1 + 0x20))(piVar1,1);
      }
      *(undefined4 *)(this + 0x30) = 0;
    }
    XiTextInputManager::textInputManagerOn
              (_g_xiTextInputManager,(XiTextInputContext *)0x0);
    if (*(int *)(this + 0x14) != 0) {
      (**(code **)(this + 0x14))(*(undefined4 *)(this + 0x18),this + 0x1c);
    }
    *(undefined4 *)(this + 0x14) = 0;
    *(undefined4 *)(this + 0x18) = 0;
    *(undefined1 *)(this + 0x1c) = 0;
    CTkMenuMng::DestroyDrawMenu
              ((CTkMenuMng *)&g_TkMenuMng,*(CTkMenuCtrlData **)(this + 8),'\x01');
  }
  return;
}

