// AUTOGENERATED by ffxi-decomp. Do not edit by hand.
// version: 972 (sha256=d4622c1cc4a3012c, image_base=0x00100000)
// source:  main/miyagawa/ymmem.h
// functions: 7


// ---------------------------------------------------------------------------
// GetTail
// YmElemMcb::GetTail(void)
//   symbol: GetTail__9YmElemMcbFv
//   rva:    0x00001390  size: 12 bytes  tool: ghidra-12.0.4
//   source: main/miyagawa/ymmem.h
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

undefined4 YmElemMcb::GetTail(YmElemMcb *this)

{
  return _tail__9YmElemMcb;
}



// ---------------------------------------------------------------------------
// GetHead
// YmElemMcb::GetHead(void)
//   symbol: GetHead__9YmElemMcbFv
//   rva:    0x000013a0  size: 12 bytes  tool: ghidra-12.0.4
//   source: main/miyagawa/ymmem.h
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

undefined4 YmElemMcb::GetHead(YmElemMcb *this)

{
  return _head__9YmElemMcb;
}



// ---------------------------------------------------------------------------
// OnEndGarbageCollection
// YmMcb::OnEndGarbageCollection(YmMcb *)
//   symbol: OnEndGarbageCollection__5YmMcbFP5YmMcb
//   rva:    0x00002120  size: 16 bytes  tool: ghidra-12.0.4
//   source: main/miyagawa/ymmem.h
// ---------------------------------------------------------------------------


/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void YmMcb::OnEndGarbageCollection(YmMcb *this,YmMcb *arg1)

{
  return;
}



// ---------------------------------------------------------------------------
// OnBeginGarbageCollection
// YmMcb::OnBeginGarbageCollection(YmMcb *)
//   symbol: OnBeginGarbageCollection__5YmMcbFP5YmMcb
//   rva:    0x00002130  size: 16 bytes  tool: ghidra-12.0.4
//   source: main/miyagawa/ymmem.h
// ---------------------------------------------------------------------------


/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void YmMcb::OnBeginGarbageCollection(YmMcb *this,YmMcb *arg1)

{
  return;
}



// ---------------------------------------------------------------------------
// @160@OnDeleteCaster
// [thunk] XiDollActor::OnDeleteCaster(void)
//   symbol: @160@OnDeleteCaster__11XiDollActorFv
//   rva:    0x001eeb20  size: 8 bytes  tool: ghidra-12.0.4
//   source: main/miyagawa/ymmem.h
// ---------------------------------------------------------------------------


/* WARNING: Unknown calling convention -- yet parameter storage is locked */

undefined4 _160_OnDeleteCaster__11XiDollActorFv(XiDollActor *this)

{
  undefined1 *puVar1;
  
  puVar1 = &this[-1].field_0x350;
  if (puVar1 != (undefined1 *)0x0) {
    (**(code **)(*(int *)puVar1 + 0x194))(puVar1,1);
  }
  return 1;
}



// ---------------------------------------------------------------------------
// @16@OnDeleteTarget
// [thunk] YmLoadResourceTask::OnDeleteTarget(void)
//   symbol: @16@OnDeleteTarget__18YmLoadResourceTaskFv
//   rva:    0x00280790  size: 8 bytes  tool: ghidra-12.0.4
//   source: main/miyagawa/ymmem.h
// ---------------------------------------------------------------------------


/* WARNING: Unknown calling convention -- yet parameter storage is locked */

undefined8 _16_OnDeleteTarget__18YmLoadResourceTaskFv(YmLoadResourceTask *this)

{
  YmLoadResourceTask::OnDeleteActor((YmLoadResourceTask *)&this[-1].file);
  return 0;
}



// ---------------------------------------------------------------------------
// @16@OnDeleteCaster
// [thunk] YmLoadResourceTask::OnDeleteCaster(void)
//   symbol: @16@OnDeleteCaster__18YmLoadResourceTaskFv
//   rva:    0x002807a0  size: 8 bytes  tool: ghidra-12.0.4
//   source: main/miyagawa/ymmem.h
// ---------------------------------------------------------------------------


/* WARNING: Unknown calling convention -- yet parameter storage is locked */

undefined8 _16_OnDeleteCaster__18YmLoadResourceTaskFv(YmLoadResourceTask *this)

{
  YmLoadResourceTask::OnDeleteActor((YmLoadResourceTask *)&this[-1].file);
  return 0;
}

