// AUTOGENERATED by ffxi-decomp. Do not edit by hand.
// version: 972 (sha256=d4622c1cc4a3012c, image_base=0x00100000)
// source:  main/net/game_cli/gcauction.c
// functions: 25


// ---------------------------------------------------------------------------
// updateAucBoxWork
// updateAucBoxWork(GC_AUC_SYS *, int, GP_SERV_AUC *)
//   symbol: updateAucBoxWork__FP10GC_AUC_SYSiP11GP_SERV_AUC
//   rva:    0x003aff10  size: 260 bytes  tool: ghidra-12.0.4
//   source: main/net/game_cli/gcauction.c
// ---------------------------------------------------------------------------


void updateAucBoxWork__FP10GC_AUC_SYSiP11GP_SERV_AUC(int pAucSys,uint index,int pRecv)

{
  int iVar1;
  
  if ((((pAucSys != 0) && (-1 < (int)index)) && ((int)index < 8)) && (pRecv != 0)) {
    iVar1 = pAucSys + index * 0x28;
    *(undefined1 *)(iVar1 + 0x28) = *(undefined1 *)(pRecv + 0x14);
    memcpy((void *)(iVar1 + 0x2c),(void *)(pRecv + 0x18),0x10);
    *(undefined2 *)(iVar1 + 0x3c) = *(undefined2 *)(pRecv + 0x28);
    *(undefined1 *)(iVar1 + 0x3e) = *(undefined1 *)(pRecv + 0x2a);
    *(undefined1 *)(iVar1 + 0x3f) = *(undefined1 *)(pRecv + 0x2b);
    *(undefined4 *)(iVar1 + 0x40) = *(undefined4 *)(pRecv + 0x2c);
    *(undefined4 *)(iVar1 + 0x44) = *(undefined4 *)(pRecv + 0x30);
    *(undefined4 *)(iVar1 + 0x48) = *(undefined4 *)(pRecv + 0x34);
    *(undefined4 *)(iVar1 + 0x4c) = *(undefined4 *)(pRecv + 0x38);
    *(uint *)(pAucSys + 0xc) = *(uint *)(pAucSys + 0xc) | 1 << (index & 0x1f);
  }
  return;
}



// ---------------------------------------------------------------------------
// updateAucBoxUseCount
// updateAucBoxUseCount(GC_AUC_SYS *)
//   symbol: updateAucBoxUseCount__FP10GC_AUC_SYS
//   rva:    0x003b0020  size: 128 bytes  tool: ghidra-12.0.4
//   source: main/net/game_cli/gcauction.c
// ---------------------------------------------------------------------------


void updateAucBoxUseCount__FP10GC_AUC_SYS(char *pAucSys)

{
  char *pcVar1;
  int iVar2;
  
  if (pAucSys != (char *)0x0) {
    iVar2 = 0;
    pcVar1 = pAucSys;
    while (pcVar1 = pcVar1 + 0x28, pcVar1 < pAucSys + 0x168) {
      if (*pcVar1 != '\0') {
        iVar2 = iVar2 + 1;
      }
    }
    *(int *)(pAucSys + 0x10) = iVar2;
  }
  return;
}



// ---------------------------------------------------------------------------
// SendAuction_Transfer
//   symbol: SendAuction_Transfer
//   rva:    0x003b00a0  size: 340 bytes  tool: ghidra-12.0.4
//   source: main/net/game_cli/gcauction.c
// ---------------------------------------------------------------------------


undefined1 SendAuction_Transfer(undefined4 addr,undefined4 size)

{
  long lVar1;
  int iVar2;
  undefined1 uVar3;
  
  lVar1 = gcZoneSendQueSearch(0x4e,1);
  iVar2 = (int)lVar1;
  if (lVar1 == 0) {
    uVar3 = 0;
    wng_print(0x53f740,addr,size);
  }
  else {
    *(undefined1 *)(iVar2 + 4) = 1;
    *(undefined1 *)(iVar2 + 5) = 0;
    *(undefined1 *)(iVar2 + 6) = 0;
    *(undefined1 *)(iVar2 + 7) = 0;
    memset((void *)(iVar2 + 8),0,0xc);
    memset((void *)(iVar2 + 0x14),0,0x28);
    *(undefined2 *)(iVar2 + 8) = 0x4254;
    *(undefined2 *)(iVar2 + 10) = 0;
    *(undefined2 *)(iVar2 + 0xc) = 0;
    *(undefined2 *)(iVar2 + 0xe) = 0;
    *(undefined2 *)(iVar2 + 0x10) = 1;
    *(undefined2 *)(iVar2 + 0x12) = 1;
    if (lVar1 != 0) {
      gcZoneSendQueSet(lVar1,0x3c);
    }
    uVar3 = 1;
    dump_AUC_packet__FcPv(0x53,lVar1);
  }
  return uVar3;
}



// ---------------------------------------------------------------------------
// SendAuction_MenuControl
//   symbol: SendAuction_MenuControl
//   rva:    0x003b0200  size: 296 bytes  tool: ghidra-12.0.4
//   source: main/net/game_cli/gcauction.c
// ---------------------------------------------------------------------------


undefined1 SendAuction_MenuControl(undefined4 command)

{
  long lVar1;
  int iVar2;
  undefined1 uVar3;
  undefined1 uStack_10;
  
  lVar1 = gcZoneSendQueSearch(0x4e,1);
  if (lVar1 == 0) {
    uVar3 = 0;
    wng_print(0x53f760,command);
  }
  else {
    uStack_10 = (undefined1)command;
    iVar2 = (int)lVar1;
    *(undefined1 *)(iVar2 + 4) = uStack_10;
    *(undefined1 *)(iVar2 + 5) = 0;
    *(undefined1 *)(iVar2 + 6) = 0;
    *(undefined1 *)(iVar2 + 7) = 0;
    memset((void *)(iVar2 + 8),0,0xc);
    memset((void *)(iVar2 + 0x14),0,0x28);
    if (lVar1 != 0) {
      gcZoneSendQueSet(lVar1,0x3c);
    }
    uVar3 = 1;
    dump_AUC_packet__FcPv(0x53,lVar1);
  }
  return uVar3;
}



// ---------------------------------------------------------------------------
// SendAuction_AskCommit
//   symbol: SendAuction_AskCommit
//   rva:    0x003b0330  size: 524 bytes  tool: ghidra-12.0.4
//   source: main/net/game_cli/gcauction.c
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined1 SendAuction_AskCommit(int commission,int itemWorkIndex,int itemNo,undefined4 itemStacks)

{
  long lVar1;
  int iVar2;
  bool bVar3;
  undefined1 uVar4;
  undefined2 uStack_30;
  undefined2 uStack_20;
  
  bVar3 = true;
  if ((((commission < 0) || (itemWorkIndex < 0)) || (itemNo < 0)) || (0xffff < itemNo)) {
    bVar3 = false;
  }
  else if (_pGlobalNowZone == 0) {
    bVar3 = false;
  }
  else {
    *(undefined4 *)(_pGlobalNowZone + 0x198d8) = 0;
    *(undefined4 *)(_pGlobalNowZone + 0x198dc) = 0;
    *(undefined4 *)(_pGlobalNowZone + 0x198e0) = 0;
    *(undefined4 *)(_pGlobalNowZone + 0x198e4) = 0;
    *(undefined4 *)(_pGlobalNowZone + 0x198e8) = 0;
  }
  uVar4 = 0;
  if (bVar3) {
    lVar1 = gcZoneSendQueSearch(0x4e,1);
    iVar2 = (int)lVar1;
    if (lVar1 == 0) {
      uVar4 = 0;
      wng_print(0x53f780,commission,itemWorkIndex,itemNo,itemStacks);
    }
    else {
      *(undefined1 *)(iVar2 + 4) = 4;
      *(undefined1 *)(iVar2 + 5) = 0;
      *(undefined1 *)(iVar2 + 6) = 0;
      *(undefined1 *)(iVar2 + 7) = 0;
      memset((void *)(iVar2 + 8),0,0xc);
      memset((void *)(iVar2 + 0x14),0,0x28);
      *(int *)(iVar2 + 8) = commission;
      uStack_30 = (undefined2)itemWorkIndex;
      *(undefined2 *)(iVar2 + 0xc) = uStack_30;
      uStack_20 = (undefined2)itemNo;
      *(undefined2 *)(iVar2 + 0xe) = uStack_20;
      *(undefined4 *)(iVar2 + 0x10) = itemStacks;
      if (lVar1 != 0) {
        gcZoneSendQueSet(lVar1,0x3c);
      }
      uVar4 = 1;
      dump_AUC_packet__FcPv(0x53,lVar1);
    }
  }
  return uVar4;
}



// ---------------------------------------------------------------------------
// SendAuction_Info
//   symbol: SendAuction_Info
//   rva:    0x003b0540  size: 272 bytes  tool: ghidra-12.0.4
//   source: main/net/game_cli/gcauction.c
// ---------------------------------------------------------------------------


undefined1 SendAuction_Info(void)

{
  long lVar1;
  int iVar2;
  undefined1 uVar3;
  
  lVar1 = gcZoneSendQueSearch(0x4e,1);
  if (lVar1 == 0) {
    uVar3 = 0;
    wng_print(0x53f7b0);
  }
  else {
    iVar2 = (int)lVar1;
    *(undefined1 *)(iVar2 + 4) = 5;
    *(undefined1 *)(iVar2 + 5) = 0;
    *(undefined1 *)(iVar2 + 6) = 0;
    *(undefined1 *)(iVar2 + 7) = 0;
    memset((void *)(iVar2 + 8),0,0xc);
    memset((void *)(iVar2 + 0x14),0,0x28);
    if (lVar1 != 0) {
      gcZoneSendQueSet(lVar1,0x3c);
    }
    uVar3 = 1;
    dump_AUC_packet__FcPv(0x53,lVar1);
  }
  return uVar3;
}



// ---------------------------------------------------------------------------
// SendAuction_work
//   symbol: SendAuction_work
//   rva:    0x003b0650  size: 500 bytes  tool: ghidra-12.0.4
//   source: main/net/game_cli/gcauction.c
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined1 SendAuction_work(uint aucWorkIndex)

{
  long lVar1;
  int iVar2;
  bool bVar3;
  undefined1 uVar4;
  uint uVar5;
  undefined1 uStack_10;
  
  bVar3 = true;
  wng_print(0x53f7d0,aucWorkIndex);
  if (((int)aucWorkIndex < -1) || (7 < (int)aucWorkIndex)) {
    bVar3 = false;
  }
  uVar4 = 0;
  if (bVar3) {
    lVar1 = gcZoneSendQueSearch(0x4e,1);
    iVar2 = (int)lVar1;
    if (lVar1 == 0) {
      uVar4 = 0;
      wng_print(0x53f7f0);
    }
    else {
      *(undefined1 *)(iVar2 + 4) = 10;
      *(undefined1 *)(iVar2 + 5) = 0;
      *(undefined1 *)(iVar2 + 6) = 0;
      *(undefined1 *)(iVar2 + 7) = 0;
      memset((void *)(iVar2 + 8),0,0xc);
      memset((void *)(iVar2 + 0x14),0,0x28);
      uVar5 = 0;
      if (aucWorkIndex == 0xffffffff) {
        uVar5 = 0xff;
      }
      else if ((-1 < (int)aucWorkIndex) && ((int)aucWorkIndex < 8)) {
        uVar5 = 1 << (aucWorkIndex & 0x1f) & 0xff;
      }
      if ((uVar5 != 0) && (_pGlobalNowZone != 0)) {
        *(uint *)(_pGlobalNowZone + 0x198d0) = *(uint *)(_pGlobalNowZone + 0x198d0) & ~uVar5;
      }
      uStack_10 = (undefined1)aucWorkIndex;
      *(undefined1 *)(iVar2 + 5) = uStack_10;
      if (lVar1 != 0) {
        gcZoneSendQueSet(lVar1,0x3c);
      }
      uVar4 = 1;
      dump_AUC_packet__FcPv(0x53,lVar1);
    }
  }
  return uVar4;
}



// ---------------------------------------------------------------------------
// SendAuction_LotIn
//   symbol: SendAuction_LotIn
//   rva:    0x003b0850  size: 632 bytes  tool: ghidra-12.0.4
//   source: main/net/game_cli/gcauction.c
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined1 SendAuction_LotIn(uint aucWorkIndex,int itemWorkIndex,int limitPrice,int itemStacks)

{
  long lVar1;
  int iVar2;
  bool bVar3;
  undefined1 uVar4;
  uint uVar5;
  undefined1 uStack_40;
  undefined2 uStack_30;
  
  bVar3 = true;
  wng_print(0x53f820,aucWorkIndex,itemWorkIndex,limitPrice,itemStacks);
  if (((int)aucWorkIndex < 0) || (7 < (int)aucWorkIndex)) {
    bVar3 = false;
  }
  if ((itemWorkIndex < 0) || (0x50 < itemWorkIndex)) {
    bVar3 = false;
  }
  if ((limitPrice < 1) || (999999999 < limitPrice)) {
    bVar3 = false;
  }
  if (itemStacks < 0) {
    bVar3 = false;
  }
  uVar4 = 0;
  if (bVar3) {
    lVar1 = gcZoneSendQueSearch(0x4e,1);
    iVar2 = (int)lVar1;
    if (lVar1 == 0) {
      uVar4 = 0;
      wng_print(0x53f850);
    }
    else {
      *(undefined1 *)(iVar2 + 4) = 0xb;
      *(undefined1 *)(iVar2 + 5) = 0;
      *(undefined1 *)(iVar2 + 6) = 0;
      *(undefined1 *)(iVar2 + 7) = 0;
      memset((void *)(iVar2 + 8),0,0xc);
      memset((void *)(iVar2 + 0x14),0,0x28);
      uVar5 = 0;
      if (aucWorkIndex == 0xffffffff) {
        uVar5 = 0xff;
      }
      else if ((-1 < (int)aucWorkIndex) && ((int)aucWorkIndex < 8)) {
        uVar5 = 1 << (aucWorkIndex & 0x1f) & 0xff;
      }
      if ((uVar5 != 0) && (_pGlobalNowZone != 0)) {
        *(uint *)(_pGlobalNowZone + 0x198d0) = *(uint *)(_pGlobalNowZone + 0x198d0) & ~uVar5;
      }
      uStack_40 = (undefined1)aucWorkIndex;
      *(undefined1 *)(iVar2 + 5) = uStack_40;
      *(int *)(iVar2 + 8) = limitPrice;
      uStack_30 = (undefined2)itemWorkIndex;
      *(undefined2 *)(iVar2 + 0xc) = uStack_30;
      *(int *)(iVar2 + 0x10) = itemStacks;
      if (lVar1 != 0) {
        gcZoneSendQueSet(lVar1,0x3c);
      }
      uVar4 = 1;
      dump_AUC_packet__FcPv(0x53,lVar1);
    }
  }
  return uVar4;
}



// ---------------------------------------------------------------------------
// SendAuction_LotCancel
//   symbol: SendAuction_LotCancel
//   rva:    0x003b0ad0  size: 496 bytes  tool: ghidra-12.0.4
//   source: main/net/game_cli/gcauction.c
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined1 SendAuction_LotCancel(uint aucWorkIndex)

{
  long lVar1;
  int iVar2;
  bool bVar3;
  undefined1 uVar4;
  uint uVar5;
  undefined1 uStack_10;
  
  bVar3 = true;
  wng_print(0x53f890,aucWorkIndex);
  if (((int)aucWorkIndex < 0) || (7 < (int)aucWorkIndex)) {
    bVar3 = false;
  }
  uVar4 = 0;
  if (bVar3) {
    lVar1 = gcZoneSendQueSearch(0x4e,1);
    iVar2 = (int)lVar1;
    if (lVar1 == 0) {
      uVar4 = 0;
      wng_print(0x53f8b0);
    }
    else {
      *(undefined1 *)(iVar2 + 4) = 0xc;
      *(undefined1 *)(iVar2 + 5) = 0;
      *(undefined1 *)(iVar2 + 6) = 0;
      *(undefined1 *)(iVar2 + 7) = 0;
      memset((void *)(iVar2 + 8),0,0xc);
      memset((void *)(iVar2 + 0x14),0,0x28);
      uVar5 = 0;
      if (aucWorkIndex == 0xffffffff) {
        uVar5 = 0xff;
      }
      else if ((-1 < (int)aucWorkIndex) && ((int)aucWorkIndex < 8)) {
        uVar5 = 1 << (aucWorkIndex & 0x1f) & 0xff;
      }
      if ((uVar5 != 0) && (_pGlobalNowZone != 0)) {
        *(uint *)(_pGlobalNowZone + 0x198d0) = *(uint *)(_pGlobalNowZone + 0x198d0) & ~uVar5;
      }
      uStack_10 = (undefined1)aucWorkIndex;
      *(undefined1 *)(iVar2 + 5) = uStack_10;
      if (lVar1 != 0) {
        gcZoneSendQueSet(lVar1,0x3c);
      }
      uVar4 = 1;
      dump_AUC_packet__FcPv(0x53,lVar1);
    }
  }
  return uVar4;
}



// ---------------------------------------------------------------------------
// SendAuction_LotCheck
//   symbol: SendAuction_LotCheck
//   rva:    0x003b0cc0  size: 496 bytes  tool: ghidra-12.0.4
//   source: main/net/game_cli/gcauction.c
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined1 SendAuction_LotCheck(uint aucWorkIndex)

{
  long lVar1;
  int iVar2;
  bool bVar3;
  undefined1 uVar4;
  uint uVar5;
  undefined1 uStack_10;
  
  bVar3 = true;
  wng_print(0x53f8f0,aucWorkIndex);
  if (((int)aucWorkIndex < 0) || (7 < (int)aucWorkIndex)) {
    bVar3 = false;
  }
  uVar4 = 0;
  if (bVar3) {
    lVar1 = gcZoneSendQueSearch(0x4e,1);
    iVar2 = (int)lVar1;
    if (lVar1 == 0) {
      uVar4 = 0;
      wng_print(0x53f910);
    }
    else {
      *(undefined1 *)(iVar2 + 4) = 0xd;
      *(undefined1 *)(iVar2 + 5) = 0;
      *(undefined1 *)(iVar2 + 6) = 0;
      *(undefined1 *)(iVar2 + 7) = 0;
      memset((void *)(iVar2 + 8),0,0xc);
      memset((void *)(iVar2 + 0x14),0,0x28);
      uVar5 = 0;
      if (aucWorkIndex == 0xffffffff) {
        uVar5 = 0xff;
      }
      else if ((-1 < (int)aucWorkIndex) && ((int)aucWorkIndex < 8)) {
        uVar5 = 1 << (aucWorkIndex & 0x1f) & 0xff;
      }
      if ((uVar5 != 0) && (_pGlobalNowZone != 0)) {
        *(uint *)(_pGlobalNowZone + 0x198d0) = *(uint *)(_pGlobalNowZone + 0x198d0) & ~uVar5;
      }
      uStack_10 = (undefined1)aucWorkIndex;
      *(undefined1 *)(iVar2 + 5) = uStack_10;
      if (lVar1 != 0) {
        gcZoneSendQueSet(lVar1,0x3c);
      }
      uVar4 = 1;
      dump_AUC_packet__FcPv(0x53,lVar1);
    }
  }
  return uVar4;
}



// ---------------------------------------------------------------------------
// SendAuction_Bid
//   symbol: SendAuction_Bid
//   rva:    0x003b0eb0  size: 652 bytes  tool: ghidra-12.0.4
//   source: main/net/game_cli/gcauction.c
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined1 SendAuction_Bid(uint aucWorkIndex,int itemNo,int bidPrice,int itemStacks)

{
  long lVar1;
  int iVar2;
  bool bVar3;
  undefined1 uVar4;
  uint uVar5;
  undefined1 uStack_40;
  undefined2 uStack_30;
  
  bVar3 = true;
  wng_print(0x53f950,aucWorkIndex,itemNo,bidPrice,itemStacks);
  if (((int)aucWorkIndex < 0) || (7 < (int)aucWorkIndex)) {
    bVar3 = false;
  }
  if ((itemNo < 1) || (0xffff < itemNo)) {
    bVar3 = false;
  }
  if ((bidPrice < 1) || (999999999 < bidPrice)) {
    bVar3 = false;
  }
  if ((itemStacks < 0) || (99 < itemStacks)) {
    bVar3 = false;
  }
  uVar4 = 0;
  if (bVar3) {
    lVar1 = gcZoneSendQueSearch(0x4e,1);
    iVar2 = (int)lVar1;
    if (lVar1 == 0) {
      uVar4 = 0;
      wng_print(0x53f980);
    }
    else {
      *(undefined1 *)(iVar2 + 4) = 0xe;
      *(undefined1 *)(iVar2 + 5) = 0;
      *(undefined1 *)(iVar2 + 6) = 0;
      *(undefined1 *)(iVar2 + 7) = 0;
      memset((void *)(iVar2 + 8),0,0xc);
      memset((void *)(iVar2 + 0x14),0,0x28);
      uVar5 = 0;
      if (aucWorkIndex == 0xffffffff) {
        uVar5 = 0xff;
      }
      else if ((-1 < (int)aucWorkIndex) && ((int)aucWorkIndex < 8)) {
        uVar5 = 1 << (aucWorkIndex & 0x1f) & 0xff;
      }
      if ((uVar5 != 0) && (_pGlobalNowZone != 0)) {
        *(uint *)(_pGlobalNowZone + 0x198d0) = *(uint *)(_pGlobalNowZone + 0x198d0) & ~uVar5;
      }
      uStack_40 = (undefined1)aucWorkIndex;
      *(undefined1 *)(iVar2 + 5) = uStack_40;
      *(int *)(iVar2 + 8) = bidPrice;
      uStack_30 = (undefined2)itemNo;
      *(undefined2 *)(iVar2 + 0xc) = uStack_30;
      *(int *)(iVar2 + 0x10) = itemStacks;
      if (lVar1 != 0) {
        gcZoneSendQueSet(lVar1,0x3c);
      }
      uVar4 = 1;
      dump_AUC_packet__FcPv(0x53,lVar1);
    }
  }
  return uVar4;
}



// ---------------------------------------------------------------------------
// SendAuction_Get
//   symbol: SendAuction_Get
//   rva:    0x003b1140  size: 496 bytes  tool: ghidra-12.0.4
//   source: main/net/game_cli/gcauction.c
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined1 SendAuction_Get(uint aucWorkIndex)

{
  long lVar1;
  int iVar2;
  bool bVar3;
  undefined1 uVar4;
  uint uVar5;
  undefined1 uStack_10;
  
  bVar3 = true;
  wng_print(0x53f9c0,aucWorkIndex);
  if (((int)aucWorkIndex < 0) || (7 < (int)aucWorkIndex)) {
    bVar3 = false;
  }
  uVar4 = 0;
  if (bVar3) {
    lVar1 = gcZoneSendQueSearch(0x4e,1);
    iVar2 = (int)lVar1;
    if (lVar1 == 0) {
      uVar4 = 0;
      wng_print(0x53f9e0);
    }
    else {
      *(undefined1 *)(iVar2 + 4) = 0xf;
      *(undefined1 *)(iVar2 + 5) = 0;
      *(undefined1 *)(iVar2 + 6) = 0;
      *(undefined1 *)(iVar2 + 7) = 0;
      memset((void *)(iVar2 + 8),0,0xc);
      memset((void *)(iVar2 + 0x14),0,0x28);
      uVar5 = 0;
      if (aucWorkIndex == 0xffffffff) {
        uVar5 = 0xff;
      }
      else if ((-1 < (int)aucWorkIndex) && ((int)aucWorkIndex < 8)) {
        uVar5 = 1 << (aucWorkIndex & 0x1f) & 0xff;
      }
      if ((uVar5 != 0) && (_pGlobalNowZone != 0)) {
        *(uint *)(_pGlobalNowZone + 0x198d0) = *(uint *)(_pGlobalNowZone + 0x198d0) & ~uVar5;
      }
      uStack_10 = (undefined1)aucWorkIndex;
      *(undefined1 *)(iVar2 + 5) = uStack_10;
      if (lVar1 != 0) {
        gcZoneSendQueSet(lVar1,0x3c);
      }
      uVar4 = 1;
      dump_AUC_packet__FcPv(0x53,lVar1);
    }
  }
  return uVar4;
}



// ---------------------------------------------------------------------------
// SendAuction_Clear
//   symbol: SendAuction_Clear
//   rva:    0x003b1330  size: 496 bytes  tool: ghidra-12.0.4
//   source: main/net/game_cli/gcauction.c
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined1 SendAuction_Clear(uint aucWorkIndex)

{
  long lVar1;
  int iVar2;
  bool bVar3;
  undefined1 uVar4;
  uint uVar5;
  undefined1 uStack_10;
  
  bVar3 = true;
  wng_print(0x53fa20,aucWorkIndex);
  if (((int)aucWorkIndex < 0) || (7 < (int)aucWorkIndex)) {
    bVar3 = false;
  }
  uVar4 = 0;
  if (bVar3) {
    lVar1 = gcZoneSendQueSearch(0x4e,1);
    iVar2 = (int)lVar1;
    if (lVar1 == 0) {
      uVar4 = 0;
      wng_print(0x53fa40);
    }
    else {
      *(undefined1 *)(iVar2 + 4) = 0x10;
      *(undefined1 *)(iVar2 + 5) = 0;
      *(undefined1 *)(iVar2 + 6) = 0;
      *(undefined1 *)(iVar2 + 7) = 0;
      memset((void *)(iVar2 + 8),0,0xc);
      memset((void *)(iVar2 + 0x14),0,0x28);
      uVar5 = 0;
      if (aucWorkIndex == 0xffffffff) {
        uVar5 = 0xff;
      }
      else if ((-1 < (int)aucWorkIndex) && ((int)aucWorkIndex < 8)) {
        uVar5 = 1 << (aucWorkIndex & 0x1f) & 0xff;
      }
      if ((uVar5 != 0) && (_pGlobalNowZone != 0)) {
        *(uint *)(_pGlobalNowZone + 0x198d0) = *(uint *)(_pGlobalNowZone + 0x198d0) & ~uVar5;
      }
      uStack_10 = (undefined1)aucWorkIndex;
      *(undefined1 *)(iVar2 + 5) = uStack_10;
      if (lVar1 != 0) {
        gcZoneSendQueSet(lVar1,0x3c);
      }
      uVar4 = 1;
      dump_AUC_packet__FcPv(0x53,lVar1);
    }
  }
  return uVar4;
}



// ---------------------------------------------------------------------------
// RecvAuction_MenuControl
//   symbol: RecvAuction_MenuControl
//   rva:    0x003b1520  size: 96 bytes  tool: ghidra-12.0.4
//   source: main/net/game_cli/gcauction.c
// ---------------------------------------------------------------------------


undefined1 RecvAuction_MenuControl(undefined4 pZone,undefined4 pRecv)

{
  wng_print(0x53fa80,pZone,pRecv);
  dump_AUC_packet__FcPv(0x52,pRecv);
  return 1;
}



// ---------------------------------------------------------------------------
// RecvAuction_AskCommit
//   symbol: RecvAuction_AskCommit
//   rva:    0x003b1580  size: 516 bytes  tool: ghidra-12.0.4
//   source: main/net/game_cli/gcauction.c
// ---------------------------------------------------------------------------


undefined1 RecvAuction_AskCommit(int pZone,int pRecv)

{
  wng_print(0x53faa0,pZone,pRecv);
  dump_AUC_packet__FcPv(0x52,pRecv);
  if (*(char *)(pRecv + 6) == '\x01') {
    *(int *)(pZone + 0x198d8) = (int)*(char *)(pRecv + 7);
    *(undefined4 *)(pZone + 0x198dc) = *(undefined4 *)(pRecv + 8);
    *(uint *)(pZone + 0x198e0) = (uint)*(ushort *)(pRecv + 0xc);
    *(uint *)(pZone + 0x198e4) = (uint)*(ushort *)(pRecv + 0xe);
    *(undefined4 *)(pZone + 0x198e8) = *(undefined4 *)(pRecv + 0x10);
    wng_print(0x53fab8,*(undefined4 *)(pZone + 0x198d8));
    wng_print(0x53fad0,*(undefined4 *)(pZone + 0x198dc));
    wng_print(0x53faf0,*(undefined4 *)(pZone + 0x198e0));
    wng_print(0x53fb00,*(undefined4 *)(pZone + 0x198e4));
    wng_print(0x53fb10,*(undefined4 *)(pZone + 0x198e8));
  }
  if ((pZone != -0x198c4) && (pRecv != 0)) {
    *(uint *)(pZone + 0x198c4) = (uint)*(byte *)(pRecv + 4);
    *(int *)(pZone + 0x198c8) = (int)*(char *)(pRecv + 6);
  }
  return 1;
}



// ---------------------------------------------------------------------------
// RecvAuction_Info
//   symbol: RecvAuction_Info
//   rva:    0x003b1790  size: 192 bytes  tool: ghidra-12.0.4
//   source: main/net/game_cli/gcauction.c
// ---------------------------------------------------------------------------


undefined1 RecvAuction_Info(int pZone,int pRecv)

{
  wng_print(0x53fb30,pZone,pRecv);
  dump_AUC_packet__FcPv(0x52,pRecv);
  if ((pZone != -0x198c4) && (pRecv != 0)) {
    *(uint *)(pZone + 0x198c4) = (uint)*(byte *)(pRecv + 4);
    *(int *)(pZone + 0x198c8) = (int)*(char *)(pRecv + 6);
  }
  return 1;
}



// ---------------------------------------------------------------------------
// RecvAuction_work
//   symbol: RecvAuction_work
//   rva:    0x003b1850  size: 416 bytes  tool: ghidra-12.0.4
//   source: main/net/game_cli/gcauction.c
// ---------------------------------------------------------------------------


undefined1 RecvAuction_work(int pZone,int pRecv)

{
  char cVar1;
  
  wng_print(0x53fb50,pZone,pRecv);
  dump_AUC_packet__FcPv(0x52,pRecv);
  if ((pZone != 0) && (pRecv != 0)) {
    cVar1 = *(char *)(pRecv + 5);
    if ((-1 < cVar1) && (cVar1 < '\b')) {
      updateAucBoxWork__FP10GC_AUC_SYSiP11GP_SERV_AUC(pZone + 0x198c4,cVar1,pRecv);
      updateAucBoxUseCount__FP10GC_AUC_SYS(pZone + 0x198c4);
    }
    if ((pZone != -0x198c4) && (pRecv != 0)) {
      *(uint *)(pZone + 0x198c4) = (uint)*(byte *)(pRecv + 4);
      *(int *)(pZone + 0x198c8) = (int)*(char *)(pRecv + 6);
    }
  }
  if ((pZone != -0x198c4) && (pRecv != 0)) {
    *(uint *)(pZone + 0x198c4) = (uint)*(byte *)(pRecv + 4);
    *(int *)(pZone + 0x198c8) = (int)*(char *)(pRecv + 6);
  }
  return 1;
}



// ---------------------------------------------------------------------------
// RecvAuction_LotIn
//   symbol: RecvAuction_LotIn
//   rva:    0x003b19f0  size: 416 bytes  tool: ghidra-12.0.4
//   source: main/net/game_cli/gcauction.c
// ---------------------------------------------------------------------------


undefined1 RecvAuction_LotIn(int pZone,int pRecv)

{
  char cVar1;
  
  wng_print(0x53fb70,pZone,pRecv);
  dump_AUC_packet__FcPv(0x52,pRecv);
  if ((pZone != 0) && (pRecv != 0)) {
    cVar1 = *(char *)(pRecv + 5);
    if ((-1 < cVar1) && (cVar1 < '\b')) {
      updateAucBoxWork__FP10GC_AUC_SYSiP11GP_SERV_AUC(pZone + 0x198c4,cVar1,pRecv);
      updateAucBoxUseCount__FP10GC_AUC_SYS(pZone + 0x198c4);
    }
    if ((pZone != -0x198c4) && (pRecv != 0)) {
      *(uint *)(pZone + 0x198c4) = (uint)*(byte *)(pRecv + 4);
      *(int *)(pZone + 0x198c8) = (int)*(char *)(pRecv + 6);
    }
  }
  if ((pZone != -0x198c4) && (pRecv != 0)) {
    *(uint *)(pZone + 0x198c4) = (uint)*(byte *)(pRecv + 4);
    *(int *)(pZone + 0x198c8) = (int)*(char *)(pRecv + 6);
  }
  return 1;
}



// ---------------------------------------------------------------------------
// RecvAuction_LotCancel
//   symbol: RecvAuction_LotCancel
//   rva:    0x003b1b90  size: 416 bytes  tool: ghidra-12.0.4
//   source: main/net/game_cli/gcauction.c
// ---------------------------------------------------------------------------


undefined1 RecvAuction_LotCancel(int pZone,int pRecv)

{
  char cVar1;
  
  wng_print(0x53fb90,pZone,pRecv);
  dump_AUC_packet__FcPv(0x52,pRecv);
  if ((pZone != 0) && (pRecv != 0)) {
    cVar1 = *(char *)(pRecv + 5);
    if ((-1 < cVar1) && (cVar1 < '\b')) {
      updateAucBoxWork__FP10GC_AUC_SYSiP11GP_SERV_AUC(pZone + 0x198c4,cVar1,pRecv);
      updateAucBoxUseCount__FP10GC_AUC_SYS(pZone + 0x198c4);
    }
    if ((pZone != -0x198c4) && (pRecv != 0)) {
      *(uint *)(pZone + 0x198c4) = (uint)*(byte *)(pRecv + 4);
      *(int *)(pZone + 0x198c8) = (int)*(char *)(pRecv + 6);
    }
  }
  if ((pZone != -0x198c4) && (pRecv != 0)) {
    *(uint *)(pZone + 0x198c4) = (uint)*(byte *)(pRecv + 4);
    *(int *)(pZone + 0x198c8) = (int)*(char *)(pRecv + 6);
  }
  return 1;
}



// ---------------------------------------------------------------------------
// RecvAuction_LotCheck
//   symbol: RecvAuction_LotCheck
//   rva:    0x003b1d30  size: 416 bytes  tool: ghidra-12.0.4
//   source: main/net/game_cli/gcauction.c
// ---------------------------------------------------------------------------


undefined1 RecvAuction_LotCheck(int pZone,int pRecv)

{
  char cVar1;
  
  wng_print(0x53fbb0,pZone,pRecv);
  dump_AUC_packet__FcPv(0x52,pRecv);
  if ((pZone != 0) && (pRecv != 0)) {
    cVar1 = *(char *)(pRecv + 5);
    if ((-1 < cVar1) && (cVar1 < '\b')) {
      updateAucBoxWork__FP10GC_AUC_SYSiP11GP_SERV_AUC(pZone + 0x198c4,cVar1,pRecv);
      updateAucBoxUseCount__FP10GC_AUC_SYS(pZone + 0x198c4);
    }
    if ((pZone != -0x198c4) && (pRecv != 0)) {
      *(uint *)(pZone + 0x198c4) = (uint)*(byte *)(pRecv + 4);
      *(int *)(pZone + 0x198c8) = (int)*(char *)(pRecv + 6);
    }
  }
  if ((pZone != -0x198c4) && (pRecv != 0)) {
    *(uint *)(pZone + 0x198c4) = (uint)*(byte *)(pRecv + 4);
    *(int *)(pZone + 0x198c8) = (int)*(char *)(pRecv + 6);
  }
  return 1;
}



// ---------------------------------------------------------------------------
// RecvAuction_Bid
//   symbol: RecvAuction_Bid
//   rva:    0x003b1ed0  size: 416 bytes  tool: ghidra-12.0.4
//   source: main/net/game_cli/gcauction.c
// ---------------------------------------------------------------------------


undefined1 RecvAuction_Bid(int pZone,int pRecv)

{
  char cVar1;
  
  wng_print(0x53fbd0,pZone,pRecv);
  dump_AUC_packet__FcPv(0x52,pRecv);
  if ((pZone != 0) && (pRecv != 0)) {
    cVar1 = *(char *)(pRecv + 5);
    if ((-1 < cVar1) && (cVar1 < '\b')) {
      updateAucBoxWork__FP10GC_AUC_SYSiP11GP_SERV_AUC(pZone + 0x198c4,cVar1,pRecv);
      updateAucBoxUseCount__FP10GC_AUC_SYS(pZone + 0x198c4);
    }
    if ((pZone != -0x198c4) && (pRecv != 0)) {
      *(uint *)(pZone + 0x198c4) = (uint)*(byte *)(pRecv + 4);
      *(int *)(pZone + 0x198c8) = (int)*(char *)(pRecv + 6);
    }
  }
  if ((pZone != -0x198c4) && (pRecv != 0)) {
    *(uint *)(pZone + 0x198c4) = (uint)*(byte *)(pRecv + 4);
    *(int *)(pZone + 0x198c8) = (int)*(char *)(pRecv + 6);
  }
  return 1;
}



// ---------------------------------------------------------------------------
// RecvAuction_Get
//   symbol: RecvAuction_Get
//   rva:    0x003b2070  size: 416 bytes  tool: ghidra-12.0.4
//   source: main/net/game_cli/gcauction.c
// ---------------------------------------------------------------------------


undefined1 RecvAuction_Get(int pZone,int pRecv)

{
  char cVar1;
  
  wng_print(0x53fbf0,pZone,pRecv);
  dump_AUC_packet__FcPv(0x52,pRecv);
  if ((pZone != 0) && (pRecv != 0)) {
    cVar1 = *(char *)(pRecv + 5);
    if ((-1 < cVar1) && (cVar1 < '\b')) {
      updateAucBoxWork__FP10GC_AUC_SYSiP11GP_SERV_AUC(pZone + 0x198c4,cVar1,pRecv);
      updateAucBoxUseCount__FP10GC_AUC_SYS(pZone + 0x198c4);
    }
    if ((pZone != -0x198c4) && (pRecv != 0)) {
      *(uint *)(pZone + 0x198c4) = (uint)*(byte *)(pRecv + 4);
      *(int *)(pZone + 0x198c8) = (int)*(char *)(pRecv + 6);
    }
  }
  if ((pZone != -0x198c4) && (pRecv != 0)) {
    *(uint *)(pZone + 0x198c4) = (uint)*(byte *)(pRecv + 4);
    *(int *)(pZone + 0x198c8) = (int)*(char *)(pRecv + 6);
  }
  return 1;
}



// ---------------------------------------------------------------------------
// RecvAuction_Clear
//   symbol: RecvAuction_Clear
//   rva:    0x003b2210  size: 416 bytes  tool: ghidra-12.0.4
//   source: main/net/game_cli/gcauction.c
// ---------------------------------------------------------------------------


undefined1 RecvAuction_Clear(int pZone,int pRecv)

{
  char cVar1;
  
  wng_print(0x53fc10,pZone,pRecv);
  dump_AUC_packet__FcPv(0x52,pRecv);
  if ((pZone != 0) && (pRecv != 0)) {
    cVar1 = *(char *)(pRecv + 5);
    if ((-1 < cVar1) && (cVar1 < '\b')) {
      updateAucBoxWork__FP10GC_AUC_SYSiP11GP_SERV_AUC(pZone + 0x198c4,cVar1,pRecv);
      updateAucBoxUseCount__FP10GC_AUC_SYS(pZone + 0x198c4);
    }
    if ((pZone != -0x198c4) && (pRecv != 0)) {
      *(uint *)(pZone + 0x198c4) = (uint)*(byte *)(pRecv + 4);
      *(int *)(pZone + 0x198c8) = (int)*(char *)(pRecv + 6);
    }
  }
  if ((pZone != -0x198c4) && (pRecv != 0)) {
    *(uint *)(pZone + 0x198c4) = (uint)*(byte *)(pRecv + 4);
    *(int *)(pZone + 0x198c8) = (int)*(char *)(pRecv + 6);
  }
  return 1;
}



// ---------------------------------------------------------------------------
// dump_AUC_packet
// dump_AUC_packet(char, void *)
//   symbol: dump_AUC_packet__FcPv
//   rva:    0x003b23b0  size: 1524 bytes  tool: ghidra-12.0.4
//   source: main/net/game_cli/gcauction.c
// ---------------------------------------------------------------------------


void dump_AUC_packet__FcPv(char mark,int p)

{
  char cVar1;
  uint uVar2;
  int *piVar3;
  int iVar4;
  long lVar5;
  byte bStack_23;
  byte bStack_22;
  byte bStack_21;
  char cStack_20;
  
  if (p == 0) {
    wng_print(0x540140);
  }
  else {
    cStack_20 = mark;
    if (((long)(char)_ctype_[mark + 1] & 0x97U) == 0) {
      cStack_20 = '?';
    }
    if (cStack_20 == 'R') {
      if (*(char *)(p + 4) == '\r') {
        bStack_23 = *(byte *)(p + 4);
        if (0x13 < bStack_23) {
          bStack_23 = 0x13;
        }
        cVar1 = *(char *)(p + 6);
        iVar4 = _auc_result_strings._12_4_;
        if (cVar1 < '\0') {
          for (piVar3 = &auc_result_table; *piVar3 < 0; piVar3 = piVar3 + 2) {
            if ((long)cVar1 == (long)*piVar3) {
              iVar4 = piVar3[1];
              break;
            }
          }
        }
        else if (cVar1 < '\x04') {
          iVar4 = *(int *)(_auc_result_strings + cVar1 * 4);
        }
        lVar5 = (long)*(char *)(p + 7);
        if ((lVar5 < 0) || (9 < lVar5)) {
          lVar5 = 9;
        }
        wng_print(0x540180,0x52,*(undefined4 *)(_auc_command_strings + (uint)bStack_23 * 4),
                  *(undefined1 *)(p + 5),iVar4,
                  *(undefined4 *)(_auc_resultstatus_strings + (int)lVar5 * 4));
      }
      else {
        uVar2 = (uint)*(byte *)(p + 4);
        if (0x13 < uVar2) {
          uVar2 = 0x13;
        }
        cVar1 = *(char *)(p + 6);
        iVar4 = _auc_result_strings._12_4_;
        if (cVar1 < '\0') {
          for (piVar3 = &auc_result_table; *piVar3 < 0; piVar3 = piVar3 + 2) {
            if ((long)cVar1 == (long)*piVar3) {
              iVar4 = piVar3[1];
              break;
            }
          }
        }
        else if (cVar1 < '\x04') {
          iVar4 = *(int *)(_auc_result_strings + cVar1 * 4);
        }
        wng_print(0x540160,0x52,*(undefined4 *)(_auc_command_strings + uVar2 * 4),
                  *(undefined1 *)(p + 5),iVar4,*(undefined1 *)(p + 7));
      }
    }
    else {
      bStack_22 = *(byte *)(p + 4);
      if (0x13 < bStack_22) {
        bStack_22 = 0x13;
      }
      wng_print(0x5401a0,cStack_20,*(undefined4 *)(_auc_command_strings + (uint)bStack_22 * 4),
                *(undefined1 *)(p + 5));
    }
    cVar1 = *(char *)(p + 4);
    if ((cVar1 != '\x03') && (cVar1 != '\x02')) {
      if (((cVar1 == '\x10') ||
          ((((cVar1 == '\x0f' || (cVar1 == '\x0e')) || (cVar1 == '\r')) ||
           ((cVar1 == '\f' || (cVar1 == '\v')))))) || (cVar1 == '\n')) {
        if ((cStack_20 != 'S') && (p != -0x14)) {
          bStack_21 = *(byte *)(p + 0x14);
          if (0x17 < bStack_21) {
            bStack_21 = 0x17;
          }
          wng_print(0x540100,*(undefined4 *)(_auc_stat_strings + (uint)bStack_21 * 4),p + 0x18
                   );
          wng_print(0x540110,*(undefined2 *)(p + 0x28),*(undefined1 *)(p + 0x2a),
                    *(undefined1 *)(p + 0x2b),*(undefined4 *)(p + 0x2c),
                    *(undefined4 *)(p + 0x30),*(undefined4 *)(p + 0x34));
          wng_print(0x540130,*(undefined4 *)(p + 0x38));
        }
      }
      else if (cVar1 == '\x01') {
        wng_print(0x5401c0,*(undefined2 *)(p + 8));
        wng_print(0x5401e0,*(undefined2 *)(p + 10));
        wng_print(0x5401f0,*(undefined2 *)(p + 0xc));
        wng_print(0x540200,*(undefined2 *)(p + 0xe));
        wng_print(0x540210,*(undefined2 *)(p + 0x10));
        wng_print(0x540230,*(undefined2 *)(p + 0x12));
      }
    }
  }
  return;
}



// ---------------------------------------------------------------------------
// dumpAucBoxWork
//   symbol: dumpAucBoxWork
//   rva:    0x003b29b0  size: 676 bytes  tool: ghidra-12.0.4
//   source: main/net/game_cli/gcauction.c
// ---------------------------------------------------------------------------


void dumpAucBoxWork(int pZone,int from,int to)

{
  uint uVar1;
  int iStack_20;
  int iStack_10;
  
  if (pZone != 0) {
    if ((((from < 0) || (7 < from)) || (to < 0)) ||
       (iStack_20 = from, iStack_10 = to, 7 < to)) {
      iStack_20 = 0;
      iStack_10 = 7;
    }
    for (; iStack_20 <= iStack_10; iStack_20 = iStack_20 + 1) {
      wng_print(0x540248,iStack_20);
      if (pZone + iStack_20 * 0x28 != -0x198ec) {
        uVar1 = (uint)*(byte *)(pZone + iStack_20 * 0x28 + 0x198ec);
        if (0x17 < uVar1) {
          uVar1 = 0x17;
        }
        wng_print(0x540100,*(undefined4 *)(_auc_stat_strings + uVar1 * 4),
                  pZone + iStack_20 * 0x28 + 0x198f0);
        wng_print(0x540110,*(undefined2 *)(pZone + iStack_20 * 0x28 + 0x19900),
                  *(undefined1 *)(pZone + iStack_20 * 0x28 + 0x19902),
                  *(undefined1 *)(pZone + iStack_20 * 0x28 + 0x19903),
                  *(undefined4 *)(pZone + iStack_20 * 0x28 + 0x19904),
                  *(undefined4 *)(pZone + iStack_20 * 0x28 + 0x19908),
                  *(undefined4 *)(pZone + iStack_20 * 0x28 + 0x1990c));
        wng_print(0x540130,*(undefined4 *)(pZone + iStack_20 * 0x28 + 0x19910));
      }
    }
  }
  return;
}

