// AUTOGENERATED by ffxi-decomp. Do not edit by hand.
// version: 972 (sha256=d4622c1cc4a3012c, image_base=0x00100000)
// source:  main/miyagawa/effect/ymvtx.cpp
// functions: 5


// ---------------------------------------------------------------------------
// 
// YmVtxList::operator[](int)
//   symbol: __vc__9YmVtxListFi
//   rva:    0x001b2520  size: 100 bytes  tool: ghidra-12.0.4
//   source: main/miyagawa/effect/ymvtx.cpp
// ---------------------------------------------------------------------------


/* WARNING: Unknown calling convention -- yet parameter storage is locked */

YmVtxList * YmVtxList::operator[](YmVtxList *this,int arg1)

{
  YmVtxList *pYVar1;
  
  if (arg1 < this->vtx_num) {
    pYVar1 = this + arg1 + 1;
  }
  else {
    pYVar1 = (YmVtxList *)&unknown_522;
  }
  return pYVar1;
}



// ---------------------------------------------------------------------------
// Open
// YmVtxRes::Open(void)
//   symbol: Open__8YmVtxResFv
//   rva:    0x001b2590  size: 36 bytes  tool: ghidra-12.0.4
//   source: main/miyagawa/effect/ymvtx.cpp
// ---------------------------------------------------------------------------


/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void YmVtxRes::Open(YmVtxRes *this)

{
  *(undefined4 *)(this + 0x24) = 0;
  *(undefined4 *)(this + 0x28) = 0;
  return;
}



// ---------------------------------------------------------------------------
// Close
// YmVtxRes::Close(void)
//   symbol: Close__8YmVtxResFv
//   rva:    0x001b25c0  size: 72 bytes  tool: ghidra-12.0.4
//   source: main/miyagawa/effect/ymvtx.cpp
// ---------------------------------------------------------------------------


/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void YmVtxRes::Close(YmVtxRes *this)

{
  if (*(int *)(this + 0x24) != 0) {
    YmSpline::~YmSpline(*(YmSpline **)(this + 0x24));
  }
  *(undefined4 *)(this + 0x24) = 0;
  return;
}



// ---------------------------------------------------------------------------
// GetSpline
// YmVtxList::GetSpline(void)
//   symbol: GetSpline__9YmVtxListFv
//   rva:    0x001b2610  size: 620 bytes  tool: ghidra-12.0.4
//   source: main/miyagawa/effect/ymvtx.cpp
// ---------------------------------------------------------------------------


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

YmSpline * YmVtxList::GetSpline(YmVtxList *this)

{
  YmSpline *this_00;
  YmSpline *pYVar1;
  float *pfVar2;
  long lVar3;
  float *pfVar4;
  float *pfVar5;
  YmVtxList *pYVar6;
  int iVar7;
  YmMcb *in_a3_lo;
  uint unaff_retaddr;
  float in_f21;
  float unaff_f20;
  float unaff_f22;
  
  if (this->spline == (YmSpline *)0x0) {
    lVar3 = YmMcb::CreateElemMcb
                      ((YmMcb *)0x30,_head__9YmElemMcb,_tail__9YmElemMcb,in_a3_lo);
    this_00 = (YmSpline *)lVar3;
    *(uint *)&this_00->field_0x4 =
         *(uint *)&this_00->field_0x4 & 0xc0000000 |
         (uint)((ulong)((long)(int)(unaff_retaddr >> 2) << 0x22) >> 0x22);
    pYVar1 = (YmSpline *)0x0;
    if (lVar3 != 0) {
      pYVar1 = (YmSpline *)YmSpline::YmSpline(this_00);
    }
    this->spline = pYVar1;
    YmSpline::Init(this->spline,this->vtx_num,3);
    pfVar2 = this->spline->x;
    pfVar4 = this->spline->y;
    pfVar5 = this->spline->z;
    for (iVar7 = 0; iVar7 < this->vtx_num; iVar7 = iVar7 + 1) {
      if (iVar7 < this->vtx_num) {
        pYVar6 = this + iVar7 + 1;
      }
      else {
        pYVar6 = (YmVtxList *)&unknown_522;
      }
      *pfVar2 = (float)pYVar6->vtx_num;
      if (iVar7 < this->vtx_num) {
        pYVar6 = this + iVar7 + 1;
      }
      else {
        pYVar6 = (YmVtxList *)&unknown_522;
      }
      *pfVar4 = (float)pYVar6->spline;
      if (iVar7 < this->vtx_num) {
        pYVar6 = this + iVar7 + 1;
      }
      else {
        pYVar6 = (YmVtxList *)&unknown_522;
      }
      *pfVar5 = (float)pYVar6->spline_ref_cnt;
      if (((unaff_f20 == *pfVar2) && (in_f21 == *pfVar4)) && (unaff_f22 == *pfVar5)) {
        *pfVar4 = *pfVar4 + DAT_0054c1f4;
      }
      unaff_f20 = *pfVar2;
      pfVar2 = pfVar2 + 1;
      in_f21 = *pfVar4;
      pfVar4 = pfVar4 + 1;
      unaff_f22 = *pfVar5;
      pfVar5 = pfVar5 + 1;
    }
    if (((unaff_f20 == *pfVar2) && (in_f21 == *pfVar4)) && (unaff_f22 == *pfVar5)) {
      *pfVar4 = *pfVar4 + DAT_0054c1f4;
    }
    *pfVar2 = unaff_f20;
    *pfVar4 = in_f21;
    *pfVar5 = unaff_f22;
    YmSpline::CalcTable(this->spline);
  }
  return this->spline;
}



// ---------------------------------------------------------------------------
// GetSplinePos
// YmVtxList::GetSplinePos(float *, float)
//   symbol: GetSplinePos__9YmVtxListFPff
//   rva:    0x001b2880  size: 100 bytes  tool: ghidra-12.0.4
//   source: main/miyagawa/effect/ymvtx.cpp
// ---------------------------------------------------------------------------


/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void YmVtxList::GetSplinePos(YmVtxList *this,float *v,float t)

{
  YmSpline *this_00;
  
  v[3] = 1.0;
  this_00 = (YmSpline *)YmVtxList::GetSpline(this);
  YmSpline::GetSpline(this_00,t,v,v + 1,v + 2);
  return;
}

