// AUTOGENERATED by ffxi-decomp. Do not edit by hand.
// version: 972 (sha256=d4622c1cc4a3012c, image_base=0x00100000)
// class:   CIwNetWinSub1
// methods: 3
// fields:  3
// extends: CTkMenuPrimitive
//
// Field sources: 'mdebug' = original PS2 DWARF1 debug symbols (authoritative);
// 'llm' = name proposed by review pass; 'synth' = layout-only, name pending.
// Methods recovered from GCC 2.x mangled symbols. NOT a real header --
// treat as documentation, not a build artifact.

#pragma once

class CIwNetWinSub1 : public CTkMenuPrimitive {
public:
    // --- fields ---
    /* +0x0004 */ void** mVTable;  // 2 accesses [llm]
    /* +0x0008 */ CTkMenuCtrlData* mCtrlData;  /* 4b */  // 7 accesses [llm]
    /* +0x0014 */ float m_percent;  /* 4b */  // 0 accesses

    // --- methods ---
    ~CIwNetWinSub1(void);  // __dt__13CIwNetWinSub1Fv @ 0x0015c2c0
    OnDrawPrimitive(void);  // OnDrawPrimitive__13CIwNetWinSub1Fv @ 0x0031bd30
    OnInitialUpdatePrimitive(void);  // OnInitialUpdatePrimitive__13CIwNetWinSub1Fv @ 0x0031bf30
};
