// AUTOGENERATED by ffxi-decomp. Do not edit by hand.
// version: 972 (sha256=d4622c1cc4a3012c, image_base=0x00100000)
// class:   CTkSpoolMsgBase
// methods: 9
// fields:  16
// extends: CTkMenuPrimitive
//
// Field sources: 'mdebug' = original PS2 DWARF1 debug symbols (authoritative);
// 'llm' = name proposed by review pass; 'synth' = layout-only, name pending.
// Methods recovered from GCC 2.x mangled symbols. NOT a real header --
// treat as documentation, not a build artifact.

#pragma once

class CTkSpoolMsgBase : public CTkMenuPrimitive {
public:
    // --- fields ---
    /* +0x0004 */ void** mVtable;  /* 4b */  // 6 accesses [llm]
    /* +0x0008 */ CTkMenuCtrlData* mMenuCtrlData;  /* 4b */  // 32 accesses [llm]
    /* +0x000e */ undefined2 mMenuId;  /* 2b */  // 2 accesses [llm]
    /* +0x0014 */ class CTkObList m_SpoolMsgDatas;  /* 28b */  // 4 accesses
    /* +0x0030 */ class TKRECT m_WindowRect;  /* 8b */  // 1 access
    /* +0x0038 */ class TKRECT m_OrignalRect;  /* 8b */  // 3 accesses
    /* +0x0040 */ signed long m_cmd;  /* 4b */  // 2 accesses
    /* +0x0048 */ char m_IsNoWin;  /* 1b */  // 2 accesses
    /* +0x004a */ signed short m_NoWinX;  /* 2b */  // 6 accesses
    /* +0x004c */ signed short m_NoWinY;  /* 2b */  // 6 accesses
    /* +0x004e */ signed short m_LineCnt;  /* 2b */  // 2 accesses
    /* +0x0050 */ signed int m_LineNo;  /* 4b */  // 2 accesses
    /* +0x0054 */ signed short m_subDspLine;  /* 2b */  // 4 accesses
    /* +0x0056 */ char m_isButtonWait;  /* 1b */  // 0 accesses
    /* +0x0058 */ class __POSITION * m_drawpos;  /* 4b */  // 0 accesses
    /* +0x005c */ signed int m_drawcnt;  /* 4b */  // 0 accesses

    // --- methods ---
    CTkSpoolMsgBase(void);  // __ct__15CTkSpoolMsgBaseFv @ 0x001bb500
    ~CTkSpoolMsgBase(void);  // __dt__15CTkSpoolMsgBaseFv @ 0x001bb5f0
    OnInitialUpdatePrimitive(void);  // OnInitialUpdatePrimitive__15CTkSpoolMsgBaseFv @ 0x001bb690
    DisableDraw(void);  // DisableDraw__15CTkSpoolMsgBaseFv @ 0x001bb7c0
    EnableDraw(void);  // EnableDraw__15CTkSpoolMsgBaseFv @ 0x001bb8a0
    SpoolMsg(char *, char, char);  // SpoolMsg__15CTkSpoolMsgBaseFPccc @ 0x001bbb30
    UpdateData(void);  // UpdateData__15CTkSpoolMsgBaseFv @ 0x001bbd00
    RemoveAllMsg(void);  // RemoveAllMsg__15CTkSpoolMsgBaseFv @ 0x001bbd10
    PresetEventMessageMode(char, short, short);  // PresetEventMessageMode__15CTkSpoolMsgBaseFcss @ 0x001bbde0
};
