// AUTOGENERATED by ffxi-decomp. Do not edit by hand.
// version: 972 (sha256=d4622c1cc4a3012c, image_base=0x00100000)
// class:   FsFileThreadManager
// methods: 22
// fields:  8
// extends: YmWorkObject
//
// Field sources: 'mdebug' = original PS2 DWARF1 debug symbols (authoritative);
// 'llm' = name proposed by review pass; 'synth' = layout-only, name pending.
// Methods recovered from GCC 2.x mangled symbols. NOT a real header --
// treat as documentation, not a build artifact.

#pragma once

class FsFileThreadManager : public YmWorkObject {
public:
    // --- fields ---
    /* +0x0004 */ FsFileQueue* mFileQueue;  /* 4b */  // 12 accesses [llm]
    /* +0x0008 */ char[256] mPathBuf;  // 8 accesses [llm]
    /* +0x0010 */ class FsThread * m_fileThread;  /* 4b */  // 10 accesses
    /* +0x0014 */ class FsFileThreadSync * m_threadSync;  /* 4b */  // 26 accesses
    /* +0x010c */ /* unknown */ field_0x10c;  // 1 access [synth]
    /* +0x0114 */ undefined4 field_0x114;  /* 4b */  // 2 accesses [synth]
    /* +0x0118 */ int field_0x118;  /* 4b */  // 2 accesses [synth]
    /* +0x011c */ int field_0x11c;  /* 4b */  // 2 accesses [synth]

    // --- methods ---
    FsFileThreadManager(void);  // __ct__19FsFileThreadManagerFv @ 0x00277ce0
    ~FsFileThreadManager(void);  // __dt__19FsFileThreadManagerFv @ 0x00277d70
    init(int);  // init__19FsFileThreadManagerFi @ 0x00277de0
    uninit(void);  // uninit__19FsFileThreadManagerFv @ 0x00277f10
    addFileEvent(FsFileEvent *);  // addFileEvent__19FsFileThreadManagerFP11FsFileEvent @ 0x002780b0
    checkFileEvent(FsFileEvent *);  // checkFileEvent__19FsFileThreadManagerFP11FsFileEvent @ 0x002781b0
    doEventNow(FsFileEvent *);  // doEventNow__19FsFileThreadManagerFP11FsFileEvent @ 0x002781f0
    cancelAllEvents(void);  // cancelAllEvents__19FsFileThreadManagerFv @ 0x00278380
    doAllEvents(void);  // doAllEvents__19FsFileThreadManagerFv @ 0x002783b0
    pauseFileThread(void);  // pauseFileThread__19FsFileThreadManagerFv @ 0x00278440
    resumeFileThread(void);  // resumeFileThread__19FsFileThreadManagerFv @ 0x00278490
    handleErrors(void);  // handleErrors__19FsFileThreadManagerFv @ 0x002784e0
    threadControlFunction(void *);  // threadControlFunction__19FsFileThreadManagerFPv @ 0x00278550
    handleFileEvent(FsFileEvent);  // handleFileEvent__19FsFileThreadManagerF11FsFileEvent @ 0x00278940
    doRead(FsFileEvent);  // doRead__19FsFileThreadManagerF11FsFileEvent @ 0x00279340
    doReadEx(FsFileEvent);  // doReadEx__19FsFileThreadManagerF11FsFileEvent @ 0x00279490
    doWrite(FsFileEvent);  // doWrite__19FsFileThreadManagerF11FsFileEvent @ 0x002797b0
    doGetFileSize(FsFileEvent);  // doGetFileSize__19FsFileThreadManagerF11FsFileEvent @ 0x002798a0
    doGetStat(FsFileEvent);  // doGetStat__19FsFileThreadManagerF11FsFileEvent @ 0x00279900
    doRemove(FsFileEvent);  // doRemove__19FsFileThreadManagerF11FsFileEvent @ 0x00279950
    doExist(FsFileEvent);  // doExist__19FsFileThreadManagerF11FsFileEvent @ 0x00279990
    doExit(void);  // doExit__19FsFileThreadManagerFv @ 0x002799d0
};
