// AUTOGENERATED by ffxi-decomp. Do not edit by hand.
// version: 972 (sha256=d4622c1cc4a3012c, image_base=0x00100000)
// class:   FsHdd
// methods: 11
// fields:  3
//
// Field sources: 'mdebug' = original PS2 DWARF1 debug symbols (authoritative);
// 'llm' = name proposed by review pass; 'synth' = layout-only, name pending.
// Methods recovered from GCC 2.x mangled symbols. NOT a real header --
// treat as documentation, not a build artifact.

#pragma once

class FsHdd {
public:
    // --- fields ---
    /* +0x0004 */ char m_hddName;  /* 256b */  // 7 accesses
    /* +0x0104 */ char m_errorString;  /* 16b */  // 7 accesses
    /* +0x0114 */ signed int m_pfsNum;  /* 4b */  // 2 accesses

    // --- methods ---
    FsHdd(char *);  // __ct__5FsHddFPc @ 0x002874f0
    ~FsHdd(void);  // __dt__5FsHddFv @ 0x00287560
    partitionExists(char *);  // partitionExists__5FsHddFPc @ 0x002875c0
    makeMainPartition(char *, char *, char *, char *);  // makeMainPartition__5FsHddFPcPcPcPc @ 0x002876a0
    makeSubPartition(char *, char *, char *, char *);  // makeSubPartition__5FsHddFPcPcPcPc @ 0x00287740
    removeMainPartition(char *, char *);  // removeMainPartition__5FsHddFPcPc @ 0x00287840
    formatPfs(char *, char *, int, char *);  // formatPfs__5FsHddFPcPciPc @ 0x002878c0
    mountPfs(char *, char *, char *);  // mountPfs__5FsHddFPcPcPc @ 0x00287970
    unmountPfs(char *);  // unmountPfs__5FsHddFPc @ 0x00287a10
    doSceFsInit(void);  // doSceFsInit__5FsHddFv @ 0x00287a70
    _getError(int);  // _getError__5FsHddFi @ 0x00287aa0
};
