// AUTOGENERATED by ffxi-decomp. Do not edit by hand.
// version: 972 (sha256=d4622c1cc4a3012c, image_base=0x00100000)
// class:   KaAbilityData
// methods: 2
// fields:  0
// extends: KaComDataBuf
//
// Field sources: 'mdebug' = original PS2 DWARF1 debug symbols (authoritative);
// 'llm' = name proposed by review pass; 'synth' = layout-only, name pending.
// Methods recovered from GCC 2.x mangled symbols. NOT a real header --
// treat as documentation, not a build artifact.

#pragma once

class KaAbilityData : public KaComDataBuf {
public:
    // --- methods ---
    ~KaAbilityData(void);  // __dt__13KaAbilityDataFv @ 0x0033e2a0
    KaAbilityData(void);  // __ct__13KaAbilityDataFv @ 0x0033e940
};
