// AUTOGENERATED by ffxi-decomp. Do not edit by hand.
// version: 972 (sha256=d4622c1cc4a3012c, image_base=0x00100000)
// class:   LockCasterControl_2733ymschdecript_cpp
// methods: 6
// fields:  0
//
// Field sources: 'mdebug' = original PS2 DWARF1 debug symbols (authoritative);
// 'llm' = name proposed by review pass; 'synth' = layout-only, name pending.
// Methods recovered from GCC 2.x mangled symbols. NOT a real header --
// treat as documentation, not a build artifact.

#pragma once

class LockCasterControl_2733ymschdecript_cpp {
public:
    // --- methods ---
    ~LockCasterControl$2733ymschdecript_cpp(void);  // __dt__Q215YmSchedulerTask38LockCasterControl$2733ymschdecript_cppFv @ 0x00266c80
    OnMove(void);  // OnMove__Q215YmSchedulerTask38LockCasterControl$2733ymschdecript_cppFv @ 0x00266d60
    OnDeleteTarget(void);  // OnDeleteTarget__Q215YmSchedulerTask38LockCasterControl$2733ymschdecript_cppFv @ 0x00266e10
    OnDeleteCaster(void);  // OnDeleteCaster__Q215YmSchedulerTask38LockCasterControl$2733ymschdecript_cppFv @ 0x00266e60
    OnDeleteTarget(void);  // @32@OnDeleteTarget__Q215YmSchedulerTask38LockCasterControl$2733ymschdecript_cppFv @ 0x002691c0
    OnDeleteCaster(void);  // @32@OnDeleteCaster__Q215YmSchedulerTask38LockCasterControl$2733ymschdecript_cppFv @ 0x002691d0
};
