// AUTOGENERATED by ffxi-decomp. Do not edit by hand.
// version: 972 (sha256=d4622c1cc4a3012c, image_base=0x00100000)
// class:   XiCollisionActor
// methods: 10
// fields:  21
// extends: XiControlActor
//
// Field sources: 'mdebug' = original PS2 DWARF1 debug symbols (authoritative);
// 'llm' = name proposed by review pass; 'synth' = layout-only, name pending.
// Methods recovered from GCC 2.x mangled symbols. NOT a real header --
// treat as documentation, not a build artifact.

#pragma once

class XiCollisionActor : public XiControlActor {
public:
    // --- fields ---
    /* +0x0010 */ /* unknown */ field_0x10;  // 1 access [synth]
    /* +0x003c */ XiActor* mItem;  /* 4b */  // 2 accesses [llm]
    /* +0x00b0 */ /* unknown */ field_0xb0;  // 1 access [synth]
    /* +0x00c4 */ /* unknown */ field_0xc4;  // 1 access [synth]
    /* +0x00d0 */ float mGroundY;  /* 4b */  // 12 accesses [llm]
    /* +0x00f0 */ /* unknown */ field_0xf0;  // 1 access [synth]
    /* +0x0150 */ undefined4 field_0x150;  /* 4b */  // 2 accesses [synth]
    /* +0x0154 */ undefined4 field_0x154;  /* 4b */  // 4 accesses [synth]
    /* +0x0158 */ undefined4 field_0x158;  /* 4b */  // 2 accesses [synth]
    /* +0x0180 */ float pos;  /* 16b */  // 17 accesses
    /* +0x0190 */ float prev_lift_pos;  /* 16b */  // 0 accesses
    /* +0x01a0 */ float last_hit_chk_pos;  /* 16b */  // 5 accesses
    /* +0x01b0 */ float last_hit_chk_result;  /* 16b */  // 2 accesses
    /* +0x01c0 */ char IsTouch;  /* 1b */  // 0 accesses
    /* +0x01c1 */ char is_on_lift;  /* 1b */  // 0 accesses
    /* +0x01c4 */ signed int current_area_id;  /* 4b */  // 4 accesses
    /* +0x01c8 */ signed int hit_check_count;  /* 4b */  // 10 accesses
    /* +0x01d0 */ __int128 current_plight;  /* 16b */  // 4 accesses
    /* +0x01e0 */ /* unknown */ field_0x1e0;  // 1 access [synth]
    /* +0x01e8 */ /* unknown */ field_0x1e8;  // 1 access [synth]
    /* +0x01f0 */ /* unknown */ field_0x1f0;  // 1 access [synth]

    // --- methods ---
    IsOnLift(void);  // IsOnLift__16XiCollisionActorFv @ 0x0009b5e0
    GetRuntimeClass(void) const;  // GetRuntimeClass__16XiCollisionActorCFv @ 0x000be6b0
    XiCollisionActor(void);  // __ct__16XiCollisionActorFv @ 0x000be6d0
    CorrectNormal(void);  // CorrectNormal__16XiCollisionActorFv @ 0x000be800
    OnMove(void);  // OnMove__16XiCollisionActorFv @ 0x000bea30
    IsBlendNormal(void);  // IsBlendNormal__16XiCollisionActorFv @ 0x000bf0a0
    IsTouchDown(void);  // IsTouchDown__16XiCollisionActorFv @ 0x000bf0c0
    ExecHitCheck(void);  // ExecHitCheck__16XiCollisionActorFv @ 0x000bf120
    ~XiCollisionActor(void);  // __dt__16XiCollisionActorFv @ 0x000bf140
    GetPos(void);  // GetPos__16XiCollisionActorFv @ 0x000bf1f0
};
