// AUTOGENERATED by ffxi-decomp. Do not edit by hand.
// version: 972 (sha256=d4622c1cc4a3012c, image_base=0x00100000)
// class:   YkFurniture
// methods: 26
// fields:  21
// extends: YmObject
//
// Field sources: 'mdebug' = original PS2 DWARF1 debug symbols (authoritative);
// 'llm' = name proposed by review pass; 'synth' = layout-only, name pending.
// Methods recovered from GCC 2.x mangled symbols. NOT a real header --
// treat as documentation, not a build artifact.

#pragma once

class YkFurniture : public YmObject {
public:
    // --- fields ---
    /* +0x0004 */ char m_mode;  /* 1b */  // 0 accesses
    /* +0x0005 */ unsigned char m_tbl;  /* 1b */  // 0 accesses
    /* +0x0006 */ unsigned short m_item;  /* 2b */  // 2 accesses
    /* +0x0008 */ signed int x;  /* 4b */  // 46 accesses
    /* +0x000c */ signed int y;  /* 4b */  // 32 accesses
    /* +0x0010 */ signed int z;  /* 4b */  // 44 accesses
    /* +0x0014 */ signed int v;  /* 4b */  // 28 accesses
    /* +0x0018 */ signed short m_color;  /* 2b */  // 22 accesses
    /* +0x001a */ signed short m_colv;  /* 2b */  // 10 accesses
    /* +0x001c */ signed short m_plnt_step;  /* 2b */  // 8 accesses
    /* +0x001e */ char m_packet_send_req;  /* 1b */  // 0 accesses
    /* +0x001f */ char m_close_req;  /* 1b */  // 0 accesses
    /* +0x0020 */ char m_placed;  /* 1b */  // 0 accesses
    /* +0x0024 */ class YmResourceFile * m_res;  /* 4b */  // 5 accesses
    /* +0x0028 */ class XiModelActor * m_model;  /* 4b */  // 38 accesses
    /* +0x002c */ class YmResourceFile * m_plnt_res;  /* 8b */  // 5 accesses
    /* +0x0034 */ class XiModelActor * m_plnt_model;  /* 8b */  // 33 accesses
    /* +0x003c */ char m_falling;  /* 1b */  // 0 accesses
    /* +0x0040 */ signed int child_num;  /* 4b */  // 20 accesses
    /* +0x0044 */ class YkFurniture * child;  /* 128b */  // 0 accesses
    /* +0x00c4 */ class FurnitureProperty * fp;  /* 4b */  // 22 accesses

    // --- methods ---
    GetRuntimeClass(void) const;  // GetRuntimeClass__11YkFurnitureCFv @ 0x002b4b00
    SendPos(int);  // SendPos__11YkFurnitureFi @ 0x002b4b20
    Move(int, int);  // Move__11YkFurnitureFii @ 0x002b4d70
    MoveChild(int, int);  // MoveChild__11YkFurnitureFii @ 0x002b5030
    RotChild(YkFurniture *, int);  // RotChild__11YkFurnitureFP11YkFurniturei @ 0x002b50a0
    YkFurniture(unsigned short, unsigned char);  // __ct__11YkFurnitureFUsUc @ 0x002b5220
    ~YkFurniture(void);  // __dt__11YkFurnitureFv @ 0x002b5740
    CheckStep(void);  // CheckStep__11YkFurnitureFv @ 0x002b5890
    SetPosInt(int, int, int);  // SetPosInt__11YkFurnitureFiii @ 0x002b5f10
    SetDirInt(int);  // SetDirInt__11YkFurnitureFi @ 0x002b6170
    Close(void);  // Close__11YkFurnitureFv @ 0x002b66f0
    HasPlant(void);  // HasPlant__11YkFurnitureFv @ 0x002b6800
    ChangeMode(int, int);  // ChangeMode__11YkFurnitureFii @ 0x002b6950
    OnMove(void);  // OnMove__11YkFurnitureFv @ 0x002b6ad0
    TargettingColorAnm(void);  // TargettingColorAnm__11YkFurnitureFv @ 0x002b7730
    ResetColor(void);  // ResetColor__11YkFurnitureFv @ 0x002b78c0
    DeletedAllChildren(void);  // DeletedAllChildren__11YkFurnitureFv @ 0x002b79e0
    SetColor(unsigned int);  // SetColor__11YkFurnitureFUi @ 0x002b7a00
    GetX(void);  // GetX__11YkFurnitureFv @ 0x002b7a70
    GetY(void);  // GetY__11YkFurnitureFv @ 0x002b7a90
    GetZ(void);  // GetZ__11YkFurnitureFv @ 0x002b7ab0
    GetXSize(void);  // GetXSize__11YkFurnitureFv @ 0x002b7ad0
    GetZSize(void);  // GetZSize__11YkFurnitureFv @ 0x002b7b60
    CanHang(void);  // CanHang__11YkFurnitureFv @ 0x002b7bf0
    CanBePut(void);  // CanBePut__11YkFurnitureFv @ 0x002b7c20
    CanPutOn(void);  // CanPutOn__11YkFurnitureFv @ 0x002b7c50
};
