// AUTOGENERATED by ffxi-decomp. Do not edit by hand.
// version: 972 (sha256=d4622c1cc4a3012c, image_base=0x00100000)
// class:   YkWndYesno
// methods: 8
// fields:  10
// extends: CTkMenuPrimitive
//
// Field sources: 'mdebug' = original PS2 DWARF1 debug symbols (authoritative);
// 'llm' = name proposed by review pass; 'synth' = layout-only, name pending.
// Methods recovered from GCC 2.x mangled symbols. NOT a real header --
// treat as documentation, not a build artifact.

#pragma once

class YkWndYesno : public CTkMenuPrimitive {
public:
    // --- fields ---
    /* +0x0004 */ void** mVTable;  /* 4b */  // 6 accesses [llm]
    /* +0x0008 */ CTkMenuCtrlData* mMenuCtrl;  /* 4b */  // 9 accesses [llm]
    /* +0x000e */ undefined2 mState;  /* 2b */  // 2 accesses [llm]
    /* +0x0014 */ void(*)(void*, char) mCallback;  /* 4b */  // 24 accesses [llm]
    /* +0x0018 */ void * m_user;  /* 4b */  // 14 accesses
    /* +0x001c */ char * m_str;  /* 4b */  // 10 accesses
    /* +0x0020 */ char m_id;  /* 17b */  // 2 accesses
    /* +0x0034 */ char * m_title;  /* 4b */  // 11 accesses
    /* +0x0038 */ char m_bcancel;  /* 1b */  // 0 accesses
    /* +0x0039 */ char m_bcancelnow;  /* 1b */  // 2 accesses

    // --- methods ---
    ~YkWndYesno(void);  // __dt__10YkWndYesnoFv @ 0x002d46f0
    YkWndYesno(char *, char);  // __ct__10YkWndYesnoFPcc @ 0x003447f0
    Open(void);  // Open__10YkWndYesnoFPFPvc_vPvPCccPCcc @ 0x00344910
    Close(char);  // Close__10YkWndYesnoFc @ 0x00344aa0
    OnDrawCalc(char);  // OnDrawCalc__10YkWndYesnoFc @ 0x00344b10
    OnDrawPrimitive(void);  // OnDrawPrimitive__10YkWndYesnoFv @ 0x00344b60
    OnKeyDown(short, short);  // OnKeyDown__10YkWndYesnoFss @ 0x00344c10
    OnDestroyPrimitive(void);  // OnDestroyPrimitive__10YkWndYesnoFv @ 0x00344d80
};
