// AUTOGENERATED by ffxi-decomp. Do not edit by hand.
// version: 972 (sha256=d4622c1cc4a3012c, image_base=0x00100000)
// class:   YkWndSearchMenu
// methods: 5
// fields:  7
// extends: CTkMenuPrimitive
//
// Field sources: 'mdebug' = original PS2 DWARF1 debug symbols (authoritative);
// 'llm' = name proposed by review pass; 'synth' = layout-only, name pending.
// Methods recovered from GCC 2.x mangled symbols. NOT a real header --
// treat as documentation, not a build artifact.

#pragma once

class YkWndSearchMenu : public CTkMenuPrimitive {
public:
    // --- fields ---
    /* +0x0004 */ void** mVTable;  /* 4b */  // 6 accesses [llm]
    /* +0x0008 */ CTkMenuCtrlData* mMenuCtrlData;  /* 4b */  // 30 accesses [llm]
    /* +0x000e */ undefined2 field_0xe;  /* 2b */  // 2 accesses [synth]
    /* +0x0014 */ signed int m_mode;  /* 4b */  // 10 accesses
    /* +0x0018 */ class CShape * m_btn;  /* 8b */  // 2 accesses
    /* +0x0020 */ char m_helped;  /* 1b */  // 0 accesses
    /* +0x0021 */ char m_myself;  /* 1b */  // 0 accesses

    // --- methods ---
    ~YkWndSearchMenu(void);  // __dt__15YkWndSearchMenuFv @ 0x0037c2a0
    YkWndSearchMenu(void);  // __ct__15YkWndSearchMenuFv @ 0x0037cc10
    OnInitialUpdatePrimitive(void);  // OnInitialUpdatePrimitive__15YkWndSearchMenuFv @ 0x0037cd10
    OnDrawPrimitive(void);  // OnDrawPrimitive__15YkWndSearchMenuFv @ 0x0037d2d0
    OnKeyDown(short, short);  // OnKeyDown__15YkWndSearchMenuFss @ 0x0037d7d0
};
