// AUTOGENERATED by ffxi-decomp. Do not edit by hand.
// version: 972 (sha256=d4622c1cc4a3012c, image_base=0x00100000)
// class:   YkWndPlant4
// methods: 5
// fields:  2
// extends: CTkMenuPrimitive
//
// Field sources: 'mdebug' = original PS2 DWARF1 debug symbols (authoritative);
// 'llm' = name proposed by review pass; 'synth' = layout-only, name pending.
// Methods recovered from GCC 2.x mangled symbols. NOT a real header --
// treat as documentation, not a build artifact.

#pragma once

class YkWndPlant4 : public CTkMenuPrimitive {
public:
    // --- fields ---
    /* +0x0004 */ void** mVTable;  // 2 accesses [llm]
    /* +0x0008 */ CTkMenuCtrlData* mMenuCtrlData;  // 1 access [llm]

    // --- methods ---
    OnActive(unsigned char);  // OnActive__11YkWndPlant4FUc @ 0x002c2590
    OnDestroyPrimitive(void);  // OnDestroyPrimitive__11YkWndPlant4Fv @ 0x002c26e0
    OnTargetLost(void);  // OnTargetLost__11YkWndPlant4Fv @ 0x002c27d0
    OnKeyDown(short, short);  // OnKeyDown__11YkWndPlant4Fss @ 0x002c2e30
    ~YkWndPlant4(void);  // __dt__11YkWndPlant4Fv @ 0x002c3ec0
};
