// AUTOGENERATED by ffxi-decomp. Do not edit by hand.
// version: 972 (sha256=d4622c1cc4a3012c, image_base=0x00100000)
// class:   YkWndShopCtrl
// methods: 9
// fields:  6
//
// Field sources: 'mdebug' = original PS2 DWARF1 debug symbols (authoritative);
// 'llm' = name proposed by review pass; 'synth' = layout-only, name pending.
// Methods recovered from GCC 2.x mangled symbols. NOT a real header --
// treat as documentation, not a build artifact.

#pragma once

class YkWndShopCtrl {
public:
    // --- fields ---
    /* +0x0000 */ signed short m_idx;  /* 2b */  // 0 accesses
    /* +0x0002 */ signed short m_max;  /* 2b */  // 0 accesses
    /* +0x0004 */ class YkWndListItem * m_item;  /* 4b */  // 12 accesses
    /* +0x0008 */ char m_wide;  /* 1b */  // 0 accesses
    /* +0x000a */ signed short m_widesize;  /* 2b */  // 0 accesses
    /* +0x000c */ void* mDispatcher;  /* 4b */  // 2 accesses [llm]

    // --- methods ---
    OnCalc(char, unsigned char);  // OnCalc__13YkWndShopCtrlFcUc @ 0x00363ae0
    Clear(void);  // Clear__13YkWndShopCtrlFv @ 0x00364040
    GetHelp(void);  // GetHelp__13YkWndShopCtrlFv @ 0x00365640
    GetTitle(void);  // GetTitle__13YkWndShopCtrlFv @ 0x00365660
    OnCreate(void);  // OnCreate__13YkWndShopCtrlFv @ 0x00365680
    OnDestroy(void);  // OnDestroy__13YkWndShopCtrlFv @ 0x003657a0
    MakeList(YkWndList *, int);  // MakeList__13YkWndShopCtrlFP9YkWndListi @ 0x003658e0
    OnCancel(void);  // OnCancel__13YkWndShopCtrlFv @ 0x00365d50
    DispFilter(GC_ITEM_DATA *, CTkItemDataMenber *);  // DispFilter__13YkWndShopCtrlFP12GC_ITEM_DATAP17CTkItemDataMenber @ 0x00366650
};
