// AUTOGENERATED by ffxi-decomp. Do not edit by hand.
// version: 972 (sha256=d4622c1cc4a3012c, image_base=0x00100000)
// class:   YkWndClinkData
// methods: 2
// fields:  2
// extends: CTkMenuPrimitive
//
// Field sources: 'mdebug' = original PS2 DWARF1 debug symbols (authoritative);
// 'llm' = name proposed by review pass; 'synth' = layout-only, name pending.
// Methods recovered from GCC 2.x mangled symbols. NOT a real header --
// treat as documentation, not a build artifact.

#pragma once

class YkWndClinkData : public CTkMenuPrimitive {
public:
    // --- fields ---
    /* +0x0004 */ void** mVTable;  // 2 accesses [llm]
    /* +0x0008 */ CTkMenuCtrlData* mMenuCtrlData;  // 1 access [llm]

    // --- methods ---
    ~YkWndClinkData(void);  // __dt__14YkWndClinkDataFv @ 0x003822f0
    OnDrawPrimitive(void);  // OnDrawPrimitive__14YkWndClinkDataFv @ 0x00384a00
};
