// AUTOGENERATED by ffxi-decomp. Do not edit by hand.
// version: 972 (sha256=d4622c1cc4a3012c, image_base=0x00100000)
// class:   YmAnmElem
// methods: 3
// fields:  4
// extends: YmElem
//
// Field sources: 'mdebug' = original PS2 DWARF1 debug symbols (authoritative);
// 'llm' = name proposed by review pass; 'synth' = layout-only, name pending.
// Methods recovered from GCC 2.x mangled symbols. NOT a real header --
// treat as documentation, not a build artifact.

#pragma once

class YmAnmElem : public YmElem {
public:
    // --- fields ---
    /* +0x00c4 */ void* mShape;  /* 4b */  // 2 accesses [llm]
    /* +0x0100 */ unsigned short shape_index;  /* 2b */  // 0 accesses
    /* +0x0104 */ float interval_time;  /* 4b */  // 0 accesses
    /* +0x0108 */ float interval_wait;  /* 4b */  // 0 accesses

    // --- methods ---
    GetRuntimeClass(void) const;  // GetRuntimeClass__9YmAnmElemCFv @ 0x000e21f0
    OnDraw(void);  // OnDraw__9YmAnmElemFv @ 0x000e2c20
    ~YmAnmElem(void);  // __dt__9YmAnmElemFv @ 0x000e5040
};
