// AUTOGENERATED by ffxi-decomp. Do not edit by hand.
// version: 972 (sha256=d4622c1cc4a3012c, image_base=0x00100000)
// class:   YmGeneraterWindow
// methods: 2
// fields:  4
// extends: YmWindow
//
// Field sources: 'mdebug' = original PS2 DWARF1 debug symbols (authoritative);
// 'llm' = name proposed by review pass; 'synth' = layout-only, name pending.
// Methods recovered from GCC 2.x mangled symbols. NOT a real header --
// treat as documentation, not a build artifact.

#pragma once

class YmGeneraterWindow : public YmWindow {
public:
    // --- fields ---
    /* +0x0154 */ char was_active;  /* 1b */  // 0 accesses
    /* +0x0158 */ class YmResSelectControl * model_select_control;  /* 4b */  // 0 accesses
    /* +0x015c */ class YmGenerater * document;  /* 4b */  // 0 accesses
    /* +0x0160 */ class YmString caption;  /* 132b */  // 0 accesses

    // --- methods ---
    KillAll(void);  // KillAll__17YmGeneraterWindowFv @ 0x001109e0
    Update(YmGenerater *);  // Update__17YmGeneraterWindowFP11YmGenerater @ 0x00110b30
};
