// AUTOGENERATED by ffxi-decomp. Do not edit by hand.
// version: 972 (sha256=d4622c1cc4a3012c, image_base=0x00100000)
// class:   YmLfdElem
// methods: 3
// fields:  4
// extends: YmElem
//
// Field sources: 'mdebug' = original PS2 DWARF1 debug symbols (authoritative);
// 'llm' = name proposed by review pass; 'synth' = layout-only, name pending.
// Methods recovered from GCC 2.x mangled symbols. NOT a real header --
// treat as documentation, not a build artifact.

#pragma once

class YmLfdElem : public YmElem {
public:
    // --- fields ---
    /* +0x00c4 */ int mLensFlareOwner;  /* 4b */  // 2 accesses [llm]
    /* +0x0100 */ unsigned int sc_rgb;  /* 4b */  // 0 accesses
    /* +0x0104 */ float size;  /* 4b */  // 0 accesses
    /* +0x0108 */ float screen_coloring_rate;  /* 4b */  // 0 accesses

    // --- methods ---
    GetRuntimeClass(void) const;  // GetRuntimeClass__9YmLfdElemCFv @ 0x000e2270
    OnDraw(void);  // OnDraw__9YmLfdElemFv @ 0x000e3740
    ~YmLfdElem(void);  // __dt__9YmLfdElemFv @ 0x000e4e00
};
